### ISSUE TITLE
mobile: Crash on playing audio?

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1018]
```
Non-fatal Exception: go.Universe$proxyerror: java.lang.IllegalStateException: play() called on uninitialized AudioTrack.
       at com.rpgsnack.runtime.ebitenmobileview.Ebitenmobileview.update(Ebitenmobileview.java)
       at com.rpgsnack.runtime.mobile.EbitenSurfaceView$EbitenRenderer.onDrawFrame(EbitenSurfaceView.java:30)
       at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1608)
       at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1299)
```

Reported by @wasedaigo

**Comment by hajimehoshi** [comment]
It looks like this was fixed by https://github.com/hajimehoshi/ebiten/commit/802693fa20ad0a1cb410981440155c189e8d3082.
