### ISSUE TITLE
test: Strange error on Wasm tests on Travis CI

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1027]
https://travis-ci.org/hajimehoshi/ebiten/builds/626760475

```
Error: Go program has already exited
    at global.Go._resume (http://localhost:40559/wasm_exec.js:484:11)
    at http://localhost:40559/wasm_exec.js:269:14
```

**Comment by hajimehoshi** [comment]
Oops this was not fixed yet.

**Comment by hajimehoshi** [comment]
* `github.com/hajimehoshi/ebiten/audio/internal/convert`
* `github.com/hajimehoshi/ebiten/internal/buffered`

**Comment by hajimehoshi** [comment]
The latest change fixes the issue for `buffered`. The error for `convert` has disappeared with unknown reasons.
