### ISSUE TITLE
shareable: panic: Alloc result must not be nil at TryAlloc

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1028]
```
panic: shareable: Alloc result must not be nil at TryAlloc

goroutine 11 [running]:
github.com/hajimehoshi/ebiten/internal/shareable.(*backend).TryAlloc(0xc0000de000, 0x280, 0x480, 0x457bb28, 0x0)
        /Users/hajimehoshi/ebiten/internal/shareable/image.go:119 +0x20d
github.com/hajimehoshi/ebiten/internal/shareable.(*Image).allocate(0xc00504ed20, 0x2d0001)
        /Users/hajimehoshi/ebiten/internal/shareable/image.go:511 +0x145
github.com/hajimehoshi/ebiten/internal/shareable.(*Image).replacePixels(0xc00504ed20, 0xc000b90000, 0x2d0000, 0x2d0000)
        /Users/hajimehoshi/ebiten/internal/shareable/image.go:374 +0x10a
github.com/hajimehoshi/ebiten/internal/shareable.(*Image).ReplacePixels(0xc00504ed20, 0xc000b90000, 0x2d0000, 0x2d0000)
        /Users/hajimehoshi/ebiten/internal/shareable/image.go:363 +0x9f
github.com/hajimehoshi/ebiten/internal/buffered.(*Image).ReplacePixels(0xc0055b3e80, 0xc000b90000, 0x2d0000, 0x2d0000)
        /Users/hajimehoshi/ebiten/internal/buffered/image.go:218 +0xa8
github.com/hajimehoshi/ebiten.(*mipmap).replacePixels(0xc00504ed50, 0xc000b90000, 0x2d0000, 0x2d0000)
        /Users/hajimehoshi/ebiten/mipmap.go:68 +0x4d
github.com/hajimehoshi/ebiten.(*Image).ReplacePixels(0xc0055b3ec0, 0xc000b90000, 0x2d0000, 0x2d0000, 0x2d0000, 0xc00014e890)
        /Users/hajimehoshi/ebiten/image.go:457 +0xbd
github.com/hajimehoshi/ebiten.NewImageFromImage(0x46034a0, 0xc0002945a0, 0x0, 0xc0002945a0, 0x0, 0x0)
        /Users/hajimehoshi/ebiten/image.go:537 +0x15d
```

This was hard to create a case to reproduce this, but we found one.

The culprit is 63f9ac2ccc2a48281d3851991ea1aa4ae4201aeb

**Comment by hajimehoshi** [comment]
@wasedaigo reported
