### ISSUE TITLE
mobile: Fail to run games on iPad 2 (A1395)

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1054]
Metal is not supported!

**Comment by hajimehoshi** [comment]
Allowed to use OpenGL, but I found another error:

```
opengl: glCreateShader failed: shader type: 35633
goroutine 9 [running]:
runtime/debug.Stack(0x4002fc6c, 0x362f08, 0x40018060)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x80
github.com/hajimehoshi/ebiten/internal/uidriver/mobile.(*UserInterface).run.func1(0x4002ff9c)
        /Users/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/internal/uidriver/mobile/ui.go:219 +0x3c
panic(0x362f08, 0x40018060)
        /usr/local/go/src/runtime/panic.go:679 +0x1a0
github.com/hajimehoshi/ebiten/internal/graphicsdriver/opengl.(*openGLState).reset(0x7c7c00, 0x7c7c4c, 0x0, 0x0)
        /Users/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/internal/graphicsdriver/opengl/program.go:196 +0x6ec
github.com/hajimehoshi/ebiten/internal/graphicsdriver/opengl.(*Driver).Reset(0x7c7c00, 0xb0900, 0x1)
        /Users/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/internal/graphicsdriver/opengl/driver.go:104 +0x28
github.com/hajimehoshi/ebiten/internal/graphicscommand.ResetGraphicsDriverState(...)
        /Users/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/internal/graphicscommand/command.go:612
github.com/hajimehoshi/ebiten/internal/restorable.InitializeGraphicsDriverState(...)
        /Users/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/internal/restorable/images.go:220
github.com/hajimehoshi/ebiten/internal/shareable.BeginFrame.func1()
        /Users/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/internal/shareable/image.go:555 +0x40
sync.(*Once).doSlow(0x7d7a18, 0x4002fe64)
        /usr/local/go/src/sync/once.go:66 +0xb4
sync.(*Once).Do(0x7d7a18, 0x4002fe64)
        /usr/local/go/src/sync/once.go:57 +0x44
github.com/hajimehoshi/ebiten/internal/shareable.BeginFrame(0x0, 0x0)
        /Users/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/internal/shareable/image.go:554 +0x9c
github.com/hajimehoshi/ebiten/internal/mipmap.BeginFrame(...)
        /Users/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/internal/mipmap/mipmap.go:36
github.com/hajimehoshi/ebiten/internal/buffered.BeginFrame(0x10, 0x3774e0)
        /Users/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/internal/buffered/image.go:36 +0x14
github.com/hajimehoshi/ebiten.(*uiContext).Update(0x7c7818, 0x400160f0, 0x2, 0x0)
        /Users/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/uicontext.go:236 +0x14
github.com/hajimehoshi/ebiten/internal/uidriver/mobile.(*UserInterface).update(0x7c7b98, 0x478420, 0x7c7818, 0x0, 0x0)
        /Users/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/internal/uidriver/mobile/ui.go:309 +0x178
github.com/hajimehoshi/ebiten/internal/uidriver/mobile.(*UserInterface).run(0x7c7b98, 0x140, 0xf0, 0x55555555, 0x3ff55555, 0x478420, 0x7c7818, 0x41ea00, 0x0, 0x0)
        /Users/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/internal/uidriver/mobile/ui.go:252 +0x1b4
github.com/hajimehoshi/ebiten/internal/uidriver/mobile.(*UserInterface).RunWithoutMainLoop.func1(0x40085340, 0x7c7b98, 0x140, 0xf0, 0x55555555, 0x3ff55555, 0x478420, 0x7c7818)
        /Users/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/internal/uidriver/mobile/ui.go:204 +0x7c
created by github.com/hajimehoshi/ebiten/internal/uidriver/mobile.(*UserInterface).RunWithoutMainLoop
        /Users/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/internal/uidriver/mobile/ui.go:201 +0x78
```

**Comment by hajimehoshi** [comment]
`gldebug` tag did not help unfortunately :-/

**Comment by hajimehoshi** [comment]
I think I found the cause: on mobile, the offscreen is not cleared very well.

**Comment by hajimehoshi** [comment]
iPad 2 is no longer supported.
