### ISSUE TITLE
panic: opengl: mapPixelBuffer failed

### ISSUE THREAD

**Issue by servusDei2018** [hajimehoshi/ebiten#1095]
I get this error when I run my code, which runs fine (the graphics work) until I put on screen the images of my main user interface, at which it crashes and I get:
```
goroutine 19 [running]:
github.com/hajimehoshi/ebiten/internal/graphicsdriver/opengl.(*pboState).mapPBO(0x784f58, 0x1577be0)
	/home/###/go/src/github.com/hajimehoshi/ebiten/internal/graphicsdriver/opengl/pbo_desktop.go:46 +0x138
github.com/hajimehoshi/ebiten/internal/graphicsdriver/opengl.(*Image).ReplacePixels(0x1577be0, 0x17e60f8, 0x2, 0x2)
	/home/###/go/src/github.com/hajimehoshi/ebiten/internal/graphicsdriver/opengl/image.go:115 +0x58
github.com/hajimehoshi/ebiten/internal/graphicscommand.(*replacePixelsCommand).Exec(0x15ec130, 0x3c, 0x0, 0x0)
	/home/###/go/src/github.com/hajimehoshi/ebiten/internal/graphicscommand/command.go:447 +0x44
github.com/hajimehoshi/ebiten/internal/graphicscommand.(*commandQueue).Flush(0x7853b0)
	/home/###/go/src/github.com/hajimehoshi/ebiten/internal/graphicscommand/command.go:265 +0x388
github.com/hajimehoshi/ebiten/internal/graphicscommand.FlushCommands(...)
	/home/###/go/src/github.com/hajimehoshi/ebiten/internal/graphicscommand/command.go:298
github.com/hajimehoshi/ebiten/internal/restorable.ResolveStaleImages()
	/home/###/go/src/github.com/hajimehoshi/ebiten/internal/restorable/images.go:55 +0x20
github.com/hajimehoshi/ebiten/internal/shareable.EndFrame(0x140c0c0, 0x14733c0)
	/home/###/go/src/github.com/hajimehoshi/ebiten/internal/shareable/image.go:546 +0x20
github.com/hajimehoshi/ebiten/internal/buffered.EndFrame(...)
	/home/###/go/src/github.com/hajimehoshi/ebiten/internal/buffered/image.go:43
github.com/hajimehoshi/ebiten.(*uiContext).Update(0x1490750, 0x17fccb0, 0x0, 0x0)
	/home/###/go/src/github.com/hajimehoshi/ebiten/uicontext.go:129 +0x28c
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).update(0x5b8948, 0x3d4e28, 0x1490750, 0x0, 0x0)
	/home/###/go/src/github.com/hajimehoshi/ebiten/internal/uidriver/glfw/ui.go:846 +0x1a8
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).loop(0x5b8948, 0x3d4e28, 0x1490750, 0x0, 0x0)
	/home/###/go/src/github.com/hajimehoshi/ebiten/internal/uidriver/glfw/ui.go:888 +0xac
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).run(0x5b8948, 0x500, 0x400, 0x0, 0x3ff00000, 0x35face, 0x12, 0x3d4e28, 0x1490750, 0x5bd7f8, ...)
	/home/###/go/src/github.com/hajimehoshi/ebiten/internal/uidriver/glfw/ui.go:746 +0x140
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).Run.func1(0x14707c8, 0x148f980, 0x5b8948, 0x500, 0x400, 0x0, 0x3ff00000, 0x35face, 0x12, 0x3d4e28, ...)
	/home/###/go/src/github.com/hajimehoshi/ebiten/internal/uidriver/glfw/ui.go:610 +0xa4
created by github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).Run
	/home/###/go/src/github.com/hajimehoshi/ebiten/internal/uidriver/glfw/ui.go:607 +0x150
```
It seems like it's an OpenGL issue, but I can't find documentation for this online, and the error isn't very verbose.

**Comment by servusDei2018** [comment]
It would be nice if I could see which part of my code causes this issue, or even to get an error returned instead of a panic.

**Comment by servusDei2018** [comment]
Update: After running `go get github.com/hajimehoshi/ebiten/...` (after backing up the current version as I use it in a production environment), my issue was resolved. I noticed that the file that raised that panic no longer exists in the stable version. Thankyou!
