### ISSUE TITLE
Trying to render text crashes the program

### ISSUE THREAD

**Issue by SamusAranX** [hajimehoshi/ebiten#1097]
I'm trying to render text using this font: https://www.fontsquirrel.com/fonts/varela-round
I used go-bindata to wrap the .otf file in a code file like this: https://gist.github.com/SamusAranX/732fba5f9862a905f0e73cbeaec50fdc

I load the font file in my `main()` like this:
```go
varela, err := Asset("ui/fonts/VarelaRound-Regular.otf")
if err != nil {
	panic(err)
}

varelaFont, err := sfnt.Parse(varela)
if err != nil {
	panic(err)
}

varelaOptions := opentype.FaceOptions{ Size: 14, DPI: 72, Hinting: font.HintingFull }
varelaFontFace, err = opentype.NewFace(varelaFont, &varelaOptions)
if err != nil {
	panic(err)
}
```

Later, in my `update()`, this line of code reliably crashes the program:
```go
text.Draw(screen, "Hello World", varelaFontFace, 0, 48, color.White)
```

Any ideas what I might be doing wrong?
Here's the error message in full:
```
GOROOT=/usr/local/Cellar/go/1.14/libexec #gosetup
GOPATH=/Users/hallo/go #gosetup
/usr/local/Cellar/go/1.14/libexec/bin/go build -i -o /private/var/folders/jy/mdtk2_ns2vz24rm9vhl_kdy00000gn/T/___Build_and_Run . #gosetup
/private/var/folders/jy/mdtk2_ns2vz24rm9vhl_kdy00000gn/T/___Build_and_Run #gosetup
panic: not implemented

goroutine 6 [running]:
golang.org/x/image/font/opentype.(*Face).GlyphBounds(0xc000102300, 0xc000000046, 0xc000000046, 0x46d2b80, 0xc0000a6100)
        /Users/hallo/go/src/golang.org/x/image/font/opentype/face.go:90 +0x76
github.com/hajimehoshi/ebiten/text.getGlyphBounds(0x442cbc0, 0xc000102300, 0xc000000046, 0x46d2b80)
        /Users/hallo/go/src/github.com/hajimehoshi/ebiten/text/text.go:80 +0x10e
github.com/hajimehoshi/ebiten/text.getGlyphImages(0x442cbc0, 0xc000102300, 0xc00014d9a8, 0xc, 0x20, 0x20, 0x0, 0x0)
        /Users/hallo/go/src/github.com/hajimehoshi/ebiten/text/text.go:125 +0x357
github.com/hajimehoshi/ebiten/text.Draw(0xc000020900, 0x43a6746, 0xc, 0x442cbc0, 0xc000102300, 0x0, 0x30, 0x4424be0, 0xc000092d64)
        /Users/hallo/go/src/github.com/hajimehoshi/ebiten/text/text.go:281 +0xc5
main.update(0xc000020900, 0xc000079380, 0xc000048bb0)
        /Users/hallo/GitHub/FastLauncher/main.go:55 +0x322
github.com/hajimehoshi/ebiten.(*imageDumper).update(0xc000020580, 0xc000020900, 0x0, 0x415b469)
        /Users/hallo/go/src/github.com/hajimehoshi/ebiten/imagedumper_desktop.go:106 +0x4e
github.com/hajimehoshi/ebiten.(*defaultGame).Update(0xc00000e4a0, 0xc000020900, 0x46d2b80, 0x0)
        /Users/hallo/go/src/github.com/hajimehoshi/ebiten/uicontext.go:37 +0x33
github.com/hajimehoshi/ebiten.(*uiContext).update(0x46a6b20, 0xc000094120, 0x0, 0x0)
        /Users/hallo/go/src/github.com/hajimehoshi/ebiten/uicontext.go:262 +0x150
github.com/hajimehoshi/ebiten.(*uiContext).Update(0x46a6b20, 0xc000094120, 0x0, 0x0)
        /Users/hallo/go/src/github.com/hajimehoshi/ebiten/uicontext.go:239 +0xb4
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).update(0x46a1b80, 0x442ada0, 0x46a6b20, 0xc00006e180, 0x0)
        /Users/hallo/go/src/github.com/hajimehoshi/ebiten/internal/uidriver/glfw/ui.go:751 +0x1d9
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).loop(0x46a1b80, 0x442ada0, 0x46a6b20, 0x0, 0x0)
        /Users/hallo/go/src/github.com/hajimehoshi/ebiten/internal/uidriver/glfw/ui.go:797 +0xce
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).run(0x46a1b80, 0x442ada0, 0x46a6b20, 0x0, 0x0)
        /Users/hallo/go/src/github.com/hajimehoshi/ebiten/internal/uidriver/glfw/ui.go:669 +0x232
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).Run.func1(0xc0000131c0, 0xc000062480, 0x46a1b80, 0x442ada0, 0x46a6b20)
        /Users/hallo/go/src/github.com/hajimehoshi/ebiten/internal/uidriver/glfw/ui.go:535 +0x85
created by github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).Run
        /Users/hallo/go/src/github.com/hajimehoshi/ebiten/internal/uidriver/glfw/ui.go:532 +0x1ba

Process finished with exit code 2
```

**Comment by SamusAranX** [comment]
It just occurred to me to check the opentype package:
```go
// GlyphBounds satisfies the font.Face interface.
func (f *Face) GlyphBounds(r rune) (bounds fixed.Rectangle26_6, advance fixed.Int26_6, ok bool) {
	advance, ok = f.GlyphAdvance(r)
	if !ok {
		return bounds, advance, ok
	}
	panic("not implemented")
}
```

Turns out it's a Go problem, not an ebiten problem.
Closing this.

**Comment by hajimehoshi** [comment]
Yes, the OpenType font parser is not implemented yet unfortunately.

BTW I have a CL but I'm not sure when this will be reviewed: https://go-review.googlesource.com/c/image/+/217817
