### ISSUE TITLE
ebiten: Time out on TravisCI on Wasm

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1138]
https://travis-ci.org/github/hajimehoshi/ebiten/builds/676552778

```
=== RUN   TestFloat32Reader
--- PASS: TestFloat32Reader (0.56s)
=== RUN   TestResampling
--- PASS: TestResampling (3.23s)
PASS
http://localhost:35095/wasm_exec.js:541:10 Uncaught
Error: Go program has already exited
    at global.Go._resume (http://localhost:35095/wasm_exec.js:542:11)
    at http://localhost:35095/wasm_exec.js:308:14
[wasmbrowsertest]: 2020/04/18 12:12:30 main.go:150: context canceled
ok  	github.com/hajimehoshi/ebiten/audio/internal/convert	4.771s
```

**Comment by hajimehoshi** [comment]
That's too bad, I could not reproduce this on my machine :-/

**Comment by hajimehoshi** [comment]
Oops, the true reason why TravisCI fails was:

```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
The build has been terminated
```
