### ISSUE TITLE
cmd/ebitenmobile: Rare EbitenMobileView crash

### ISSUE THREAD

**Issue by wasedaigo** [hajimehoshi/ebiten#1185]
This is a recently observed error on Android devices.
Not a serious issue, but this is affecting 11 users for our game so far.

```
Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'int android.view.InputDevice.getSources()' on a null object reference
****.mobile.EbitenView.onInputDeviceRemoved (EbitenView.java:348)
android.hardware.input.InputManager$InputDeviceListenerDelegate.handleMessage (InputManager.java:1161)
android.os.Handler.dispatchMessage (Handler.java:106)
android.os.Looper.loop (Looper.java:164)
android.app.ActivityThread.main (ActivityThread.java:6687)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:438)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:810)
```

**Comment by hajimehoshi** [comment]
Reproduced by disabling Bluetooth.

```
2020-06-09 23:23:27.967 17495-17495/com.hajimehoshi.goinovation E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.hajimehoshi.goinovation, PID: 17495
    java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.InputDevice.getSources()' on a null object reference
        at com.hajimehoshi.goinovation.mobile.EbitenView.onInputDeviceRemoved(EbitenView.java:348)
        at android.hardware.input.InputManager$InputDeviceListenerDelegate.handleMessage(InputManager.java:1156)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6518)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```
