### ISSUE TITLE
Crash when dragging a window to another 4K monitor

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1198]
Reported by @essial

`panic: graphics: x must be positive`

```
goroutine 9 [running]:
github.com/hajimehoshi/ebiten/internal/graphics.InternalImageSize(0x0, 0x1)
        /Users/lunaticedit/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.11.0-alpha.2.0.20200102072751-e66f1fb71e2e/internal/graphics/math.go:26 +0x7a
github.com/hajimehoshi/ebiten/internal/graphicscommand.(*Image).InternalSize(0xc0000b9980, 0x8, 0xc0016b96e0)
        /Users/lunaticedit/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.11.0-alpha.2.0.20200102072751-e66f1fb71e2e/internal/graphicscommand/image.go:116 +0x79
github.com/hajimehoshi/ebiten/internal/restorable.fillImage(0xc0000b9980, 0xc000000000)
        /Users/lunaticedit/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.11.0-alpha.2.0.20200102072751-e66f1fb71e2e/internal/restorable/image.go:250 +0xe6
github.com/hajimehoshi/ebiten/internal/restorable.NewScreenFramebufferImage(0x0, 0x0, 0x4616800)
        /Users/lunaticedit/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.11.0-alpha.2.0.20200102072751-e66f1fb71e2e/internal/restorable/image.go:199 +0x160
github.com/hajimehoshi/ebiten/internal/shareable.(*Image).allocate(0xc002630030, 0x100)
        /Users/lunaticedit/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.11.0-alpha.2.0.20200102072751-e66f1fb71e2e/internal/shareable/image.go:485 +0x486
github.com/hajimehoshi/ebiten/internal/shareable.(*Image).ensureNotShared(0xc002630030)
        /Users/lunaticedit/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.11.0-alpha.2.0.20200102072751-e66f1fb71e2e/internal/shareable/image.go:190 +0x3ce
github.com/hajimehoshi/ebiten/internal/shareable.(*Image).DrawTriangles(0xc002630030, 0xc0016b9140, 0xc005e19140, 0x30, 0x433b0, 0x4c5b5c8, 0x6, 0x6, 0x0, 0x2, ...)
        /Users/lunaticedit/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.11.0-alpha.2.0.20200102072751-e66f1fb71e2e/internal/shareable/image.go:293 +0x70
github.com/hajimehoshi/ebiten/internal/buffered.(*Image).DrawTriangles(0xc002656000, 0xc002113300, 0xc005e19140, 0x30, 0x433b0, 0x4c5b5c8, 0x6, 0x6, 0x0, 0x2, ...)
        /Users/lunaticedit/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.11.0-alpha.2.0.20200102072751-e66f1fb71e2e/internal/buffered/image.go:224 +0x121
github.com/hajimehoshi/ebiten.(*mipmap).drawImage(0xc002630060, 0xc0016b96b0, 0x0, 0x0, 0x320, 0x258, 0xc001e4fd80, 0x0, 0x2, 0x3)
        /Users/lunaticedit/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.11.0-alpha.2.0.20200102072751-e66f1fb71e2e/mipmap.go:137 +0x39b
github.com/hajimehoshi/ebiten.(*Image).DrawImage(0xc002656040, 0xc002113340, 0xc001e4fd80, 0x0, 0x0)
        /Users/lunaticedit/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.11.0-alpha.2.0.20200102072751-e66f1fb71e2e/image.go:202 +0x4e1
github.com/hajimehoshi/ebiten.(*uiContext).update(0x4fbdcc0, 0xc00479da60, 0xc0046e2401, 0xc00479da60)
        /Users/lunaticedit/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.11.0-alpha.2.0.20200102072751-e66f1fb71e2e/uicontext.go:301 +0x3af
github.com/hajimehoshi/ebiten.(*uiContext).Update(0x4fbdcc0, 0xc00479da60, 0x0, 0x0)
        /Users/lunaticedit/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.11.0-alpha.2.0.20200102072751-e66f1fb71e2e/uicontext.go:237 +0x4c
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).update(0x4ca6580, 0x48278e0, 0x4fbdcc0, 0x0, 0x0)
        /Users/lunaticedit/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.11.0-alpha.2.0.20200102072751-e66f1fb71e2e/internal/uidriver/glfw/ui.go:738 +0x1d9
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).loop(0x4ca6580, 0x48278e0, 0x4fbdcc0, 0x0, 0x0)
        /Users/lunaticedit/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.11.0-alpha.2.0.20200102072751-e66f1fb71e2e/internal/uidriver/glfw/ui.go:784 +0xce
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).run(0x4ca6580, 0x48278e0, 0x4fbdcc0, 0x0, 0x0)
        /Users/lunaticedit/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.11.0-alpha.2.0.20200102072751-e66f1fb71e2e/internal/uidriver/glfw/ui.go:656 +0x226
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).Run.func1(0xc002ebf200, 0xc002ed57a0, 0x4ca6580, 0x48278e0, 0x4fbdcc0)
        /Users/lunaticedit/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.11.0-alpha.2.0.20200102072751-e66f1fb71e2e/internal/uidriver/glfw/ui.go:524 +0x85
created by github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).Run
        /Users/lunaticedit/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.11.0-alpha.2.0.20200102072751-e66f1fb71e2e/internal/uidriver/glfw/ui.go:521 +0x171
```

> if I launch the game on my secondary 1080p monitor, it shows nothing, and when i try to drag back to main 4k monitor it crashes

> it's 100% reproducable so i just did it agian to grab the stack trace
> but even before then, it's just straight up a blank screen on the secondary monitor
> oh if i run it on primary, it works, if i drag to secondary it's ag ray screen
> if i try to drag it back it crashes

**Comment by hajimehoshi** [comment]
The bug was reproduced by `v1.11.0-alpha.2.0.20200102072751-e66f1fb71e2e` but it looks like this was already fixed by the current master.
