### ISSUE TITLE
Crash on macOS (Failed to initialize OpenGL?)

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1241]
```
Unable to create basic Accelerated OpenGL renderer.
Unable to create basic Accelerated OpenGL renderer.
Core Image is now using the software OpenGL renderer. This will be slow.
GLFW: An invalid error was not accepted by the caller: FormatUnavailable: NSGL: Failed to find a suitable pixel format
GLFW: Please report this bug in the Go package immediately.
panic: FormatUnavailable: NSGL: Failed to find a suitable pixel format

goroutine 1 [running, locked to thread]:
github.com/go-gl/glfw/v3.3/glfw.acceptError(0xc000143c30, 0x2, 0x2, 0x0, 0x0)
        /Users/hajimehoshi/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20200707082815-5321531c36a2/error.go:178 +0x201
github.com/go-gl/glfw/v3.3/glfw.CreateWindow(0x10, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/hajimehoshi/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20200707082815-5321531c36a2/window.go:350 +0x1aa
github.com/hajimehoshi/ebiten/internal/glfw.CreateWindow(0x10, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/hajimehoshi/ebiten/internal/glfw/glfw_notwindows.go:243 +0x7c
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).createWindow(0x46f9980, 0xf, 0x0)
        /Users/hajimehoshi/ebiten/internal/uidriver/glfw/ui.go:619 +0x54
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).run.func1(0xc000143db8, 0xc000143d90)
        /Users/hajimehoshi/ebiten/internal/uidriver/glfw/ui.go:701 +0x1bd
github.com/hajimehoshi/ebiten/internal/thread.(*Thread).Loop(0xc00008f460, 0x446ed80, 0xc0003a0100)
        /Users/hajimehoshi/ebiten/internal/thread/thread.go:47 +0x3b
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).Run(0x46f9980, 0x446ef80, 0x46fe740, 0x0, 0x4391fe0)
        /Users/hajimehoshi/ebiten/internal/uidriver/glfw/ui.go:599 +0x1b9
github.com/hajimehoshi/ebiten.runGame(0x446bb40, 0xc000091bc0, 0x0, 0xaa195a0, 0xc0000a4690)
        /Users/hajimehoshi/ebiten/run.go:302 +0x82
github.com/hajimehoshi/ebiten.RunGame(0x446bb80, 0xc0000a4690, 0x0, 0x0)
        /Users/hajimehoshi/ebiten/run.go:293 +0xa7
main.main()
        /Users/hajimehoshi/ebiten/examples/blocks/main.go:46 +0xf6
exit status 2
```

```
$ screenfetch 
                               
                 -/+:.          hajimehoshi@Hajimes-MacBook-Pro-2020
                :++++.          OS: 64bit Mac OS X 10.15.5 19F101
               /+++/.           Kernel: x86_64 Darwin 19.5.0
       .:-::- .+/:-``.::-       Uptime: 4d 22h 19m
    .:/++++++/::::/++++++/:`    Packages: 51
  .:///////////////////////:`   Shell: bash 3.2.57
  ////////////////////////`     Resolution: 2560x1600 
 -+++++++++++++++++++++++`      DE: Aqua
 /++++++++++++++++++++++/       WM: Quartz Compositor
 /sssssssssssssssssssssss.      WM Theme: Blue
 :ssssssssssssssssssssssss-     Disk: 11G / 1.0T (2%)
  osssssssssssssssssssssssso/`  CPU: Intel Core i7-1068NG7 @ 2.30GHz
  `syyyyyyyyyyyyyyyyyyyyyyyy+`  GPU: Intel Iris Plus Graphics 
   `ossssssssssssssssssssss/    RAM: 17696MiB / 32768MiB
     :ooooooooooooooooooo+.    
      `:+oo+/:-..-:/+o+/-      
```

**Comment by hajimehoshi** [comment]
It looks like another process initializing OpenGL did not finish yet?

**Comment by hajimehoshi** [comment]
See #1243: Rebooting Chrome changed the situation.
