### ISSUE TITLE
writing image is not possible

### ISSUE THREAD

**Issue by kulti** [hajimehoshi/ebiten#1264]
Hi.

It looks like it is not possible to write ebiten.Image.

Simple example:
```
func main() {
	img, _ := ebiten.NewImage(10, 10, ebiten.FilterDefault)
	img.Fill(color.Black)

	buf := &bytes.Buffer{}
	png.Encode(buf, img)
}
```

panicked with:
```
panic: buffered: the command queue is not available yet at At

goroutine 1 [running, locked to thread]:
github.com/hajimehoshi/ebiten/internal/buffered.(*Image).At(0xc00011a000, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/abakin/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.11.4/internal/buffered/image.go:142 +0x262
github.com/hajimehoshi/ebiten.(*Image).At(0xc00011a040, 0x0, 0x0, 0xa, 0xa)
	/Users/abakin/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.11.4/image.go:403 +0x8c
image/png.opaque(0x41e0340, 0xc00011a040, 0xc000010010)
	/usr/local/go/src/image/png/writer.go:78 +0xe2
image/png.(*Encoder).Encode(0xc000116040, 0x41db860, 0xc00011c030, 0x41e0340, 0xc00011a040, 0x0, 0x0)
	/usr/local/go/src/image/png/writer.go:613 +0x59b
image/png.Encode(...)
	/usr/local/go/src/image/png/writer.go:561
main.main()
	/tmp/eb/ebiten.go:16 +0xe7
exit status 2
```

I found that happens, because ebiten.Image expects to BeginFrame before drawing.

My use case of writing image is unit-testing. I create a scene, add some objects, and draw the scene. Then I want to compare image with expected image.

**Comment by hajimehoshi** [comment]
This seems duplicated with #790 

For unit tests, you can run the loop in the test like this:

```go
var regularTermination = errors.New("regular termination")

type game struct {
        m    *testing.M
        code int
}

func (g *game) Update(*ebiten.Image) error {
        g.code = g.m.Run()
        return regularTermination
}

func (*game) Draw(*ebiten.Image) {
}

func (*game) Layout(int, int) (int, int) {
        return 320, 240
}

func MainWithRunLoop(m *testing.M) {
        testflock.Lock()
        defer testflock.Unlock()

        // Run an Ebiten process so that (*Image).At is available.                                                                                                                                                                            
        g := &game{
                m: m,
        }
        if err := ebiten.RunGame(g); err != nil && err != regularTermination {
                panic(err)
        }
        os.Exit(g.code)
}
```

**Comment by kulti** [comment]
Thank you for your suggestion. It works locally.

But RunGame creates a window. I try to run tests on CI and they do not work because of some X11 dependencies. Probably it can be fixed, but I try to find another way to test my cases on CI.

I close this issue as a duplicate. Also, we have a workaround to run tests locally. If I found another way to test it on CI I post it here.
