### ISSUE TITLE
Wasm tests sometimes time out on Windows

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1313]
https://github.com/hajimehoshi/ebiten/runs/999152695

```
*** Test killed: ran too long (11m0s).
```

Are there race conditions somewhere?

**Comment by hajimehoshi** [comment]
Let's test with `-race` wherever possible.

**Comment by hajimehoshi** [comment]
```
http://localhost:50127/wasm_exec.js:483:10 Uncaught
Error: Go program has already exited
    at global.Go._resume (http://localhost:50127/wasm_exec.js:484:11)
    at http://localhost:50127/wasm_exec.js:269:14
[wasmbrowsertest]: 2020/08/19 13:47:14 main.go:169: context canceled
```

Even if skipping the heavy tests, the timeout happens. Isn't this an issue in wasmbrowsertest?

**Comment by hajimehoshi** [comment]
Now the tests succeeded. Probably #2274 changed the situation.
