### ISSUE TITLE
shader: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by tomlister** [hajimehoshi/ebiten#1326]
Code: https://gist.github.com/tomlister/2a3635f0a0f700def10b5670b252667e
Shader: https://gist.github.com/tomlister/b9603a4e215035439b0f8ab680136be8
Stacktrace: 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x421e0f9]

goroutine 22 [running]:
github.com/hajimehoshi/ebiten.(*Image).DrawRectShader(0xc000bee740, 0x280, 0x1e0, 0x0, 0xc0040835e0)
	/Users/tom.lister/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.12.0-alpha.10.0.20200817193359-c921a63c21a3/image.go:545 +0x299
main.caveLightingRenderCode(0xc00465d710, 0x461bc88, 0xc0001c4000, 0x45f5a40, 0xa, 0x280, 0x1e0, 0xc000bee740)
	/Users/tom.lister/tile/cave.go:143 +0x52e
main.PipelineWrapper.update(0x461bc88, 0xc0001c4000, 0x45f5a40, 0xa, 0x280, 0x1e0, 0xc000bee740, 0x0, 0xc004083948)
	/Users/tom.lister/tile/pipeline.go:70 +0x522
github.com/hajimehoshi/ebiten.(*imageDumper).update(0xc000317200, 0xc000bee740, 0xc004083c60, 0x421ca79)
	/Users/tom.lister/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.12.0-alpha.10.0.20200817193359-c921a63c21a3/imagedumper_desktop.go:106 +0x4e
github.com/hajimehoshi/ebiten.(*defaultGame).Update(0xc000354000, 0xc000bee740, 0x4a8e480, 0x0)
	/Users/tom.lister/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.12.0-alpha.10.0.20200817193359-c921a63c21a3/uicontext.go:37 +0x33
github.com/hajimehoshi/ebiten.(*uiContext).update(0x4a70540, 0x0, 0x0)
	/Users/tom.lister/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.12.0-alpha.10.0.20200817193359-c921a63c21a3/uicontext.go:296 +0x122
github.com/hajimehoshi/ebiten.(*uiContext).Update(0x4a70540, 0xc004083da0, 0x46bf080)
	/Users/tom.lister/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.12.0-alpha.10.0.20200817193359-c921a63c21a3/uicontext.go:241 +0xaa
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).update(0x4a6b3a0, 0x20001, 0x1)
	/Users/tom.lister/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.12.0-alpha.10.0.20200817193359-c921a63c21a3/internal/uidriver/glfw/ui.go:842 +0x266
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).loop(0x4a6b3a0, 0x0, 0x0)
	/Users/tom.lister/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.12.0-alpha.10.0.20200817193359-c921a63c21a3/internal/uidriver/glfw/ui.go:888 +0xd2
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).run(0x4a6b3a0, 0x0, 0x0)
	/Users/tom.lister/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.12.0-alpha.10.0.20200817193359-c921a63c21a3/internal/uidriver/glfw/ui.go:757 +0x2e4
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).Run.func1(0xc0000219f0, 0xc0001aaae0, 0x4a6b3a0)
	/Users/tom.lister/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.12.0-alpha.10.0.20200817193359-c921a63c21a3/internal/uidriver/glfw/ui.go:593 +0x9e
created by github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).Run
	/Users/tom.lister/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.12.0-alpha.10.0.20200817193359-c921a63c21a3/internal/uidriver/glfw/ui.go:590 +0x17d
```

**Comment by tomlister** [comment]
Fixed.
