### ISSUE TITLE
Raspberry Pi Support

### ISSUE THREAD

**Issue by goisgreat** [hajimehoshi/ebiten#1401]
I did what I usually do to install go:
```bash
go get -u github.com/hajimehoshi/ebiten/
```
but I got an eror:
```
# pkg-config --cflags  -- gl gl
Package gl was not found in the pkg-config search path.
Perhaps you should add the directory containing `gl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gl' found
Package gl was not found in the pkg-config search path.
Perhaps you should add the directory containing `gl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gl' found
pkg-config: exit status 1
# github.com/go-gl/glfw/v3.3/glfw
In file included from github.com/go-gl/glfw/v3.3/glfw/native_linbsd.go:10:0:
./glfw/include/GLFW/glfw3native.h:114:21: fatal error: GL/glx.h: No such file or directory
  #include <GL/glx.h>
                     ^
compilation terminated.
```
EDIT: maybe I should do something so it *successfully* includes `GL/glx.h`

**Comment by hajimehoshi** [comment]
Raspberry Pi is already supported. See https://ebiten.org/documents/install.html?os=linux#Debian_/_Ubuntu

**Comment by goisgreat** [comment]
> Raspberry Pi is already supported. See https://ebiten.org/documents/install.html?os=linux#Debian_/_Ubuntu

Thanks!

**Comment by goisgreat** [comment]
Wait.... I got a runtime error:
```
panic: NotInitialized: The GLFW library is not initialized

goroutine 1 [running]:
github.com/go-gl/glfw/v3.3/glfw.acceptError(0x0, 0x0, 0x0, 0x0, 0x10006)
	/home/pi/go/src/github.com/go-gl/glfw/v3.3/glfw/error.go:174 +0x1a4
github.com/go-gl/glfw/v3.3/glfw.panicError(...)
	/home/pi/go/src/github.com/go-gl/glfw/v3.3/glfw/error.go:185
github.com/go-gl/glfw/v3.3/glfw.WindowHint(0x20004, 0x0)
	/home/pi/go/src/github.com/go-gl/glfw/v3.3/glfw/window.go:275 +0x40
github.com/hajimehoshi/ebiten/internal/glfw.WindowHint(...)
	/home/pi/go/src/github.com/hajimehoshi/ebiten/internal/glfw/glfw_notwindows.go:329
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.initialize(0x80c540, 0x5582c)
	/home/pi/go/src/github.com/hajimehoshi/ebiten/internal/uidriver/glfw/ui.go:133 +0x3c
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.init.1()
	/home/pi/go/src/github.com/hajimehoshi/ebiten/internal/uidriver/glfw/ui.go:120 +0x14
```

**Comment by hajimehoshi** [comment]
Thanks. Which Raspberry Pi are you using?

**Comment by goisgreat** [comment]
Um.... This is embarrassing, but I think it fixed itself! I simply grabbed the latest version of ebiten and it worked fine. I had `go.mod` doing ebiten v2.0, so there must have been a problem there. I guess all is well that ends well!
