### ISSUE TITLE
shareable: Crash at makeImagesShared

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1421]
```
runtime error: invalid memory address or nil pointer dereference
goroutine 13 [running]:
runtime/debug.Stack(0x40003d7a28, 0x7a41733cc0, 0x7a41a2bee0)
        runtime/debug/stack.go:24 +0x80
github.com/hajimehoshi/ebiten/v2/internal/uidriver/mobile.(*UserInterface).run.func1(0x40003d7f98)
        github.com/hajimehoshi/ebiten/v2@v2.1.0-alpha.3/internal/uidriver/mobile/ui.go:258 +0x40
panic(0x7a41733cc0, 0x7a41a2bee0)
        runtime/panic.go:969 +0x114
github.com/hajimehoshi/ebiten/v2/internal/shareable.makeImagesShared(0x0, 0xbfe36e45d9f148ee)
        github.com/hajimehoshi/ebiten/v2@v2.1.0-alpha.3/internal/shareable/image.go:79 +0x124
github.com/hajimehoshi/ebiten/v2/internal/shareable.init.0.func1(0x0, 0x0)
        github.com/hajimehoshi/ebiten/v2@v2.1.0-alpha.3/internal/shareable/image.go:54 +0x78
github.com/hajimehoshi/ebiten/v2/internal/hooks.RunBeforeUpdateHooks(0x0, 0x0)
        github.com/hajimehoshi/ebiten/v2@v2.1.0-alpha.3/internal/hooks/hooks.go:38 +0xb8
github.com/hajimehoshi/ebiten/v2.(*uiContext).update(0x7a41b3bee0, 0x0, 0x0)
        github.com/hajimehoshi/ebiten/v2@v2.1.0-alpha.3/uicontext.go:166 +0x88
github.com/hajimehoshi/ebiten/v2.(*uiContext).Update(0x7a41b3bee0, 0x0, 0x0)
        github.com/hajimehoshi/ebiten/v2@v2.1.0-alpha.3/uicontext.go:147 +0x8c
github.com/hajimehoshi/ebiten/v2/internal/uidriver/mobile.(*UserInterface).update(0x7a41a33620, 0x0, 0x0)
        github.com/hajimehoshi/ebiten/v2@v2.1.0-alpha.3/internal/uidriver/mobile/ui.go:323 +0x64
github.com/hajimehoshi/ebiten/v2/internal/uidriver/mobile.(*UserInterface).run(0x7a41a33620, 0x7a417dc4e0, 0x7a41b3bee0, 0x0, 0x0, 0x0)
        github.com/hajimehoshi/ebiten/v2@v2.1.0-alpha.3/internal/uidriver/mobile/ui.go:286 +0x158
github.com/hajimehoshi/ebiten/v2/internal/uidriver/mobile.(*UserInterface).RunWithoutMainLoop.func1(0x7a41a33620, 0x7a417dc4e0, 0x7a41b3bee0)
        github.com/hajimehoshi/ebiten/v2@v2.1.0-alpha.3/internal/uidriver/mobile/ui.go:245 +0x34
created by github.com/hajimehoshi/ebiten/v2/internal/uidriver/mobile.(*UserInterface).RunWithoutMainLoop
        github.com/hajimehoshi/ebiten/v2@v2.1.0-alpha.3/internal/uidriver/mobile/ui.go:243 +0x44
```

**Comment by hajimehoshi** [comment]
CC @wasedaigo

**Comment by hajimehoshi** [comment]
The culprit: a8f96ee9afbd4e654da749e8c5d92d6e19dc67fc
