### ISSUE TITLE
It shows picture noise in Lubuntu 20.04

### ISSUE THREAD

**Issue by z-Wind** [hajimehoshi/ebiten#1455]
When I run example, It always shows picture noise, like below.
And It does not show any errors in my console.
`go run -tags=example github.com/hajimehoshi/ebiten/examples/font`
![error](https://user-images.githubusercontent.com/16359142/103479952-2018c380-4e0c-11eb-837c-4df43d59c13e.png)
> OS: Lubuntu 20.04
> Distributor ID: Ubuntu
> Description:    Ubuntu 20.04.1 LTS
> Release:        20.04
> Codename:       focal
> LXQt About Version | 0.14.1
> LXQt Version | 0.14.1
> Qt | 5.12.8
> VGA compatible controller: NVIDIA Corporation G72M [Quadro NVS 110M/GeForce Go 7300] (rev a1)

**Comment by hajimehoshi** [comment]
Could you try Ebiten v2?

```
go run -tags=example github.com/hajimehoshi/ebiten/v2/examples/font
```

**Comment by hajimehoshi** [comment]
> VGA compatible controller: NVIDIA Corporation G72M [Quadro NVS 110M/GeForce Go 7300] (rev a1)

Thank you for the information. This seems a pretty old GPU. Would it be possible to update your graphics driver?

**Comment by z-Wind** [comment]
Sorry, I can not update my graphic driver. It's too old to find proper drivers, only nouveau works fine.
Maybe my openGL is too old so that cause this problem??
> OpenGL version string: 2.1 Mesa 20.0.8

When I run the command, I get the error as below
`go run -tags=example github.com/hajimehoshi/ebiten/v2/examples/font`
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x58ad86]
> 
> goroutine 1 [running]:
> github.com/hajimehoshi/ebiten/v2/internal/glfw.(*Monitor).GetVideoMode(0x0, 0x0)
>         /home/zps/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.0.2/internal/glfw/glfw_notwindows.go:74 +0x26
> github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.initialize(0xc00006e690, 0xc00006e660)
>         /home/zps/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.0.2/internal/uidriver/glfw/ui.go:149 +0x108
> github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.init.1()
>         /home/zps/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.0.2/internal/uidriver/glfw/ui.go:120 +0x25
> exit status 2

**Comment by hajimehoshi** [comment]
> Sorry, I can not update my graphic driver. It's too old to find proper drivers, only nouveau works fine.
> Maybe my openGL is too old so that cause this problem??

Unfortunately, this seems right. Your GPU is more than 10 years ago and there seems something wrong in the driver.

> When I run the command, I get the error as below

Interesting. This seems another issue (`glfw.GetPrimaryMonitor` returns nil?), but I guess this is also due to the old driver.

**Comment by z-Wind** [comment]
Thanks for your help.
