### ISSUE TITLE
Panic when trying to run examples on ubuntu

### ISSUE THREAD

**Issue by noxer** [hajimehoshi/ebiten#154]
When I try to run the examples on linux with go 1.6 I get the following message:
```
tim@ultra:~/projects/go/src/github.com/hajimehoshi/ebiten/examples$ GODEBUG=cgocheck=0 go run mosaic/main.go 
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x100000000 pc=0x7fd70cc97fda]

runtime stack:
runtime.throw(0x765e60, 0x2a)
	/home/tim/opt/go/src/runtime/panic.go:530 +0x90
runtime.sigpanic()
	/home/tim/opt/go/src/runtime/sigpanic_unix.go:12 +0x5a

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x5d63e0, 0xc82004dd40, 0x0)
	/home/tim/opt/go/src/runtime/cgocall.go:123 +0x11b fp=0xc82004dd08 sp=0xc82004dcd8
github.com/go-gl/glfw/v3.1/glfw._Cfunc_glfwSwapBuffers(0x2b60aa0)
	??:0 +0x36 fp=0xc82004dd40 sp=0xc82004dd08
github.com/go-gl/glfw/v3.1/glfw.(*Window).SwapBuffers(0xc8200fa000)
	/home/tim/projects/go/src/github.com/go-gl/glfw/v3.1/glfw/context.go:40 +0x78 fp=0xc82004dd90 sp=0xc82004dd40
github.com/hajimehoshi/ebiten/internal/ui.(*userInterface).swapBuffers(0xc820074360)
	/home/tim/projects/go/src/github.com/hajimehoshi/ebiten/internal/ui/ui_glfw.go:153 +0x24 fp=0xc82004dda0 sp=0xc82004dd90
github.com/hajimehoshi/ebiten/internal/ui.SwapBuffers()
	/home/tim/projects/go/src/github.com/hajimehoshi/ebiten/internal/ui/ui_glfw.go:91 +0x23 fp=0xc82004ddb0 sp=0xc82004dda0
github.com/hajimehoshi/ebiten.Run(0x912dc0, 0x140, 0xf0, 0x2, 0x705f30, 0x14, 0x0, 0x0)
	/home/tim/projects/go/src/github.com/hajimehoshi/ebiten/run.go:120 +0x3d6 fp=0xc82004de90 sp=0xc82004ddb0
main.main()
	/home/tim/projects/go/src/github.com/hajimehoshi/ebiten/examples/mosaic/main.go:58 +0x2e1 fp=0xc82004df50 sp=0xc82004de90
runtime.main()
	/home/tim/opt/go/src/runtime/proc.go:188 +0x2b0 fp=0xc82004dfa0 sp=0xc82004df50
runtime.goexit()
	/home/tim/opt/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82004dfa8 sp=0xc82004dfa0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/home/tim/opt/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 20 [chan receive, locked to thread]:
github.com/hajimehoshi/ebiten/internal/ui.Init.func1(0xc820074360)
	/home/tim/projects/go/src/github.com/hajimehoshi/ebiten/internal/ui/ui_glfw.go:57 +0xda
created by github.com/hajimehoshi/ebiten/internal/ui.Init
	/home/tim/projects/go/src/github.com/hajimehoshi/ebiten/internal/ui/ui_glfw.go:60 +0x348
exit status 2
```
on a amd64 ubuntu 15.10 machine.

**Comment by hajimehoshi** [comment]
Thank you, I'll investigate this!

**Comment by hajimehoshi** [comment]
I guess this has been fixed. Would you verify this when you are available?

**Comment by noxer** [comment]
Sorry for not responding. Yes it has been fixed. There are a bunch of new problems but I'll open new issues for them.

**Comment by hajimehoshi** [comment]
I appreciate it!
