### ISSUE TITLE
examples/windowsize: Crash when minimizing the window on Windows

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1585]
```
panic: opengl: width (0) must be equal or more than 1

goroutine 1 [running, locked to thread]:
github.com/hajimehoshi/ebiten/v2/internal/graphicsdriver/opengl.(*Graphics).checkSize(0x866780, 0x0, 0x0)
        C:/Users/hajimehoshi/ebiten/internal/graphicsdriver/opengl/graphics.go:62 +0x34d
github.com/hajimehoshi/ebiten/v2/internal/graphicsdriver/opengl.(*Graphics).NewScreenFramebufferImage(0x866780, 0x0, 0x0, 0xc0001b2000, 0xc000535bc0, 0x52b8dd, 0xc0000a0100)
        C:/Users/hajimehoshi/ebiten/internal/graphicsdriver/opengl/graphics.go:112 +0x4a
github.com/hajimehoshi/ebiten/v2/internal/graphicscommand.(*newScreenFramebufferImageCommand).Exec(0xc000004d20, 0x264c, 0x0, 0x0)
        C:/Users/hajimehoshi/ebiten/internal/graphicscommand/command.go:673 +0x57
github.com/hajimehoshi/ebiten/v2/internal/graphicscommand.(*commandQueue).flush(0x8666e0, 0x58e801, 0xc000170101)
        C:/Users/hajimehoshi/ebiten/internal/graphicscommand/command.go:282 +0x58c
github.com/hajimehoshi/ebiten/v2/internal/graphicscommand.(*commandQueue).Flush.func1(0xc00000e2a0, 0xc000535d78)
        C:/Users/hajimehoshi/ebiten/internal/graphicscommand/command.go:206 +0x31
github.com/hajimehoshi/ebiten/v2/internal/thread.(*OSThread).Loop(0xc000043120)
        C:/Users/hajimehoshi/ebiten/internal/thread/thread.go:51 +0xa3
github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.(*UserInterface).Run(0x861760, 0x6a1850, 0x866500, 0x19, 0x863478)
        C:/Users/hajimehoshi/ebiten/internal/uidriver/glfw/run_notsinglethread.go:58 +0x1ac
github.com/hajimehoshi/ebiten/v2.RunGame(0x6a13c0, 0xc000012960, 0x0, 0x0)
        C:/Users/hajimehoshi/ebiten/run.go:172 +0xed
main.main()
        C:/Users/hajimehoshi/ebiten/examples/windowsize/main.go:428 +0x68a
exit status 2
exit status 1
```

**Comment by hajimehoshi** [comment]
This happens when pressing N key. This happens only with the master branch and not with the 2.0 branch. This is a regression.

**Comment by hajimehoshi** [comment]
fda1fd9a95a2568f96ae0581e23e684fc227efa4 is the culprit.

**Comment by hajimehoshi** [comment]
The odd thing is the culprit change is in 2.0 and 1.12 but they don't reproduce the issue. Intresting...
