### ISSUE TITLE
examples/windowsize: Crash when pressing D many times

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1588]
```
fatal error: too many callback functions

goroutine 1 [running, locked to thread]:
runtime.throw(0xdc56e9, 0x1b)
        C:/Program Files/Go/src/runtime/panic.go:1117 +0x79 fp=0xc000065b60 sp=0xc000065b30 pc=0xb99279
syscall.compileCallback(0xd7a780, 0xc000313150, 0xc000065c00, 0xb6e6ff)
        C:/Program Files/Go/src/runtime/syscall_windows.go:201 +0x5e5 fp=0xc000065c58 sp=0xc000065b60 pc=0xbc8545
syscall.NewCallbackCDecl(...)
        C:/Program Files/Go/src/syscall/syscall_windows.go:184
golang.org/x/sys/windows.NewCallbackCDecl(...)
        C:/Users/hajimehoshi/go/pkg/mod/golang.org/x/sys@v0.0.0-20210415045647-66c3f260301c/windows/syscall_windows.go:164
github.com/hajimehoshi/ebiten/v2/internal/glfw.(*Window).SetSizeCallback(0xc0000426d0, 0xc000312fe0, 0x6c445020)
        C:/Users/hajimehoshi/ebiten/internal/glfw/glfw_windows.go:244 +0x157 fp=0xc000065ca8 sp=0xc000065c58 pc=0xcfae17
github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.(*UserInterface).registerWindowSetSizeCallback(0xfd1760)
        C:/Users/hajimehoshi/ebiten/internal/uidriver/glfw/ui.go:715 +0x67 fp=0xc000065cd0 sp=0xc000065ca8 pc=0xd05be7
github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.(*UserInterface).setDecorated(0xfd1760, 0xc000264001)
        C:/Users/hajimehoshi/ebiten/internal/uidriver/glfw/ui.go:1381 +0xc8 fp=0xc000065d18 sp=0xc000065cd0 pc=0xd07f48
github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.(*window).SetDecorated.func1(0xc000264000, 0xc000065d78)
        C:/Users/hajimehoshi/ebiten/internal/uidriver/glfw/window.go:54 +0x45 fp=0xc000065d50 sp=0xc000065d18 pc=0xd0be65
github.com/hajimehoshi/ebiten/v2/internal/thread.(*OSThread).Loop(0xc000090a50)
        C:/Users/hajimehoshi/ebiten/internal/thread/thread.go:51 +0xa3 fp=0xc000065db0 sp=0xc000065d50 pc=0xcfe883
github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.(*UserInterface).Run(0xfd1760, 0xe11870, 0xfd6500, 0x19, 0xfd3478)
        C:/Users/hajimehoshi/ebiten/internal/uidriver/glfw/run_notsinglethread.go:58 +0x1ac fp=0xc000065e10 sp=0xc000065db0 pc=0xd0292c
github.com/hajimehoshi/ebiten/v2.RunGame(0xe113e0, 0xc00008e648, 0x0, 0x0)
        C:/Users/hajimehoshi/ebiten/run.go:172 +0xed fp=0xc000065e70 sp=0xc000065e10 pc=0xd13fcd
main.main()
        C:/Users/hajimehoshi/ebiten/examples/windowsize/main.go:428 +0x68a fp=0xc000065f88 sp=0xc000065e70 pc=0xd4ea0a
runtime.main()
        C:/Program Files/Go/src/runtime/proc.go:225 +0x256 fp=0xc000065fe0 sp=0xc000065f88 pc=0xb9bb56
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc000065fe8 sp=0xc000065fe0 pc=0xbcc161

goroutine 18 [chan receive]:
github.com/hajimehoshi/ebiten/v2/internal/thread.(*OSThread).Call(0xc000090a50, 0xc000256078, 0xc000061b90, 0xd0538c)
        C:/Users/hajimehoshi/ebiten/internal/thread/thread.go:69 +0x6d
github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.(*window).SetDecorated(0xfd3460, 0xe13501)
        C:/Users/hajimehoshi/ebiten/internal/uidriver/glfw/window.go:49 +0x92
github.com/hajimehoshi/ebiten/v2.SetWindowDecorated(0xfd1701)
        C:/Users/hajimehoshi/ebiten/window.go:51 +0x62
main.(*game).Update(0xc00008e648, 0x0, 0x0)
        C:/Users/hajimehoshi/ebiten/examples/windowsize/main.go:252 +0x545
github.com/hajimehoshi/ebiten/v2.(*imageDumper).update(0xc000408050, 0x101a878, 0xdd5670)
        C:/Users/hajimehoshi/ebiten/imagedumper_desktop.go:112 +0x6b
github.com/hajimehoshi/ebiten/v2.(*imageDumperGame).Update(0xc00008cd80, 0x0, 0xc000127080)
        C:/Users/hajimehoshi/ebiten/run.go:115 +0x52
github.com/hajimehoshi/ebiten/v2.(*uiContext).update(0xfd6500, 0x1, 0x0, 0x0)
        C:/Users/hajimehoshi/ebiten/uicontext.go:187 +0xd2
github.com/hajimehoshi/ebiten/v2.(*uiContext).Update(0xfd6500, 0xc00008d590, 0x0)
        C:/Users/hajimehoshi/ebiten/uicontext.go:148 +0xd3
github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.(*UserInterface).loop(0xfd1760, 0x0, 0x0)
        C:/Users/hajimehoshi/ebiten/internal/uidriver/glfw/ui.go:952 +0x15f
github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.(*UserInterface).Run.func1(0xfd1760, 0xc0000f0240)
        C:/Users/hajimehoshi/ebiten/internal/uidriver/glfw/run_notsinglethread.go:52 +0xe5
created by github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.(*UserInterface).Run
        C:/Users/hajimehoshi/ebiten/internal/uidriver/glfw/run_notsinglethread.go:36 +0x186
exit status 2
exit status 1
```

Not sure how to reproduce this deterministically. Toggling fullscreen and/or making the window resizable might be needed.

**Comment by hajimehoshi** [comment]
https://github.com/golang/go/blob/2ebe77a2fda1ee9ff6fd9a3e08933ad1ebaea039/src/runtime/syscall_windows.go#L308

So this error came from the Go runtime.

Probably we should not create so many callback functions and reuse them as much as possible.
