### ISSUE TITLE
examples: Crash when restoring from iconified state

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1589]
```
panic: opengl: width (0) must be equal or more than 1

goroutine 1 [running, locked to thread]:
github.com/hajimehoshi/ebiten/v2/internal/graphicsdriver/opengl.(*Graphics).checkSize(0xa7b740, 0x0, 0x0)
        C:/Users/hajimehoshi/ebiten/internal/graphicsdriver/opengl/graphics.go:62 +0x34d
github.com/hajimehoshi/ebiten/v2/internal/graphicsdriver/opengl.(*Graphics).NewScreenFramebufferImage(0xa7b740, 0x0, 0x0, 0xc00045ea80, 0xc000343c68, 0x69fa1d, 0xc0004680c0)
        C:/Users/hajimehoshi/ebiten/internal/graphicsdriver/opengl/graphics.go:112 +0x4a
github.com/hajimehoshi/ebiten/v2/internal/graphicscommand.(*newScreenFramebufferImageCommand).Exec(0xc000545d70, 0x300, 0x0, 0x0)

        C:/Users/hajimehoshi/ebiten/internal/graphicscommand/command.go:673 +0x57
github.com/hajimehoshi/ebiten/v2/internal/graphicscommand.(*commandQueue).flush(0xa7b6a0, 0x71b101, 0xc000470101)
        C:/Users/hajimehoshi/ebiten/internal/graphicscommand/command.go:282 +0x58c
github.com/hajimehoshi/ebiten/v2/internal/graphicscommand.(*commandQueue).Flush.func1(0xc00000e240, 0xc000343e20)
        C:/Users/hajimehoshi/ebiten/internal/graphicscommand/command.go:206 +0x31
github.com/hajimehoshi/ebiten/v2/internal/thread.(*OSThread).Loop(0xc000043d20)
        C:/Users/hajimehoshi/ebiten/internal/thread/thread.go:51 +0xa3
github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.(*UserInterface).Run(0xa76360, 0x86d790, 0xa7b4c0, 0x0, 0xc00010ff08)
        C:/Users/hajimehoshi/ebiten/internal/uidriver/glfw/run_notsinglethread.go:58 +0x1ac
github.com/hajimehoshi/ebiten/v2.RunGame(0x86d050, 0xc000050af0, 0x0, 0x0)
        C:/Users/hajimehoshi/ebiten/run.go:172 +0xed
main.main()
        C:/Users/hajimehoshi/ebiten/examples/blocks/main.go:46 +0xfe
exit status 2
exit status 1
```

This depends on displays. This doesn't happen on some displays, but happens on the others. Interesting...

**Comment by hajimehoshi** [comment]
1.12 doesn't reproduce this issue. 2.0 reproduced this issue and the cause was 16d30858844fc80442e28d7c565eb42291a1b7c3.

**Comment by hajimehoshi** [comment]
I'm not sure why this doesn't happen on 1.12, but I'll backport the fix just in case.
