### ISSUE TITLE
audio: crash on Piano example on linux

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#160]
```
panic: audio: error after closing: 40963

goroutine 22 [running]:
panic(0x5a56e0, 0xc8203310d0)
        /usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/hajimehoshi/ebiten/exp/audio.(*player).close(0xc820398000, 0x0, 0x0)                                                                                                                   
        /home/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/exp/audio/audio_openal.go:205 +0x5d6                                                                                               
github.com/hajimehoshi/ebiten/exp/audio.(*player).play.func1(0xc820398000)                                                                                                                        
        /home/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/exp/audio/audio_openal.go:180 +0xab                                                                                                
created by github.com/hajimehoshi/ebiten/exp/audio.(*player).play                                                                                                                                 
        /home/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/exp/audio/audio_openal.go:180 +0x4fc                                                                                               
exit status 2
```

This crash happens just after a note ends playing.

**Comment by hajimehoshi** [comment]
Now this doesn't happen.
