### ISSUE TITLE
Confirm that Ebiten works only with Steam Runtime

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1733]
https://partner.steamgames.com/doc/store/application/platforms/linux

**Comment by hajimehoshi** [comment]
I'm testing the Steam Runtime.

1. Install the Steam Runtime for Docker:

* Download `*-sysroot.tar.gz` file
* Download `*-sysroot.Dockerfile`
* Run `sudo docker build -f com.valvesoftware.SteamRuntime.Sdk-amd64,i386-scout-sysroot.Dockerfile -t steamrt_scout_amd64:latest .`

2. Run `docker build .` with this Dockerfile:

```
FROM steamrt_scout_amd64:latest

WORKDIR /work

RUN curl -L --output go1.16.6.linux-amd64.tar.gz https://golang.org/dl/go1.16.6.linux-amd64.tar.gz
RUN rm -rf /usr/local/go && tar -C /usr/local -xzf go1.16.6.linux-amd64.tar.gz
ENV PATH=$PATH:/usr/local/go/bin
RUN go mod init foo
RUN go get github.com/hajimehoshi/go-inovation
RUN go build github.com/hajimehoshi/go-inovation
```

I found that C99 (variable declarations in `for`s) doesn't work there. I'll take a look more

**Comment by hajimehoshi** [comment]
`CGO_CFLAGS=-std=c99` solved the issue.

I found another issue:

```
#9 25.10 # runtime/cgo
#9 25.10 gcc_libinit.c: In function '_cgo_try_pthread_create':
#9 25.10 gcc_libinit.c:110:3: error: implicit declaration of function 'nanosleep' [-Werror=implicit-function-declaration]
#9 25.10    nanosleep(&ts, nil);
#9 25.10    ^
#9 25.10 cc1: all warnings being treated as errors
```

🤔

**Comment by hajimehoshi** [comment]
Finally, this Dockerfile succeeded to build an Ebiten application!

```
FROM steamrt_scout_amd64:latest

WORKDIR /work

RUN curl -L --output go1.16.6.linux-amd64.tar.gz https://golang.org/dl/go1.16.6.linux-amd64.tar.gz
RUN rm -rf /usr/local/go && tar -C /usr/local -xzf go1.16.6.linux-amd64.tar.gz
ENV PATH=$PATH:/usr/local/go/bin
ENV CGO_CFLAGS=-std=gnu99
RUN go mod init foo
RUN go get github.com/hajimehoshi/go-inovation
RUN go build github.com/hajimehoshi/go-inovation
```

I'll add a test at Github Actions.

**Comment by hajimehoshi** [comment]
OK now I've succeeded to run tests:

`Dockerfile`:

```
FROM steamrt_scout_amd64:latest

WORKDIR /work

RUN curl -L --output go1.16.6.linux-amd64.tar.gz https://golang.org/dl/go1.16.6.linux-amd64.tar.gz
RUN rm -rf /usr/local/go && tar -C /usr/local -xzf go1.16.6.linux-amd64.tar.gz
ENV PATH $PATH:/usr/local/go/bin
ENV CGO_CFLAGS -std=gnu99
RUN go mod init foo

ENV DISPLAY :99.0
```

`run.sh`:

```
docker run --rm --volume $(pwd):/work $(docker build -q . | head -n1) /bin/sh -c ' \                                                                                                                                                                                                  
       go get github.com/hajimehoshi/ebiten/v2@v2.2.0-alpha.11                                                                                                                                                                                                                        
       go get github.com/hajimehoshi/ebiten/v2/internal/testflock@v2.2.0-alpha.11                                                                                                                                                                                                     
       Xvfb :99 -screen 0 1024x768x24 &                                                                                                                                                                                                                                               
       go test github.com/hajimehoshi/ebiten/v2'
```

```
$ ./run.sh
[...]
panic: opengl: height (8192) must be less than or equal to 4096

goroutine 1 [running, locked to thread]:
github.com/hajimehoshi/ebiten/v2/internal/graphicsdriver/opengl.(*Graphics).checkSize(0xaeaf40, 0x20, 0x2000)
        /root/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.2.0-alpha.11/internal/graphicsdriver/opengl/graphics.go:72 +0x146
github.com/hajimehoshi/ebiten/v2/internal/graphicsdriver/opengl.(*Graphics).NewImage(0xaeaf40, 0x12, 0x1002, 0xc000986000, 0x12, 0x4000, 0xaeaf68)
        /root/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.2.0-alpha.11/internal/graphicsdriver/opengl/graphics.go:95 +0xe5
github.com/hajimehoshi/ebiten/v2/internal/graphicscommand.(*newImageCommand).Exec(0xc000aa5398, 0x0, 0x60, 0x13000)
        /root/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.2.0-alpha.11/internal/graphicscommand/command.go:614 +0x50
github.com/hajimehoshi/ebiten/v2/internal/graphicscommand.(*commandQueue).flush(0xaeae00, 0x5ef401, 0x101)
        /root/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.2.0-alpha.11/internal/graphicscommand/command.go:286 +0x47f
github.com/hajimehoshi/ebiten/v2/internal/graphicscommand.(*commandQueue).Flush.func1(0xc00001a300, 0xc000111d78)
        /root/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.2.0-alpha.11/internal/graphicscommand/command.go:208 +0x2a
github.com/hajimehoshi/ebiten/v2/internal/thread.(*OSThread).Loop(0xc000044630)
        /root/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.2.0-alpha.11/internal/thread/thread.go:51 +0x99
github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.(*UserInterface).Run(0xa8b360, 0x7306a8, 0xaead20, 0x0, 0xc000115e60)
        /root/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.2.0-alpha.11/internal/uidriver/glfw/run_notsinglethread.go:60 +0x1ab
github.com/hajimehoshi/ebiten/v2.RunGame(0x72f068, 0xc000044620, 0x0, 0x0)
        /root/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.2.0-alpha.11/run.go:172 +0xe6
github.com/hajimehoshi/ebiten/v2/internal/testing.MainWithRunLoop(0xc00012e000)
        /root/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.2.0-alpha.11/internal/testing/testing.go:53 +0xc8
github.com/hajimehoshi/ebiten/v2_test.TestMain(...)
        /root/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.2.0-alpha.11/image_test.go:48
main.main()
        _testmain.go:259 +0x16c
FAIL    github.com/hajimehoshi/ebiten/v2        35.115s
FAIL
```
