### ISSUE TITLE
Crash on GOOS=windows GOARCH=386

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1750]
```
panic: The specified module could not be found.

goroutine 1 [running]:
golang.org/x/sys/windows.(*LazyProc).mustFind(...)
        /Users/hajimehoshi/go/pkg/mod/golang.org/x/sys@v0.0.0-20210510120138-977fb7262007/windows/dll_windows.go:325
golang.org/x/sys/windows.(*LazyProc).Call(0x118db7d0, 0x1189c164, 0x1, 0x1, 0x11886748, 0x6ebf00, 0x4, 0x8cf8a0)
        /Users/hajimehoshi/go/pkg/mod/golang.org/x/sys@v0.0.0-20210510120138-977fb7262007/windows/dll_windows.go:347 +0x8f
github.com/hajimehoshi/ebiten/v2/internal/glfw.(*dll).call(0x118823e0, 0x91778f, 0x14, 0x1189c164, 0x1, 0x1, 0x1)
        /Users/hajimehoshi/ebiten/internal/glfw/load_windows.go:42 +0xa5
github.com/hajimehoshi/ebiten/v2/internal/glfw.init.0()
        /Users/hajimehoshi/ebiten/internal/glfw/load_windows.go:195 +0xb7
```

**Comment by hajimehoshi** [comment]
git-bisect says b604391b21acc2ad463a522dec55649f842289a5 is the culprit
