### ISSUE TITLE
Crash with a vJoy Device (w/ Nintendo Switch controller) on Windows

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1752]
```
panic: glfw: invalid value: Invalid button in gamepad mapping 0300000034120000adbe000000000000 (vJoy Device)

goroutine 1 [running]:
github.com/hajimehoshi/ebiten/v2/internal/glfw.acceptError({0x0, 0x0, 0x4254e})
        C:/home/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.2.0-alpha.11.0.20210812183551-797f42b839cd/internal/glfw/load_windows.go:165 +0xf9
github.com/hajimehoshi/ebiten/v2/internal/glfw.panicError(...)
        C:/home/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.2.0-alpha.11.0.20210812183551-797f42b839cd/internal/glfw/load_windows.go:139
github.com/hajimehoshi/ebiten/v2/internal/glfw.UpdateGamepadMappings({0xc000180000, 0x4254e})
        C:/home/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.2.0-alpha.11.0.20210812183551-797f42b839cd/internal/glfw/glfw_windows.go:558 +0x16c
github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.initialize()
        C:/home/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.2.0-alpha.11.0.20210812183551-797f42b839cd/internal/uidriver/glfw/ui.go:175 +0x6b
github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.init.1()
        C:/home/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.2.0-alpha.11.0.20210812183551-797f42b839cd/internal/uidriver/glfw/ui.go:159 +0x1e
```

Reported by @raa0121

**Comment by raa0121** [comment]
vJoy Device is http://vjoystick.sourceforge.net/joomla/
It is unofficial Nintendo Switch JoyCon Driver.
So this bug is low priority

**Comment by hajimehoshi** [comment]
From https://github.com/gabomdq/SDL_GameControllerDB/blob/master/gamecontrollerdb.txt

```
0300000034120000adbe000000000000,vJoy Device,a:b0,b:b1,back:b15,dpdown:b6,dpleft:b7,dpright:b8,dpup:b5,guide:b16,leftshoulder:b9,leftstick:b13,lefttrigger:b11,leftx:a0,lefty:a1,rightshoulder:b10,rightstick:b14,righttrigger:b12,rightx:a3,righty:a4,start:b4,x:b2,y:b3,platform:Windows,
```

**Comment by hajimehoshi** [comment]
go-gl/glfw' GLFW crashes when a wrong button is assigned (e.g., the number of buttons are less than the assigned button number):

https://github.com/go-gl/glfw/blob/62640a716d485dcbf341a7c187227a4a99fb1eba/v3.3/glfw/glfw/src/input.c#L78-L111

While the latest GLFW's implementation ignores this error:

https://github.com/glfw/glfw/blob/201400b974b63eb7f23eb7d8563589df9c699d7c/src/input.c#L95-L116

This means updating the GLFW side will solve this issue automatically.

**Comment by hajimehoshi** [comment]
Duplicated with #1802
