### ISSUE TITLE
Update MinGW to 10

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1758]
Now a 32bit binary crashes:

```
panic: The specified module could not be found.

goroutine 1 [running]:
golang.org/x/sys/windows.(*LazyProc).mustFind(...)
        /Users/hajimehoshi/go/pkg/mod/golang.org/x/sys@v0.0.0-20210510120138-977fb7262007/windows/dll_windows.go:325
golang.org/x/sys/windows.(*LazyProc).Call(0x118db7d0, 0x1189e164, 0x1, 0x1, 0x11888898, 0xacbf00, 0x4, 0xcaf8a0)
        /Users/hajimehoshi/go/pkg/mod/golang.org/x/sys@v0.0.0-20210510120138-977fb7262007/windows/dll_windows.go:347 +0x8f
github.com/hajimehoshi/ebiten/v2/internal/glfw.(*dll).call(0x118843e0, 0xcf778d, 0x14, 0x1189e164, 0x1, 0x1, 0x1)
        /Users/hajimehoshi/ebiten/internal/glfw/load_windows.go:42 +0xa5
github.com/hajimehoshi/ebiten/v2/internal/glfw.init.0()
        /Users/hajimehoshi/ebiten/internal/glfw/load_windows.go:195 +0xb7
```

See also #1750

**Comment by hajimehoshi** [comment]
Probably the C runtime cannot be found due to the lack of a manifest file.

**Comment by hajimehoshi** [comment]
See https://github.com/msys2/MINGW-packages/issues/2600

**Comment by hajimehoshi** [comment]
We no longer need MinGW for Windows.
