### ISSUE TITLE
Empty ColorM is no longer valid

### ISSUE THREAD

**Issue by divVerent** [hajimehoshi/ebiten#1765]
This code panics due to nil access after recent changes to make affine.ColorM an interface:

```
var a, b ebiten.ColorM
a.Concat(b)
```

As a workaround, this works:

```
var a, b ebiten.ColorM
b.Reset()
a.Concat(b)
```

**Comment by hajimehoshi** [comment]
```
var a, b ebiten.ColorM
a.Concat(b)
```

I couldn't reproduce the panic with this code. Is this the minimum code to reproduce the issue?

**Comment by divVerent** [comment]
Oh, I forgot a crucial part when simplifying. This now crashes:

```
   var a, b ebiten.ColorM                                                       
   a.SetElement(1, 2, -1)                                                       
   a.Concat(b)                                                                  
```

as follows:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x53e817]

goroutine 1 [running, locked to thread]:
github.com/hajimehoshi/ebiten/v2/internal/affine.(*colorMImplBodyTranslate).Concat(0xc00b281f40, 0x0, 0x0, 0x2, 0xc0bf800000)
	/home/rpolzer/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.2.0-alpha.11.0.20210817032719-12350e2fee5d/internal/affine/colorm.go:498 +0x37
github.com/hajimehoshi/ebiten/v2.(*ColorM).Concat(...)
	/home/rpolzer/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.2.0-alpha.11.0.20210817032719-12350e2fee5d/colorm.go:67
```
```

**Comment by divVerent** [comment]
The previous example didn't hit this crash due to this special case:

```
func (c ColorMIdentity) Concat(other ColorM) ColorM {
        return other
}
```

The issue appears to be that IsIdentity() can't be called when the interface value is an untyped nil - which is precisely the case in an ebiten.ColorM{}.

TBH I don't understand why the renderer doesn't crash all the time due to this issue, given that internal/graphicsdriver/opengl/graphics.go calls IsIdentity() on an interface value too.
