### ISSUE TITLE
examples/gamepad: Crash with PS1 controller on Linux

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1825]
1. Connect a PS1 controller with Elecom's converter (JC-PS102USV)
2. Run `examples/gamepad`

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x500e9f]

goroutine 54 [running]:
github.com/hajimehoshi/ebiten/v2/internal/gamepaddb.IsButtonPressed({0xc00046a080, 0x20}, 0x7f8c4987a868, {0x6a8c08, 0xc00010a900})
	/home/hajimehoshi/ebiten/internal/gamepaddb/gamepaddb.go:447 +0xff
github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.(*Input).IsStandardGamepadButtonPressed(0x815310, 0x0, 0x1)
	/home/hajimehoshi/ebiten/internal/uidriver/glfw/input.go:410 +0x13d
github.com/hajimehoshi/ebiten/v2.IsStandardGamepadButtonPressed(0x61bdc0, 0xc00042f470)
	/home/hajimehoshi/ebiten/input.go:237 +0x43
github.com/hajimehoshi/ebiten/v2/inpututil.(*inputState).update(0x895cc0)
	/home/hajimehoshi/ebiten/inpututil/inpututil.go:156 +0xc5f
github.com/hajimehoshi/ebiten/v2/inpututil.init.0.func1()
	/home/hajimehoshi/ebiten/inpututil/inpututil.go:75 +0x25
github.com/hajimehoshi/ebiten/v2/internal/hooks.RunBeforeUpdateHooks()
	/home/hajimehoshi/ebiten/internal/hooks/hooks.go:38 +0xc7
github.com/hajimehoshi/ebiten/v2.(*uiContext).updateFrameImpl(0x8958e0, 0x1)
	/home/hajimehoshi/ebiten/uicontext.go:184 +0xaf
github.com/hajimehoshi/ebiten/v2.(*uiContext).updateFrame(0x8958e0, 0x0)
	/home/hajimehoshi/ebiten/uicontext.go:159 +0x86
github.com/hajimehoshi/ebiten/v2.(*uiContext).UpdateFrame(0xc000012030)
	/home/hajimehoshi/ebiten/uicontext.go:138 +0x32
github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.(*UserInterface).loop(0x8151e0)
	/home/hajimehoshi/ebiten/internal/uidriver/glfw/ui.go:1064 +0x1f7
github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.(*UserInterface).Run.func1()
	/home/hajimehoshi/ebiten/internal/uidriver/glfw/run_notsinglethread.go:53 +0xe6
created by github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.(*UserInterface).Run
	/home/hajimehoshi/ebiten/internal/uidriver/glfw/run_notsinglethread.go:37 +0x19d
```

**Comment by hajimehoshi** [comment]
This happens as of 2.2.
