### ISSUE TITLE
panic: syscall/js: call of Value.Get on null wasm_exec.js

### ISSUE THREAD

**Issue by sedyh** [hajimehoshi/ebiten#1838]
Hello, I'm getting a panic while running my game via wasmserve on amdgpu-pro drivers.

Enviroment:

Golang: 1.16
Ebiten: 2.1.0
Browser: firefox 92.0
OS: linux mint 20.2
GPU: rx5700xt
Drivers: amdgpu-pro-21.30

Panic and trace:
```
WebGL warning: <Create>: AllowWebgl2:false restricts context creation on this system. wasm_exec.js:399:31
Failed to create WebGL context: WebGL creation failed: 
* AllowWebgl2:false restricts context creation on this system. () wasm_exec.js:399:31
panic: syscall/js: call of Value.Get on null wasm_exec.js:51:14
<empty string> wasm_exec.js:51:14
goroutine 7 [running]: wasm_exec.js:51:14
syscall/js.Value.Get(0x7ff8000000000002, 0x0, 0x88a79, 0xd, 0x0, 0x0) wasm_exec.js:51:14
	/home/sedyh/.local/share/go/root-sdk/go1.16.7/src/syscall/js/js.go:299 +0xc wasm_exec.js:51:14
github.com/hajimehoshi/ebiten/v2/internal/graphicsdriver/opengl.newGL(0x7ff8000000000002, 0x0, 0x87833) wasm_exec.js:51:14
	/home/sedyh/.local/share/go/path-workspace/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.0/internal/graphicsdriver/opengl/gl_js.go:88 +0x2 wasm_exec.js:51:14
github.com/hajimehoshi/ebiten/v2/internal/graphicsdriver/opengl.(*context).initGL(0x39d650) wasm_exec.js:51:14
	/home/sedyh/.local/share/go/path-workspace/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.0/internal/graphicsdriver/opengl/context_js.go:121 +0xe wasm_exec.js:51:14
github.com/hajimehoshi/ebiten/v2/internal/graphicsdriver/opengl.(*context).reset(0x39d650, 0x3da328, 0x10f50040) wasm_exec.js:51:14
	/home/sedyh/.local/share/go/path-workspace/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.0/internal/graphicsdriver/opengl/context_js.go:132 +0x11 wasm_exec.js:51:14
github.com/hajimehoshi/ebiten/v2/internal/graphicsdriver/opengl.(*openGLState).reset(0x39d600, 0x39d650, 0x0, 0x0) wasm_exec.js:51:14
	/home/sedyh/.local/share/go/path-workspace/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.0/internal/graphicsdriver/opengl/program.go:146 +0x2 wasm_exec.js:51:14
github.com/hajimehoshi/ebiten/v2/internal/graphicsdriver/opengl.(*Graphics).Reset(0x39d600, 0x80eb80, 0xb18c9b614149bbb4) wasm_exec.js:51:14
	/home/sedyh/.local/share/go/path-workspace/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.0/internal/graphicsdriver/opengl/graphics.go:140 +0x4 wasm_exec.js:51:14
github.com/hajimehoshi/ebiten/v2/internal/graphicscommand.ResetGraphicsDriverState.func1(0x10000af0dc8, 0x3da328) wasm_exec.js:51:14
	/home/sedyh/.local/share/go/path-workspace/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.0/internal/graphicscommand/command.go:733 +0x4 wasm_exec.js:51:14
github.com/hajimehoshi/ebiten/v2/internal/graphicscommand.runOnMainThread(0x103b20, 0x29be0, 0x2eae0) wasm_exec.js:51:14
	/home/sedyh/.local/share/go/path-workspace/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.0/internal/graphicscommand/thread.go:33 +0x9 wasm_exec.js:51:14
github.com/hajimehoshi/ebiten/v2/internal/graphicscommand.ResetGraphicsDriverState(0x3b9d4c, 0x100000000) wasm_exec.js:51:14
	/home/sedyh/.local/share/go/path-workspace/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.0/internal/graphicscommand/command.go:732 +0x2 wasm_exec.js:51:14
github.com/hajimehoshi/ebiten/v2/internal/restorable.InitializeGraphicsDriverState(...) wasm_exec.js:51:14
	/home/sedyh/.local/share/go/path-workspace/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.0/internal/restorable/images.go:275 wasm_exec.js:51:14
github.com/hajimehoshi/ebiten/v2/internal/atlas.BeginFrame.func1() wasm_exec.js:51:14
	/home/sedyh/.local/share/go/path-workspace/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.0/internal/atlas/image.go:711 +0x4 wasm_exec.js:51:14
sync.(*Once).doSlow(0x3b9d48, 0xaf0e48) wasm_exec.js:51:14
	/home/sedyh/.local/share/go/root-sdk/go1.16.7/src/sync/once.go:68 +0x10 wasm_exec.js:51:14
sync.(*Once).Do(0x3b9d48, 0xaf0e48) wasm_exec.js:51:14
	/home/sedyh/.local/share/go/root-sdk/go1.16.7/src/sync/once.go:59 +0x9 wasm_exec.js:51:14
github.com/hajimehoshi/ebiten/v2/internal/atlas.BeginFrame(0x0, 0x0) wasm_exec.js:51:14
	/home/sedyh/.local/share/go/path-workspace/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.0/internal/atlas/image.go:710 +0x2 wasm_exec.js:51:14
github.com/hajimehoshi/ebiten/v2/internal/buffered.BeginFrame(0x41500, 0x0) wasm_exec.js:51:14
	/home/sedyh/.local/share/go/path-workspace/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.0/internal/buffered/image.go:38 +0x2 wasm_exec.js:51:14
github.com/hajimehoshi/ebiten/v2.(*uiContext).Update(0x39d300, 0x0, 0x3b9a88) wasm_exec.js:51:14
	/home/sedyh/.local/share/go/path-workspace/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.0/uicontext.go:150 +0x8 wasm_exec.js:51:14
github.com/hajimehoshi/ebiten/v2/internal/uidriver/js.(*UserInterface).updateImpl(0x378e60, 0x0, 0x0, 0x0) wasm_exec.js:51:14
	/home/sedyh/.local/share/go/path-workspace/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.0/internal/uidriver/js/ui_js.go:249 +0x10 wasm_exec.js:51:14
github.com/hajimehoshi/ebiten/v2/internal/uidriver/js.(*UserInterface).update(0x378e60, 0x0, 0x0) wasm_exec.js:51:14
	/home/sedyh/.local/share/go/path-workspace/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.0/internal/uidriver/js/ui_js.go:237 +0xa wasm_exec.js:51:14
github.com/hajimehoshi/ebiten/v2/internal/uidriver/js.(*UserInterface).loop.func1() wasm_exec.js:51:14
	/home/sedyh/.local/share/go/path-workspace/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.0/internal/uidriver/js/ui_js.go:270 +0x5 wasm_exec.js:51:14
created by github.com/hajimehoshi/ebiten/v2/internal/uidriver/js.(*UserInterface).loop wasm_exec.js:51:14
	/home/sedyh/.local/share/go/path-workspace/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.0/internal/uidriver/js/ui_js.go:293 +0x13 wasm_exec.js:51:14
exit code: 2
```

And, after a few minutes the application starts spamming with this error in batches of 5-10 pieces every few seconds 

Error:

```
Uncaught Error: Go program has already exited
    _resume http://xxx/wasm_exec.js:576
    _makeFuncWrapper http://xxx/wasm_exec.js:589
    valueCall http://xxx/wasm_exec.js:399
    run http://xxx/wasm_exec.js:567
    <anonymous> http://xxx/:17
```

**Comment by hajimehoshi** [comment]
I'm not sure there is a workaround...

**Comment by hajimehoshi** [comment]
Does Chrome work instead of Firefox?

**Comment by hajimehoshi** [comment]
Have you tried https://support.mozilla.org/en-US/questions/1334668 ?

**Comment by sedyh** [comment]
> I'm not sure there is a workaround...

In terms of support, the problem is more likely on my side, but it seems that the application should work out this case correctly, without spamming errors in a loop.

This is how get.webgl.org reacts:
![image](https://user-images.githubusercontent.com/19890545/135904757-524a957e-02be-4e0c-bf46-e538cee076a8.png)

This is how ebiten reacts:
![errors](https://user-images.githubusercontent.com/19890545/135904551-3466d15f-c50f-4969-b580-06ce16bebd62.gif)

> Does Chrome work instead of Firefox?
> Have you tried https://support.mozilla.org/en-US/questions/1334668?

Yes... both work, it seems I was in a hurry to send the problem, however, the behavior with the feature disabled is still worth correcting.

**Comment by sedyh** [comment]
Hmm, this is quite strange, but after switching on, oom occurs after a couple of minutes of the game, I don't seem to create anything expensive for memory.

![s1](https://user-images.githubusercontent.com/19890545/135906324-2e140832-44d3-4f40-a4bb-6967000fac00.png)

```
runtime: out of memory: cannot allocate 16777216-byte block (2944237568 in use) wasm_exec.js:51:14
fatal error: out of memory wasm_exec.js:51:14
<empty string> wasm_exec.js:51:14
goroutine 1462 [running]: wasm_exec.js:51:14
runtime.throw(0x88c67, 0xd) wasm_exec.js:51:14
	/home/sedyh/.local/share/go/root-sdk/go1.16.7/src/runtime/panic.go:1117 +0x7 fp=0x89b870 sp=0x89b848 pc=0x11d90007 wasm_exec.js:51:14
runtime.(*mcache).allocLarge(0x3d0108, 0xc82710, 0xe090101, 0x7ff8000100000593) wasm_exec.js:51:14
	/home/sedyh/.local/share/go/root-sdk/go1.16.7/src/runtime/mcache.go:226 +0x35 fp=0x89b8d0 sp=0x89b870 pc=0x10e40035 wasm_exec.js:51:14
runtime.mallocgc(0xc82710, 0x2ffa0, 0x7ff8000100000501, 0x637b3e8) wasm_exec.js:51:14
	/home/sedyh/.local/share/go/root-sdk/go1.16.7/src/runtime/malloc.go:1078 +0xbf fp=0x89b960 sp=0x89b8d0 pc=0x109e00bf wasm_exec.js:51:14
runtime.makeslice(0x2ffa0, 0xc82710, 0xc82710, 0x9) wasm_exec.js:51:14
	/home/sedyh/.local/share/go/root-sdk/go1.16.7/src/runtime/slice.go:98 +0xd fp=0x89b988 sp=0x89b960 pc=0x1284000d wasm_exec.js:51:14
github.com/hajimehoshi/ebiten/v2/internal/jsutil.Uint8ArrayToSlice(0x7ff8000100000593, 0x637b3e8, 0xc82710, 0x7, 0x7, 0x0) wasm_exec.js:51:14
	/home/sedyh/.local/share/go/path-workspace/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.0/internal/jsutil/slice_js.go:29 +0x9 fp=0x89b9d0 sp=0x89b988 pc=0x19e60009 wasm_exec.js:51:14
github.com/hajimehoshi/ebiten/v2/internal/graphicsdriver/opengl.(*context).framebufferPixels(0x39d650, 0x8b7c270, 0x9f6, 0x506, 0x14b50004, 0x39d6b8, 0x1) wasm_exec.js:51:14
	/home/sedyh/.local/share/go/path-workspace/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.0/internal/graphicsdriver/opengl/context_js.go:206 +0xe fp=0x89bab0 sp=0x89b9d0 pc=0x1a06000e wasm_exec.js:51:14
github.com/hajimehoshi/ebiten/v2/internal/graphicsdriver/opengl.(*Image).Pixels(0x8b1acd0, 0x1a490000, 0x39d650, 0x1a300004, 0x39d650, 0x1) wasm_exec.js:51:14
	/home/sedyh/.local/share/go/path-workspace/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.0/internal/graphicsdriver/opengl/image.go:72 +0x12 fp=0x89baf8 sp=0x89bab0 pc=0x1a390012 wasm_exec.js:51:14
github.com/hajimehoshi/ebiten/v2/internal/graphicscommand.(*pixelsCommand).Exec(0xdfbe100, 0x0, 0x768c0, 0x64641e8) wasm_exec.js:51:14
	/home/sedyh/.local/share/go/path-workspace/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.0/internal/graphicscommand/command.go:524 +0x8 fp=0x89bb30 sp=0x89baf8 pc=0x18a90008 wasm_exec.js:51:14
github.com/hajimehoshi/ebiten/v2/internal/graphicscommand.(*commandQueue).flush(0x39d480, 0x0, 0xdfbe100) wasm_exec.js:51:14
	/home/sedyh/.local/share/go/path-workspace/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.0/internal/graphicscommand/command.go:282 +0x34 fp=0x89bc68 sp=0x89bb30 pc=0x189a0034 wasm_exec.js:51:14
github.com/hajimehoshi/ebiten/v2/internal/graphicscommand.(*commandQueue).Flush.func1(0x10, 0x469a0) wasm_exec.js:51:14
	/home/sedyh/.local/share/go/path-workspace/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.0/internal/graphicscommand/command.go:206 +0x2 fp=0x89bc88 sp=0x89bc68 pc=0x18db0002 wasm_exec.js:51:14
github.com/hajimehoshi/ebiten/v2/internal/graphicscommand.runOnMainThread(0xe0920c0, 0xe0920c0, 0xdfbe100) wasm_exec.js:51:14
	/home/sedyh/.local/share/go/path-workspace/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.0/internal/graphicscommand/thread.go:33 +0x9 fp=0x89bcb0 sp=0x89bc88 pc=0x18da0009 wasm_exec.js:51:14
github.com/hajimehoshi/ebiten/v2/internal/graphicscommand.(*commandQueue).Flush(0x39d480, 0xdfbe100, 0x0) wasm_exec.js:51:14
	/home/sedyh/.local/share/go/path-workspace/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.0/internal/graphicscommand/command.go:205 +0x5 fp=0x89bcd0 sp=0x89bcb0 pc=0x18990005 wasm_exec.js:51:14
github.com/hajimehoshi/ebiten/v2/internal/graphicscommand.(*Image).Pixels(0x1077a40, 0xfec00000, 0xc82710, 0xc82710, 0x0, 0x0) wasm_exec.js:51:14
	/home/sedyh/.local/share/go/path-workspace/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.0/internal/graphicscommand/image.go:174 +0x15 fp=0x89bd38 sp=0x89bcd0 pc=0x18d80015 wasm_exec.js:51:14
github.com/hajimehoshi/ebiten/v2/internal/restorable.(*Image).readPixelsFromGPU(0x8b40b40, 0x1, 0x9f94ff0) wasm_exec.js:51:14
	/home/sedyh/.local/share/go/path-workspace/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.0/internal/restorable/image.go:476 +0x4 fp=0x89bdb0 sp=0x89bd38 pc=0x18f00004 wasm_exec.js:51:14
github.com/hajimehoshi/ebiten/v2/internal/restorable.(*Image).resolveStale(0x8b40b40, 0x0, 0x0) wasm_exec.js:51:14
	/home/sedyh/.local/share/go/path-workspace/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.0/internal/restorable/image.go:502 +0xb fp=0x89bdd0 sp=0x89bdb0 pc=0x18f1000b wasm_exec.js:51:14
github.com/hajimehoshi/ebiten/v2/internal/restorable.(*images).resolveStaleImages(0x39cd60, 0x1, 0x0) wasm_exec.js:51:14
	/home/sedyh/.local/share/go/path-workspace/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.0/internal/restorable/images.go:149 +0xb fp=0x89be50 sp=0x89bdd0 pc=0x18f9000b wasm_exec.js:51:14
github.com/hajimehoshi/ebiten/v2/internal/restorable.ResolveStaleImages(0x3b9a08, 0x2) wasm_exec.js:51:14
	/home/sedyh/.local/share/go/path-workspace/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.0/internal/restorable/images.go:65 +0xb fp=0x89be70 sp=0x89be50 pc=0x18f7000b wasm_exec.js:51:14
github.com/hajimehoshi/ebiten/v2/internal/atlas.EndFrame(0x39d300, 0x1) wasm_exec.js:51:14
	/home/sedyh/.local/share/go/path-workspace/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.0/internal/atlas/image.go:703 +0x3 fp=0x89be88 sp=0x89be70 pc=0x19170003 wasm_exec.js:51:14
github.com/hajimehoshi/ebiten/v2/internal/buffered.EndFrame(...) wasm_exec.js:51:14
	/home/sedyh/.local/share/go/path-workspace/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.0/internal/buffered/image.go:45 wasm_exec.js:51:14
github.com/hajimehoshi/ebiten/v2.(*uiContext).Update(0x39d300, 0x0, 0x3b9a88) wasm_exec.js:51:14
	/home/sedyh/.local/share/go/path-workspace/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.0/uicontext.go:156 +0x13 fp=0x89bec0 sp=0x89be88 pc=0x1aba0013 wasm_exec.js:51:14
github.com/hajimehoshi/ebiten/v2/internal/uidriver/js.(*UserInterface).updateImpl(0x378e60, 0x0, 0x0, 0x0) wasm_exec.js:51:14
	/home/sedyh/.local/share/go/path-workspace/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.0/internal/uidriver/js/ui_js.go:249 +0x10 fp=0x89bee8 sp=0x89bec0 pc=0x1a6d0010 wasm_exec.js:51:14
github.com/hajimehoshi/ebiten/v2/internal/uidriver/js.(*UserInterface).update(0x378e60, 0x0, 0x0) wasm_exec.js:51:14
	/home/sedyh/.local/share/go/path-workspace/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.0/internal/uidriver/js/ui_js.go:237 +0xa fp=0x89bf10 sp=0x89bee8 pc=0x1a6c000a wasm_exec.js:51:14
github.com/hajimehoshi/ebiten/v2/internal/uidriver/js.(*UserInterface).loop.func1() wasm_exec.js:51:14
	/home/sedyh/.local/share/go/path-workspace/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.0/internal/uidriver/js/ui_js.go:270 +0x5 fp=0x89bfe0 sp=0x89bf10 pc=0x1a790005 wasm_exec.js:51:14
runtime.goexit() wasm_exec.js:51:14
	/home/sedyh/.local/share/go/root-sdk/go1.16.7/src/runtime/asm_wasm.s:427 +0x1 fp=0x89bfe8 sp=0x89bfe0 pc=0x13c50001 wasm_exec.js:51:14
created by github.com/hajimehoshi/ebiten/v2/internal/uidriver/js.(*UserInterface).loop.func2 wasm_exec.js:51:14
	/home/sedyh/.local/share/go/path-workspace/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.0/internal/uidriver/js/ui_js.go:288 +0x4 wasm_exec.js:51:14
<empty string> wasm_exec.js:51:14
goroutine 1 [chan receive, 2 minutes]: wasm_exec.js:51:14
github.com/hajimehoshi/ebiten/v2/internal/uidriver/js.(*UserInterface).Run(0x378e60, 0x135670, 0x39d300, 0x8940a8, 0x8901c0) wasm_exec.js:51:14
	/home/sedyh/.local/share/go/path-workspace/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.0/internal/uidriver/js/ui_js.go:527 +0x8 wasm_exec.js:51:14
github.com/hajimehoshi/ebiten/v2.RunGame(0x134fa0, 0x834320, 0x0, 0x0) wasm_exec.js:51:14
	/home/sedyh/.local/share/go/path-workspace/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.0/run.go:172 +0x9 wasm_exec.js:51:14
kettler/engine.(*Game).Run(...) wasm_exec.js:51:14
	/home/sedyh/projects/go/kettler/engine/game.go:56 wasm_exec.js:51:14
main.main() wasm_exec.js:51:14
	/home/sedyh/projects/go/kettler/main.go:20 +0x13 wasm_exec.js:51:14
<empty string> wasm_exec.js:51:14
goroutine 9 [waiting]: wasm_exec.js:51:14
runtime.gopark(0x0, 0x0, 0x0, 0x1) wasm_exec.js:51:14
	/home/sedyh/.local/share/go/root-sdk/go1.16.7/src/runtime/proc.go:336 +0x22 wasm_exec.js:51:14
runtime.handleEvent() wasm_exec.js:51:14
	/home/sedyh/.local/share/go/root-sdk/go1.16.7/src/runtime/lock_js.go:244 +0xf wasm_exec.js:51:14
runtime.goexit() wasm_exec.js:51:14
	/home/sedyh/.local/share/go/root-sdk/go1.16.7/src/runtime/asm_wasm.s:427 +0x1 wasm_exec.js:51:14
<empty string> wasm_exec.js:51:14
goroutine 8 [select]: wasm_exec.js:51:14
github.com/hajimehoshi/ebiten/v2/internal/uidriver/js.(*UserInterface).loop.func3(0x836240, 0x378e60, 0x8361e0) wasm_exec.js:51:14
	/home/sedyh/.local/share/go/path-workspace/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.0/internal/uidriver/js/ui_js.go:316 +0x7 wasm_exec.js:51:14
created by github.com/hajimehoshi/ebiten/v2/internal/uidriver/js.(*UserInterface).loop wasm_exec.js:51:14
	/home/sedyh/.local/share/go/path-workspace/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.1.0/internal/uidriver/js/ui_js.go:298 +0x14 wasm_exec.js:51:14
exit code: 2
```

And again, there are same endless errors a few minutes after panic.

**Comment by hajimehoshi** [comment]
> without spamming errors in a loop.

I think this is due to Go runtime rather than Ebiten.

Apparently there seems nothing Ebiten can do so far. Let me close this. Do not hesitate to reopen this if you find a good solution or new insights. Thanks,

**Comment by hajimehoshi** [comment]
> Hmm, this is quite strange, but after switching on, oom occurs after a couple of minutes of the game, I don't seem to create anything expensive for memory. On the desktop, memory practically does not grow after startup, it seems there is something here

What about Ebiten v2.2.0-rc.2?

**Comment by superloach** [comment]
> > without spamming errors in a loop.
> 
> I think this is due to Go runtime rather than Ebiten.
> 
> Apparently there seems nothing Ebiten can do so far. Let me close this. Do not hesitate to reopen this if you find a good solution or new insights. Thanks,

I think perhaps Ebiten should avoid crashing when it fails to get a WebGL context (null check), show an error message, and exit gracefully. This would avoid the issues with the Go runtime.

**Comment by hajimehoshi** [comment]
The message spam still happens after the runtime exits, but making this an error instead of a panic makes sense.
