### ISSUE TITLE
Ebiten mac app with transparent window crashes when green fullscreen button is clicked

### ISSUE THREAD

**Issue by IlyaFloppy** [hajimehoshi/ebiten#1857]
```go
package main

import (
	"fmt"
	"log"

	"github.com/hajimehoshi/ebiten/v2"
	"github.com/hajimehoshi/ebiten/v2/ebitenutil"
)

type Game struct {
}

func (g *Game) Update() error {
	return nil
}

func (g *Game) Draw(screen *ebiten.Image) {
	ebitenutil.DebugPrint(screen, fmt.Sprintf("fps=%0.2f\ntps=%0.2f", ebiten.CurrentFPS(), ebiten.CurrentTPS()))
}

func (g *Game) Layout(outsideWidth, outsideHeight int) (int, int) {
	return outsideWidth, outsideHeight
}

func main() {
	ebiten.SetScreenTransparent(true)
	ebiten.SetWindowResizable(true)

	if err := ebiten.RunGame(&Game{}); err != nil {
		log.Fatal(err)
	}
}

```

<details>
  <summary>Crash log</summary>
  
```
~/Development/gobugs/ebitennsexception » go run main.go                                                                               1 ↵ ilya@mb-pro
2021-10-30 03:24:50.591 main[32110:711310] *** Assertion failure in -[_NSFullScreenMenuBarCompanionController getToolbarLayout], _NSFullScreenMenuBarCompanionController.m:234
2021-10-30 03:24:50.600 main[32110:711310] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'getToolbarLayout called with a nil content view'
*** First throw call stack:
(
        0   CoreFoundation                      0x00007ff819d77e5b __exceptionPreprocess + 242
        1   libobjc.A.dylib                     0x00007ff819ad8b9d objc_exception_throw + 48
        2   Foundation                          0x00007ff81ac2e653 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 267
        3   AppKit                              0x00007ff81cdbf816 -[_NSFullScreenMenuBarCompanionController getToolbarLayout] + 149
        4   AppKit                              0x00007ff81cdc028e -[_NSFullScreenMenuBarCompanionController _visibleWindowHeight] + 42
        5   AppKit                              0x00007ff81cdc0223 -[_NSFullScreenMenuBarCompanionController effectiveClampedAutohideHeight] + 31
        6   AppKit                              0x00007ff81cdc080a -[_NSFullScreenMenuBarCompanionController correctWindowTopTarget] + 150
        7   AppKit                              0x00007ff81cdc168b -[_NSFullScreenMenuBarCompanionController _calcWindowTopLeft] + 113
        8   AppKit                              0x00007ff81cdc2fc8 -[_NSFullScreenMenuBarCompanionController tile] + 343
        9   AppKit                              0x00007ff81d239c9f -[NSWindow(NSFullScreen) _fullScreenStatusChanged] + 187
        10  AppKit                              0x00007ff81c77547e __25-[NSWindow setStyleMask:]_block_invoke + 1973
        11  AppKit                              0x00007ff81c774c71 NSPerformVisuallyAtomicChange + 132
        12  AppKit                              0x00007ff81c774b7e -[NSWindow setStyleMask:] + 170
        13  AppKit                              0x00007ff81d07fc58 __76-[_NSEnterFullScreenTransitionController setupWindowForAfterFullScreenEnter]_block_invoke + 116
        14  AppKit                              0x00007ff81c774c71 NSPerformVisuallyAtomicChange + 132
        15  AppKit                              0x00007ff81d07fb85 -[_NSEnterFullScreenTransitionController setupWindowForAfterFullScreenEnter] + 317
        16  AppKit                              0x00007ff81d083aad -[_NSEnterFullScreenTransitionController start] + 930
        17  AppKit                              0x00007ff81d1ebdd9 -[_NSFullScreenSpace(Transitions) startTransition:] + 133
        18  AppKit                              0x00007ff81c92a64d -[NSApplication(NSResponder) sendAction:to:from:] + 288
        19  AppKit                              0x00007ff81c92a4f4 -[NSControl sendAction:to:] + 86
        20  AppKit                              0x00007ff81c92a426 __26-[NSCell _sendActionFrom:]_block_invoke + 131
        21  AppKit                              0x00007ff81c92a32f -[NSCell _sendActionFrom:] + 171
        22  AppKit                              0x00007ff81c92a276 -[NSButtonCell _sendActionFrom:] + 96
        23  AppKit                              0x00007ff81d043aed -[_NSThemeZoomWidgetCell _sendActionFrom:] + 71
        24  AppKit                              0x00007ff81c9270e4 NSControlTrackMouse + 1817
        25  AppKit                              0x00007ff81c9269a7 -[NSCell trackMouse:inRect:ofView:untilMouseUp:] + 121
        26  AppKit                              0x00007ff81c92687a -[NSButtonCell trackMouse:inRect:ofView:untilMouseUp:] + 679
        27  AppKit                              0x00007ff81d043788 -[_NSThemeZoomWidgetCell trackMouse:inRect:ofView:untilMouseUp:] + 331
        28  AppKit                              0x00007ff81c925c48 -[NSControl mouseDown:] + 678
        29  AppKit                              0x00007ff81c924127 -[NSWindow(NSEventRouting) _handleMouseDownEvent:isDelayedEvent:] + 4949
        30  AppKit                              0x00007ff81c8980a4 -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 2582
        31  AppKit                              0x00007ff81c89746e -[NSWindow(NSEventRouting) sendEvent:] + 352
        32  AppKit                              0x00007ff81c89583c -[NSApplication(NSEvent) sendEvent:] + 352
        33  main                                0x00000000041c0ed1 _glfwPlatformPollEvents + 177
        34  main                                0x0000000004062124 runtime.asmcgocall.abi0 + 100
)
libc++abi: terminating with uncaught exception of type NSException
SIGABRT: abort
PC=0x7ff819bff112 m=0 sigcode=0
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x41c51c0, 0xc0000c1d98)
        /Users/ilya/Development/go/src/runtime/cgocall.go:157 +0x5c fp=0xc0000c1d70 sp=0xc0000c1d38 pc=0x400507c
github.com/go-gl/glfw/v3.3/glfw._Cfunc_glfwPollEvents()
        _cgo_gotypes.go:1477 +0x45 fp=0xc0000c1d98 sp=0xc0000c1d70 pc=0x410a545
github.com/go-gl/glfw/v3.3/glfw.PollEvents()
        /Users/ilya/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20210727001814-0db043d8d5be/window.go:964 +0x17 fp=0xc0000c1da8 sp=0xc0000c1d98 pc=0x4111157
github.com/hajimehoshi/ebiten/v2/internal/glfw.PollEvents(...)
        /Users/ilya/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.2.1/internal/glfw/glfw_notwindows.go:325
github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.(*UserInterface).update(0x4433bc0)
        /Users/ilya/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.2.1/internal/uidriver/glfw/ui.go:1035 +0x150 fp=0xc0000c1e00 sp=0xc0000c1da8 pc=0x4147410
github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.(*UserInterface).loop.func2()
        /Users/ilya/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.2.1/internal/uidriver/glfw/ui.go:1084 +0x38 fp=0xc0000c1e30 sp=0xc0000c1e00 pc=0x4147e18
github.com/hajimehoshi/ebiten/v2/internal/thread.(*OSThread).Loop(0xc000098e60)
        /Users/ilya/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.2.1/internal/thread/thread.go:51 +0x77 fp=0xc0000c1e88 sp=0xc0000c1e30 pc=0x4112f97
github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.(*UserInterface).Run(0x4433bc0, {0x4274050, 0x4439060})
        /Users/ilya/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.2.1/internal/uidriver/glfw/run_notsinglethread.go:60 +0x1c2 fp=0xc0000c1ed8 sp=0xc0000c1e88 pc=0x4143782
github.com/hajimehoshi/ebiten/v2.RunGame({0x4273d38, 0x4469630})
        /Users/ilya/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.2.1/run.go:160 +0xe5 fp=0xc0000c1f48 sp=0xc0000c1ed8 pc=0x414fb45
main.main()
        /Users/ilya/Development/gobugs/ebitennsexception/main.go:30 +0x45 fp=0xc0000c1f80 sp=0xc0000c1f48 pc=0x41af645
runtime.main()
        /Users/ilya/Development/go/src/runtime/proc.go:255 +0x227 fp=0xc0000c1fe0 sp=0xc0000c1f80 pc=0x4036c47
runtime.goexit()
        /Users/ilya/Development/go/src/runtime/asm_amd64.s:1446 +0x1 fp=0xc0000c1fe8 sp=0xc0000c1fe0 pc=0x4062441

goroutine 7 [chan receive]:
github.com/hajimehoshi/ebiten/v2/internal/thread.(*OSThread).Call(0xc000098e60, 0xacbd9238)
        /Users/ilya/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.2.1/internal/thread/thread.go:69 +0x47
github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.(*UserInterface).loop(0x4433bc0)
        /Users/ilya/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.2.1/internal/uidriver/glfw/ui.go:1082 +0x1a3
github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.(*UserInterface).Run.func1()
        /Users/ilya/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.2.1/internal/uidriver/glfw/run_notsinglethread.go:53 +0xe6
created by github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.(*UserInterface).Run
        /Users/ilya/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.2.1/internal/uidriver/glfw/run_notsinglethread.go:37 +0x19f

rax    0x0
rbx    0x5ca9600
rcx    0x7ff7bfefd558
rdx    0x0
rdi    0x103
rsi    0x6
rbp    0x7ff7bfefd580
rsp    0x7ff7bfefd558
r8     0x7ff7bfefd420
r9     0x7ff819bf4fa1
r10    0x0
r11    0x246
r12    0x103
r13    0x3000000008
r14    0x6
r15    0x16
rip    0x7ff819bff112
rflags 0x246
cs     0x7
fs     0x0
gs     0x0
exit status 2
```
  
</details>

**Comment by hajimehoshi** [comment]
I'll take a look, thanks

**Comment by hajimehoshi** [comment]
Confirmed.

**Comment by hajimehoshi** [comment]
The culprit a7b5db6f6519f0c807ee30023ad169313699357c

**Comment by hajimehoshi** [comment]
Another change to change the behavior 428c079e52ba4a1010b4f395d303f575b34f1e8a
