### ISSUE TITLE
examples/audio: Crash on Ubuntu Linux (DELL Inspiron 11 3162)

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#187]
```
panic: audio: Queue in process: 40963
        panic: audio: error after closing: 40963

goroutine 18 [running]:
panic(0x6253e0, 0xc8201108f0)
        /usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/hajimehoshi/ebiten/exp/audio.(*player).close(0xc82010e140, 0x0, 0x0)
        /home/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/exp/audio/audio_openal.go:175 +0x593
panic(0x6253e0, 0xc8201108d0)
        /usr/local/go/src/runtime/panic.go:426 +0x4e9
github.com/hajimehoshi/ebiten/exp/audio.(*player).proceed(0xc82010e140, 0x0, 0x0)
        /home/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/exp/audio/audio_openal.go:95 +0x7c6
github.com/hajimehoshi/ebiten/exp/audio.(*player).start.func1(0xc82010e140)
        /home/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/exp/audio/audio_openal.go:141 +0x50
created by github.com/hajimehoshi/ebiten/exp/audio.(*player).start
        /home/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/exp/audio/audio_openal.go:152 +0x4d9
exit status 2
```

**Comment by hajimehoshi** [comment]
Instead of fixing this bug, how about using `/dev/dsp` on Linux?
