### ISSUE TITLE
OpenAL on OS X is buggy so that audio.NewContext causes crash

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#195]
```
runtime: writebarrierptr *0x45ec598 = 0x18
fatal error: bad pointer in write barrier

runtime stack:
runtime.throw(0x4337840, 0x1c)
        /usr/local/go/src/runtime/panic.go:530 +0x90
runtime.writebarrierptr.func1()
        /usr/local/go/src/runtime/mbarrier.go:140 +0xb3
runtime.systemstack(0xc82001c000)
        /usr/local/go/src/runtime/asm_amd64.s:291 +0x79
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1048

goroutine 6 [running]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:245 fp=0xc820038b90 sp=0xc820038b88
runtime.writebarrierptr(0x45ec598, 0x18)
        /usr/local/go/src/runtime/mbarrier.go:141 +0x97 fp=0xc820038bc0 sp=0xc820038b90
golang.org/x/mobile/exp/audio/al.OpenDevice(0x0, 0x0)
        /Users/hajimehoshi/go/src/golang.org/x/mobile/exp/audio/al/alc.go:53 +0x47c fp=0xc820038c78 sp=0xc820038bc0
github.com/hajimehoshi/ebiten/exp/audio.startPlaying(0xc790000, 0xc8200fc000, 0xac44, 0xc790000, 0x0, 0x0)
        /Users/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/exp/audio/audio_openal.go:44 +0x36 fp=0xc820038d58 sp=0xc820038c78
github.com/hajimehoshi/ebiten/exp/audio.NewContext(0xac44, 0x4522070)
        /Users/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/exp/audio/audio.go:125 +0x151 fp=0xc820038e18 sp=0xc820038d58
main.initAudio.func1(0xc820016540)
        /Users/hajimehoshi/go/src/github.com/hajimehoshi/go-inovation/audio.go:33 +0x70 fp=0xc820038fa8 sp=0xc820038e18
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820038fb0 sp=0xc820038fa8
created by main.initAudio
        /Users/hajimehoshi/go/src/github.com/hajimehoshi/go-inovation/audio.go:68 +0x53

goroutine 1 [runnable, locked to thread]:
github.com/hajimehoshi/ebiten/internal/graphics/opengl.(*Context).NewTexture(0xc8200e0000, 0x200, 0x800, 0xc8205fc000, 0x400000, 0x400000, 0x2600, 0x4d04458, 0xc82000ad50, 0x40b7f41)
        /Users/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/internal/graphics/opengl/context_desktop.go:132
github.com/hajimehoshi/ebiten/internal/graphics.NewTextureFromImage(0xc8200e0000, 0x4d04608, 0xc820010400, 0x2600, 0xc8200ff000, 0x0, 0x0)
        /Users/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/internal/graphics/texture.go:82 +0x3be
github.com/hajimehoshi/ebiten.NewImageFromImage(0x4d04608, 0xc820010400, 0x0, 0xc820010400, 0x0, 0x0)
        /Users/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/image.go:228 +0x7a
github.com/hajimehoshi/ebiten/ebitenutil.NewImageFromFile(0xc82000e880, 0x1c, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/ebitenutil/loadimage.go:37 +0x1b6
main.Run(0x0, 0x0)
        /Users/hajimehoshi/go/src/github.com/hajimehoshi/go-inovation/main.go:443 +0x30e
main.main()
        /Users/hajimehoshi/go/src/github.com/hajimehoshi/go-inovation/main.go:457 +0x1c

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 5 [chan receive, locked to thread]:
github.com/hajimehoshi/ebiten/internal/graphics/opengl.(*Context).Loop(0xc8200e0000)
        /Users/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/internal/graphics/opengl/context_desktop.go:83 +0x55
github.com/hajimehoshi/ebiten/internal/ui.Init.func1(0xc820012280, 0xc820016120)
        /Users/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/internal/ui/ui_glfw.go:79 +0xe4
created by github.com/hajimehoshi/ebiten/internal/ui.Init
        /Users/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/internal/ui/ui_glfw.go:80 +0x362
exit status 2
```

**Comment by hajimehoshi** [comment]
Seems like alcOpenDevice returns 0x18. Really?

**Comment by hajimehoshi** [comment]
https://groups.google.com/forum/#!topic/golang-bugs/nARJpJCYum4 Oh, this is a known issue...

**Comment by hajimehoshi** [comment]
Ugh, this still happens even with another OpenAL program...

```
runtime: bad pointer in frame github.com/timshannon/go-openal/openal.OpenDevice at 0xc82002a4d0: 0x18
fatal error: invalid stack pointer

runtime stack:
runtime.throw(0x4336bd0, 0x15)
        /usr/local/go/src/runtime/panic.go:530 +0x90 fp=0x7000004ab6f8 sp=0x7000004ab6e0
runtime.adjustpointers(0xc82002a4c8, 0x7000004ab878, 0x7000004abba0, 0x45baaf0)
        /usr/local/go/src/runtime/stack.go:579 +0x2d4 fp=0x7000004ab7f0 sp=0x7000004ab6f8
runtime.adjustframe(0x7000004abac0, 0x7000004abba0, 0x7000004ab901)
        /usr/local/go/src/runtime/stack.go:644 +0x1cb fp=0x7000004ab8b0 sp=0x7000004ab7f0
runtime.gentraceback(0x401f090, 0xc82002a2b8, 0x0, 0xc820001b00, 0x0, 0x0, 0x7fffffff, 0x45305c0, 0x7000004abba0, 0x0, ...)
        /usr/local/go/src/runtime/traceback.go:369 +0xd95 fp=0x7000004abb18 sp=0x7000004ab8b0
runtime.copystack(0xc820001b00, 0x1000)
        /usr/local/go/src/runtime/stack.go:759 +0x1be fp=0x7000004abd08 sp=0x7000004abb18
runtime.newstack()
        /usr/local/go/src/runtime/stack.go:947 +0xb4d fp=0x7000004abe78 sp=0x7000004abd08
runtime.morestack()
        /usr/local/go/src/runtime/asm_amd64.s:359 +0x7f fp=0x7000004abe80 sp=0x7000004abe78

goroutine 7 [copystack]:
runtime.mallocgc(0x0, 0x4200740, 0x1, 0x0)
        /usr/local/go/src/runtime/malloc.go:499 fp=0xc82002a2c0 sp=0xc82002a2b8
runtime.newobject(0x4200740, 0x45e1988)
        /usr/local/go/src/runtime/malloc.go:781 +0x42 fp=0xc82002a2e8 sp=0xc82002a2c0
sync.poolCleanup()
        /usr/local/go/src/sync/pool.go:207 +0x185 fp=0xc82002a360 sp=0xc82002a2e8
runtime.clearpools()
        /usr/local/go/src/runtime/mgc.go:1755 +0x31 fp=0xc82002a370 sp=0xc82002a360
runtime.gcStart(0x0, 0x0)
        /usr/local/go/src/runtime/mgc.go:950 +0x27b fp=0xc82002a398 sp=0xc82002a370
runtime.mallocgc(0x8, 0x42a3320, 0x0, 0x4848db0)
        /usr/local/go/src/runtime/malloc.go:744 +0x578 fp=0xc82002a470 sp=0xc82002a398
runtime.newobject(0x42a3320, 0x4848db0)
        /usr/local/go/src/runtime/malloc.go:781 +0x42 fp=0xc82002a498 sp=0xc82002a470
github.com/timshannon/go-openal/openal.OpenDevice(0x0, 0x0, 0x0)
        /Users/hajimehoshi/go/src/github.com/timshannon/go-openal/openal/alcCore.go:114 +0x9f fp=0xc82002a4f8 sp=0xc82002a498
github.com/hajimehoshi/ebiten/exp/audio/internal/driver.NewPlayer(0xd078000, 0xc8200e8040, 0xac44, 0x2, 0x2, 0x4b00960, 0x0, 0x0)
        /Users/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/exp/audio/internal/driver/driver_openal.go:59 +0x44 fp=0xc82002a648 sp=0xc82002a4f8
github.com/hajimehoshi/ebiten/exp/audio.NewContext(0xac44, 0xc8200f2000, 0x0, 0x0)
        /Users/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/exp/audio/audio.go:200 +0x189 fp=0xc82002a6d0 sp=0xc82002a648
main.(*Game).loadAudio(0xc820010340)
        /Users/hajimehoshi/go/src/github.com/hajimehoshi/go-inovation/audio.go:44 +0xb8 fp=0xc82002a7a8 sp=0xc82002a6d0
main.Run.func2(0xc820010340)
        /Users/hajimehoshi/go/src/github.com/hajimehoshi/go-inovation/main.go:533 +0x21 fp=0xc82002a7b8 sp=0xc82002a7a8
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82002a7c0 sp=0xc82002a7b8
created by main.Run
        /Users/hajimehoshi/go/src/github.com/hajimehoshi/go-inovation/main.go:534 +0x182

...
```

**Comment by hajimehoshi** [comment]
96296f076dd66a27b816c2dc3eac4a55baa218cd might solve this.

**Comment by hajimehoshi** [comment]
Finally I have created my fork of an OpenAL lib and fixed this to use uintptrs instead of C pointers.
