### ISSUE TITLE
ebiten: test failed on Ubuntu

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1951]
https://github.com/hajimehoshi/ebiten/runs/4777556985?check_suite_focus=true

```
=== RUN   TestImageDrawImageCannotAllocateImageForMipmap
--- FAIL: TestImageDrawImageCannotAllocateImageForMipmap (0.00s)
panic: opengl: fragment shader compile error: opengl: shader compile failed: 0:28(22): error: operator '%' is reserved in GLSL 1.10 (GLSL 1.30 or GLSL ES 3.00 required)
0:28(17): error: cannot construct `vec4' from a non-numeric data type
, source:
#if defined(GL_ES)
precision highp float;
#else
#define lowp
#define mediump
#define highp
#endif

uniform vec2 U0;
uniform vec2 U1[4];
uniform vec2 U2;
uniform vec2 U3;
uniform vec2 U4[3];
uniform vec2 U5;
uniform vec2 U6;
uniform sampler2D T0;
uniform sampler2D T1;
uniform sampler2D T2;
uniform sampler2D T3;
varying vec2 V0;
varying vec4 V1;

void main(void) {
	int l0 = 0;
	int l1 = 0;
	l0 = 2;
	l1 = 1;
	gl_FragColor = vec4((l0) % (l1));
	return;
}
 [recovered]
	panic: opengl: fragment shader compile error: opengl: shader compile failed: 0:28(22): error: operator '%' is reserved in GLSL 1.10 (GLSL 1.30 or GLSL ES 3.00 required)
0:28(17): error: cannot construct `vec4' from a non-numeric data type
, source:
#if defined(GL_ES)
precision highp float;
#else
#define lowp
#define mediump
#define highp
#endif

uniform vec2 U0;
uniform vec2 U1[4];
uniform vec2 U2;
uniform vec2 U3;
uniform vec2 U4[3];
uniform vec2 U5;
uniform vec2 U6;
uniform sampler2D T0;
uniform sampler2D T1;
uniform sampler2D T2;
uniform sampler2D T3;
varying vec2 V0;
varying vec4 V1;

void main(void) {
	int l0 = 0;
	int l1 = 0;
	l0 = 2;
	l1 = 1;
	gl_FragColor = vec4((l0) % (l1));
	return;
}


goroutine 68 [running]:
testing.tRunner.func1.2({0x680ca0, 0xc0009591a0})
	/opt/hostedtoolcache/go/1.17.5/x64/src/testing/testing.go:1209 +0x24e
testing.tRunner.func1()
	/opt/hostedtoolcache/go/1.17.5/x64/src/testing/testing.go:1212 +0x218
panic({0x680ca0, 0xc0009591a0})
	/opt/hostedtoolcache/go/1.17.5/x64/src/runtime/panic.go:1038 +0x215
github.com/hajimehoshi/ebiten/v2.(*Image).at(0x474, 0xc0009ad1d0, 0x868508)
	/home/runner/work/ebiten/ebiten/image.go:719 +0x159
github.com/hajimehoshi/ebiten/v2.(*Image).At(0xc000955ac0, 0xc000955b80, 0x79882c)
	/home/runner/work/ebiten/ebiten/image.go:689 +0x19
github.com/hajimehoshi/ebiten/v2_test.TestImageDrawImageCannotAllocateImageForMipmap(0xc000086b60)
	/home/runner/work/ebiten/ebiten/image_test.go:2181 +0x94
testing.tRunner(0xc000087860, 0x6e1200)
	/opt/hostedtoolcache/go/1.17.5/x64/src/testing/testing.go:1259 +0x102
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.17.5/x64/src/testing/testing.go:1306 +0x35a
FAIL	github.com/hajimehoshi/ebiten/v2	3.740s
```

**Comment by hajimehoshi** [comment]
TestImageDrawImageCannotAllocateImageForMipmap is not related. This is very mysterious.
