### ISSUE TITLE
Crash on Alpine Linux

### ISSUE THREAD

**Issue by divVerent** [hajimehoshi/ebiten#2027]
Repro:

- Install Alpine Linux, X11 and Go
- Clone Ebiten
- Run: `go run examples/rotate/main.go`
- All works fine, until you press a key (any key will do). Then:

```
panic: runtime error: index out of range [65317] with length 512

goroutine 1 [running, locked to thread]:
github.com/hajimehoshi/ebiten/v2/internal/gamepad.(*nativeGamepad).update(0xc0000b4028, 0x41bf90)
        /home/rpolzer/src/ebiten/internal/gamepad/gamepad_linux.go:331 +0x21f
github.com/hajimehoshi/ebiten/v2/internal/gamepad.(*Gamepad).update(0x8afe48, 0x0)
        /home/rpolzer/src/ebiten/internal/gamepad/gamepad.go:166 +0x9b
github.com/hajimehoshi/ebiten/v2/internal/gamepad.(*gamepads).update(0x8afe20)
        /home/rpolzer/src/ebiten/internal/gamepad/gamepad.go:94 +0x152
github.com/hajimehoshi/ebiten/v2/internal/gamepad.Update(...)
        /home/rpolzer/src/ebiten/internal/gamepad/gamepad.go:55
github.com/hajimehoshi/ebiten/v2/internal/ui.(*Input).update(0x8b06b0, 0xc0004e2010, 0x0)
        /home/rpolzer/src/ebiten/internal/ui/input_glfw.go:206 +0x3cc
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).update(0x8b0580)
        /home/rpolzer/src/ebiten/internal/ui/ui_glfw.go:981 +0x170
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).loop.func1()
        /home/rpolzer/src/ebiten/internal/ui/ui_glfw.go:1023 +0x4a
github.com/hajimehoshi/ebiten/v2/internal/thread.(*OSThread).Loop.func1(0xc000445e10, 0xc000445e00)
        /home/rpolzer/src/ebiten/internal/thread/thread.go:54 +0x53
github.com/hajimehoshi/ebiten/v2/internal/thread.(*OSThread).Loop(0xc0004e4030)
        /home/rpolzer/src/ebiten/internal/thread/thread.go:55 +0x2e
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).Run(0x8b0580, {0x6bd878, 0xc0004f6040})
        /home/rpolzer/src/ebiten/internal/ui/run_notsinglethread.go:53 +0x21f
github.com/hajimehoshi/ebiten/v2.RunGame({0x6be418, 0xc0004e60f0})
        /home/rpolzer/src/ebiten/run.go:175 +0x145
main.main()
        /home/rpolzer/src/ebiten/examples/rotate/main.go:85 +0x149
exit status 2
```

Have not investigated yet, though.

**Comment by divVerent** [comment]
Crashing line is:

```
idx := g.keyMap[e.code-_BTN_MISC]
```

_BTN_MISC is 0x100. e.code thus was 0x10025. Don't yet know which "gamepad" this is from, as I don't even have one connected.

**Comment by divVerent** [comment]
`go run examples/moire/moire.go` crashes differently:

```
panic: runtime error: index out of range [32] with length 32

goroutine 34 [running]:
github.com/hajimehoshi/ebiten/v2/inpututil.(*inputState).update(0x8a2a80)
        /home/rpolzer/src/ebiten/inpututil/inpututil.go:148 +0xd35
github.com/hajimehoshi/ebiten/v2/inpututil.init.0.func1()
        /home/rpolzer/src/ebiten/inpututil/inpututil.go:75 +0x25
github.com/hajimehoshi/ebiten/v2/internal/hooks.RunBeforeUpdateHooks()
        /home/rpolzer/src/ebiten/internal/hooks/hooks.go:38 +0xc7
github.com/hajimehoshi/ebiten/v2/internal/ui.(*contextImpl).updateFrameImpl(0xc000432100, {0x6bf318, 0x8a2b60}, 0x1, 0x4084000000000000, 0x407e000000000000, 0xc000254670)
        /home/rpolzer/src/ebiten/internal/ui/context.go:98 +0x185
github.com/hajimehoshi/ebiten/v2/internal/ui.(*contextImpl).updateFrame(0xc00000e108, {0x6bf318, 0x8a2b60}, 0x3, 0x10000c000254720, 0x0)
        /home/rpolzer/src/ebiten/internal/ui/context.go:60 +0x8e
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).loop(0x8a2f20)
        /home/rpolzer/src/ebiten/internal/ui/ui_glfw.go:1029 +0x25f
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).Run.func1()
        /home/rpolzer/src/ebiten/internal/ui/run_notsinglethread.go:46 +0x13d
created by github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).Run
        /home/rpolzer/src/ebiten/internal/ui/run_notsinglethread.go:33 +0x1fd
exit status 2
```

Code in question is also gamepad button related, apparently `ebiten.GamepadButtonNum(id)` is greater than `ebiten.GamepadButtonMax` for some device here that Ebiten thinks might be a gamepad.

**Comment by divVerent** [comment]
`ebiten.GamepadName` for the gamepad that crashes in inpututil is "ITE Tec", which sadly isn't very helpful as ALL my input devices start with that. I suspect that Ebiten decided to open my keyboard and assume it's a gamepad device.

**Comment by divVerent** [comment]
Going by `strace`, it seems like Ebiten has had open a fd to `/dev/input/event0`, which is indeed my keyboard. It had not kept any other event node open.

And TBH in `internal/gamepad/gamepad_linux.go` I see nothing that looks like it's trying to exclude keyboards...

**Comment by divVerent** [comment]
Cannot reproduce on other systems - issue might be specific to this laptop and/or Alpine Linux.

Fixing this by adding the necessary bounds checks (either at runtime, or maybe just reject gamepads with too many buttons at connect time) should do.

**Comment by hajimehoshi** [comment]
Thanks. I think this happens with the latest Ebiten, but does this happen with Ebiten v2.2.5?

**Comment by hajimehoshi** [comment]
I'll cherry-pick the inpututil issue

**Comment by divVerent** [comment]
Sadly not fixed yet; I am going to send a PR to fix the crashes, although it seems like the real solution would be to skip the entire devices.

Including a screenshot of the gamepad demo to show better what's going on: keyboard and touchpad are appearing as "gamepads".

![20220325-152857](https://user-images.githubusercontent.com/251568/160188684-5ec6591e-3f41-4ad9-bd9a-6d8dcbe5609e.png)

**Comment by divVerent** [comment]
With these two changes it's crashfree on that laptop.
