### ISSUE TITLE
Game encounters deadlock after upgrading from ebiten 2.2.7 to 2.3.0

### ISSUE THREAD

**Issue by jcgraybill** [hajimehoshi/ebiten#2079]
Hi! I tried upgrading my game to ebiten 2.3.0 this morning, and now when I run it, it looks like it enters a deadlock state at startup. I've reproduced that downgrading to 2.2.7 resolves this - so it seems pretty isolated to something that changed in 2.3.0.

Game source is at https://github.com/jcgraybill/ship-shape 

Is there any way I can help? Thank you!

```
PS C:\Users\jcg\Documents\GitHub\ship-shape> .\ship-shape.exe
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [select, locked to thread]:
github.com/hajimehoshi/ebiten/v2/internal/thread.(*OSThread).Loop(0xc0005441e0)
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.0/internal/thread/thread.go:47 +0x85
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).Run(0x8f5ba0, {0x682ce8?, 0xc0005441c8})
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.0/internal/ui/run_notsinglethread.go:53 +0x22c
github.com/hajimehoshi/ebiten/v2.RunGame({0x682b48?, 0xc0003f9000})
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.0/run.go:191 +0x12c
main.main()
        C:/Users/jcg/Documents/GitHub/ship-shape/main.go:60 +0x1f3

goroutine 34 [semacquire]:
sync.runtime_SemacquireMutex(0x2?, 0x2?, 0x0?)
        C:/Program Files/Go/src/runtime/sema.go:71 +0x25
sync.(*Mutex).lockSlow(0x94ab50)
        C:/Program Files/Go/src/sync/mutex.go:162 +0x165
sync.(*Mutex).Lock(...)
        C:/Program Files/Go/src/sync/mutex.go:81
github.com/hajimehoshi/ebiten/v2/internal/atlas.(*Image).DrawTriangles(0x0?, {0xc003f2a000, 0x0, 0x0, 0x0}, {0xc005ef2000?, 0x20?, 0x80000?}, {0x7c7788?, 0x6?, ...}, ...)
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.0/internal/atlas/image.go:408 +0x125
github.com/hajimehoshi/ebiten/v2/internal/buffered.(*Image).DrawTriangles(0xc007392be0, {0xc000060140, 0x0, 0x0, 0x0}, {0xc005ef2000?, 0x20, 0x80000}, 
{0x7c7788?, 0x6, ...}, ...)
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.0/internal/buffered/image.go:268 +0x6b7
github.com/hajimehoshi/ebiten/v2/internal/mipmap.(*Mipmap).DrawTriangles(0xc0073776e0, {0xc00044c8d0, 0x0, 0x0, 0x0}, {0xc005ef2000?, 0x20, 0x80000}, {0x7c7788?, 0x6, ...}, ...)
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.0/internal/mipmap/mipmap.go:146 +0x3a5
github.com/hajimehoshi/ebiten/v2/internal/ui.(*Image).DrawTriangles(0x275823f0108?, {0xc000004168, 0x0, 0x0, 0x0}, {0xc005ef2000?, 0xc00004f400?, 0xc007391d80?}, {0x7c7788?, 0x201?, ...}, ...)
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.0/internal/ui/image.go:76 +0x167
github.com/hajimehoshi/ebiten/v2/internal/ui.(*Image).Fill(0xc0072a1c50, 0x31a888?, 0x0?, 0x4?, 0x0?, 0x0, 0x0, 0xc8, 0x244)
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.0/internal/ui/image.go:141 +0x197
github.com/hajimehoshi/ebiten/v2.(*Image).Fill(0xc007391d80, {0x681028?, 0xc0074d1490?})
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.0/image.go:84 +0xc5
github.com/jcgraybill/ship-shape/panel.(*Panel).Resize(0xc001b06420, 0xc00734fce0?, 0x475ff3?)
        C:/Users/jcg/Documents/GitHub/ship-shape/panel/panel.go:136 +0xe5
main.(*Game).Layout(0xc0003f9000, 0x0?, 0x683948?)
        C:/Users/jcg/Documents/GitHub/ship-shape/main.go:88 +0x4f
github.com/hajimehoshi/ebiten/v2.(*imageDumperGame).Layout(0x479797?, 0x8f5460?, 0x0?)
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.0/run.go:159 +0x22
github.com/hajimehoshi/ebiten/v2.(*gameForUI).Layout(0x0?, 0x683948?, 0xc00734fd88?)
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.0/gameforui.go:42 +0x22
github.com/hajimehoshi/ebiten/v2/internal/ui.(*context).layoutGame(0xc0037cca00, 0x4089000000000000, 0x4082c00000000000, 0x3ff4000000000000)
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.0/internal/ui/context.go:215 +0x102
github.com/hajimehoshi/ebiten/v2/internal/ui.(*context).updateFrameImpl(0xc0037cca00, {0x683948, 0x8f5da0}, 0x1, 0x4089000000000000, 0x4082c00000000000, 0xc00734fe98?)
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.0/internal/ui/context.go:94 +0x9c
github.com/hajimehoshi/ebiten/v2/internal/ui.(*context).updateFrame(0xc0005441e0?, {0x683948, 0x8f5da0}, 0xc00059f8b8?, 0xc000501380?, 0xc000501408?)  
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.0/internal/ui/context.go:64 +0x8e
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).loop(0x8f5ba0)
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.0/internal/ui/ui_glfw.go:1065 +0x1ea
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).Run.func1()
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.0/internal/ui/run_notsinglethread.go:46 +0x13d
created by github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).Run
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.0/internal/ui/run_notsinglethread.go:33 +0x20a
```

**Comment by hajimehoshi** [comment]
I'll take a look tomorrow. Thank you for reporting!

**Comment by hajimehoshi** [comment]
Confirmed a dead lock or freezing happened with the latest Ebiten (even on macOS)

**Comment by hajimehoshi** [comment]
git-bisect says 08ae7006ef5284ab40b139ae40579ddfa28dd059 is the culprit

```
08ae7006ef5284ab40b139ae40579ddfa28dd059 is the first bad commit
commit 08ae7006ef5284ab40b139ae40579ddfa28dd059
Author: Hajime Hoshi <hajimehoshi@gmail.com>
Date:   Sun Feb 13 18:12:28 2022 +0900

    internal/ui: refactoring: move some logics to internal/ui

 internal/ui/context.go | 50 +++++++++++++++++++++++++++----------
 uicontext.go           | 68 ++++++++++++++------------------------------------
```

**Comment by hajimehoshi** [comment]
The game's `Layout` was invoked before `BeginFrame`, which caused a deadlock, as Ebiten's image functions can be called inside the `Layout`. `Layout` should have been called after `BeginFrame.`

**Comment by jcgraybill** [comment]
> I think this was fixed. Could you try:
> 
> ```
> go get github.com/hajimehoshi/ebiten/v2@45929e04e11e8ce6d99a9d10c71c48f0402ff55f 
> ```
> 
> ?

Confirmed, that fixes the deadlock issue. Thank you!

The bad news, I now encounter a panic when resizing the window. Here's the stack trace - let me know if you'd rather I open a new issue instead.

```
PS C:\Users\jcg\Documents\GitHub\ship-shape> .\ship-shape.exe
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x24 pc=0x919e20]

goroutine 1 [running, locked to thread]:
github.com/hajimehoshi/ebiten/v2/internal/graphicsdriver/directx.(*Image).transiteState(0xd6f3e0?, 0x282aff97ae0?, 0x0?)
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.1-0.20220425161440-45929e04e11e/internal/graphicsdriver/directx/graphics_windows.go:1405 +0x20
github.com/hajimehoshi/ebiten/v2/internal/graphicsdriver/directx.(*Graphics).End(0xd6f3e0, 0x1)
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.1-0.20220425161440-45929e04e11e/internal/graphicsdriver/directx/graphics_windows.go:581 +0x76
github.com/hajimehoshi/ebiten/v2/internal/graphicscommand.(*commandQueue).flush(0xd6eaa0, {0xaf39e8?, 0xd6f3e0?})
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.1-0.20220425161440-45929e04e11e/internal/graphicscommand/command.go:258 +0x3a6   
github.com/hajimehoshi/ebiten/v2/internal/graphicscommand.(*commandQueue).Flush.func1()
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.1-0.20220425161440-45929e04e11e/internal/graphicscommand/command.go:196 +0x2e    
github.com/hajimehoshi/ebiten/v2/internal/thread.(*OSThread).Loop.func1(0xc006f4abf0?, 0xc006f4abe0?)
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.1-0.20220425161440-45929e04e11e/internal/thread/thread.go:54 +0x53
github.com/hajimehoshi/ebiten/v2/internal/thread.(*OSThread).Loop(0xc0005a2d08)
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.1-0.20220425161440-45929e04e11e/internal/thread/thread.go:55 +0x2e
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).runOnAnotherThreadFromMainThread(0xd6f1e0, 0xc0005aa540)
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.1-0.20220425161440-45929e04e11e/internal/ui/run_notsinglethread.go:78 +0x206     
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).registerWindowSetSizeCallback.func1(0x7cedab?, 0x780, 0x3e9)
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.1-0.20220425161440-45929e04e11e/internal/ui/ui_glfw.go:717 +0x1e9
github.com/hajimehoshi/ebiten/v2/internal/glfw.ToSizeCallback.func1(0xb0?, 0xb0?, 0x77cfa5?)
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.1-0.20220425161440-45929e04e11e/internal/glfw/callback_windows.go:68 +0x53       
syscall.SyscallN(0xaf1940?, {0xc006f4b3d8?, 0xc00453e7d0?, 0x8bf260?})
        C:/Program Files/Go/src/runtime/syscall_windows.go:538 +0x109
syscall.Syscall6(0x7?, 0x3?, 0x0?, 0x0?, 0x0?, 0x0?, 0x0?, 0xc000597170?)
        C:/Program Files/Go/src/runtime/syscall_windows.go:482 +0x50
golang.org/x/sys/windows.(*Proc).Call(0x77d307?, {0xc0005a6840?, 0x9be0c0?, 0xc004521f01?})
        C:/Users/jcg/go/pkg/mod/golang.org/x/sys@v0.0.0-20220422013727-9388b58f7150/windows/dll_windows.go:178 +0x265
golang.org/x/sys/windows.(*LazyProc).Call(0xc000450300, {0xc0005a6840, 0x5, 0x5})
        C:/Users/jcg/go/pkg/mod/golang.org/x/sys@v0.0.0-20220422013727-9388b58f7150/windows/dll_windows.go:348 +0x50
github.com/hajimehoshi/ebiten/v2/internal/gamepad.callWindowProcW(...)
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.1-0.20220425161440-45929e04e11e/internal/gamepad/api_windows.go:171
github.com/hajimehoshi/ebiten/v2/internal/gamepad.(*nativeGamepads).wndProc(0x0?, 0x4b075e, 0x5, 0x2, 0x3e90780)
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.1-0.20220425161440-45929e04e11e/internal/gamepad/gamepad_windows.go:541 +0x97    
syscall.SyscallN(0xc000709a00?, {0xc006f4bc18?, 0xc4e8c0?, 0x64?})
        C:/Program Files/Go/src/runtime/syscall_windows.go:538 +0x109
syscall.Syscall6(0x82379e?, 0x2?, 0x822d07?, 0x1?, 0xc000709a00?, 0x7e827e?, 0x7e804e?, 0xc006f4bcb8?)
        C:/Program Files/Go/src/runtime/syscall_windows.go:482 +0x50
golang.org/x/sys/windows.(*Proc).Call(0x77d307?, {0xc0005a67e0?, 0x9be0c0?, 0xc000709a01?})
        C:/Users/jcg/go/pkg/mod/golang.org/x/sys@v0.0.0-20220422013727-9388b58f7150/windows/dll_windows.go:178 +0x265
golang.org/x/sys/windows.(*LazyProc).Call(0xc000450300, {0xc0005a67e0, 0x5, 0x5})
        C:/Users/jcg/go/pkg/mod/golang.org/x/sys@v0.0.0-20220422013727-9388b58f7150/windows/dll_windows.go:348 +0x50
github.com/hajimehoshi/ebiten/v2/internal/gamepad.callWindowProcW(...)
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.1-0.20220425161440-45929e04e11e/internal/gamepad/api_windows.go:171
github.com/hajimehoshi/ebiten/v2/internal/gamepad.(*nativeGamepads).wndProc(0x0?, 0x4b075e, 0x47, 0x0, 0xb5c31fdec0)
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.1-0.20220425161440-45929e04e11e/internal/gamepad/gamepad_windows.go:541 +0x97    
syscall.SyscallN(0x0?, {0xc006f4c458?, 0xc000709a68?, 0xc006f4c4a0?})
        C:/Program Files/Go/src/runtime/syscall_windows.go:538 +0x109
syscall.Syscall6(0xb?, 0x3fd999999999999a?, 0x826326?, 0xffffffffffffffff?, 0xa?, 0x3030303030303034?, 0x303030?, 0x0?)
        C:/Program Files/Go/src/runtime/syscall_windows.go:482 +0x50
golang.org/x/sys/windows.(*Proc).Call(0x77d307?, {0xc000544c60?, 0x9be0c0?, 0x8a5401?})
        C:/Users/jcg/go/pkg/mod/golang.org/x/sys@v0.0.0-20220422013727-9388b58f7150/windows/dll_windows.go:178 +0x265
golang.org/x/sys/windows.(*LazyProc).Call(0xc000450300, {0xc000544c60, 0x5, 0x5})
        C:/Users/jcg/go/pkg/mod/golang.org/x/sys@v0.0.0-20220422013727-9388b58f7150/windows/dll_windows.go:348 +0x50
github.com/hajimehoshi/ebiten/v2/internal/gamepad.callWindowProcW(...)
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.1-0.20220425161440-45929e04e11e/internal/gamepad/api_windows.go:171
github.com/hajimehoshi/ebiten/v2/internal/gamepad.(*nativeGamepads).wndProc(0x0?, 0x4b075e, 0x112, 0xf030, 0x1306b4)
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.1-0.20220425161440-45929e04e11e/internal/gamepad/gamepad_windows.go:541 +0x97    
syscall.SyscallN(0xc000044000?, {0xc006f4cc98?, 0xc000044000?, 0xc006f4ccc0?})
        C:/Program Files/Go/src/runtime/syscall_windows.go:538 +0x109
syscall.Syscall6(0xd6f8c0?, 0x0?, 0xbde22800?, 0xc000044000?, 0xc006f4cd70?, 0x7ceadc?, 0x7d37c0?, 0xd6f8c0?)
        C:/Program Files/Go/src/runtime/syscall_windows.go:482 +0x50
golang.org/x/sys/windows.(*Proc).Call(0x77d307?, {0xc0005a6690?, 0x9be0c0?, 0x1005001?})
        C:/Users/jcg/go/pkg/mod/golang.org/x/sys@v0.0.0-20220422013727-9388b58f7150/windows/dll_windows.go:178 +0x265
golang.org/x/sys/windows.(*LazyProc).Call(0xc000450300, {0xc0005a6690, 0x5, 0x5})
        C:/Users/jcg/go/pkg/mod/golang.org/x/sys@v0.0.0-20220422013727-9388b58f7150/windows/dll_windows.go:348 +0x50
github.com/hajimehoshi/ebiten/v2/internal/gamepad.callWindowProcW(...)
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.1-0.20220425161440-45929e04e11e/internal/gamepad/api_windows.go:171
github.com/hajimehoshi/ebiten/v2/internal/gamepad.(*nativeGamepads).wndProc(0x0?, 0x4b075e, 0xa1, 0x9, 0x1306b4)
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.1-0.20220425161440-45929e04e11e/internal/gamepad/gamepad_windows.go:541 +0x97    
syscall.SyscallN(0x65eaf9df?, {0xc006f4d4d8?, 0x3?, 0x8e8e90?})
        C:/Program Files/Go/src/runtime/syscall_windows.go:538 +0x109
syscall.Syscall(0x93b6d9?, 0x772f7e?, 0x0?, 0xc006f4d540?, 0x905dae?)
        C:/Program Files/Go/src/runtime/syscall_windows.go:476 +0x3b
golang.org/x/sys/windows.(*Proc).Call(0xdc41f8?, {0x0?, 0xc0005b60d0?, 0x9384ca?})
        C:/Users/jcg/go/pkg/mod/golang.org/x/sys@v0.0.0-20220422013727-9388b58f7150/windows/dll_windows.go:168 +0x6d
golang.org/x/sys/windows.(*LazyProc).Call(0xc0005aa060, {0x0, 0x0, 0x0})
        C:/Users/jcg/go/pkg/mod/golang.org/x/sys@v0.0.0-20220422013727-9388b58f7150/windows/dll_windows.go:348 +0x50
github.com/hajimehoshi/ebiten/v2/internal/glfw.(*dll).call(0xc000050020, {0xa0fd27, 0xe}, {0x0, 0x0, 0x0})
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.1-0.20220425161440-45929e04e11e/internal/glfw/load_windows.go:37 +0x173
github.com/hajimehoshi/ebiten/v2/internal/glfw.PollEvents()
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.1-0.20220425161440-45929e04e11e/internal/glfw/glfw_windows.go:513 +0x33
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).update(0xd6f1e0)
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.1-0.20220425161440-45929e04e11e/internal/ui/ui_glfw.go:1013 +0x167
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).loop.func1()
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.1-0.20220425161440-45929e04e11e/internal/ui/ui_glfw.go:1059 +0x4a
github.com/hajimehoshi/ebiten/v2/internal/thread.(*OSThread).Loop.func1(0xc006f4d780?, 0xc006f4d770?)
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.1-0.20220425161440-45929e04e11e/internal/thread/thread.go:54 +0x53
github.com/hajimehoshi/ebiten/v2/internal/thread.(*OSThread).Loop(0xc004773c80)
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.1-0.20220425161440-45929e04e11e/internal/thread/thread.go:55 +0x2e
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).Run(0xd6f1e0, {0xaf2d28?, 0xc004773c68})
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.1-0.20220425161440-45929e04e11e/internal/ui/run_notsinglethread.go:53 +0x22c     
github.com/hajimehoshi/ebiten/v2.RunGame({0xaf2b98?, 0xc0031e7000})
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.1-0.20220425161440-45929e04e11e/run.go:191 +0x12c
main.main()
```
