### ISSUE TITLE
internal/graphicsdriver/directx: resizing window causes panic in Ebiten 45929e04 on Windows

### ISSUE THREAD

**Issue by jcgraybill** [hajimehoshi/ebiten#2081]
Hi, creating a new issue forked from #2079. I've confirmed this on Windows, and confirmed it *doesn't* happen on MacOS or Ubuntu. I encounter a panic when resizing the window. 

I've created a branch of [the app I'm building](https://github.com/jcgraybill/ship-shape) that demonstrates the error:

```
git clone -b ebiten-2.3.1 https://github.com/jcgraybill/ship-shape.git
```

Here's the stack trace:

```
PS C:\Users\jcg\Documents\GitHub\ship-shape> .\ship-shape.exe
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x24 pc=0x359e20]

goroutine 1 [running, locked to thread]:
github.com/hajimehoshi/ebiten/v2/internal/graphicsdriver/directx.(*Image).transiteState(0x7af3e0?, 0x21754bbad90?, 0x0?)
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.1-0.20220425161440-45929e04e11e/internal/graphicsdriver/directx/graphics_windows.go:1405 +0x20
github.com/hajimehoshi/ebiten/v2/internal/graphicsdriver/directx.(*Graphics).End(0x7af3e0, 0x1)
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.1-0.20220425161440-45929e04e11e/internal/graphicsdriver/directx/graphics_windows.go:581 +0x76
github.com/hajimehoshi/ebiten/v2/internal/graphicscommand.(*commandQueue).flush(0x7aeaa0, {0x533a08?, 0x7af3e0?})
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.1-0.20220425161440-45929e04e11e/internal/graphicscommand/command.go:258 +0x3a6   
github.com/hajimehoshi/ebiten/v2/internal/graphicscommand.(*commandQueue).Flush.func1()
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.1-0.20220425161440-45929e04e11e/internal/graphicscommand/command.go:196 +0x2e    
github.com/hajimehoshi/ebiten/v2/internal/thread.(*OSThread).Loop.func1(0xc0056f0bf0?, 0xc0056f0be0?)
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.1-0.20220425161440-45929e04e11e/internal/thread/thread.go:54 +0x53
github.com/hajimehoshi/ebiten/v2/internal/thread.(*OSThread).Loop(0xc0011bbf08)
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.1-0.20220425161440-45929e04e11e/internal/thread/thread.go:55 +0x2e
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).runOnAnotherThreadFromMainThread(0x7af1e0, 0xc0000e1410)
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.1-0.20220425161440-45929e04e11e/internal/ui/run_notsinglethread.go:78 +0x206     
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).registerWindowSetSizeCallback.func1(0x20edab?, 0x780, 0x3e9)
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.1-0.20220425161440-45929e04e11e/internal/ui/ui_glfw.go:717 +0x1e9
github.com/hajimehoshi/ebiten/v2/internal/glfw.ToSizeCallback.func1(0x0?, 0x0?, 0x0?)
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.1-0.20220425161440-45929e04e11e/internal/glfw/callback_windows.go:68 +0x53       
syscall.SyscallN(0x0?, {0xc0056f13d8?, 0x0?, 0x0?})
        C:/Program Files/Go/src/runtime/syscall_windows.go:538 +0x109
syscall.Syscall6(0x1bc70d?, 0x2175a324a30?, 0x0?, 0x0?, 0x0?, 0x0?, 0x2175a324a30?, 0xb?)
        C:/Program Files/Go/src/runtime/syscall_windows.go:482 +0x50
golang.org/x/sys/windows.(*Proc).Call(0x1bd307?, {0xc0000db7d0?, 0x3fe0c0?, 0x1?})
        C:/Users/jcg/go/pkg/mod/golang.org/x/sys@v0.0.0-20220422013727-9388b58f7150/windows/dll_windows.go:178 +0x265
golang.org/x/sys/windows.(*LazyProc).Call(0xc00047e300, {0xc0000db7d0, 0x5, 0x5})
        C:/Users/jcg/go/pkg/mod/golang.org/x/sys@v0.0.0-20220422013727-9388b58f7150/windows/dll_windows.go:348 +0x50
github.com/hajimehoshi/ebiten/v2/internal/gamepad.callWindowProcW(...)
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.1-0.20220425161440-45929e04e11e/internal/gamepad/api_windows.go:171
github.com/hajimehoshi/ebiten/v2/internal/gamepad.(*nativeGamepads).wndProc(0x0?, 0x40772, 0x5, 0x2, 0x3e90780)
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.1-0.20220425161440-45929e04e11e/internal/gamepad/gamepad_windows.go:541 +0x97    
syscall.SyscallN(0xc0000fe000?, {0xc0056f1c18?, 0x68e8c0?, 0x64?})
        C:/Program Files/Go/src/runtime/syscall_windows.go:538 +0x109
syscall.Syscall6(0x26379e?, 0x2?, 0x262d07?, 0x1?, 0xc0000fe000?, 0x22827e?, 0x22804e?, 0xc0056f1cb8?)
        C:/Program Files/Go/src/runtime/syscall_windows.go:482 +0x50
golang.org/x/sys/windows.(*Proc).Call(0x1bd307?, {0xc0000db770?, 0x3fe0c0?, 0xc0000fe001?})
        C:/Users/jcg/go/pkg/mod/golang.org/x/sys@v0.0.0-20220422013727-9388b58f7150/windows/dll_windows.go:178 +0x265
golang.org/x/sys/windows.(*LazyProc).Call(0xc00047e300, {0xc0000db770, 0x5, 0x5})
        C:/Users/jcg/go/pkg/mod/golang.org/x/sys@v0.0.0-20220422013727-9388b58f7150/windows/dll_windows.go:348 +0x50
github.com/hajimehoshi/ebiten/v2/internal/gamepad.callWindowProcW(...)
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.1-0.20220425161440-45929e04e11e/internal/gamepad/api_windows.go:171
github.com/hajimehoshi/ebiten/v2/internal/gamepad.(*nativeGamepads).wndProc(0x0?, 0x40772, 0x47, 0x0, 0xd7cdffe160)
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.1-0.20220425161440-45929e04e11e/internal/gamepad/gamepad_windows.go:541 +0x97    
syscall.SyscallN(0x0?, {0xc0056f2458?, 0xc0000fe068?, 0xc0056f24a0?})
        C:/Program Files/Go/src/runtime/syscall_windows.go:538 +0x109
syscall.Syscall6(0xb?, 0x3fd999999999999a?, 0x266326?, 0xffffffffffffffff?, 0xa?, 0x3030303030303034?, 0x303030?, 0x0?)
        C:/Program Files/Go/src/runtime/syscall_windows.go:482 +0x50
golang.org/x/sys/windows.(*Proc).Call(0x1bd307?, {0xc0000db620?, 0x3fe0c0?, 0x2e5401?})
        C:/Users/jcg/go/pkg/mod/golang.org/x/sys@v0.0.0-20220422013727-9388b58f7150/windows/dll_windows.go:178 +0x265
golang.org/x/sys/windows.(*LazyProc).Call(0xc00047e300, {0xc0000db620, 0x5, 0x5})
        C:/Users/jcg/go/pkg/mod/golang.org/x/sys@v0.0.0-20220422013727-9388b58f7150/windows/dll_windows.go:348 +0x50
github.com/hajimehoshi/ebiten/v2/internal/gamepad.callWindowProcW(...)
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.1-0.20220425161440-45929e04e11e/internal/gamepad/api_windows.go:171
github.com/hajimehoshi/ebiten/v2/internal/gamepad.(*nativeGamepads).wndProc(0x0?, 0x40772, 0x112, 0xf030, 0x1606c2)
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.1-0.20220425161440-45929e04e11e/internal/gamepad/gamepad_windows.go:541 +0x97    
syscall.SyscallN(0xc000044000?, {0xc0056f2c98?, 0xc000044000?, 0xc0056f2cc0?})
        C:/Program Files/Go/src/runtime/syscall_windows.go:538 +0x109
syscall.Syscall6(0x7af8c0?, 0x0?, 0x657b03f0?, 0xc000044000?, 0xc0056f2d70?, 0x20eadc?, 0x2137c0?, 0x7af8c0?)
        C:/Program Files/Go/src/runtime/syscall_windows.go:482 +0x50
golang.org/x/sys/windows.(*Proc).Call(0x1bd307?, {0xc0000db5c0?, 0x3fe0c0?, 0x1005001?})
        C:/Users/jcg/go/pkg/mod/golang.org/x/sys@v0.0.0-20220422013727-9388b58f7150/windows/dll_windows.go:178 +0x265
golang.org/x/sys/windows.(*LazyProc).Call(0xc00047e300, {0xc0000db5c0, 0x5, 0x5})
        C:/Users/jcg/go/pkg/mod/golang.org/x/sys@v0.0.0-20220422013727-9388b58f7150/windows/dll_windows.go:348 +0x50
github.com/hajimehoshi/ebiten/v2/internal/gamepad.callWindowProcW(...)
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.1-0.20220425161440-45929e04e11e/internal/gamepad/api_windows.go:171
github.com/hajimehoshi/ebiten/v2/internal/gamepad.(*nativeGamepads).wndProc(0x0?, 0x40772, 0xa1, 0x9, 0x1606c2)
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.1-0.20220425161440-45929e04e11e/internal/gamepad/gamepad_windows.go:541 +0x97    
syscall.SyscallN(0x65ecf9df?, {0xc0056f34d8?, 0x3?, 0x328e90?})
        C:/Program Files/Go/src/runtime/syscall_windows.go:538 +0x109
syscall.Syscall(0x37b6d9?, 0x1b2f7e?, 0x0?, 0xc0056f3540?, 0x345dae?)
        C:/Program Files/Go/src/runtime/syscall_windows.go:476 +0x3b
golang.org/x/sys/windows.(*Proc).Call(0x8041f8?, {0x0?, 0xc0000ec000?, 0x3784ca?})
        C:/Users/jcg/go/pkg/mod/golang.org/x/sys@v0.0.0-20220422013727-9388b58f7150/windows/dll_windows.go:168 +0x6d
golang.org/x/sys/windows.(*LazyProc).Call(0xc0000e0060, {0x0, 0x0, 0x0})
        C:/Users/jcg/go/pkg/mod/golang.org/x/sys@v0.0.0-20220422013727-9388b58f7150/windows/dll_windows.go:348 +0x50
github.com/hajimehoshi/ebiten/v2/internal/glfw.(*dll).call(0xc000050020, {0x44fd27, 0xe}, {0x0, 0x0, 0x0})
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.1-0.20220425161440-45929e04e11e/internal/glfw/load_windows.go:37 +0x173
github.com/hajimehoshi/ebiten/v2/internal/glfw.PollEvents()
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.1-0.20220425161440-45929e04e11e/internal/glfw/glfw_windows.go:513 +0x33
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).update(0x7af1e0)
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.1-0.20220425161440-45929e04e11e/internal/ui/ui_glfw.go:1013 +0x167
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).loop.func1()
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.1-0.20220425161440-45929e04e11e/internal/ui/ui_glfw.go:1059 +0x4a
github.com/hajimehoshi/ebiten/v2/internal/thread.(*OSThread).Loop.func1(0xc0056f3780?, 0xc0056f3770?)
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.1-0.20220425161440-45929e04e11e/internal/thread/thread.go:54 +0x53
github.com/hajimehoshi/ebiten/v2/internal/thread.(*OSThread).Loop(0xc003d5fcb0)
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.1-0.20220425161440-45929e04e11e/internal/thread/thread.go:55 +0x2e
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).Run(0x7af1e0, {0x532d48?, 0xc003d5fc98})
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.1-0.20220425161440-45929e04e11e/internal/ui/run_notsinglethread.go:53 +0x22c     
github.com/hajimehoshi/ebiten/v2.RunGame({0x532ba8?, 0xc00009c000})
        C:/Users/jcg/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.1-0.20220425161440-45929e04e11e/run.go:191 +0x12c
main.main()
        C:/Users/jcg/Documents/GitHub/ship-shape/main.go:60 +0x205
```

**Comment by hajimehoshi** [comment]
Thank you for the reporting! I'll take a look.

**Comment by hajimehoshi** [comment]
I have confirmed this issue.

**Comment by hajimehoshi** [comment]
Could you try 9d9439751f1a0e9c987a409687ac2ba57f6b5626?

```
go get github.com/hajimehoshi/ebiten/v2@9d9439751f1a0e9c987a409687ac2ba57f6b5626
```

Thanks,

**Comment by jcgraybill** [comment]
> Could you try [9d94397](https://github.com/hajimehoshi/ebiten/commit/9d9439751f1a0e9c987a409687ac2ba57f6b5626)?
> 
> ```
> go get github.com/hajimehoshi/ebiten/v2@9d9439751f1a0e9c987a409687ac2ba57f6b5626
> ```
> 
> Thanks,

Confirmed - this fix resolves the issue for me. Thank you!
