### ISSUE TITLE
Windows: inpututil Crash on Versions 2.3+

### ISSUE THREAD

**Issue by OpenSauce** [hajimehoshi/ebiten#2103]
Hi,

It seems on a 2.3.0+ anytime I even import inpututil:

`	_ "github.com/hajimehoshi/ebiten/v2/inpututil"`

I get the following error:

```
panic: runtime error: index out of range [0] with length 0

goroutine 23 [running]:
github.com/hajimehoshi/ebiten/v2/internal/gamepad.(*nativeGamepad).hatState(...)
        C:/Users/leigh/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.0/internal/gamepad/gamepad_windows.go:739
github.com/hajimehoshi/ebiten/v2/internal/gamepad.(*Gamepad).Hat(0x10af2a0?, 0xc000272750?)
        C:/Users/leigh/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.0/internal/gamepad/gamepad.go:236 +0x136
github.com/hajimehoshi/ebiten/v2/internal/gamepad.(*Gamepad).IsStandardButtonPressed(0xc008b680c0, 0x6e680917948f7d87?)
        C:/Users/leigh/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.0/internal/gamepad/gamepad.go:275 +0x53
github.com/hajimehoshi/ebiten/v2.IsStandardGamepadButtonPressed(0x10af180?, 0xc00040f710?)
        C:/Users/leigh/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.0/input.go:278 +0x3a
github.com/hajimehoshi/ebiten/v2/inpututil.(*inputState).update(0x1571240)
        C:/Users/leigh/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.0/inpututil/inpututil.go:156 +0xc7f
github.com/hajimehoshi/ebiten/v2/inpututil.init.0.func1()
        C:/Users/leigh/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.0/inpututil/inpututil.go:75 +0x25
github.com/hajimehoshi/ebiten/v2/internal/hooks.RunBeforeUpdateHooks()
        C:/Users/leigh/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.0/internal/hooks/hooks.go:38 +0xc7
github.com/hajimehoshi/ebiten/v2/internal/ui.(*context).updateFrameImpl(0xc000461000, {0x1154290, 0x1571980}, 0x1, 0x409e000000000000, 0x4090e00000000000, 0xc000073e98?)
        C:/Users/leigh/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.0/internal/ui/context.go:113 +0x13d
github.com/hajimehoshi/ebiten/v2/internal/ui.(*context).updateFrame(0xc000096378?, {0x1154290, 0x1571980}, 0xc000086358?, 0xc000428680?, 0xc000428708?)
        C:/Users/leigh/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.0/internal/ui/context.go:64 +0x8e
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).loop(0x1571780)
        C:/Users/leigh/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.0/internal/ui/ui_glfw.go:1065 +0x1ea
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).Run.func1()
        C:/Users/leigh/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.0/internal/ui/run_notsinglethread.go:46 +0x13d
created by github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).Run
        C:/Users/leigh/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.0/internal/ui/run_notsinglethread.go:33 +0x20a
```

I've rolled back the versions and 2.2.7 works fine. I don't have any gamepads plugged in.

Thanks for everything you're doing!

**Comment by hajimehoshi** [comment]
Thank you for reporting!

Could you try `go get github.com/hajimehoshi/ebiten/v2@331dbfd899a306ef70d71d3d68f80ea78700f98f`? Thanks!
