### ISSUE TITLE
Steam Deck panic (windows binary using Proton)

### ISSUE THREAD

**Issue by TheMightyGit** [hajimehoshi/ebiten#2113]
In trying to run my project on a Steam Deck (using a Windows build run via either 'GE-Proton7-20' or 'Proton 7.0') I get this panic:

```
panic: glfwwin: SetProcessDpiAwarenessContext failed: Invalid parameter.

goroutine 1 [running]:
github.com/hajimehoshi/ebiten/v2/internal/ui.init.2()
        /Users/johnny/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.4.0-alpha.3.0.20220529181715-c99b948df3da/internal/ui/ui_glfw.go:151 +0xa8
```

I'm new to using both Proton and Windows builds so maybe I've misconfigured something? Happy to try and debug, I've just got no idea where to start.

**Comment by hajimehoshi** [comment]
Thanks. Does this happen with v2.3.3?

**Comment by hajimehoshi** [comment]
I guess the culprit is that error checking in the v2.4 era became much more stricter than the v2.3 era. Actually the return value is checked at SetProcessDpiAwarenessContext now. Before fixing this, I'd like to confirm your app works with v2.3.

**Comment by TheMightyGit** [comment]
Mixed success.

v2.3.3 in DirectX mode: gets past the previous panic but then (both Proton 7.0 and GE-7.20)...

```
2022/06/01 08:16:06 directx: ID3D12Resource1::Unmap failed: winapi error #710606896
```

v2.3.3 in OpenGL mode (via EBITEN_GRAPHICS_LIBRARY=opengl) : works!

**Comment by hajimehoshi** [comment]
Thanks. Does Steam Deck use Wine to run a Windows application?

**Comment by TheMightyGit** [comment]
Yes, Proton uses Wine.

**Comment by hajimehoshi** [comment]
Thanks. This is just out of curiosity, but I was wondering why you run a Windows binary instead of a Linux binary on Steam Deck.

**Comment by TheMightyGit** [comment]
Three reasons really.

1) I was curious if Ebiten projects would 'just work' in Proton (it's quite magical that so many games 'just work' on the Deck).
2) I don't have a Linux build environment set up right now (I generally work on a Mac).
3) So Ebitengine could brag about Steam Deck compatibility :D

**Comment by hajimehoshi** [comment]
Thanks. As an Ebitengine Window binary should work as it is on Steam Deck, this should be an issue. I'll try to fix the issue.

On the other hand, you can use Docker to build a Linux binary from macOS. See https://ebiten.org/blog/steam.html#Linux

**Comment by hajimehoshi** [comment]
@TheMightyGit I don't think this was fixed, but could you try `0dc6e4e64ee1046ab6f832f0451e4d43a3f3b8e6`? Thanks,

**Comment by hajimehoshi** [comment]
Thanks!

> panic: glfwwin: DwmFlush failed: Success.

Hmm this is mysterious...

**Comment by hajimehoshi** [comment]
OK now the Unmap error should be gone. Please take a look at `fb03a1e351fe67d9a4fbe77a8e3184d2245d330b`. Thanks,

**Comment by TheMightyGit** [comment]
> OK now the Unmap error should be gone. Please take a look at fb03a1e351fe67d9a4fbe77a8e3184d2245d330b. Thanks,

@hajimehoshi  This is with both 'Proton 7.0' and 'GE-Proton7-20':

OpenGL:

```
panic: glfwwin: DwmFlush failed: Success.

goroutine 1 [running, locked to thread]:
github.com/hajimehoshi/ebiten/v2/internal/glfw.(*Window).SwapBuffers(...)
        /Users/johnny/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.4.0-alpha.3.0.20220602035258-fb03a1e351fe/internal/glfw/glfw_windows.go:297
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).swapBuffers(0xcb0940)
        /Users/johnny/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.4.0-alpha.3.0.20220602035258-fb03a1e351fe/internal/ui/ui_glfw.go:1134 +0x5a
github.com/hajimehoshi/ebiten/v2/internal/thread.(*OSThread).Loop.func1(0xc000461dd0?, 0xc000461dc0?)
        /Users/johnny/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.4.0-alpha.3.0.20220602035258-fb03a1e351fe/internal/thread/thread.go:54 +0x53
github.com/hajimehoshi/ebiten/v2/internal/thread.(*OSThread).Loop(0xc0000041f8)
        /Users/johnny/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.4.0-alpha.3.0.20220602035258-fb03a1e351fe/internal/thread/thread.go:55 +0x2e
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).Run(0xcb0940, {0xa59fe0?, 0xc0000041e0})
        /Users/johnny/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.4.0-alpha.3.0.20220602035258-fb03a1e351fe/internal/ui/run_notsinglethread.go:53 +0x22c
github.com/hajimehoshi/ebiten/v2.RunGame({0xa58ef0?, 0xc00007e000})
        /Users/johnny/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.4.0-alpha.3.0.20220602035258-fb03a1e351fe/run.go:191 +0x12c
github.com/TheMightyGit/marv/marvlib.(*marvAPI).ConsoleBoot(0xcac578, {0x76c589, 0xa}, {0xa57220, 0xa5c320}, 0x6f7e40?, 0xc000054000?)
        /Users/johnny/marv300/marvlib/api.go:45 +0x10e
main.main()
        /Users/johnny/marv_cartridges/worldworlds/cmd/wordworlds/main.go:9 +0x50
```

DirectX:

```
2022/06/02 10:17:15 directx: D3DCompile failed: shader:8:16: E5005: Function "floor" is not defined.
: Call failed.
```

**Comment by hajimehoshi** [comment]
Thanks!

> DwmFlush failed: Success.

OK so I think not using `GetLastError` (the `e` value) would solve this...

> Function "floor" is not defined.

This is mysterious. I hope this is solvable.

**Comment by TheMightyGit** [comment]
>  I fixed the error message at DwmFlush for OpenGL. Could you take a look at 666d50e83d06136b2c8e0a5e2c844e68f412f9a8? As the error should still occur, I'll ignore it later.

@hajimehoshi 

OpenGL:

```
panic: glfwwin: DwmFlush failed: Not implemented.

goroutine 1 [running, locked to thread]:
github.com/hajimehoshi/ebiten/v2/internal/glfw.(*Window).SwapBuffers(...)
        /Users/johnny/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.4.0-alpha.3.0.20220602140209-666d50e83d06/internal/glfw/glfw_windows.go:297
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).swapBuffers(0xcb0940)
        /Users/johnny/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.4.0-alpha.3.0.20220602140209-666d50e83d06/internal/ui/ui_glfw.go:1134 +0x5a
github.com/hajimehoshi/ebiten/v2/internal/thread.(*OSThread).Loop.func1(0xc000595dd0?, 0xc000595dc0?)
        /Users/johnny/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.4.0-alpha.3.0.20220602140209-666d50e83d06/internal/thread/thread.go:54 +0x53
github.com/hajimehoshi/ebiten/v2/internal/thread.(*OSThread).Loop(0xc0004361b0)
        /Users/johnny/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.4.0-alpha.3.0.20220602140209-666d50e83d06/internal/thread/thread.go:55 +0x2e
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).Run(0xcb0940, {0xa59fe0?, 0xc000436198})
        /Users/johnny/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.4.0-alpha.3.0.20220602140209-666d50e83d06/internal/ui/run_notsinglethread.go:53 +0x22c
github.com/hajimehoshi/ebiten/v2.RunGame({0xa58ef0?, 0xc000446280})
        /Users/johnny/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.4.0-alpha.3.0.20220602140209-666d50e83d06/run.go:191 +0x12c
github.com/TheMightyGit/marv/marvlib.(*marvAPI).ConsoleBoot(0xcac578, {0x76c589, 0xa}, {0xa57220, 0xa5c320}, 0x6f7e40?, 0xc000056000?)
        /Users/johnny/marv300/marvlib/api.go:45 +0x10e
main.main()
        /Users/johnny/marv_cartridges/worldworlds/cmd/wordworlds/main.go:9 +0x50
```

**Comment by TheMightyGit** [comment]
> I fixed `Map` to retry up to 5 times when needed. @TheMightyGit Could you take a look at `55a490736acd0ffc147d43acb1014c6ecf621fe5`? Thanks,

@hajimehoshi 

DirectX mode:

```
unexpected fault address 0x7fce587d1fe0
fatal error: fault
[signal 0xc0000005 code=0x1 addr=0x7fce587d1fe0 pc=0x463172]

goroutine 1 [running, locked to thread]:
runtime.throw({0x65d64c?, 0x7fce587f2000?})
        /usr/local/Cellar/go/1.18.2/libexec/src/runtime/panic.go:992 +0x76 fp=0xc000445a10 sp=0xc0004459e0 pc=0x435fd6
runtime.sigpanic()
        /usr/local/Cellar/go/1.18.2/libexec/src/runtime/signal_windows.go:261 +0x125 fp=0xc000445a58 sp=0xc000445a10 pc=0x449085
runtime.memmove()
        /usr/local/Cellar/go/1.18.2/libexec/src/runtime/memmove_amd64.s:517 +0x672 fp=0xc000445a60 sp=0xc000445a58 pc=0x463172
github.com/hajimehoshi/ebiten/v2/internal/graphicsdriver/directx.(*Image).ReplacePixels(0xc00050a180, {0xc0000060c8, 0x1, 0x10000001c?})
        /Users/johnny/ebiten/internal/graphicsdriver/directx/graphics_windows.go:1403 +0x3eb fp=0xc000445b70 sp=0xc000445a60 pc=0x57e6cb
github.com/hajimehoshi/ebiten/v2/internal/graphicscommand.(*replacePixelsCommand).Exec(0xc000057f20, {0x6bd160?, 0x886960?}, 0x0?)
        /Users/johnny/ebiten/internal/graphicscommand/command.go:559 +0x1c3 fp=0xc000445be8 sp=0xc000445b70 pc=0x508743
github.com/hajimehoshi/ebiten/v2/internal/graphicscommand.(*commandQueue).flush(0x886100, {0x6bd160?, 0x886960?})
        /Users/johnny/ebiten/internal/graphicscommand/command.go:245 +0x6d5 fp=0xc000445d78 sp=0xc000445be8 pc=0x506ff5
github.com/hajimehoshi/ebiten/v2/internal/graphicscommand.(*commandQueue).Flush.func1()
        /Users/johnny/ebiten/internal/graphicscommand/command.go:196 +0x2e fp=0xc000445da8 sp=0xc000445d78 pc=0x5068ee
github.com/hajimehoshi/ebiten/v2/internal/thread.(*OSThread).Loop.func1(0xc000445e18?, 0xc000445e08?)
        /Users/johnny/ebiten/internal/thread/thread.go:54 +0x53 fp=0xc000445dd8 sp=0xc000445da8 pc=0x56afd3
github.com/hajimehoshi/ebiten/v2/internal/thread.(*OSThread).Loop(0xc000004318)
        /Users/johnny/ebiten/internal/thread/thread.go:55 +0x2e fp=0xc000445e48 sp=0xc000445dd8 pc=0x56aeee
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).Run(0x886760, {0x6bc588?, 0xc000004300})
        /Users/johnny/ebiten/internal/ui/run_notsinglethread.go:53 +0x22c fp=0xc000445ea8 sp=0xc000445e48 pc=0x59a9ec
github.com/hajimehoshi/ebiten/v2.RunGame({0x6bc320?, 0x8dd8f8})
        /Users/johnny/ebiten/run.go:191 +0x12c fp=0xc000445f20 sp=0xc000445ea8 pc=0x5a7b8c
main.main()
        /Users/johnny/ebiten/examples/filter/main.go:82 +0x130 fp=0xc000445f80 sp=0xc000445f20 pc=0x5f2f30
runtime.main()
        /usr/local/Cellar/go/1.18.2/libexec/src/runtime/proc.go:250 +0x1fe fp=0xc000445fe0 sp=0xc000445f80 pc=0x43869e
runtime.goexit()
        /usr/local/Cellar/go/1.18.2/libexec/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc000445fe8 sp=0xc000445fe0 pc=0x461ca1

goroutine 9 [chan receive]:
github.com/hajimehoshi/ebiten/v2/internal/thread.(*OSThread).Call(0xc000004318, 0x598401?)
        /Users/johnny/ebiten/internal/thread/thread.go:74 +0x3e
github.com/hajimehoshi/ebiten/v2/internal/graphicscommand.runOnRenderingThread(0x0?)
        /Users/johnny/ebiten/internal/graphicscommand/thread.go:39 +0x33
github.com/hajimehoshi/ebiten/v2/internal/graphicscommand.(*commandQueue).Flush(0x886100, {0x6bd160?, 0x886960})
        /Users/johnny/ebiten/internal/graphicscommand/command.go:195 +0xbc
github.com/hajimehoshi/ebiten/v2/internal/graphicscommand.FlushCommands(...)
        /Users/johnny/ebiten/internal/graphicscommand/command.go:281
github.com/hajimehoshi/ebiten/v2/internal/restorable.ResolveStaleImages({0x6bd160, 0x886960})
        /Users/johnny/ebiten/internal/restorable/images.go:70 +0x37
github.com/hajimehoshi/ebiten/v2/internal/atlas.EndFrame({0x6bd160?, 0x886960?})
        /Users/johnny/ebiten/internal/atlas/image.go:820 +0x105
github.com/hajimehoshi/ebiten/v2/internal/buffered.EndFrame(...)
        /Users/johnny/ebiten/internal/buffered/image.go:45
github.com/hajimehoshi/ebiten/v2/internal/ui.(*context).updateFrameImpl.func1.1()
        /Users/johnny/ebiten/internal/ui/context.go:102 +0x25
github.com/hajimehoshi/ebiten/v2/internal/graphics.(*verticesBackend).lockAndReset(0x885f00, 0x0?)
        /Users/johnny/ebiten/internal/graphics/vertex.go:105 +0x97
github.com/hajimehoshi/ebiten/v2/internal/graphics.LockAndResetVertices(...)
        /Users/johnny/ebiten/internal/graphics/vertex.go:135
github.com/hajimehoshi/ebiten/v2/internal/ui.(*context).updateFrameImpl.func1()
        /Users/johnny/ebiten/internal/ui/context.go:101 +0x5f
github.com/hajimehoshi/ebiten/v2/internal/ui.(*context).updateFrameImpl(0xc00002a440, {0x6bd160, 0x886960}, 0x1, 0x4084000000000000, 0x407e000000000000, 0xc00049de80?)
        /Users/johnny/ebiten/internal/ui/context.go:144 +0x30b
github.com/hajimehoshi/ebiten/v2/internal/ui.(*context).updateFrame(0xc000004318?, {0x6bd160, 0x886960}, 0x0?, 0x40cf65?, 0xc00059a060?)
        /Users/johnny/ebiten/internal/ui/context.go:64 +0x8e
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).loop(0x886760)
        /Users/johnny/ebiten/internal/ui/ui_glfw.go:1072 +0x247
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).Run.func1()
        /Users/johnny/ebiten/internal/ui/run_notsinglethread.go:46 +0x13d
created by github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).Run
        /Users/johnny/ebiten/internal/ui/run_notsinglethread.go:33 +0x20a
```

**Comment by TheMightyGit** [comment]
This is the build info just to confirm it was using the correct version:

```
go      go1.18.2
path    command-line-arguments
dep     github.com/hajimehoshi/ebiten/v2        v2.4.0-alpha.3.0.20220603125634-55a490736acd    h1:8PAauBXoKgbYPfSW8Q68ovb6BSrn6hqfrjN9vndIWa0=
dep     golang.org/x/sys        v0.0.0-20220520151302-bc2c85ada10a      h1:dGzPydgVsqGcTRVwiLJ1jVbufYwmzD3LfVPLKsKg+0k=
build   -compiler=gc
build   CGO_ENABLED=0
build   GOARCH=amd64
build   GOOS=windows
build   GOAMD64=v1
```

**Comment by hajimehoshi** [comment]
> 386 mode works, does 386 fall back to opengl on windows? 

Yes, 386 forces to use OpenGL so far, but the situation will change.

**Comment by hajimehoshi** [comment]
@TheMightyGit I have added some fixes after the last commit you tested (55a490736acd0ffc147d43acb1014c6ecf621fe5). Could you test the latest commit? Thanks,

**Comment by hajimehoshi** [comment]
Ping @TheMightyGit (The latest commit is now 8522bfd0bf30ca41031df3230ea67c14a1da1a96)

**Comment by hajimehoshi** [comment]
https://github.com/hajimehoshi/ebiten/issues/2114 is solved so I hope this issue is also fixed (by using OpenGL instead of DirectX 12)...
