### ISSUE TITLE
audio: crash at oto on Linux

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2118]
OS: Pop OS 22.04

```
oto: ALSA error: No such file or directory: goroutine 1 [running, locked to thread]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x65
main.logErrorAndExit({0x90a5c0, 0xc0130fb630}, 0xc000122940)
	github.com/wasedaigo/rpgsnack-runtime/main.go:110 +0x3f
main.main()
	github.com/wasedaigo/rpgsnack-runtime/main.go:98 +0x313
```

CC @wasedaigo

**Comment by hajimehoshi** [comment]
This was not fixed on the reporter's machine:

```
oto: ALSA error at snd_pcm_open: "default": No such file or directory, "default:0": No such file or directory, "plughw": No such file or directory, "plughw:0": No such file or directory, "plughw:0,0": No such file or directory: goroutine 1 [running, locked to thread]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x65
main.logErrorAndExit({0x90b7c0, 0xc0104e7400}, 0xc00052a010)
	github.com/wasedaigo/rpgsnack-runtime/main.go:110 +0x3f
main.main()
	github.com/wasedaigo/rpgsnack-runtime/main.go:98 +0x2d3
```

**Comment by hajimehoshi** [comment]
https://wiki.archlinux.org/title/Advanced_Linux_Sound_Architecture/Troubleshooting

**Comment by hajimehoshi** [comment]
https://alsa-devel.alsa-project.narkive.com/DU8TdIvy/default-device-with-fallback Specifying a concrete device name might be better.

**Comment by hajimehoshi** [comment]
I decided not to back-port this fix since

* `default` should be available in most cases (actually Chromium and SDL don't seem to care such case enough)
* We have not tested how safe the current fix is very well

**Comment by captkirk88** [comment]
@hajimehoshi I encountered this issue on Windows Subsystem for Linux using Ubuntu distro.  My go package would run but crash with Oto errors.  Further research led me to alsa-utils but that didn't help.

```
ALSA lib confmisc.c:768:(parse_card) cannot find card '0'
ALSA lib conf.c:4248:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4248:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1251:(snd_func_refer) error evaluating name
ALSA lib conf.c:4248:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4727:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: alsa_open_playback: Could not open playback device 'default': No such file or directory
```

The fix was to `sudo apt install pulseaudio` and reboot.

If anyone comes across this issue, try pulseaudio.  I hope it fixes the soundcard issue for you too.

**Comment by hajimehoshi** [comment]
I don't plan to support WSL.
