### ISSUE TITLE
audio: crash when alt+tabbing/maximizing/minimizing the window on Linux

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2125]
```
oto: ALSA error at snd_pcm_writei: File descriptor in bad state: goroutine 1 [running, locked to thread]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x65
main.logErrorAndExit({0x914d00, 0xc0166923e0}, 0xc00012ca20)
	github.com/wasedaigo/rpgsnack-runtime/main.go:114 +0x3f
main.main()
	github.com/wasedaigo/rpgsnack-runtime/main.go:102 +0x353
```

CC @wasedaigo

**Comment by hajimehoshi** [comment]
https://github.com/gaojunchen/imx6-dual-core-hardware/blob/8857eb68aa99c3e4f2df63f472b1991ed6fe123d/alsa_sound/AudioStreamOutALSA.cpp#L101-L119 

I'm not sure but there is a way to handle this. The problem is that I cannot reproduce this issue yet.

**Comment by hajimehoshi** [comment]
Another possible solution is to mark the device unusable and recreate a handler with another candidate device.

**Comment by hajimehoshi** [comment]
A better algorithm to choose a device

https://source.chromium.org/chromium/chromium/src/+/main:media/audio/alsa/alsa_output.cc;l=665;drc=1946212ac0100668f14eb9e2843bdd846e510a1e

**Comment by hajimehoshi** [comment]
This causes on an actual game, and I cannot reproduce this yet. I think the minimized test case is 

1. Run `examples/audio`
2. Press `U`
3. Press `Alt+Tab` several times

I appreciate if someone could reproduce the case.

**Comment by hajimehoshi** [comment]
I've not confirmed this fixed yet, but hopefully the current Oto usage fixed this.
