### ISSUE TITLE
internal/graphicsdriver/directx: crash at CreateFence

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2142]
```
directx: ID3D12Device::CreateFence failed: HRESULT(2289696773): goroutine 1 [running, locked to thread]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x65
main.logErrorAndExit({0x131ab60, 0xc0001fc000}, 0xc00049a950)
        github.com/wasedaigo/rpgsnack-runtime/main.go:114 +0x3f
main.main()
        github.com/wasedaigo/rpgsnack-runtime/main.go:102 +0x353
```

GPU: intel hd 4400

/CC @wasedaigo

**Comment by hajimehoshi** [comment]
https://ugetfix.com/ask/how-to-fix-dxgi_error_device_hung-error/

**Comment by hajimehoshi** [comment]
I feel like this is an issue in the driver, and there is nothing Ebitengine could do.

**Comment by hajimehoshi** [comment]
https://github.com/gfx-rs/wgpu/issues/1382

**Comment by hajimehoshi** [comment]
I could reproduce this issue with https://github.com/hajimehoshi/ebiten/issues/2138#issue-1268742218

**Comment by hajimehoshi** [comment]
Hmmm, after rebooting this machine, I could no longer reproduce this issue.

**Comment by hajimehoshi** [comment]
```
[3424] D3D12 ERROR: ID3D12CommandList::DrawIndexedInstanced: The current primitive topology in the Command List is D3D_PRIMITIVE_TOPOLOGY_UNDEFINED. This is invalid since the command list topology must match the Pipeline State topology type which cannot be undefined. [ EXECUTION ERROR #219: COMMAND_LIST_DRAW_INVALID_PRIMITIVETOPOLOGY]
[3424] D3D12 WARNING: ID3D12CommandList::DrawIndexedInstanced: An Index Buffer is expected, but none is set on the command list. This is OK, as reading from a missing Index Buffer is defined to return 0.However the developer probably did not intend to make use of this behavior.  [ EXECUTION WARNING #211: COMMAND_LIST_DRAW_INDEX_BUFFER_NOT_SET]
[3424] D3D12 ERROR: ID3D12CommandList::DrawIndexedInstanced: The depth stencil format does not match that specified by the current pipeline state. A null depth stencil view may only be bound when the pipeline state depth stencil format is UNKNOWN. (pipeline state = D24_UNORM_S8_UINT, DSV ID3D12Resource* = 0x0000000000000000:'(nullptr)') [ EXECUTION ERROR #615: DEPTH_STENCIL_FORMAT_MISMATCH_PIPELINE_STATE]
[3424] D3D12: Removing Device.
[3424] D3D12 MESSAGE: ID3D12Device::RemoveDevice: Device removal has been triggered for the following reason (DXGI_ERROR_DEVICE_REMOVED: Plug-and-play stop has been exercised on this adapter. Odds are good that the adapter might no longer be available). [ EXECUTION MESSAGE #234: DEVICE_REMOVAL_PROCESS_NOT_AT_FAULT]
```

**Comment by hajimehoshi** [comment]
Reproducible case (based on @steampoweredtaco's example)

```go
package main

import (
	"fmt"
	"image"
	"image/color"
	"math"
	"math/rand"

	"github.com/hajimehoshi/ebiten/v2"
	"github.com/hajimehoshi/ebiten/v2/text"
	"github.com/hajimehoshi/ebiten/v2/vector"
	"github.com/llgcode/draw2d/draw2dimg"
	"github.com/llgcode/draw2d/draw2dkit"
	"golang.org/x/image/colornames"
	"golang.org/x/image/font"
	"golang.org/x/image/font/gofont/goregular"
	"golang.org/x/image/font/opentype"
)

type GameConfig struct {
	Width  int
	Height int
	Title  string
}

var (
	CFG = GameConfig{
		Width:  800,
		Height: 600,
		Title:  "Bugs?",
	}
)

var (
	emptyImage        = ebiten.NewImage(3, 3)
	debugCircleImage  *ebiten.Image
	emptyTextureImage = emptyImage.SubImage(image.Rect(1, 1, 2, 2)).(*ebiten.Image)
	face              font.Face
)

func NormalizeInt(v, fromMin, fromMax, toMin, toMax int) int {
	ratio := float64(toMax-toMin) / float64(fromMax-fromMin)
	return int(math.Round(float64(toMin) + ratio*float64(v-fromMin)))
}

func init() {
	emptyImage.Fill(color.White)
	img := image.NewRGBA(image.Rect(0, 0, 20, 20))
	gc := draw2dimg.NewGraphicContext(img)
	gc.SetStrokeColor(color.NRGBA{255, 0, 0, 255})
	gc.SetLineWidth(1)
	draw2dkit.Circle(gc, 10, 10, 7)
	gc.Stroke()
	debugCircleImage = ebiten.NewImageFromImage(img)
	emptyImage.Fill(colornames.Aquamarine)
	f, _ := opentype.Parse(goregular.TTF)
	face, _ = opentype.NewFace(f, &opentype.FaceOptions{
		Size: 12,
		DPI:  72,
	})
}

type Location struct {
	X int
	Y int
}

type Circle struct {
	id     int
	size   int
	color  color.RGBA
	center Location
}

type Game struct {
	screenWidth, screenHeight int
	circles                   []Circle
}

func (g *Game) Update() error {
	return nil
}

func (g *Game) Draw(screen *ebiten.Image) {
	for _, c := range g.circles {
		p := vector.Path{}
		p.Arc(float32(c.center.X), float32(c.center.Y), float32(c.size)/2, 0, 2*math.Pi, vector.Clockwise)
		filling, indicies := p.AppendVerticesAndIndicesForFilling(nil, nil)

		for i := range filling {
			filling[i].ColorR = float32(c.color.R) / 0xff
			filling[i].ColorG = float32(c.color.G) / 0xff
			filling[i].ColorB = float32(c.color.B) / 0xff
		}

		op := &ebiten.DrawImageOptions{
			GeoM:          ebiten.GeoM{},
			ColorM:        ebiten.ColorM{},
			CompositeMode: 0,
			Filter:        0,
		}
		op.GeoM.Translate(float64(c.center.X), float64(c.center.Y))
		screen.DrawImage(debugCircleImage, op)
		cord := fmt.Sprintf("%d, %.2f, %.2f, %.2f", c.id, float32(c.center.X), float32(c.center.Y), float32(c.size)/2)

		text.Draw(screen, cord, face, c.center.X, c.center.Y, colornames.White)

		op2 := &ebiten.DrawTrianglesOptions{
			FillRule: ebiten.EvenOdd,
		}

		screen.DrawTriangles(filling, indicies, emptyTextureImage, op2)

	}
}

func (g *Game) Layout(outsideWidth, outsideHeight int) (screenWidth, screenHeight int) {
	screenWidth = g.screenWidth
	screenHeight = g.screenHeight
	return
}

func NewGame(width, height, initNumberOfOrganisms int) *Game {
	g := &Game{
		screenWidth:  width,
		screenHeight: height,
		circles:      make([]Circle, 0, initNumberOfOrganisms),
	}
	for i := 0; i < initNumberOfOrganisms; i += 1 {
		g.circles = append(g.circles, NewCircle(i+1, width, height))
	}
	return g
}

func NewCircle(id, maxX, maxY int) Circle {
	o := Circle{
		id:     id,
		size:   12,
		color:  colornames.Azure,
		center: Location{rand.Intn(maxX), rand.Intn(maxY)},
	}
	return o
}

func main() {
	ebiten.SetWindowSize(CFG.Width, CFG.Height)
	ebiten.SetWindowTitle(CFG.Title)
	g := NewGame(CFG.Width, CFG.Height, 100)
	if err := ebiten.RunGame(g); err != nil {
		panic(err)
	}

}
```

**Comment by hajimehoshi** [comment]
Apparently, there are multiple potential reasons for the error HRESULT(2289696773). I'll focus on each concrete issue.

**Comment by hajimehoshi** [comment]
Note to myself: this error from CreateFence was resolved by using the fallback of OpenGL. The same error occurred at other places, and I solved them as difference issues.
