### ISSUE TITLE
out of memory on browsers

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2156]
@Critters reported this issue:

Reproducible case
https://github.com/Critters/ebitengine-sprite-crash

**Comment by hajimehoshi** [comment]
@Critters How do you run this for browsers? I used `wasmserve` and could not load images.

**Comment by hajimehoshi** [comment]
Or I'd appreciate if you could use `go:embed` instead of loading the resources via HTTP. Thanks,

**Comment by Critters** [comment]
I use "live server" in VS code.
If I use go:embed, that'd put a copy of the assets in the wasm correct? Which would be fine for this test but the goal of having a game with thousands of assets that are loaded as needed vs in an initial download would be thwarted. If you have a game with a lot of content that is revealed over many play sessions, it'd be impractical (IMO) to preload all of that for a new player.

**Comment by hajimehoshi** [comment]
What I want to know is whether the memory allocation issue is in Ebitengine or not, so I just want a minimized reproducible test case. Whether you use go:embed in your actual product is a different question (and IMO you should not if loading time matters)

**Comment by Critters** [comment]
I will test

**Comment by Critters** [comment]
I'm sorry, how do I do this? NewImageFromFile? That seems to still load in the asset at runtime which is the same behavior as NewImageFromURL.

**Comment by hajimehoshi** [comment]
> I'm sorry, how do I do this? NewImageFromFile? 

I'd use NewImageFromImage.

```go
//go:embed images/foo.png
var foo []byte

func load() *ebiten.Image {
    d, _, _ := image.Decode(bytes.NewReader(foo))
    img := ebiten.NewImageFromImage(d)
    return img
}
```

or

```go
//go:embed images
var images fs.FS

func load() *ebiten.Image {
    f, _ := images.Open("foo.png")
    defer f.Close()
    d, _, _ := image.Decode(f)
    img := ebiten.NewImageFromImage(d)
    return img
}
```

**Comment by Critters** [comment]
I got it in, confirmed in the console that it was not requesting those images at runtime, had the same error where after a few seconds it halted:

```
panic: JavaScript error: Array buffer allocation failed
wasm_exec.js:22 
wasm_exec.js:22 goroutine 775 [running]:
wasm_exec.js:22 syscall/js.Value.New({{}, 0x7ff800040000000d, 0xc10098}, {0xe298e8, 0x1, 0x1})
wasm_exec.js:22 	C:/Program Files/Go/src/syscall/js/js.go:427 +0xe
wasm_exec.js:22 github.com/hajimehoshi/ebiten/v2/internal/jsutil.ensureTemporaryArrayBufferSize(0x4e7000)
wasm_exec.js:22 	C:/Users/David/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.4.0-alpha.7/internal/jsutil/buf_js.go:85 +0x18
wasm_exec.js:22 github.com/hajimehoshi/ebiten/v2/internal/jsutil.TemporaryUint8ArrayFromFloat32Slice(0x139c00, {0x1d10000, 0x4e700, 0x55800})
wasm_exec.js:22 	C:/Users/David/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.4.0-alpha.7/internal/jsutil/buf_js.go:117 +0x2
wasm_exec.js:22 github.com/hajimehoshi/ebiten/v2/internal/graphicsdriver/opengl.(*context).arrayBufferSubData(0xdda350, {0x1d10000, 0x4e700, 0x55800})
wasm_exec.js:22 	C:/Users/David/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.4.0-alpha.7/internal/graphicsdriver/opengl/context_js.go:569 +0x4
wasm_exec.js:22 github.com/hajimehoshi/ebiten/v2/internal/graphicsdriver/opengl.(*Graphics).SetVertices(0xdda300, {0x1d10000, 0x4e700, 0x55800}, {0xcfc000, 0xeb50, 0x12000})
wasm_exec.js:22 	C:/Users/David/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.4.0-alpha.7/internal/graphicsdriver/opengl/graphics.go:166 +0x4
wasm_exec.js:22 github.com/hajimehoshi/ebiten/v2/internal/graphicscommand.(*commandQueue).flush(0x9476a0, {0x996b0, 0xdda300})
wasm_exec.js:22 	C:/Users/David/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.4.0-alpha.7/internal/graphicscommand/command.go:237 +0x13
wasm_exec.js:22 github.com/hajimehoshi/ebiten/v2/internal/graphicscommand.(*commandQueue).Flush.func1()
wasm_exec.js:22 	C:/Users/David/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.4.0-alpha.7/internal/graphicscommand/command.go:196 +0x2
wasm_exec.js:22 github.com/hajimehoshi/ebiten/v2/internal/graphicscommand.runOnRenderingThread(0xfbe450)
wasm_exec.js:22 	C:/Users/David/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.4.0-alpha.7/internal/graphicscommand/thread.go:36 +0x9
wasm_exec.js:22 github.com/hajimehoshi/ebiten/v2/internal/graphicscommand.(*commandQueue).Flush(0x9476a0, {0x996b0, 0xdda300})
wasm_exec.js:22 	C:/Users/David/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.4.0-alpha.7/internal/graphicscommand/command.go:195 +0xd
wasm_exec.js:22 github.com/hajimehoshi/ebiten/v2/internal/graphicscommand.FlushCommands(...)
wasm_exec.js:22 	C:/Users/David/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.4.0-alpha.7/internal/graphicscommand/command.go:281
wasm_exec.js:22 github.com/hajimehoshi/ebiten/v2/internal/restorable.ResolveStaleImages({0x996b0, 0xdda300})
wasm_exec.js:22 	C:/Users/David/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.4.0-alpha.7/internal/restorable/images.go:70 +0x6
wasm_exec.js:22 github.com/hajimehoshi/ebiten/v2/internal/atlas.EndFrame({0x996b0, 0xdda300})
wasm_exec.js:22 	C:/Users/David/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.4.0-alpha.7/internal/atlas/image.go:808 +0x16
wasm_exec.js:22 github.com/hajimehoshi/ebiten/v2/internal/buffered.EndFrame(...)
wasm_exec.js:22 	C:/Users/David/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.4.0-alpha.7/internal/buffered/image.go:45
wasm_exec.js:22 github.com/hajimehoshi/ebiten/v2/internal/ui.(*context).updateFrameImpl.func1.1()
wasm_exec.js:22 	C:/Users/David/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.4.0-alpha.7/internal/ui/context.go:103 +0x4
wasm_exec.js:22 github.com/hajimehoshi/ebiten/v2/internal/graphics.(*verticesBackend).lockAndReset(0x9473e0, 0xe29d60)
wasm_exec.js:22 	C:/Users/David/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.4.0-alpha.7/internal/graphics/vertex.go:105 +0x7
wasm_exec.js:22 github.com/hajimehoshi/ebiten/v2/internal/graphics.LockAndResetVertices(...)
wasm_exec.js:22 	C:/Users/David/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.4.0-alpha.7/internal/graphics/vertex.go:135
wasm_exec.js:22 github.com/hajimehoshi/ebiten/v2/internal/ui.(*context).updateFrameImpl.func1()
wasm_exec.js:22 	C:/Users/David/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.4.0-alpha.7/internal/ui/context.go:102 +0x6
wasm_exec.js:22 github.com/hajimehoshi/ebiten/v2/internal/ui.(*context).updateFrameImpl(0xc484c0, {0x996b0, 0xdda300}, 0x1, 0x40a3de0000000000, 0x4081600000000000, 0x3ff0000000000000)
wasm_exec.js:22 	C:/Users/David/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.4.0-alpha.7/internal/ui/context.go:145 +0x3e
wasm_exec.js:22 github.com/hajimehoshi/ebiten/v2/internal/ui.(*context).updateFrame(0xc484c0, {0x996b0, 0xdda300}, 0x40a3de0000000000, 0x4081600000000000, 0x3ff0000000000000)
wasm_exec.js:22 	C:/Users/David/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.4.0-alpha.7/internal/ui/context.go:65 +0x4
wasm_exec.js:22 github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).updateImpl(0x947720, 0x0)
wasm_exec.js:22 	C:/Users/David/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.4.0-alpha.7/internal/ui/ui_js.go:308 +0x2a
wasm_exec.js:22 github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).update(0x947720)
wasm_exec.js:22 	C:/Users/David/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.4.0-alpha.7/internal/ui/ui_js.go:284 +0x10
wasm_exec.js:22 github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).loop.func1()
wasm_exec.js:22 	C:/Users/David/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.4.0-alpha.7/internal/ui/ui_js.go:341 +0xc
wasm_exec.js:22 created by github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).loop.func2
wasm_exec.js:22 	C:/Users/David/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.4.0-alpha.7/internal/ui/ui_js.go:362 +0x4
```

**Comment by hajimehoshi** [comment]
Thanks! Could you update the repository so that I can try this on my local machine?

**Comment by hajimehoshi** [comment]
Unfortunately, I couldn't reproduce the crash on my browser. From the profile, I saw what took so much memory.

![image](https://user-images.githubusercontent.com/16950/174702316-f699ae25-7086-425f-b1c0-7a7a7fa15efb.png)

**Comment by Critters** [comment]
FWIW, if you set the number of sprites on this example to 20,000 (probably happens at lower values) it crashes with the same "array buffer allocation failed"
https://ebiten.org/examples/sprites.html

**Comment by hajimehoshi** [comment]
OK I found there is a bug in buf_js.go. I'll fix this asap

**Comment by Critters** [comment]
Typo in your name there :)
I can confirm it is fixed. Before I would crash at over 5k sprites and now I am unable to break it with even 40k, (which is 8fps so not a number I would approach IRL)

**Comment by hajimehoshi** [comment]
Though this is a performance fix, this fixes crashes in actual browser Ebitengine games. I'll backport this to v2.3.
