### ISSUE TITLE
NewShader - fatal error deadlock

### ISSUE THREAD

**Issue by Zyko0** [hajimehoshi/ebiten#2162]
On Windows and main `2d23168ac`, I'm getting a crash on a call to `NewShader`
```
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [semacquire, locked to thread]:
sync.runtime_SemacquireMutex(0x0?, 0x0?, 0x0?)
        /go1.18.3/src/runtime/sema.go:71 +0x25
sync.(*Mutex).lockSlow(0xe5afc8)
        /go1.18.3/src/sync/mutex.go:162 +0x165
sync.(*Mutex).Lock(...)
        /go1.18.3/src/sync/mutex.go:81
github.com/hajimehoshi/ebiten/v2/internal/atlas.NewShader(0xc00060c448)
```

Reproducible case:
<details>

```go
package main

import (
	"log"

	"github.com/hajimehoshi/ebiten/v2"
)

var (
	s *ebiten.Shader
)

func init() {
	var err error

	s, err = ebiten.NewShader([]byte(`
package main

func Fragment(position vec4, texCoord vec2, color vec4) vec4 {
	return vec4(1.)
}`))
	if err != nil {
		log.Fatal(err)
	}
}

type Game struct{}

func (g *Game) Update() error {
	return nil
}

func (g *Game) Draw(screen *ebiten.Image) {
}

func (g *Game) Layout(outsideWidth, outsideHeight int) (int, int) {
	return 1, 1
}

func main() {
	ebiten.RunGame(&Game{})
}
```

</details>

**Comment by hajimehoshi** [comment]
Confirmed this was reproducible. Thanks!

**Comment by hajimehoshi** [comment]
This was not reproducible on v2.3 but on the main.

**Comment by hajimehoshi** [comment]
The culprit was 3b6a080519469560d3f03016a281f92966840944
