### ISSUE TITLE
inpututil: out of range at scanning buttons

### ISSUE THREAD

**Issue by w33zl3p00tch** [hajimehoshi/ebiten#2169]
Lately when I try to run ebiten projects that make use of inpututil, they panic. After having a look at the code (and having experienced similar issues with games written in other engines), I suspected my HOTAS and disconnected both the stick and throttle. Afterwards the ebiten games run fine.
This happened both under Linux and Windows, so this might affect all users that have this rather complicated HOTAS.

Product page: https://www.thrustmaster.com/en-us/products/hotas-warthog/

Panic trace:
```
panic: runtime error: index out of range [32] with length 32

goroutine 35 [running]:
github.com/hajimehoshi/ebiten/v2/inpututil.(*inputState).update(0x694ee0)
        C:/Users/manuel/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.5/inpututil/inpututil.go:148 +0xd0f
github.com/hajimehoshi/ebiten/v2/inpututil.init.0.func1()
        C:/Users/manuel/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.5/inpututil/inpututil.go:75 +0x25
github.com/hajimehoshi/ebiten/v2/internal/hooks.RunBeforeUpdateHooks()
        C:/Users/manuel/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.5/internal/hooks/hooks.go:38 +0xc7
github.com/hajimehoshi/ebiten/v2/internal/ui.(*context).updateFrameImpl(0xc00077b0c0, {0x3a03c0, 0x695720}, 0x1, 0x4093b00000000000, 0x4084000000000000, 0xc0004c7e98?)
        C:/Users/manuel/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.5/internal/ui/context.go:126 +0x225
github.com/hajimehoshi/ebiten/v2/internal/ui.(*context).updateFrame(0xc000726150?, {0x3a03c0, 0x695720}, 0xc00007a298?, 0xc000608340?, 0xc0006083c8?)
        C:/Users/manuel/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.5/internal/ui/context.go:64 +0x8e
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).loop(0x695520)
        C:/Users/manuel/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.5/internal/ui/ui_glfw.go:1067 +0x1ea
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).Run.func1()
        C:/Users/manuel/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.5/internal/ui/run_notsinglethread.go:46 +0x13d
created by github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).Run
        C:/Users/manuel/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.5/internal/ui/run_notsinglethread.go:33 +0x20a
exit status 2
```

Please let me know if I can do anything to help investigating or solving the issue.

**Comment by hajimehoshi** [comment]
Thank you for reporting this.

Please try `go get github.com/hajimehoshi/ebiten/v2@a1db69000eb6ee591eea818a34d4db89e3dbefb7`

**Comment by w33zl3p00tch** [comment]
Thanks for creating ebiten!

Yes, that's fixed now.
