### ISSUE TITLE
unexpected blinking screen on macOS Metal with a big-enough screen

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2174]
https://github.com/tinne26/bindless

https://gyazo.com/ad3d7ca62313a345868e76046e989a06

**Comment by hajimehoshi** [comment]
This happens only with

```go
ebiten.SetCursorShape(ebiten.CursorShapeCrosshair)
ebiten.SetScreenClearedEveryFrame(false)  
```

**Comment by hajimehoshi** [comment]
https://github.com/hajimehoshi/ebiten/commit/ac802cf0d0d97b1440329231204c446f7b049575 was the culprit!

**Comment by hajimehoshi** [comment]
Minimal reproducible case:

```go
package main

import (
        "image/color"

        "github.com/hajimehoshi/ebiten/v2"
)

var emptyImage = ebiten.NewImage(100, 100)
var pix []byte

func init() {
        w, h := emptyImage.Size()
        pix = make([]byte, 4*w*h)
        for i := range pix {
                pix[i] = 0xff
        }
}

type Game struct {
}

func (g *Game) Update() error {
        return nil
}

func (g *Game) Draw(screen *ebiten.Image) {
        screen.Fill(color.RGBA{0x80, 0x80, 0xff, 0xff})
        emptyImage.ReplacePixels(pix)
        screen.DrawImage(emptyImage, nil)
}

func (g *Game) Layout(outsideWidth, outsideHeight int) (int, int) {
        return outsideWidth * 2, outsideHeight * 2
}

func main() {
        ebiten.SetWindowResizingMode(ebiten.WindowResizingModeEnabled)
        ebiten.RunGame(&Game{})
}
```

**Comment by hajimehoshi** [comment]
https://developer.apple.com/library/archive/documentation/Miscellaneous/Conceptual/MetalProgrammingGuide/Cmd-Submiss/Cmd-Submiss.html#//apple_ref/doc/uid/TP40014221-CH3-SW1

> At any point in time, only a single command encoder can be active and append commands into a command buffer. Each command encoder must be ended before another command encoder can be created for use with the same command buffer. The one exception to the “one active command encoder for each command buffer” rule is the MTLParallelRenderCommandEncoder protocol, discussed in Encoding a Single Rendering Pass Using Multiple Threads.

**Comment by hajimehoshi** [comment]
https://developer.apple.com/library/archive/documentation/3DDrawing/Conceptual/MTLBestPracticesGuide/CommandBuffers.html
> Best Practice: Submit the fewest possible command buffers per frame without underutilizing the GPU.

Hm, so probably the fix caused unexpected GPU delays

**Comment by hajimehoshi** [comment]
I found #2154 was not solved yet.

```sh
go test ./internal/processtest/ -run=/2154 -count=100
```

```
--- FAIL: TestPrograms (1.45s)
    --- FAIL: TestPrograms/issue2154.go (1.45s)
        processtest_test.go:50: exit status 1
            panic: got: {255 255 255 255}, want: {0 0 0 255}
            
            goroutine 53 [running]:
            main.(*Game).Draw(0xc0000120b0, 0xc000026340)
                /Users/hajimehoshi/ebiten/internal/processtest/testdata/issue2154.go:79 +0x1ae
            github.com/hajimehoshi/ebiten/v2.(*imageDumperGame).Draw(0xc00050e060, 0x4181320?)
                /Users/hajimehoshi/ebiten/run.go:154 +0x35
            github.com/hajimehoshi/ebiten/v2.(*gameForUI).Draw(0xc00037c620?)
                /Users/hajimehoshi/ebiten/gameforui.go:63 +0x28
            github.com/hajimehoshi/ebiten/v2/internal/ui.(*context).drawGame(0xc0005100c0, {0x41e3b90, 0xc00032de60})
                /Users/hajimehoshi/ebiten/internal/ui/context.go:161 +0x168
            github.com/hajimehoshi/ebiten/v2/internal/ui.(*context).updateFrameImpl(0xc0005100c0, {0x41e3b90, 0xc00032de60}, 0x2, 0x4084000000000000, 0x407e000000000000, 0xc000137e60?)
                /Users/hajimehoshi/ebiten/internal/ui/context.go:141 +0x2f6
            github.com/hajimehoshi/ebiten/v2/internal/ui.(*context).updateFrame(0xc00000e060?, {0x41e3b90, 0xc00032de60}, 0xc0a8380aaa8a6d38?, 0xc4b0c70?, 0x4357860?)
                /Users/hajimehoshi/ebiten/internal/ui/context.go:65 +0x8e
            github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).loop(0x4357da0)
                /Users/hajimehoshi/ebiten/internal/ui/ui_glfw.go:1116 +0x2bb
            github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).Run.func1()
                /Users/hajimehoshi/ebiten/internal/ui/run_notsinglethread.go:46 +0x13d
            created by github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).Run
                /Users/hajimehoshi/ebiten/internal/ui/run_notsinglethread.go:33 +0x20a
            exit status 2
FAIL
FAIL    github.com/hajimehoshi/ebiten/v2/internal/processtest   162.060s
FAIL
```

**Comment by hajimehoshi** [comment]
OK this is NOT a metal issue. The test succeeded with this patch:

```diff
diff --git a/internal/graphicscommand/command.go b/internal/graphicscommand/command.go
index 6d422bfa0..ec99a54d3 100644
--- a/internal/graphicscommand/command.go
+++ b/internal/graphicscommand/command.go
@@ -529,7 +529,7 @@ func (c *replacePixelsCommand) String() string {
 // Exec executes the replacePixelsCommand.
 func (c *replacePixelsCommand) Exec(graphicsDriver graphicsdriver.Graphics, indexOffset int) error {
        var lastArgIdx int
-       for i, a := range c.args {
+       /*for i, a := range c.args {
                if a.Mask == nil {
                        continue
                }
@@ -553,7 +553,7 @@ func (c *replacePixelsCommand) Exec(graphicsDriver graphicsdriver.Graphics, inde
                }
 
                a.Mask = nil
-       }
+       }*/
 
        if len(c.args[lastArgIdx:]) > 0 {
                if err := c.dst.image.ReplacePixels(c.args[lastArgIdx:]); err != nil {
```

Of course this patch breaks other things, but the true culprit is in there.
