### ISSUE TITLE
internal/graphicsdriver/directx: DXGI_ERROR_DEVICE_HUNG error at CreateGraphicsPipelineState

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2198]
```
2022/07/11 21:04:37 directx: ID3D12Device::CreateGraphicsPipelineState failed: HRESULT(2289696773): goroutine 1 [running, locked to thread]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x65
main.logErrorAndExit({0x8a77a0, 0xc00062a020}, 0xc000006a00)
	github.com/wasedaigo/rpgsnack-runtime/main.go:124 +0x3f
main.main()
	github.com/wasedaigo/rpgsnack-runtime/main.go:112 +0x3d3
```

Reported by @wasedaigo

**Comment by hajimehoshi** [comment]
I feel like my usage of descriptor heaps is wrong...

**Comment by hajimehoshi** [comment]
I'll backport 42d5d91829bcd6dfc559ef53d7fa546f3119daa2 to v2.3 for approprite memory usages.

**Comment by hajimehoshi** [comment]
This still happens with alpha.9

```
directx: ID3D12Device::CreateGraphicsPipelineState failed: HRESULT(2289696773): goroutine 1 [running, locked to thread]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x65
main.logErrorAndExit({0x6c7a00, 0xc0000c2070}, 0xc0000cea10)
	github.com/wasedaigo/rpgsnack-runtime/main.go:124 +0x3f
main.main()
	github.com/wasedaigo/rpgsnack-runtime/main.go:112 +0x3d3
```

**Comment by hajimehoshi** [comment]
I reverted the fix as this didn't help the reporter's machine.

**Comment by hajimehoshi** [comment]
We would need an actual device if we want to fix this.

**Comment by erexo** [comment]
As described in #2485 I do have access to machine which has this problem

**Comment by hajimehoshi** [comment]
Thanks but I'm at lost what approach would be the best. DXGI_ERROR_DEVICE_HUNG seems a very notorious error.

Let me think.

**Comment by hajimehoshi** [comment]
https://www.makeuseof.com/windows-dxgi-error-device-hung-error/

This article recommends 1) stop overcloking if you already do, and/or 2) edit the registery, and so on. Unfortunately the user would have to take these approarches instead of Ebitengine. I'll investigate more.

**Comment by hajimehoshi** [comment]
From @wasedaigo's report:

```
directx: ID3D12Device::CreateCommittedResource failed: HANDLE(2289696773)
goroutine 1 [running, locked to thread]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x65
main.logErrorAndExit({0xfb9780, 0xc000129340}, 0xc00018c9b0)
	github.com/wasedaigo/rpgsnack-runtime/main.go:125 +0x2c
main.main()
	github.com/wasedaigo/rpgsnack-runtime/main.go:119 +0x3c9
```

**Comment by hajimehoshi** [comment]
My current rough guess is that adopting DirectX 11 instead of DirectX 12 might improve the situation.

* ANGLE (WebGL implementation) still uses DirectX 11.
* Final Fantasy 14 still uses DirectX 11.

**Comment by hajimehoshi** [comment]
As this is pretty rare with the DirectX 11 (not 12) driver, I'll remove the milestone. I don't think this is fixable by me anyway.
