### ISSUE TITLE
ebiten: `TestImageEdge` fails with Intel Celeron J3455

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2202]
```
--- FAIL: TestImageEdge (114.82s)
panic: directx: ID3D12GraphicsCommandList::Close failed: Not enough memory resources are available to complete this operation. [recovered]
        panic: directx: ID3D12GraphicsCommandList::Close failed: Not enough memory resources are available to complete this operation.

goroutine 62 [running]:
testing.tRunner.func1.2({0x649c60, 0xc0000ca560})
        C:/Program Files/Go/src/testing/testing.go:1389 +0x24e
testing.tRunner.func1()
        C:/Program Files/Go/src/testing/testing.go:1392 +0x39f
panic({0x649c60, 0xc0000ca560})
        C:/Program Files/Go/src/runtime/panic.go:838 +0x207
github.com/hajimehoshi/ebiten/v2/internal/ui.(*Image).At(0xc000442120, 0xc000047180?, 0xc000442120?)
        //192.168.0.5/hajimehoshi/ebiten/internal/ui/image.go:92 +0xb8
github.com/hajimehoshi/ebiten/v2.(*Image).at(0x0?, 0xc000055aa0?, 0x5f2298?)
        //192.168.0.5/hajimehoshi/ebiten/image.go:703 +0x46
github.com/hajimehoshi/ebiten/v2.(*Image).At(0xc000055bb8?, 0xc000055be8?, 0x4?)
        //192.168.0.5/hajimehoshi/ebiten/image.go:676 +0x19
github.com/hajimehoshi/ebiten/v2_test.TestImageEdge(0xc0000849c0)
        //192.168.0.5/hajimehoshi/ebiten/image_test.go:562 +0xa47
testing.tRunner(0xc0000849c0, 0x6a0c88)
        C:/Program Files/Go/src/testing/testing.go:1439 +0x102
created by testing.(*T).Run
        C:/Program Files/Go/src/testing/testing.go:1486 +0x35f
```

**Comment by hajimehoshi** [comment]
There seems a memory leak: buffers for vertices and indices are created but released less often?
