### ISSUE TITLE
Malformed gamepad mapping can crash Ebitengine

### ISSUE THREAD

**Issue by divVerent** [hajimehoshi/ebiten#2218]
I had a bug in my code that by accident sent the string "{}" to UpdateStandardGamepadLayoutMappings. This panics:

```
07-28 20:18:46.119 18289 18365 I GoLog   : 2022/07/29 00:18:46.119168 [INFO] GAMEPAD ENTRY: {}
07-28 20:18:46.122 18289 18289 E Go      : go.Universe$proxyerror: runtime error: slice bounds out of range [2:1]
07-28 20:18:46.122 18289 18289 E Go      : goroutine 13 [running]:
07-28 20:18:46.122 18289 18289 E Go      : runtime/debug.Stack()
07-28 20:18:46.122 18289 18289 E Go      : 	runtime/debug/stack.go:24 +0x88
07-28 20:18:46.122 18289 18289 E Go      : github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).run.func1(0x40063c7f98)
07-28 20:18:46.122 18289 18289 E Go      : 	github.com/hajimehoshi/ebiten/v2@v2.3.7/internal/ui/ui_mobile.go:268 +0x48
07-28 20:18:46.122 18289 18289 E Go      : panic({0x6ed42ac380, 0x40012f0678})
07-28 20:18:46.122 18289 18289 E Go      : 	runtime/panic.go:1038 +0x21c
07-28 20:18:46.122 18289 18289 E Go      : github.com/hajimehoshi/ebiten/v2/internal/gamepaddb.parseLine({0x4000025348, 0x2}, 0x4)
07-28 20:18:46.122 18289 18289 E Go      : 	github.com/hajimehoshi/ebiten/v2@v2.3.7/internal/gamepaddb/gamepaddb.go:142 +0x700
07-28 20:18:46.122 18289 18289 E Go      : github.com/hajimehoshi/ebiten/v2/internal/gamepaddb.Update({0x4000025340, 0x2, 0x8})
07-28 20:18:46.122 18289 18289 E Go      : 	github.com/hajimehoshi/ebiten/v2@v2.3.7/internal/gamepaddb/gamepaddb.go:524 +0x270
07-28 20:18:46.122 18289 18289 E Go      : github.com/hajimehoshi/ebiten/v2.UpdateStandardGamepadLayoutMappings(...)
07-28 20:18:46.122 18289 18289 E Go      : 	github.com/hajimehoshi/ebiten/v2@v2.3.7/input.go:324
```

Sure I can `recover()` from this myself, however it's not typical Go style to panic especially on bad input that could come from bad user provided data files, not just programming error like in my case.

**Comment by divVerent** [comment]
For the lulz, this is my bug: https://github.com/divVerent/aaaaxy/commit/e1df5cabe764b7f0dbcd1d01882e510a8dccb8ae - I used the same file path for my config file and the gamepad mappings. Oopsie :)
