### ISSUE TITLE
internal/processtest: fails on Parallels Windows on macOS

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2249]
```
    --- FAIL: TestPrograms/issue2154_2.go (3.49s)
        processtest_test.go:50: exit status 1
            panic: got: {0 0 0 0}, want: {0 0 0 255}

            goroutine 6 [running]:
            main.(*Game).Draw(0xc000016a88, 0x900ea0?)
                //Mac/Home/ebiten/internal/processtest/testdata/issue2154_2.go:72 +0x29d
            github.com/hajimehoshi/ebiten/v2.(*imageDumperGame).Draw(0xc000020c00, 0x7c10f9?)
                //Mac/Home/ebiten/run.go:162 +0x35
            github.com/hajimehoshi/ebiten/v2.(*gameForUI).Draw(0xc00009a820?)
                //Mac/Home/ebiten/gameforui.go:63 +0x28
            github.com/hajimehoshi/ebiten/v2/internal/ui.(*context).drawGame(0xc00004e600, {0x9010d8, 0xc000004780})
                //Mac/Home/ebiten/internal/ui/context.go:159 +0x171
            github.com/hajimehoshi/ebiten/v2/internal/ui.(*context).updateFrameImpl(0xc00004e600, {0x9010d8, 0xc000004780}, 0x1, 0x4084000000000000, 0x407e000000000000, 0xc000057e80?)
                //Mac/Home/ebiten/internal/ui/context.go:139 +0x2f6
            github.com/hajimehoshi/ebiten/v2/internal/ui.(*context).updateFrame(0xc000008348?, {0x9010d8, 0xc000004780}, 0x0?, 0x61d11f?, 0xc000050420?)
                //Mac/Home/ebiten/internal/ui/context.go:63 +0x65
            github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).loop(0xad5700)
                //Mac/Home/ebiten/internal/ui/ui_glfw.go:1118 +0x247
            github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).Run.func1()
                //Mac/Home/ebiten/internal/ui/run_notsinglethread.go:46 +0x13d
            created by github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).Run
                //Mac/Home/ebiten/internal/ui/run_notsinglethread.go:33 +0x20f
            exit status 2
    --- FAIL: TestPrograms/issue2182.go (3.68s)
        processtest_test.go:50: exit status 1
            panic: got: {0 0 0 0}, want: {0 0 0 255}

            goroutine 20 [running]:
            main.(*Game).Draw(0xc000016d38, 0xd30ec0?)
                //Mac/Home/ebiten/internal/processtest/testdata/issue2182.go:73 +0x29d
            github.com/hajimehoshi/ebiten/v2.(*imageDumperGame).Draw(0xc0001b6000, 0xbf10f9?)
                //Mac/Home/ebiten/run.go:162 +0x35
            github.com/hajimehoshi/ebiten/v2.(*gameForUI).Draw(0xc0001de3e0?)
                //Mac/Home/ebiten/gameforui.go:63 +0x28
            github.com/hajimehoshi/ebiten/v2/internal/ui.(*context).drawGame(0xc0001a9140, {0xd310f8, 0xc000004280})
                //Mac/Home/ebiten/internal/ui/context.go:159 +0x171
            github.com/hajimehoshi/ebiten/v2/internal/ui.(*context).updateFrameImpl(0xc0001a9140, {0xd310f8, 0xc000004280}, 0x1, 0x4084000000000000, 0x407e000000000000, 0xc000065e80?)
                //Mac/Home/ebiten/internal/ui/context.go:139 +0x2f6
            github.com/hajimehoshi/ebiten/v2/internal/ui.(*context).updateFrame(0xc000008030?, {0xd310f8, 0xc000004280}, 0x0?, 0xa4d155?, 0xc0001ba060?)
                //Mac/Home/ebiten/internal/ui/context.go:63 +0x65
            github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).loop(0xf05700)
                //Mac/Home/ebiten/internal/ui/ui_glfw.go:1118 +0x247
            github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).Run.func1()
                //Mac/Home/ebiten/internal/ui/run_notsinglethread.go:46 +0x13d
            created by github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).Run
                //Mac/Home/ebiten/internal/ui/run_notsinglethread.go:33 +0x20f
            exit status 2
```

**Comment by hajimehoshi** [comment]
For `issue2182.go` (which should have been `issue2180.go`), the culprit was 479483b76da089774965f6e6f796362bfc30d1b5

**Comment by hajimehoshi** [comment]
Reverted by #2292

**Comment by hajimehoshi** [comment]
Probably we should have a command list for each frame rather than on command list for all the two frames.
