### ISSUE TITLE
ebiten: test sometimes fails with 32bit Windows (HRESULT(2147942414): OOM)

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2294]
```
--- FAIL: TestImageOptionsNegativeBoundsWritePixels (0.01s)
panic: directx: ID3D12Device::CreateCommittedResource failed: HRESULT(2147942414) [recovered]
        panic: directx: ID3D12Device::CreateCommittedResource failed: HRESULT(2147942414)

goroutine 118 [running]:
testing.tRunner.func1.2({0x4e2f80, 0x1188a430})
        C:/Program Files/Go/src/testing/testing.go:1396 +0x2ab
testing.tRunner.func1()
        C:/Program Files/Go/src/testing/testing.go:1399 +0x41f
panic({0x4e2f80, 0x1188a430})
        C:/Program Files/Go/src/runtime/panic.go:884 +0x1ba
github.com/hajimehoshi/ebiten/v2/internal/ui.(*Image).ReadPixels(0x11876180, {0x11837a00, 0x4, 0x4}, 0x0, 0x0, 0x1, 0x1)
        //Mac/Home/ebiten/internal/ui/image.go:86 +0xdf
github.com/hajimehoshi/ebiten/v2.(*Image).at(0x11c1a5e0, 0xfffffff8, 0xfffffff8)
        //Mac/Home/ebiten/image.go:865 +0x152
github.com/hajimehoshi/ebiten/v2.(*Image).At(0x11c1a5e0, 0xfffffff8, 0xfffffff8)
        //Mac/Home/ebiten/image.go:833 +0x31
github.com/hajimehoshi/ebiten/v2_test.TestImageOptionsNegativeBoundsWritePixels(0x11886870)
        //Mac/Home/ebiten/image_test.go:2967 +0x424
testing.tRunner(0x11886870, 0x5328b4)
        C:/Program Files/Go/src/testing/testing.go:1446 +0x113
created by testing.(*T).Run
        C:/Program Files/Go/src/testing/testing.go:1493 +0x374
FAIL    github.com/hajimehoshi/ebiten/v2        82.431s
FAIL
```

An example in the bots https://github.com/hajimehoshi/ebiten/runs/8136457324

**Comment by hajimehoshi** [comment]
Now the test bots seem happy (probably thanks to https://github.com/hajimehoshi/ebiten/commit/cdf83ad2fc5653072b9eecbcd8d6944c4bb73008)

The test still fails on Parallels on macOS.

**Comment by hajimehoshi** [comment]
`readingStagingBuffer` size can be 8x bigger than the texture's data size. What is happening...?

**Comment by hajimehoshi** [comment]
See #2582
