### ISSUE TITLE
test failure on Windows 32bit (386)

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2332]
https://github.com/hajimehoshi/ebiten/actions/runs/3062287769/jobs/4943097605

```
--- FAIL: TestNewImageFromSubImage (0.00s)
panic: directx: ID3D12Device::CreateCommittedResource failed: HRESULT(2147942414) [recovered]
	panic: directx: ID3D12Device::CreateCommittedResource failed: HRESULT(2147942414)

goroutine 94 [running]:
testing.tRunner.func1.2({0xce9880, 0x11e2b7a8})
	C:/hostedtoolcache/windows/go/1.18.6/x64/src/testing/testing.go:1389 +0x2ab
testing.tRunner.func1()
	C:/hostedtoolcache/windows/go/1.18.6/x64/src/testing/testing.go:1392 +0x41f
panic({0xce9880, 0x11e2b7a8})
	C:/hostedtoolcache/windows/go/1.18.6/x64/src/runtime/panic.go:838 +0x1ba
github.com/hajimehoshi/ebiten/v2/internal/ui.(*Image).ReadPixels(0x11e11980, {0x1186fec4, 0x4, 0x4}, 0x0, 0x0, 0x1, 0x1)
	D:/a/ebiten/ebiten/internal/ui/image.go:86 +0xdf
github.com/hajimehoshi/ebiten/v2.(*Image).at(0x11c64da0, 0x0, 0x0)
	D:/a/ebiten/ebiten/image.go:865 +0x152
github.com/hajimehoshi/ebiten/v2.(*Image).At(0x11c64da0, 0x0, 0x0)
	D:/a/ebiten/ebiten/image.go:833 +0x31
github.com/hajimehoshi/ebiten/v2_test.TestNewImageFromSubImage(0x118aaff0)
	D:/a/ebiten/ebiten/image_test.go:401 +0x363
testing.tRunner(0x118aaff0, 0xd37e34)
	C:/hostedtoolcache/windows/go/1.18.6/x64/src/testing/testing.go:1439 +0x113
created by testing.(*T).Run
	C:/hostedtoolcache/windows/go/1.18.6/x64/src/testing/testing.go:1486 +0x374
FAIL	github.com/hajimehoshi/ebiten/v2	87.051s
-test.shuffle 1663261815719711800
```

**Comment by hajimehoshi** [comment]
This is very similar to #2294

**Comment by hajimehoshi** [comment]
`-test.shuffle 1663928590226228300` also failed

**Comment by hajimehoshi** [comment]
`-test.shuffle 1665375785988511500`

**Comment by hajimehoshi** [comment]
https://github.com/hajimehoshi/ebiten/actions/runs/3338209797/jobs/5525577022

**Comment by hajimehoshi** [comment]
Now this is rare (by skipping some heavy tests), I remove the milestone

**Comment by hajimehoshi** [comment]
#2294
