### ISSUE TITLE
internal/restorable: WritePixels for a partial region after DrawTriangles crashes on 2.4 branch on Android

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2346]
```diff
diff --git a/internal/restorable/images_test.go b/internal/restorable/images_test.go
index 5ba9880d1..52f69819a 100644
--- a/internal/restorable/images_test.go
+++ b/internal/restorable/images_test.go
@@ -1078,3 +1078,22 @@ func TestOverlappedPixels(t *testing.T) {
                }
        }
 }
+
+func TestPartialWrite(t *testing.T) {
+       const w, h = 16, 16
+       dst := restorable.NewImage(w, h, restorable.ImageTypeRegular)
+       src := restorable.NewImage(w, h, restorable.ImageTypeRegular)
+
+       vs := quadVertices(src, 1, 1, 0, 0)
+       is := graphics.QuadIndices()
+       dr := graphicsdriver.Region{
+               X:      0,
+               Y:      0,
+               Width:  w,
+               Height: h,
+       }
+       dst.DrawTriangles([graphics.ShaderImageCount]*restorable.Image{src}, [graphics.ShaderImageCount - 1][2]float32{}, vs, is, affine.ColorMIdentity{}, graphicsdriver.CompositeModeCopy, graphicsdriver.FilterNearest, graphicsdriver.AddressUnsafe, dr, graphicsdriver.Region{}, nil, nil, false)
+
+       pix := make([]byte, 4*(w/2)*(h/2))
+       dst.WritePixels(pix, 0, 0, w/2, h/2)
+}
```

```
$ go test ./internal/restorable/
--- FAIL: TestPartialWrite (0.00s)
panic: restorable: WritePixels for a part after DrawTriangles is forbidden [recovered]
        panic: restorable: WritePixels for a part after DrawTriangles is forbidden

goroutine 82 [running]:
testing.tRunner.func1.2({0x42185c0, 0x42abf40})
        /usr/local/go/src/testing/testing.go:1396 +0x24e
testing.tRunner.func1()
        /usr/local/go/src/testing/testing.go:1399 +0x39f
panic({0x42185c0, 0x42abf40})
        /usr/local/go/src/runtime/panic.go:884 +0x212
github.com/hajimehoshi/ebiten/v2/internal/restorable.(*Image).WritePixels(0xc000416370, {0xc000010900, 0x100, 0x100}, 0x0, 0x0, 0x8, 0x8)
        /Users/hajimehoshi/ebiten/internal/restorable/image.go:325 +0x6fd
github.com/hajimehoshi/ebiten/v2/internal/restorable_test.TestPartialWrite(0x0?)
        /Users/hajimehoshi/ebiten/internal/restorable/images_test.go:1098 +0x139
testing.tRunner(0xc0005b0820, 0x4271400)
        /usr/local/go/src/testing/testing.go:1446 +0x10b
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:1493 +0x35f
FAIL    github.com/hajimehoshi/ebiten/v2/internal/restorable    1.065s
FAIL
```

**Comment by hajimehoshi** [comment]
On the main branch, 243c224003e016646444d08c765e0646471637ab already fixed the issue.
