### ISSUE TITLE
examples/windowsize: crash when entering fullscreen on macOS

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2416]
### Ebitengine Version

66a3659ec2ab71aa7a14f82ad0224da023df400c

### Operating System

- [ ] Windows
- [X] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

go1.19.2 darwin/amd64

### What steps will reproduce the problem?

Press F on examples/windowsize

### What is the expected result?

Fullscreen

### What happens instead?

```
$ go run -tags=example ./examples/windowsize/
Device scale factor: 2.00
Screen size in fullscreen: 1680, 1050
panic: reflect.Value.Call: call of nil function

goroutine 1 [running, locked to thread]:
reflect.Value.call({0x127f1a0?, 0x0?, 0x2100108?}, {0x12c242a, 0x4}, {0xc0000d61e0, 0x3, 0x60000260c300?})
        /usr/local/go/src/reflect/value.go:406 +0x1bab
reflect.Value.Call({0x127f1a0?, 0x0?, 0x7ff8445d0810?}, {0xc0000d61e0?, 0x7ff845de5a88?, 0x7ff845de5a88?})
        /usr/local/go/src/reflect/value.go:368 +0xbc
github.com/ebitengine/purego.callbackWrap(0x7ff7bfefd9c0)
        /Users/hajimehoshi/go/pkg/mod/github.com/ebitengine/purego@v0.2.0-alpha.0.20221023182100-d863f555d77d/syscall_darwin.go:125 +0x259
github.com/ebitengine/purego.callbackWrapPicker(0xaa5a25ab369c00ad?, 0x1003fc5?)
        /Users/hajimehoshi/go/pkg/mod/github.com/ebitengine/purego@v0.2.0-alpha.0.20221023182100-d863f555d77d/syscall_darwin.go:108 +0x1c
github.com/ebitengine/purego.syscall_syscall9X(0x7ff802e7d400, 0x600000010820, 0x7ff81d49903f, 0x600000225d80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/hajimehoshi/go/pkg/mod/github.com/ebitengine/purego@v0.2.0-alpha.0.20221023182100-d863f555d77d/syscall_darwin.go:20 +0x165
github.com/ebitengine/purego.SyscallN(0x7ff802e7d400?, {0xc000536e40?, 0x1341480?, 0xc0000d6140?})
        /Users/hajimehoshi/go/pkg/mod/github.com/ebitengine/purego@v0.2.0-alpha.0.20221023182100-d863f555d77d/syscall.go:37 +0xdc
github.com/ebitengine/purego.RegisterFunc.func1({0xc0000d6140?, 0x3?, 0x8?})
        /Users/hajimehoshi/go/pkg/mod/github.com/ebitengine/purego@v0.2.0-alpha.0.20221023182100-d863f555d77d/func_darwin.go:113 +0x24d
github.com/ebitengine/purego/objc.ID.Send(...)
        /Users/hajimehoshi/go/pkg/mod/github.com/ebitengine/purego@v0.2.0-alpha.0.20221023182100-d863f555d77d/objc/objc_runtime_darwin.go:63
github.com/hajimehoshi/ebiten/v2/internal/ui.init.4.func8(0x0?, 0x0?, 0x0?)
        /Users/hajimehoshi/ebiten/internal/ui/ui_glfw_darwin.go:84 +0x9d
reflect.Value.call({0x1277080?, 0xc000016480?, 0x2100108?}, {0x12c242a, 0x4}, {0xc0000d60f0, 0x3, 0x1004394?})
        /usr/local/go/src/reflect/value.go:584 +0x8c5
reflect.Value.Call({0x1277080?, 0xc000016480?, 0xc00052d118?}, {0xc0000d60f0?, 0x106a117?, 0x127db40?})
        /usr/local/go/src/reflect/value.go:368 +0xbc
github.com/ebitengine/purego.callbackWrap(0x7ff7bfefdb70)
        /Users/hajimehoshi/go/pkg/mod/github.com/ebitengine/purego@v0.2.0-alpha.0.20221023182100-d863f555d77d/syscall_darwin.go:125 +0x259
github.com/ebitengine/purego.callbackWrapPicker(0x1004d86?, 0xc0000061a0?)
        /Users/hajimehoshi/go/pkg/mod/github.com/ebitengine/purego@v0.2.0-alpha.0.20221023182100-d863f555d77d/syscall_darwin.go:108 +0x1c
github.com/ebitengine/purego.syscall_syscall9X(0x7ff802e7d400, 0xa10dd50, 0x7ff81d490c91, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/hajimehoshi/go/pkg/mod/github.com/ebitengine/purego@v0.2.0-alpha.0.20221023182100-d863f555d77d/syscall_darwin.go:20 +0x165
github.com/ebitengine/purego.SyscallN(0x7ff802e7d400?, {0xc000536e10?, 0xc00052d4e8?, 0xc0000bbe50?})
        /Users/hajimehoshi/go/pkg/mod/github.com/ebitengine/purego@v0.2.0-alpha.0.20221023182100-d863f555d77d/syscall.go:37 +0xdc
github.com/ebitengine/purego.RegisterFunc.func1({0xc0000bbe50?, 0x3?, 0x8?})
        /Users/hajimehoshi/go/pkg/mod/github.com/ebitengine/purego@v0.2.0-alpha.0.20221023182100-d863f555d77d/func_darwin.go:113 +0x24d
github.com/ebitengine/purego/objc.ID.Send(...)
        /Users/hajimehoshi/go/pkg/mod/github.com/ebitengine/purego@v0.2.0-alpha.0.20221023182100-d863f555d77d/objc/objc_runtime_darwin.go:63
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).setNativeFullscreen(0x15cbc00, 0x1)
        /Users/hajimehoshi/ebiten/internal/ui/ui_glfw_darwin.go:287 +0x1b1
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).setFullscreen(0x15cbc00, 0x1)
        /Users/hajimehoshi/ebiten/internal/ui/ui_glfw.go:1298 +0xa5
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).SetFullscreen.func1()
        /Users/hajimehoshi/ebiten/internal/ui/ui_glfw.go:562 +0x47
github.com/hajimehoshi/ebiten/v2/internal/thread.(*OSThread).Loop.func1(0xc00052dd78?, 0xc00052dd68?)
        /Users/hajimehoshi/ebiten/internal/thread/thread.go:54 +0x53
github.com/hajimehoshi/ebiten/v2/internal/thread.(*OSThread).Loop(0xc0000120c0)
        /Users/hajimehoshi/ebiten/internal/thread/thread.go:55 +0x2e
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).Run(0x15cbc00, {0x133e8e8?, 0xc0000120a8})
        /Users/hajimehoshi/ebiten/internal/ui/run_notsinglethread.go:53 +0x231
github.com/hajimehoshi/ebiten/v2.RunGame({0x133e5c0?, 0xc0000240e0})
        /Users/hajimehoshi/ebiten/run.go:212 +0x12d
main.main()
        /Users/hajimehoshi/ebiten/examples/windowsize/main.go:455 +0x5ae
exit status 2
```

**Comment by hajimehoshi** [comment]
Oh, I tested it on an experimental branch.
