### ISSUE TITLE
internal/graphicsdriver/opengl/gl: crash on Windows with OpenGL

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2452]
### Ebitengine Version

b536b821094d37aa85a7f17f70a216cbab0dca94

### Operating System

- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

go version go1.19.3 windows/amd64

### What steps will reproduce the problem?

```ps
$env:EBITEN_GRAPHICS_LIBRARY = "opengl"
go run ./examples/blocks
```

### What is the expected result?

No crash

### What happens instead?

```
panic: gl: wglGetProcAddress failed: The handle is invalid.

goroutine 1 [running, locked to thread]:
github.com/hajimehoshi/ebiten/v2/internal/graphicsdriver/opengl/gl.getProcAddress({0x9ee457, 0xf})
        //Mac/Home/ebiten/internal/graphicsdriver/opengl/gl/procaddr_windows.go:28 +0x1ed
github.com/hajimehoshi/ebiten/v2/internal/graphicsdriver/opengl/gl.(*defaultContext).init(0xc000164000)
        //Mac/Home/ebiten/internal/graphicsdriver/opengl/gl/default_purego.go:444 +0x2e
github.com/hajimehoshi/ebiten/v2/internal/graphicsdriver/opengl/gl.NewDefaultContext()
        //Mac/Home/ebiten/internal/graphicsdriver/opengl/gl/default_purego.go:101 +0x2f
github.com/hajimehoshi/ebiten/v2/internal/graphicsdriver/opengl.NewGraphics()
        //Mac/Home/ebiten/internal/graphicsdriver/opengl/graphics_default.go:34 +0x1d
github.com/hajimehoshi/ebiten/v2/internal/ui.(*graphicsDriverCreatorImpl).newOpenGL(0x9f24c2)
        //Mac/Home/ebiten/internal/ui/ui_glfw_windows.go:50 +0x17
        //Mac/Home/ebiten/internal/ui/graphics.go:52 +0x25c
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).init(0xc18a40)
        //Mac/Home/ebiten/internal/ui/ui_glfw.go:899 +0xb0
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).Run.func1.1()
        //Mac/Home/ebiten/internal/ui/run_notsinglethread.go:39 +0x26
github.com/hajimehoshi/ebiten/v2/internal/thread.(*OSThread).Loop.func1(0xc00017fe28?, 0xc00017fe18?)
        //Mac/Home/ebiten/internal/thread/thread.go:54 +0x53
github.com/hajimehoshi/ebiten/v2/internal/thread.(*OSThread).Loop(0xc0000086d8)
        //Mac/Home/ebiten/internal/thread/thread.go:55 +0x2e
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).Run(0xc18a40, {0xa63850?, 0xc0001d61c0})
        //Mac/Home/ebiten/internal/ui/run_notsinglethread.go:52 +0x231
github.com/hajimehoshi/ebiten/v2.RunGame({0xa622a0, 0xc0001d6150})
        //Mac/Home/ebiten/run.go:233 +0x9d
main.main()
        //Mac/Home/ebiten/examples/blocks/main.go:44 +0x168
exit status 2
```

**Comment by hajimehoshi** [comment]
```
c4abaa32f5363dd6355897b785c6dcad217f5939 is the first bad commit
commit c4abaa32f5363dd6355897b785c6dcad217f5939
Author: Hajime Hoshi <hajimehoshi@gmail.com>
Date:   Sun Nov 13 04:13:15 2022 +0900

    internal/graphicsdriver/opengl: initialize gl at init()
    
    This changes context_gl.go a little closer to context_gles.go.
    
    Updates #2451

 internal/graphicsdriver/opengl/context_gl.go    | 9 ---------
 internal/graphicsdriver/opengl/graphics.go      | 4 +++-
 internal/graphicsdriver/opengl/graphics_gl.go   | 8 ++++++--
 internal/graphicsdriver/opengl/graphics_gles.go | 3 ++-
 internal/graphicsdriver/opengl/graphics_js.go   | 3 ++-
 5 files changed, 13 insertions(+), 14 deletions(-)
```
