### ISSUE TITLE
internal/glfw: rare crash at initialization on macOS

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2474]
### Ebitengine Version

v2.5.0-alpha.7

### Operating System

- [ ] Windows
- [X] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

v2.5.0-alpha.7

### What steps will reproduce the problem?

Just launch an application.

### What is the expected result?

```
panic: NotInitialized: The GLFW library is not initialized

goroutine 1 [running, locked to thread]:
github.com/go-gl/glfw/v3.3/glfw.acceptError({0x0, 0x0, 0xc00005ef00?})
	/Users/daigosato/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20221017161538-93cebf72946b/error.go:174 +0x1d9
github.com/go-gl/glfw/v3.3/glfw.panicError(...)
	/Users/daigosato/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20221017161538-93cebf72946b/error.go:185
github.com/go-gl/glfw/v3.3/glfw.(*Window).GetMonitor(0x1000067f1?)
	/Users/daigosato/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20221017161538-93cebf72946b/window.go:662 +0x2b
github.com/hajimehoshi/ebiten/v2/internal/glfw.(*Window).GetMonitor(...)
	/Users/daigosato/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.0-alpha.7/internal/glfw/glfw_notwindows.go:128
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).isFullscreen(0x100d62540)
	/Users/daigosato/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.0-alpha.7/internal/ui/ui_glfw.go:537 +0x33
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).loop.func3.1()
	/Users/daigosato/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.0-alpha.7/internal/ui/ui_glfw.go:1156 +0x5c
github.com/hajimehoshi/ebiten/v2/internal/thread.(*OSThread).Loop.func1(0xc01b217e08?, 0xc01b217df8?)
	/Users/daigosato/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.0-alpha.7/internal/thread/thread.go:54 +0x53
github.com/hajimehoshi/ebiten/v2/internal/thread.(*OSThread).Loop(0xc000123998)
	/Users/daigosato/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.0-alpha.7/internal/thread/thread.go:55 +0x2e
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).Run(0x100d62540, {0x10082c668?, 0xc000240bd0})
	/Users/daigosato/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.0-alpha.7/internal/ui/run_notsinglethread.go:52 +0x231
github.com/hajimehoshi/ebiten/v2.RunGame({0x1008293a8, 0xc000001680})
	/Users/daigosato/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.0-alpha.7/run.go:233 +0x9d
main.main()
	/Users/daigosato/Development/odencat/rpgsnack/rpgsnack-runtime/main.go:127 +0x1d9
```

### What happens instead?

No crash

### Anything else you feel useful to add?

The issue is very rare and there is no stable way to reproduce this.

**Comment by TotallyGamerJet** [comment]
Which go Version are u using? And the expected is no crash right?

**Comment by hajimehoshi** [comment]
Go 1.19.2. Yeah we expect no crash. I have tested your gotip branch:

```
$ go version
go version go1.19.2 darwin/amd64
```

```
$ go test ./objc
fatal error: schedule: in cgo

runtime stack:
runtime.throw({0x1135714?, 0x1222c40?})
	/usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0x7ff7bfeff500 sp=0x7ff7bfeff4d0 pc=0x1035c7d
runtime.schedule()
	/usr/local/go/src/runtime/proc.go:3192 +0x23f fp=0x7ff7bfeff538 sp=0x7ff7bfeff500 pc=0x103ec7f
runtime.park_m(0xc0000061a0?)
	/usr/local/go/src/runtime/proc.go:3355 +0x14d fp=0x7ff7bfeff568 sp=0x7ff7bfeff538 pc=0x103f02d
runtime.mcall()
	/usr/local/go/src/runtime/asm_amd64.s:448 +0x43 fp=0x7ff7bfeff578 sp=0x7ff7bfeff568 pc=0x1064603

goroutine 1 [chan receive]:
runtime.gopark(0x1115860?, 0xc000207a50?, 0xe0?, 0x87?, 0xc000207a88?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc000207a28 sp=0xc000207a08 pc=0x1038856
runtime.chanrecv(0xc00008e780, 0xc000207b60, 0x1)
	/usr/local/go/src/runtime/chan.go:583 +0x49b fp=0xc000207ab8 sp=0xc000207a28 pc=0x1006e9b
runtime.chanrecv1(0xc0000a2240?, 0x0?)
	/usr/local/go/src/runtime/chan.go:442 +0x18 fp=0xc000207ae0 sp=0xc000207ab8 pc=0x10069d8
testing.runExample.func2()
	/usr/local/go/src/testing/run_example.go:56 +0xce fp=0xc000207b80 sp=0xc000207ae0 pc=0x10bb60e
testing.runExample({{0x11378a7, 0x18}, 0x113e8b0, {0x1134b85, 0xd}, 0x0})
	/usr/local/go/src/testing/run_example.go:65 +0x2a4 fp=0xc000207c68 sp=0xc000207b80 pc=0x10bb4c4
testing.runExamples(0xc000207e58, {0x121e920?, 0x4, 0x0?})
	/usr/local/go/src/testing/example.go:44 +0x186 fp=0xc000207d08 sp=0xc000207c68 pc=0x10b7246
testing.(*M).Run(0xc0000c20a0)
	/usr/local/go/src/testing/testing.go:1728 +0x689 fp=0xc000207f00 sp=0xc000207d08 pc=0x10c07a9
main.main()
	_testmain.go:55 +0x1aa fp=0xc000207f80 sp=0xc000207f00 pc=0x1102baa
runtime.main()
	/usr/local/go/src/runtime/proc.go:250 +0x212 fp=0xc000207fe0 sp=0xc000207f80 pc=0x1038492
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000207fe8 sp=0xc000207fe0 pc=0x1066861

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc00004cfb0 sp=0xc00004cf90 pc=0x1038856
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:369
runtime.forcegchelper()
	/usr/local/go/src/runtime/proc.go:302 +0xad fp=0xc00004cfe0 sp=0xc00004cfb0 pc=0x10386ed
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00004cfe8 sp=0xc00004cfe0 pc=0x1066861
created by runtime.init.6
	/usr/local/go/src/runtime/proc.go:290 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc00004d790 sp=0xc00004d770 pc=0x1038856
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:369
runtime.bgsweep(0x0?)
	/usr/local/go/src/runtime/mgcsweep.go:278 +0x8e fp=0xc00004d7c8 sp=0xc00004d790 pc=0x1023fce
runtime.gcenable.func1()
	/usr/local/go/src/runtime/mgc.go:178 +0x26 fp=0xc00004d7e0 sp=0xc00004d7c8 pc=0x1018c86
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00004d7e8 sp=0xc00004d7e0 pc=0x1066861
created by runtime.gcenable
	/usr/local/go/src/runtime/mgc.go:178 +0x6b

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc000028070?, 0x1163110?, 0x1?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc00004df70 sp=0xc00004df50 pc=0x1038856
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:369
runtime.(*scavengerState).park(0x1222ac0)
	/usr/local/go/src/runtime/mgcscavenge.go:389 +0x53 fp=0xc00004dfa0 sp=0xc00004df70 pc=0x1022073
runtime.bgscavenge(0x0?)
	/usr/local/go/src/runtime/mgcscavenge.go:617 +0x45 fp=0xc00004dfc8 sp=0xc00004dfa0 pc=0x1022645
runtime.gcenable.func2()
	/usr/local/go/src/runtime/mgc.go:179 +0x26 fp=0xc00004dfe0 sp=0xc00004dfc8 pc=0x1018c26
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00004dfe8 sp=0xc00004dfe0 pc=0x1066861
created by runtime.gcenable
	/usr/local/go/src/runtime/mgc.go:179 +0xaa

goroutine 18 [finalizer wait]:
runtime.gopark(0x12231e0?, 0xc0000824e0?, 0x0?, 0x0?, 0xc00004c770?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc00004c628 sp=0xc00004c608 pc=0x1038856
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:369
runtime.runfinq()
	/usr/local/go/src/runtime/mfinal.go:180 +0x10f fp=0xc00004c7e0 sp=0xc00004c628 pc=0x1017d8f
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00004c7e8 sp=0xc00004c7e0 pc=0x1066861
created by runtime.createfing
	/usr/local/go/src/runtime/mfinal.go:157 +0x45

goroutine 19 [runnable]:
runtime.mallocgc(0x10?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/malloc.go:842 +0x8d1 fp=0xc000048618 sp=0xc000048610 pc=0x100d931
runtime.growslice(0xc000182000?, {0x0?, 0x8000?, 0xd?}, 0x104b912?)
	/usr/local/go/src/runtime/slice.go:284 +0x4ac fp=0xc000048680 sp=0xc000048618 pc=0x104becc
strings.(*Builder).Write(0xc000180000, {0xc000182000, 0xd, 0x1334a68?})
	/usr/local/go/src/strings/builder.go:90 +0x85 fp=0xc0000486d0 sp=0xc000048680 pc=0x10aa925
io.copyBuffer({0x1163dc0, 0xc000180000}, {0x1163d00, 0xc0000a00d0}, {0x0, 0x0, 0x0})
	/usr/local/go/src/io/io.go:429 +0x204 fp=0xc000048750 sp=0xc0000486d0 pc=0x10800e4
io.Copy(...)
	/usr/local/go/src/io/io.go:386
testing.runExample.func1()
	/usr/local/go/src/testing/run_example.go:37 +0x76 fp=0xc0000487e0 sp=0xc000048750 pc=0x10bb6f6
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0000487e8 sp=0xc0000487e0 pc=0x1066861
created by testing.runExample
	/usr/local/go/src/testing/run_example.go:35 +0x1c5
FAIL	github.com/ebitengine/purego/objc	0.122s
FAIL

```

**Comment by TotallyGamerJet** [comment]
Yeah I wouldn't really expect gotip branch to work since it doesn't play nicely with goroutines. There must be a reason it thinks that we are in Cgo when we aren't yet. I need to look into this further.

Fortunately, ebitengine won't flat at break in Go 1.20. Only -race when CGO_ENABLED=0 so a temporary fix is to just have them enable Cgo when using race which is already required. Plus ebitengine uses Cgo for glfw so it's okay for now.

**Comment by TotallyGamerJet** [comment]
I came across this [golang/go#57263](https://github.com/golang/go/issues/57263) issue which may relate.
