### ISSUE TITLE
internal/processtest: sometimes tests time out

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2571]
### Ebitengine Version

05f86b3974f0df168b7f0c85c3cec9c9f7f7cbb3

### Operating System

- [ ] Windows
- [ ] macOS
- [X] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

go 1.18 (but can be reproduced with any version probably)

### What steps will reproduce the problem?

Run tests on GitHub CI.

### What is the expected result?

Tests pass

### What happens instead?

```
panic: test timed out after 10m0s

goroutine 23 [running]:
testing.(*M).startAlarm.func1()
	/opt/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:2029 +0x8e
created by time.goFunc
	/opt/hostedtoolcache/go/1.18.10/x64/src/time/sleep.go:176 +0x32

goroutine 1 [chan receive]:
testing.(*T).Run(0xc00009aea0, {0x531064?, 0x4be2e5?}, 0x53a828)
	/opt/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:1487 +0x37a
testing.runTests.func1(0xc000090390?)
	/opt/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:1839 +0x6e
testing.tRunner(0xc00009aea0, 0xc000086cd8)
	/opt/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:1439 +0x102
testing.runTests(0xc0000ae140?, {0x60dd60, 0x1, 0x1}, {0x2?, 0x40?, 0x616b40?})
	/opt/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:1837 +0x457
testing.(*M).Run(0xc0000ae140)
	/opt/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:1719 +0x5d9
main.main()
	_testmain.go:47 +0x1aa

goroutine 18 [chan receive]:
testing.(*T).Run(0xc00009b040, {0xc0000ac140?, 0x3a?}, 0xc000090540)
	/opt/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:1487 +0x37a
github.com/hajimehoshi/ebiten/v2/internal/processtest_test.TestPrograms(0xc00009b040)
	/home/runner/work/ebiten/ebiten/internal/processtest/processtest_test.go:45 +0x186
testing.tRunner(0xc00009b040, 0x53a828)
	/opt/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:1439 +0x102
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:1486 +0x35f

goroutine 21 [syscall]:
syscall.Syscall6(0xf7, 0x1, 0x7b81, 0xc000088d28, 0x1000004, 0x0, 0x0)
	/opt/hostedtoolcache/go/1.18.10/x64/src/syscall/asm_linux_amd64.s:43 +0x5
os.(*Process).blockUntilWaitable(0xc0000b61e0)
	/opt/hostedtoolcache/go/1.18.10/x64/src/os/wait_waitid.go:32 +0x9c
os.(*Process).wait(0xc0000b61e0)
	/opt/hostedtoolcache/go/1.18.10/x64/src/os/exec_unix.go:22 +0x28
os.(*Process).Wait(...)
	/opt/hostedtoolcache/go/1.18.10/x64/src/os/exec.go:132
os/exec.(*Cmd).Wait(0xc0000d8160)
	/opt/hostedtoolcache/go/1.18.10/x64/src/os/exec/exec.go:514 +0x54
os/exec.(*Cmd).Run(0x52f6ec?)
	/opt/hostedtoolcache/go/1.18.10/x64/src/os/exec/exec.go:341 +0x39
github.com/hajimehoshi/ebiten/v2/internal/processtest_test.TestPrograms.func1(0xc00009ba00)
	/home/runner/work/ebiten/ebiten/internal/processtest/processtest_test.go:49 +0x113
testing.tRunner(0xc00009ba00, 0xc000090540)
	/opt/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:1439 +0x102
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:1486 +0x35f

goroutine 22 [IO wait]:
internal/poll.runtime_pollWait(0x7f30e6915038, 0x72)
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0xc0000984e0?, 0xc0000e474a?, 0x1)
	/opt/hostedtoolcache/go/1.18.10/x64/src/internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.18.10/x64/src/internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Read(0xc0000984e0, {0xc0000e474a, 0x4b6, 0x4b6})
	/opt/hostedtoolcache/go/1.18.10/x64/src/internal/poll/fd_unix.go:167 +0x25a
os.(*File).read(...)
	/opt/hostedtoolcache/go/1.18.10/x64/src/os/file_posix.go:31
os.(*File).Read(0xc000096068, {0xc0000e474a?, 0x6172e0?, 0xc00003aea0?})
	/opt/hostedtoolcache/go/1.18.10/x64/src/os/file.go:119 +0x5e
bytes.(*Buffer).ReadFrom(0xc000090600, {0x55d640, 0xc000096068})
	/opt/hostedtoolcache/go/1.18.10/x64/src/bytes/buffer.go:204 +0x98
io.copyBuffer({0x55d520, 0xc000090600}, {0x55d640, 0xc000096068}, {0x0, 0x0, 0x0})
	/opt/hostedtoolcache/go/1.18.10/x64/src/io/io.go:412 +0x14b
io.Copy(...)
	/opt/hostedtoolcache/go/1.18.10/x64/src/io/io.go:385
os/exec.(*Cmd).writerDescriptor.func1()
	/opt/hostedtoolcache/go/1.18.10/x64/src/os/exec/exec.go:311 +0x3a
os/exec.(*Cmd).Start.func1(0xc000090540?)
	/opt/hostedtoolcache/go/1.18.10/x64/src/os/exec/exec.go:448 +0x25
created by os/exec.(*Cmd).Start
	/opt/hostedtoolcache/go/1.18.10/x64/src/os/exec/exec.go:447 +0x785
FAIL	github.com/hajimehoshi/ebiten/v2/internal/processtest	600.065s
XGB: conn.go:47: Could not get authority info: open /home/runner/.Xauthority: no such file or directory
XGB: conn.go:48: Trying connection without authority info...
XGB: conn.go:47: Could not get authority info: open /home/runner/.Xauthority: no such file or directory
XGB: conn.go:48: Trying connection without authority info...
-test.shuffle 16[762](https://github.com/hajimehoshi/ebiten/actions/runs/4157637658/jobs/7192279229#step:16:763)26592822600114
```

e.g. https://github.com/hajimehoshi/ebiten/actions/runs/4157637658/jobs/7192279229

**Comment by hajimehoshi** [comment]
https://github.com/hajimehoshi/ebiten/actions/runs/4180959132/jobs/7242421909

**Comment by hajimehoshi** [comment]
```
=== RUN   TestPrograms/issue1753.go
=== RUN   TestPrograms/issue2079.go
```

Does this order matter?

**Comment by hajimehoshi** [comment]
The sub tests order doesn't change with a given seed, so this freezing is a flaky behavior, unfortunately.

**Comment by hajimehoshi** [comment]
https://github.com/hajimehoshi/ebiten/actions/runs/4210559213/jobs/7308329746

```
=== RUN   TestPrograms
=== RUN   TestPrograms/issue1753.go
=== RUN   TestPrograms/issue2079.go
=== RUN   TestPrograms/issue2089.go
=== RUN   TestPrograms/issue2129.go
=== RUN   TestPrograms/issue2138.go
=== RUN   TestPrograms/issue2154_1.go
panic: test timed out after 10m0s

goroutine 25 [running]:
testing.(*M).startAlarm.func1()
	/opt/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:2029 +0x8e
created by time.goFunc
	/opt/hostedtoolcache/go/1.18.10/x64/src/time/sleep.go:176 +0x32

goroutine 1 [chan receive]:
testing.(*T).Run(0xc000083040, {0x533e9c?, 0x4c0625?}, 0x53d710)
	/opt/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:1487 +0x37a
testing.runTests.func1(0xc0000a6390?)
	/opt/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:1839 +0x6e
testing.tRunner(0xc000083040, 0xc00009ccd8)
	/opt/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:1439 +0x102
testing.runTests(0xc0000c01e0?, {0x613d70, 0x1, 0x1}, {0x2?, 0x40?, 0x61cb60?})
	/opt/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:1837 +0x457
testing.(*M).Run(0xc0000c01e0)
	/opt/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:1719 +0x5d9
main.main()
	_testmain.go:47 +0x1aa

goroutine 18 [chan receive]:
testing.(*T).Run(0xc0000831e0, {0xc0000be150?, 0x3a?}, 0xc00006a390)
	/opt/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:1487 +0x37a
github.com/hajimehoshi/ebiten/v2/internal/processtest_test.TestPrograms(0xc0000831e0)
	/home/runner/work/ebiten/ebiten/internal/processtest/processtest_test.go:47 +0x186
testing.tRunner(0xc0000831e0, 0x53d710)
	/opt/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:1439 +0x102
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:1486 +0x35f

goroutine 14 [chan receive]:
os/exec.(*Cmd).Wait(0xc0000[704](https://github.com/hajimehoshi/ebiten/actions/runs/4210559213/jobs/7308329746#step:16:705)20)
	/opt/hostedtoolcache/go/1.18.10/x64/src/os/exec/exec.go:522 +0x188
os/exec.(*Cmd).Run(0x561228?)
	/opt/hostedtoolcache/go/1.18.10/x64/src/os/exec/exec.go:341 +0x39
github.com/hajimehoshi/ebiten/v2/internal/processtest_test.TestPrograms.func1(0xc000003860)
	/home/runner/work/ebiten/ebiten/internal/processtest/processtest_test.go:54 +0x1a5
testing.tRunner(0xc000003860, 0xc00006a390)
	/opt/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:1439 +0x102
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:1486 +0x35f

goroutine 15 [IO wait]:
internal/poll.runtime_pollWait(0x7f37f3444068, 0x72)
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0xc00005e900?, 0xc00010134a?, 0x1)
	/opt/hostedtoolcache/go/1.18.10/x64/src/internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.18.10/x64/src/internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Read(0xc00005e900, {0xc00010134a, 0x4b6, 0x4b6})
	/opt/hostedtoolcache/go/1.18.10/x64/src/internal/poll/fd_unix.go:167 +0x25a
os.(*File).read(...)
	/opt/hostedtoolcache/go/1.18.10/x64/src/os/file_posix.go:31
os.(*File).Read(0xc00000e0a0, {0xc00010134a?, 0x7f37f3444068?, 0xc00003a6a0?})
	/opt/hostedtoolcache/go/1.18.10/x64/src/os/file.go:119 +0x5e
bytes.(*Buffer).ReadFrom(0xc00006a450, {0x560a80, 0xc00000e0a0})
	/opt/hostedtoolcache/go/1.18.10/x64/src/bytes/buffer.go:204 +0x98
io.copyBuffer({0x560960, 0xc00006a450}, {0x560a80, 0xc00000e0a0}, {0x0, 0x0, 0x0})
	/opt/hostedtoolcache/go/1.18.10/x64/src/io/io.go:412 +0x14b
io.Copy(...)
	/opt/hostedtoolcache/go/1.18.10/x64/src/io/io.go:385
os/exec.(*Cmd).writerDescriptor.func1()
	/opt/hostedtoolcache/go/1.18.10/x64/src/os/exec/exec.go:311 +0x3a
os/exec.(*Cmd).Start.func1(0xc0000a6540?)
	/opt/hostedtoolcache/go/1.18.10/x64/src/os/exec/exec.go:448 +0x25
created by os/exec.(*Cmd).Start
	/opt/hostedtoolcache/go/1.18.10/x64/src/os/exec/exec.go:447 +0x785
FAIL	github.com/hajimehoshi/ebiten/v2/internal/processtest	600.092s
```

**Comment by hajimehoshi** [comment]
This is a very serious issue now. I think I re-introduce a file lock for tests to reduce the number of processes.

**Comment by hajimehoshi** [comment]
I think this was fixed without a file lock.

**Comment by hajimehoshi** [comment]
This is still happening...

https://github.com/hajimehoshi/ebiten/actions/runs/4262671344/jobs/7418446854

**Comment by hajimehoshi** [comment]
I hope this was fixed by `-p=1`
