### ISSUE TITLE
internal/graphicsdriver/directx: OOM on 32bit machine

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2582]
### Ebitengine Version

a0a80bbc1f4fbd17c205de9e84c1f80d43b2de6c

### Operating System

- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

Go 1.18 (but probably this doesn't matter)

### What steps will reproduce the problem?

Run `go test .`

### What is the expected result?

No crash

### What happens instead?

https://github.com/hajimehoshi/ebiten/actions/runs/4269925979/jobs/7433538622

```
panic: directx: ID3D12Device::CreateCommittedResource failed: HANDLE(2147942414) [recovered]
	panic: directx: ID3D12Device::CreateCommittedResource failed: HANDLE(2147942414)

goroutine 90 [running]:
testing.tRunner.func1.2({0xe7cd80, 0x11c04060})
	C:/hostedtoolcache/windows/go/1.18.10/x64/src/testing/testing.go:1389 +0x2ab
testing.tRunner.func1()
	C:/hostedtoolcache/windows/go/1.18.10/x64/src/testing/testing.go:1392 +0x41f
panic({0xe7cd80, 0x11c04060})
	C:/hostedtoolcache/windows/go/1.18.10/x64/src/runtime/panic.go:838 +0x1ba
github.com/hajimehoshi/ebiten/v2/internal/ui.(*Image).ReadPixels(0x11c3e2d0, {0x11d0bec0, 0x4, 0x4}, 0x0, 0x0, 0x1, 0x1)
	D:/a/ebiten/ebiten/internal/ui/image.go:167 +0x1a3
github.com/hajimehoshi/ebiten/v2.(*Image).at(0x11d36000, 0x0, 0x0)
	D:/a/ebiten/ebiten/image.go:904 +0xc2
github.com/hajimehoshi/ebiten/v2.(*Image).At(0x11d36000, 0x0, 0x0)
	D:/a/ebiten/ebiten/image.go:874 +0x31
github.com/hajimehoshi/ebiten/v2_test.TestImageBlendLighter(0x11caa3c0)
	D:/a/ebiten/ebiten/image_test.go:366 +0x20b
testing.tRunner(0x11caa3c0, 0xed7e94)
	C:/hostedtoolcache/windows/go/1.18.10/x64/src/testing/testing.go:1439 +0x[113](https://github.com/hajimehoshi/ebiten/actions/runs/4269925979/jobs/7433538622#step:19:114)
created by testing.(*T).Run
	C:/hostedtoolcache/windows/go/1.18.10/x64/src/testing/testing.go:1486 +0x374
FAIL	github.com/hajimehoshi/ebiten/v2	24.076s
```

### Anything else you feel useful to add?

Probably we don't have to keep pixel data when reading them with 32bit desktops.

**Comment by hajimehoshi** [comment]
965fd4cac8e58f8e05ab1a98349ac8b9a3440a90

**Comment by hajimehoshi** [comment]
Apparently this was fixed.
