### ISSUE TITLE
internal/packing: double-free error

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2584]
### Ebitengine Version

5e4652c4f809549f699d450ce1f269a5783cd341

### Operating System

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

go version go1.20 darwin/amd64

### What steps will reproduce the problem?

Run this test

```go
func TestDoubleFree(t *testing.T) {
        p := packing.NewPage(32, 32, 1024)
        n0 := p.Alloc(18, 18)
        n1 := p.Alloc(28, 59)
        n2 := p.Alloc(18, 18)
        n3 := p.Alloc(18, 18)
        n4 := p.Alloc(8, 10)
        n5 := p.Alloc(322, 242)
        _ = n5
        p.Free(n0)
        p.Free(n2)
        p.Free(n1)
        p.Free(n3)
        p.Free(n4)

        n6 := p.Alloc(18, 18)
        n7 := p.Alloc(98, 98)
        n8 := p.Alloc(98, 98)
        n9 := p.Alloc(130, 130)
        n10 := p.Alloc(130, 130)
        n11 := p.Alloc(162, 162)
        n12 := p.Alloc(162, 162)
        p.Free(n11)
        p.Free(n9)
        p.Free(n7)
        p.Free(n12)
        p.Free(n10)
        p.Free(n8)
        p.Free(n6)
}
```

### What is the expected result?

The test passes.

### What happens instead?

The test fails:

```
--- FAIL: TestDoubleFree (0.00s)
panic: packing: both two children must not be nil at Free: double free happened? [recovered]
        panic: packing: both two children must not be nil at Free: double free happened?

goroutine 27 [running]:
testing.tRunner.func1.2({0x1109460, 0x1157df0})
        /usr/local/go/src/testing/testing.go:1526 +0x24e
testing.tRunner.func1()
        /usr/local/go/src/testing/testing.go:1529 +0x39f
panic({0x1109460, 0x1157df0})
        /usr/local/go/src/runtime/panic.go:884 +0x213
github.com/hajimehoshi/ebiten/v2/internal/packing.(*Page).Free(0xc000163340?, 0xc000163480?)
        /Users/hajimehoshi/ebiten/internal/packing/packing.go:232 +0x114
github.com/hajimehoshi/ebiten/v2/internal/packing.(*Page).Free(0xc000158460?, 0xc000163300)
        /Users/hajimehoshi/ebiten/internal/packing/packing.go:237 +0xed
github.com/hajimehoshi/ebiten/v2/internal/packing_test.TestDoubleFree(0xc0001196c0?)
        /Users/hajimehoshi/ebiten/internal/packing/packing_test.go:463 +0x225
testing.tRunner(0xc000119860, 0x11377a0)
        /usr/local/go/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:1629 +0x3ea
FAIL    github.com/hajimehoshi/ebiten/v2/internal/packing       0.165s
FAIL
```

### Anything else you feel useful to add?

This is a critical issue so I'll backport a fix to v2.4.

This issue was found by https://github.com/hajimehoshi/ebiten/actions/runs/4290194930/jobs/7473972191

**Comment by hajimehoshi** [comment]
Minimized test case:

```go
func TestDoubleFree(t *testing.T) {
        p := packing.NewPage(32, 32, 1024)
        n0 := p.Alloc(18, 18)
        n1 := p.Alloc(28, 59)
        n2 := p.Alloc(18, 18)
        n3 := p.Alloc(18, 18)
        n4 := p.Alloc(8, 10)
        n5 := p.Alloc(322, 242)
        _ = n5
        p.Free(n0)
        p.Free(n2)
        p.Free(n1)
        p.Free(n3)
        p.Free(n4)

        n6 := p.Alloc(18, 18)
        p.Free(n6)
}
```
