### ISSUE TITLE
internal/atlas: test failures on Linux / OpenGL ES

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2632]
### Ebitengine Version

db66e3b46af7ebb1e953cef2c08036f0f789a48c

### Operating System

- [ ] Windows
- [ ] macOS
- [X] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

Go 1.19

### What steps will reproduce the problem?

(TBD)

### What is the expected result?

The tests pass

### What happens instead?

```
-test.shuffle 1680957469405281867
=== RUN   TestDisposeImmediately
--- PASS: TestDisposeImmediately (0.00s)
=== RUN   TestReputOnSourceBackend
--- PASS: TestReputOnSourceBackend (0.03s)
=== RUN   TestLongImages
--- PASS: TestLongImages (0.01s)
=== RUN   TestEnsureIsolatedFromSourceBackend
--- PASS: TestEnsureIsolatedFromSourceBackend (0.09s)
=== RUN   TestSmallImages
--- PASS: TestSmallImages (0.00s)
=== RUN   TestImageWritePixelsModify
--- PASS: TestImageWritePixelsModify (0.01s)
=== RUN   TestImageIsNotReputOnSourceBackendWithoutUsingAsSource
--- PASS: TestImageIsNotReputOnSourceBackendWithoutUsingAsSource (0.00s)
=== RUN   TestExtendWithBigImage
--- PASS: TestExtendWithBigImage (0.01s)
=== RUN   TestMaxImageSizeJust
--- PASS: TestMaxImageSizeJust (0.13s)
=== RUN   TestDisposedAndReputOnSourceBackend
--- PASS: TestDisposedAndReputOnSourceBackend (0.01s)
=== RUN   TestImageDrawTwice
--- PASS: TestImageDrawTwice (0.05s)
=== RUN   TestMaxImageSize
--- PASS: TestMaxImageSize (0.08s)
=== RUN   TestPowerOf2
--- PASS: TestPowerOf2 (0.00s)
=== RUN   TestShaderFillTwice
--- PASS: TestShaderFillTwice (0.07s)
=== RUN   TestWritePixelsAfterDrawTriangles
--- FAIL: TestWritePixelsAfterDrawTriangles (0.00s)
panic: runtime error: slice bounds out of range [7:4] [recovered]
	panic: runtime error: slice bounds out of range [7:4]

goroutine 12 [running]:
testing.tRunner.func1.2({0x7baf20, 0xc000032888})
	/opt/hostedtoolcache/go/1.19.7/x64/src/testing/testing.go:1396 +0x24e
testing.tRunner.func1()
	/opt/hostedtoolcache/go/1.19.7/x64/src/testing/testing.go:1399 +0x39f
panic({0x7baf20, 0xc000032888})
	/opt/hostedtoolcache/go/1.19.7/x64/src/runtime/panic.go:884 +0x212
github.com/hajimehoshi/ebiten/v2/internal/restorable.(*Image).makeStale(0xc0000ba180, {{0xc00003f830?, 0xc00014c6c0?}, {0x769b40?, 0x7f9720?}})
	/home/runner/work/ebiten/ebiten/internal/restorable/image.go:252 +0x1dc
github.com/hajimehoshi/ebiten/v2/internal/restorable.(*Image).WritePixels(0xc0000ba180, {0xc012874048, 0x41010, 0x3ffffb8}, 0x5, 0x0, 0x102, 0x102)
	/home/runner/work/ebiten/ebiten/internal/restorable/image.go:301 +0x885
github.com/hajimehoshi/ebiten/v2/internal/atlas.(*Image).writePixels(0xc00014c6c0, {0xc000412000, 0x40000, 0x40000}, 0x0, 0x0, 0x7f4cc42a7108?, 0x100)
	/home/runner/work/ebiten/ebiten/internal/atlas/image.go:589 +0x566
github.com/hajimehoshi/ebiten/v2/internal/atlas.(*Image).WritePixels(0xf?, {0xc000412000?, 0x0?, 0x0?}, 0x51a240?, 0x9fd370?, 0xa86180?, 0xc000169728?)
	/home/runner/work/ebiten/ebiten/internal/atlas/image.go:517 +0x10e
github.com/hajimehoshi/ebiten/v2/internal/atlas_test.TestWritePixelsAfterDrawTriangles(0xc000182000)
	/home/runner/work/ebiten/ebiten/internal/atlas/image_test.go:405 +0x1e5
testing.tRunner(0xc000182000, 0x7f97d0)
	/opt/hostedtoolcache/go/1.19.7/x64/src/testing/testing.go:1446 +0x10b
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.19.7/x64/src/testing/testing.go:1493 +0x35f
FAIL	github.com/hajimehoshi/ebiten/v2/internal/atlas	0.711s
```

### Anything else you feel useful to add?

https://github.com/hajimehoshi/ebiten/actions/runs/4645077837/jobs/8220727213?pr=2631

**Comment by hajimehoshi** [comment]
Probalby this happens only on a PR #2631
