### ISSUE TITLE
Panic when compiling Kage shader (index out of range [0] with length 0).

### ISSUE THREAD

**Issue by kalexmills** [hajimehoshi/ebiten#2654]
### Ebitengine Version

2.5.3

### Operating System

- [ ] Windows
- [X] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

go version go1.20.3 darwin/arm64

### What steps will reproduce the problem?

Attempt to compile this (probably invalid) Kage shader:

```
package main

func snoise(v vec2) float {

	// Precompute values for skewed triangular grid
	var C = vec4(0.211324865405187,
		// (3.0-sqrt(3.0))/6.0
		0.366025403784439,
		// 0.5*(sqrt(3.0)-1.0)
		-0.577350269189626,
		// -1.0 + 2.0 * C.x
		0.024390243902439)
	// 1.0 / 41.0

	// First corner (x0)
	i := floor(v + dot(v, C.yy))
	x0 := v - i + dot(i, C.xx)

	// Other two corners (x1, x2)
	i1 := vec2(0.0)
	if x0.x > x0.y {
		i1 = vec2(1, 0)
	} else {
		i1 = vec2(0, 1)
	}
	x1 := x0.xy + C.xx - i1
	x2 := x0.xy + C.zz

	// Do some permutations to avoid
	// truncation effects in permutation
	i = mod289_v2(i)
	p := permute(
		permute(i.y+vec3(0.0, i1.y, 1.0)) + i.x + vec3(0.0, i1.x, 1.0))

	m := max(0.5-vec3(
		dot(x0, x0),
		dot(x1, x1),
		dot(x2, x2)), 0.0)

	m = m * m
	m = m * m

	// Gradients:
	//  41 pts uniformly over a line, mapped onto a diamond
	//  The ring size 17*17 = 289 is close to a multiple
	//      of 41 (41*7 = 287)

	x := 2.0*fract(p*C.www) - 1.0
	h := abs(x) - 0.5
	ox := floor(x + 0.5)
	a0 := x - ox

	// Normalise gradients implicitly by scaling m
	// Approximation of: m *= inversesqrt(a0*a0 + h*h);
	m *= 1.79284291400159 - 0.85373472095314*(a0*a0+h*h)

	// Compute final noise value at P
	g := vec3(0.0)
	g.x = a0.x*x0.x + h.x*x0.y
	g.yz = a0.yz*vec2(x1.x, x2.x) + h.yz*vec2(x1.y, x2.y)
	return 130.0 * dot(m, g)
}

func mod289_v3(x vec3) { return x - floor(x*(1.0/289.0))*289.0 }
func mod289_v2(x vec2) { return x - floor(x*(1.0/289.0))*289.0 }
func permute(x vec3)   { return mod289_v3(((x * 34.0) + 1.0) * x) }

```

### What is the expected result?

Attempting to compile the shader should not produce a panic in the compiler. Ideally, we'd see an error about whatever is wrong.

### What happens instead?

```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running, locked to thread]:
github.com/hajimehoshi/ebiten/v2/internal/shader.(*compileState).assign(0x140005a0d00, 0x140003036c0, {0x140001a6598, 0x6}, 0x102fb7920?, {0x14000020940, 0x1, 0x140001a6598?}, {0x14000020960, 0x1, ...}, ...)
        /Users/kalexmills/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.3/internal/shader/stmt.go:669 +0x10a8
github.com/hajimehoshi/ebiten/v2/internal/shader.(*compileState).parseStmt(0x1400059c6e0?, 0x140003036c0, {0x140001a6598, 0x6}, {0x102fd85f0?, 0x140001f9b00?}, {0x140000ff080, 0x1, 0x1}, {0x0?, ...}, ...)
        /Users/kalexmills/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.3/internal/shader/stmt.go:59 +0x1038
github.com/hajimehoshi/ebiten/v2/internal/shader.(*compileState).parseBlock(0x140005a0d00, 0x140005a0e00, {0x140001a6598, 0x6}, {0x140002cb000, 0x15, 0x0?}, {0x140000ff080?, 0x1, 0x1}, ...)
        /Users/kalexmills/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.3/internal/shader/shader.go:875 +0x3d0
github.com/hajimehoshi/ebiten/v2/internal/shader.(*compileState).parseFunc(0x140005a0d00, 0x140005a0e00, 0x140003294a0)
        /Users/kalexmills/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.3/internal/shader/shader.go:781 +0x660
github.com/hajimehoshi/ebiten/v2/internal/shader.(*compileState).parseDecl(0x140005a0d00, 0x140005a0e00, {0x140001a6598?, 0xb?}, {0x102fd8980?, 0x140003294a0})
        /Users/kalexmills/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.3/internal/shader/shader.go:389 +0x128
github.com/hajimehoshi/ebiten/v2/internal/shader.(*compileState).parse(0x140005a0d00, 0x1400059e090)
        /Users/kalexmills/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.3/internal/shader/shader.go:287 +0x8a8
github.com/hajimehoshi/ebiten/v2/internal/shader.Compile(0x140001f9540, 0x0?, {0x102d7cdc2, 0x8}, {0x102d7ca9a, 0x8}, 0x4)
        /Users/kalexmills/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.3/internal/shader/shader.go:190 +0x104
github.com/hajimehoshi/ebiten/v2/internal/graphics.CompileShader({0x14000092000?, 0x10?, 0x102d7ff50?})
        /Users/kalexmills/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.3/internal/graphics/shader.go:127 +0xf0
github.com/hajimehoshi/ebiten/v2.NewShader({0x14000092000?, 0x102fdfbc0?, 0x140001fc3c0?})
        /Users/kalexmills/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.3/shader.go:39 +0x20
witch-in-the-woods/internal.loadShader({0x102d7ff50?, 0x1400031c0c0?})
        /Users/kalexmills/repos/personal/witch-of-the-woods/internal/resources.go:200 +0x70
witch-in-the-woods/internal.init.0()
        /Users/kalexmills/repos/personal/witch-of-the-woods/internal/resources.go:160 +0x4bc
exit status 2

```

**Comment by hajimehoshi** [comment]
Would it be possible to minimize the reproducible case? Thanks,

**Comment by hajimehoshi** [comment]
I set the milestone v2.6.0 for now, but if this is a serious issue, I reset the milestone to backport a fix.

**Comment by hajimehoshi** [comment]
I've confirmed this issue.

**Comment by hajimehoshi** [comment]
`mod289_v3`, `mod289_v2` and `permute` doesn't have returning types, though they have return statements.

This issue is actually a bug, but the panicking is weird. I'll fix this though I won't backport the fix.

**Comment by hajimehoshi** [comment]
Minimized case:

```go
package main

func foo(x vec2) {
        x = bar(x)
        _ = x
}

func bar(x vec2) {
        return x
}
```

**Comment by kalexmills** [comment]
Thanks Hajime! You're the best. Keep being awesome! :D
