### ISSUE TITLE
internal/shader: `vec2(1) < vec2(2)` unexpectedly passes to compile

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2718]
### Ebitengine Version

63df6168d97e289905a56cd557c799ede7625eeb

### Operating System

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

go version go1.20.4 darwin/amd64

### What steps will reproduce the problem?

Compile a Kage program including this comparision:

```
vec2(1) < vec2(2)
```

### What is the expected result?

Compiling fails

### What happens instead?

Compiling succeeds unexpectedly

### Anything else you feel useful to add?

Comparing vectors and matrices should fail.

**Comment by hajimehoshi** [comment]
Compilin this crashes:

```go
false < true
```

```
panic: invalid comparison false < true [recovered]
        panic: invalid comparison false < true

goroutine 141 [running]:
testing.tRunner.func1.2({0x119ff40, 0xc00030a250})
        /usr/local/go/src/testing/testing.go:1526 +0x24e
testing.tRunner.func1()
        /usr/local/go/src/testing/testing.go:1529 +0x39f
panic({0x119ff40, 0xc00030a250})
        /usr/local/go/src/runtime/panic.go:884 +0x213
go/constant.Compare({0x121c350?, 0x130bd20}, 0x28, {0x121c350?, 0x130bd28})
        /usr/local/go/src/go/constant/value.go:1409 +0x5fc
github.com/hajimehoshi/ebiten/v2/internal/shader.(*compileState).parseExpr(0xc000169680, 0xc000216b60, {0xc0003d1400, 0x8}, {0x121b880?, 0xc000205d10?}, 0x1)
        /Users/hajimehoshi/ebiten/internal/shader/expr.go:154 +0x928
github.com/hajimehoshi/ebiten/v2/internal/shader.(*compileState).assign(0xc000169680, 0xc000216b60, {0xc0003d1400, 0x8}, 0x28?, {0xc00030a1c0, 0x1, 0xc0000f13d8?}, {0xc00030a1d0, 0x1, ...}, ...)
        /Users/hajimehoshi/ebiten/internal/shader/stmt.go:612 +0x43d
github.com/hajimehoshi/ebiten/v2/internal/shader.(*compileState).parseStmt(0xc0001fbda0?, 0xc000216b60, {0xc0003d1400, 0x8}, {0x121b790?, 0xc00020b6c0?}, {0xc0001a3900, 0x3, 0x4}, {0x0, ...}, ...)
        /Users/hajimehoshi/ebiten/internal/shader/stmt.go:58 +0x1476
github.com/hajimehoshi/ebiten/v2/internal/shader.(*compileState).parseBlock(0xc000169680, 0xc000169778, {0xc0003d1400, 0x8}, {0xc0001fbe60, 0x2, 0x70?}, {0xc0001a3900, 0x3, 0x4}, ...)
        /Users/hajimehoshi/ebiten/internal/shader/shader.go:923 +0x53e
github.com/hajimehoshi/ebiten/v2/internal/shader.(*compileState).parseFunc(0xc000169680, 0xc000169778, 0xc000205d70)
        /Users/hajimehoshi/ebiten/internal/shader/shader.go:829 +0x6aa
github.com/hajimehoshi/ebiten/v2/internal/shader.(*compileState).parseDecl(0xc000169680, 0xc000169778, {0xc0003d1400?, 0x10d411e?}, {0x121bb20?, 0xc000205d70})
        /Users/hajimehoshi/ebiten/internal/shader/shader.go:443 +0x17b
github.com/hajimehoshi/ebiten/v2/internal/shader.(*compileState).parse(0xc000169680, 0xc0000bbe60)
        /Users/hajimehoshi/ebiten/internal/shader/shader.go:336 +0xabb
github.com/hajimehoshi/ebiten/v2/internal/shader.Compile({0xc000105800, 0x71, 0x80}, {0x11cf055, 0x6}, {0x11cf633, 0x8}, 0x0)
        /Users/hajimehoshi/ebiten/internal/shader/shader.go:206 +0x1a5
github.com/hajimehoshi/ebiten/v2/internal/shader_test.compileToIR(...)
        /Users/hajimehoshi/ebiten/internal/shader/syntax_test.go:27
github.com/hajimehoshi/ebiten/v2/internal/shader_test.TestSyntaxCompare(0xc000083a00)
        /Users/hajimehoshi/ebiten/internal/shader/syntax_test.go:3450 +0x118
testing.tRunner(0xc000083a00, 0x11ea168)
        /usr/local/go/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:1629 +0x3ea
FAIL    github.com/hajimehoshi/ebiten/v2/internal/shader        0.286s
FAIL
```
