### ISSUE TITLE
internal/atlas: crash (invalid memory address or nil pointer dereference)

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2729]
### Ebitengine Version

269fc2bd4d1ac83c70ef9ebcb0ee3fb8895e5560

### Operating System

- [ ] Windows
- [X] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

go version go1.20.4 darwin/amd64

### What steps will reproduce the problem?

Not sure. I'll try to minimize later. I found this issue by running an Odencat game with the latest Ebitengine.

### What is the expected result?

No crash

### What happens instead?

Crash at launching

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x100399440]

goroutine 37 [running]:
github.com/hajimehoshi/ebiten/v2/internal/atlas.putImagesOnSourceBackend.func2(0xc000954460?)
        /Users/hajimehoshi/ebiten/internal/atlas/image.go:79 +0x20
github.com/hajimehoshi/ebiten/v2/internal/atlas.(*smallImageSet).forEach(...)
        /Users/hajimehoshi/ebiten/internal/atlas/set.go:46
github.com/hajimehoshi/ebiten/v2/internal/atlas.putImagesOnSourceBackend({0x1008a83f0, 0xc00020dd40})
        /Users/hajimehoshi/ebiten/internal/atlas/image.go:78 +0x115
github.com/hajimehoshi/ebiten/v2/internal/atlas.BeginFrame({0x1008a83f0, 0xc00020dd40})
        /Users/hajimehoshi/ebiten/internal/atlas/image.go:792 +0x12c
github.com/hajimehoshi/ebiten/v2/internal/buffered.BeginFrame({0x1008a83f0?, 0xc00020dd40?})
        /Users/hajimehoshi/ebiten/internal/buffered/image.go:38 +0x25
github.com/hajimehoshi/ebiten/v2/internal/ui.(*context).updateFrameImpl(0xc0009c9dc0, {0x1008a83f0, 0xc00020dd40}, 0x0, 0x407e000000000000, 0x4090400000000000, 0x101a01878?, 0x100d92dc0, 0x0?, 0xc012aaa210)
        /Users/hajimehoshi/ebiten/internal/ui/context.go:107 +0x15a
github.com/hajimehoshi/ebiten/v2/internal/ui.(*context).updateFrame(0xc000963100?, {0x1008a83f0, 0xc00020dd40}, 0xc131841500e54f20?, 0x15be472d?, 0x100d91ee0?, 0xc0002a9eb0?, 0xc0002a9eb0?)
        /Users/hajimehoshi/ebiten/internal/ui/context.go:73 +0x98
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).updateGame(0x100d92dc0)
        /Users/hajimehoshi/ebiten/internal/ui/ui_glfw.go:1088 +0x1fe
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).loopGame(0x100d92dc0)
        /Users/hajimehoshi/ebiten/internal/ui/ui_glfw.go:1056 +0xb6
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).Run.func2()
        /Users/hajimehoshi/ebiten/internal/ui/run_glfw_notsinglethread.go:57 +0x46
golang.org/x/sync/errgroup.(*Group).Go.func1()
        /Users/hajimehoshi/go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
        /Users/hajimehoshi/go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:72 +0xa5
```

### Anything else you feel useful to add?

a9d9143d901b27e984097df54d9226a1a5c362ad is the culprit

```
a9d9143d901b27e984097df54d9226a1a5c362ad is the first bad commit
commit a9d9143d901b27e984097df54d9226a1a5c362ad
Author: Hajime Hoshi <hajimehoshi@gmail.com>
Date:   Sat Aug 19 14:57:55 2023 +0900

    internal/atlas: replace a map with a set with a slice
    
    Updates #2601

 internal/atlas/image.go | 22 ++++++++++----------
 internal/atlas/set.go   | 55 +++++++++++++++++++++++++++++++++++++++++++++++++
 2 files changed, 66 insertions(+), 11 deletions(-)
 create mode 100644 internal/atlas/set.go
```

**Comment by hajimehoshi** [comment]
The fix will be like this:

```diff
commit 778e6e8ad71cffddf462016a3f2dcd9533e13c83
Author: Hajime Hoshi <hajimehoshi@gmail.com>
Date:   Wed Aug 23 14:39:21 2023 +0900

    internal/atlas: bug fix: copy the image slice before iterating it
    
    Closes #2729

diff --git a/internal/atlas/set.go b/internal/atlas/set.go
index 8724b5449..34263264c 100644
--- a/internal/atlas/set.go
+++ b/internal/atlas/set.go
@@ -19,9 +19,14 @@ package atlas
 // If the number of items is big, a map might be better than a slice.
 type smallImageSet struct {
 	s []*Image
+
+	tmp []*Image
 }
 
 func (s *smallImageSet) add(image *Image) {
+	if image == nil {
+		panic("atlas: nil image cannot be added")
+	}
 	for _, img := range s.s {
 		if img == image {
 			return
@@ -42,9 +47,18 @@ func (s *smallImageSet) remove(image *Image) {
 }
 
 func (s *smallImageSet) forEach(f func(*Image)) {
-	for _, img := range s.s {
+	// Copy images to a temporary buffer since f might modify the original slice s.s (#2729).
+	s.tmp = append(s.tmp, s.s...)
+
+	for _, img := range s.tmp {
 		f(img)
 	}
+
+	// Clear the temporary buffer.
+	for i := range s.tmp {
+		s.tmp[i] = nil
+	}
+	s.tmp = s.tmp[:0]
 }
 
 func (s *smallImageSet) clear() {
```

I'll try to make tests.
