### ISSUE TITLE
cmd/ebitenmobile: crash with `eglChooseConfig failed`

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2740]
### Ebitengine Version

v2.6.0-alpha.4

### Operating System

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [X] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

go version go1.20.4 darwin/amd64

### What steps will reproduce the problem?

Not sure. This was reported from Crashlytics from our Android applications.

### What is the expected result?

No crash

### What happens instead?

Crash:

```
Fatal Exception: java.lang.IllegalArgumentException: eglChooseConfig failed
       at android.opengl.GLSurfaceView$BaseConfigChooser.chooseConfig(GLSurfaceView.java:889)
       at android.opengl.GLSurfaceView$EglHelper.start(GLSurfaceView.java:1064)
       at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1447)
       at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1286)
```

### Anything else you feel useful to add?

I guess this is because arguments at `setEGLConfigChooser` was not good. The version 3 changed the situation, though the version 2 worked.

This was rerpoted mainly from old Android 5-7 machines (e.g. Galaxy J1 Ace 2015), but there is also a report from Android 11. (EDIT: This should support ES3. This is odd https://gfxbench.com/device.jsp?benchmark=gfx30&D=Samsung+Galaxy+J1+Ace+(GC7000%2C+SM-J110F)&testgroup=info)

/CC @wasedaigo

**Comment by hajimehoshi** [comment]
Failed to reproduce this with ASUS_X013DB (Android 5.1.1)

**Comment by hajimehoshi** [comment]
I might not fix this if this happens only on old Android devices.

**Comment by hajimehoshi** [comment]
This still happens, but with minor devices (e.g. TCT (Alcatel) ALCATEL 1T 10)

**Comment by hajimehoshi** [comment]
Gemini suggested to use a custom chooser with a fallback:

```java
import android.opengl.GLSurfaceView;
import javax.microedition.khronos.egl.EGL10;
import javax.microedition.khronos.egl.EGLConfig;
import javax.microedition.khronos.egl.EGLDisplay;

public class SafeConfigChooser implements GLSurfaceView.EGLConfigChooser {
    @Override
    public EGLConfig chooseConfig(EGL10 egl, EGLDisplay display) {
        // 1. Try to find the ideal configuration (RGBA8888, Depth 0, Stencil 0).
        int[] idealAttribs = {
                EGL10.EGL_RED_SIZE, 8,
                EGL10.EGL_GREEN_SIZE, 8,
                EGL10.EGL_BLUE_SIZE, 8,
                EGL10.EGL_ALPHA_SIZE, 8,
                EGL10.EGL_DEPTH_SIZE, 0,
                EGL10.EGL_STENCIL_SIZE, 0,
                EGL10.EGL_RENDERABLE_TYPE, 4, // EGL_OPENGL_ES2_BIT (often compatible with ES3)
                EGL10.EGL_NONE
        };

        EGLConfig[] configs = new EGLConfig[1];
        int[] numConfig = new int[1];

        // eglChooseConfig returns false if it fails, or true with numConfig[0] == 0 if no match is found.
        if (egl.eglChooseConfig(display, idealAttribs, configs, 1, numConfig) && numConfig[0] > 0) {
            return configs[0];
        }

        // 2. Fallback: If the ideal config is not found, try a safe default (RGB565).
        // This is necessary for some minor devices or drivers that do not support 32-bit color surfaces.
        int[] fallbackAttribs = {
                EGL10.EGL_RED_SIZE, 5,
                EGL10.EGL_GREEN_SIZE, 6,
                EGL10.EGL_BLUE_SIZE, 5,
                EGL10.EGL_RENDERABLE_TYPE, 4, // EGL_OPENGL_ES2_BIT
                EGL10.EGL_NONE
        };

        if (egl.eglChooseConfig(display, fallbackAttribs, configs, 1, numConfig) && numConfig[0] > 0) {
            return configs[0];
        }

        // 3. Critical failure: No compatible config found.
        throw new IllegalArgumentException("No configs match configSpec");
    }
}
```

and

```java
setEGLConfigChooser(new SafeConfigChooser());
```
