### ISSUE TITLE
ebiten.SetCursorMode panics when run from a different goroutine just after game is started

### ISSUE THREAD

**Issue by elgopher** [hajimehoshi/ebiten#2742]
### Ebitengine Version

2.5.8

### Operating System

- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

1.21

### What steps will reproduce the problem?

```go
package main

import (
	"fmt"
	"time"

	"github.com/hajimehoshi/ebiten/v2"
)

func main() {
	go func() {
		for {
			ebiten.SetCursorMode(ebiten.CursorModeHidden) // panics after game is run
			time.Sleep(time.Millisecond)
		}
	}()
	err := ebiten.RunGame(&game{})
	if err != nil {
		fmt.Println(err)
	}
}

type game struct{}

func (g game) Update() error {
	return nil
}

func (g game) Draw(screen *ebiten.Image) {}

func (g game) Layout(outsideWidth, outsideHeight int) (screenWidth, screenHeight int) {
	return outsideWidth, outsideHeight
}
```

### What is the expected result?

Not panic.

### What happens instead?

Panics, possible because of race condition.

**Comment by hajimehoshi** [comment]
Confirmed. Thanks!

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x10023eafc]

goroutine 21 [running]:
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).SetCursorMode(0x10055ab00, 0x1)
        /Users/hajimehoshi/ebiten/internal/ui/ui_glfw.go:763 +0x7c
github.com/hajimehoshi/ebiten/v2.SetCursorMode(...)
        /Users/hajimehoshi/ebiten/run.go:367
main.main.func1()
        /Users/hajimehoshi/ebiten/examples/test/main.go:13 +0x27
created by main.main
        /Users/hajimehoshi/ebiten/examples/test/main.go:11 +0x25
exit status 2
```

**Comment by hajimehoshi** [comment]
Apparently `mainThread` was not set.

@elgopher Was the panic message the same?

**Comment by elgopher** [comment]
> Apparently `mainThread` was not set.
> 
> @elgopher Was the panic message the same?

Yes. `mainThread` was nil in `userInterfaceImpl` (ui_glfw.go)

**Comment by hajimehoshi** [comment]
I found a solution. I'll fix within a day. Thanks,

**Comment by hajimehoshi** [comment]
Please try 6016c934f5f23884fd866163450d3ce1b4cbe4f4 (2.5 branch). Thanks!

**Comment by elgopher** [comment]
> Please try [6016c93](https://github.com/hajimehoshi/ebiten/commit/6016c934f5f23884fd866163450d3ce1b4cbe4f4) (2.5 branch). Thanks!

Thanks :) It looks like it is working fine :) Although, when I close the window (alt+f4) and `ebiten.SetCursorMode(ebiten.CursorModeHidden)` is run in the background goroutine I'm getting another panic:

```
panic: the GLFW library is not initialized

goroutine 1 [running, locked to thread]:
github.com/hajimehoshi/ebiten/v2/internal/glfw.(*Window).SetInputMode(...)
        C:/Users/jacek/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.9-0.20230901192638-6016c934f5f2/internal/glfw/glfw_windows.go:263
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).SetCursorMode.func1()
        C:/Users/jacek/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.9-0.20230901192638-6016c934f5f2/internal/ui/ui_glfw.go:613 +0xb3
github.com/hajimehoshi/ebiten/v2/internal/thread.(*OSThread).Loop.func1(0xc000419d78?, 0xc000419d50?)
        C:/Users/jacek/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.9-0.20230901192638-6016c934f5f2/internal/thread/thread.go:51 +0x48
github.com/hajimehoshi/ebiten/v2/internal/thread.(*OSThread).Loop(0xc00008ac70, {0xabeaf0, 0xc0000d1310})
        C:/Users/jacek/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.9-0.20230901192638-6016c934f5f2/internal/thread/thread.go:52 +0x74
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).Run(0xd05c20, {0xac0368?, 0xc000071880}, 0x78d296?)
        C:/Users/jacek/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.9-0.20230901192638-6016c934f5f2/internal/ui/run_glfw_notsinglethread.go:64 +0x3f7
github.com/hajimehoshi/ebiten/v2.RunGameWithOptions({0xabd9f0, 0xd5c360}, 0x0)
        C:/Users/jacek/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.9-0.20230901192638-6016c934f5f2/run.go:305 +0x175
github.com/hajimehoshi/ebiten/v2.RunGame(...)
        C:/Users/jacek/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.9-0.20230901192638-6016c934f5f2/run.go:229
main.main()
        C:/Users/jacek/GolandProjects/pi/aaa/main.go:17 +0x30
```

**Comment by hajimehoshi** [comment]
Thank you for confirming it!

Oh that's interesting. Actually the current implementation doesn't care the case when calling such global functions after `RunGame` ends. At least I'll fix Ebitengine not to cause panics, but I would not backport the fix to the stable branch.
