### ISSUE TITLE
ebiten: calling `SetCursorMode` in a different goroutine after a window close crashes

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2743]
### Ebitengine Version

6e968558b1e83bd37288baa5feb79f46b4dbff56

### Operating System

- [X] Windows
- [X] macOS
- [X] Linux
- [X] FreeBSD
- [X] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

go version go1.20.4 darwin/amd64

### What steps will reproduce the problem?

Run this program

```go
package main

import (
	"time"

	"github.com/hajimehoshi/ebiten/v2"
)

type Game struct{}

func (g *Game) Update() error {
	return ebiten.Termination
}

func (g *Game) Draw(screen *ebiten.Image) {}

func (g *Game) Layout(width, height int) (int, int) {
	return width, height
}

func main() {
	go func() {
		for {
			ebiten.SetCursorMode(ebiten.CursorModeHidden)
			time.Sleep(time.Millisecond)
		}
	}()
	if err := ebiten.RunGame(&Game{}); err != nil {
		panic(err)
	}
	
}
```

### What is the expected result?

No crash

### What happens instead?

Crash

```
panic: NotInitialized: The GLFW library is not initialized

goroutine 1 [running, locked to thread]:
github.com/hajimehoshi/ebiten/v2/internal/cglfw.acceptError({0x0, 0x0, 0x34002?})
        /Users/hajimehoshi/ebiten/internal/cglfw/error.go:184 +0x1ae
github.com/hajimehoshi/ebiten/v2/internal/cglfw.panicError(...)
        /Users/hajimehoshi/ebiten/internal/cglfw/error.go:195
github.com/hajimehoshi/ebiten/v2/internal/cglfw.(*Window).SetInputMode(0xc00041ddb4?, 0x10000893d?, 0xc00008e240?)
        /Users/hajimehoshi/ebiten/internal/cglfw/input.go:336 +0x26
github.com/hajimehoshi/ebiten/v2/internal/glfw.(*Window).SetInputMode(...)
        /Users/hajimehoshi/ebiten/internal/glfw/glfw_cglfw.go:233
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).SetCursorMode.func1()
        /Users/hajimehoshi/ebiten/internal/ui/ui_glfw.go:764 +0x65
github.com/hajimehoshi/ebiten/v2/internal/thread.(*OSThread).Loop.func1({0xc000215518?, 0xb0?}, 0xc0000ac960?)
        /Users/hajimehoshi/ebiten/internal/thread/thread.go:67 +0x64
github.com/hajimehoshi/ebiten/v2/internal/thread.(*OSThread).Loop(0xc0001a8020, {0x100336358, 0xc0000c5770})
        /Users/hajimehoshi/ebiten/internal/thread/thread.go:68 +0x8a
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).Run(0x10055ab00, {0x1003379d0?, 0xc0000c8000}, 0x10003d685?)
        /Users/hajimehoshi/ebiten/internal/ui/run_glfw_notsinglethread.go:64 +0x3f3
github.com/hajimehoshi/ebiten/v2.RunGameWithOptions({0x1003361a8, 0x100595390}, 0x0)
        /Users/hajimehoshi/ebiten/run.go:305 +0x185
github.com/hajimehoshi/ebiten/v2.RunGame(...)
        /Users/hajimehoshi/ebiten/run.go:229
main.main()
        /Users/hajimehoshi/ebiten/examples/test/main.go:28 +0x3a
exit status 2
```

### Anything else you feel useful to add?

Reported at https://github.com/hajimehoshi/ebiten/issues/2742#issuecomment-1703251106 by @elgopher

**Comment by hajimehoshi** [comment]
My current idea is at least to suppress the panics. Ebitengine basically doesn't care the state after RunGame, so I would not backport the fix to the stable branch.

**Comment by hajimehoshi** [comment]
By the way, this would not happen if we didn't have global functions... https://github.com/hajimehoshi/ebiten/issues/2658
