### ISSUE TITLE
examples/monitor: crash when the initial monitor is a monitor above the primary monitor

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2794]
### Ebitengine Version

v2.6.0

### Operating System

- [ ] Windows
- [X] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

go version go1.21.1 darwin/amd64

### What steps will reproduce the problem?

1. Connect a monitor that is arranged to be above the primary monitor
2. Run `examples/monitor` with the cursor position in the new monitor

### What is the expected result?

The window is shown in the second monitor

### What happens instead?

Crash

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x100249484]

goroutine 1 [running]:
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).setInitMonitor(0x1006af680, 0x0)
        /Users/hajimehoshi/ebiten/internal/ui/ui_glfw.go:217 +0xa4
github.com/hajimehoshi/ebiten/v2/internal/ui.initialize()
        /Users/hajimehoshi/ebiten/internal/ui/ui_glfw.go:193 +0xbb
github.com/hajimehoshi/ebiten/v2/internal/ui.init.2()
        /Users/hajimehoshi/ebiten/internal/ui/ui_glfw.go:159 +0x13
exit status 2
```

### Anything else you feel useful to add?

Reported by @bfreis

**Comment by hajimehoshi** [comment]
In the main branch (94bf6a4cc18b8961a2dd00df1f63bb17b7c7982f):

```
$ go run ./examples/monitor/
panic: ui: no monitor was found at initialize

goroutine 1 [running]:
github.com/hajimehoshi/ebiten/v2/internal/ui.init.2()
        /Users/hajimehoshi/ebiten/internal/ui/ui_glfw.go:153 +0x50
exit status 2
```

**Comment by hajimehoshi** [comment]
Note that this could happen only with one display by putting a cursor on an extreme position (top of the display). If your display's height is 1329, the cursposition Y can take 0 <= y <= 1329, not 0 <= y < 1329!
