### ISSUE TITLE
Rare SIGSEGV when polling for inputs

### ISSUE THREAD

**Issue by SolarLune** [hajimehoshi/ebiten#2836]
### Ebitengine Version

2.6.2

### Operating System

- [ ] Windows
- [ ] macOS
- [X] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] PlayStation 5
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

1.21.3

### What steps will reproduce the problem?

Unfortunately, I can't reproduce the problem reliably. 

When it happens, it happens when I press a key; however, it **very** rarely happens. I would say once every hour of usage, this issue will happen, resulting in a SIGSEGV crash. It seems to be related to polling for inputs from GLFW. Maybe it's a race condition? I've observed this under tests for resolv, my collision testing library (which use Ebitengine 2.5.4), and when using Tetra3D (which uses Ebitengine v2.6.2).

Here's the output from the most recent crash:

```
SIGSEGV: segmentation violation
PC=0x7f8a51e010ce m=0 sigcode=1
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x71fae0, 0xc0008adc90)
        /usr/lib/go/src/runtime/cgocall.go:157 +0x4b fp=0xc0008adc68 sp=0xc0008adc30 pc=0x40c36b
github.com/go-gl/glfw/v3.3/glfw._Cfunc_glfwPollEvents()
        _cgo_gotypes.go:1595 +0x3f fp=0xc0008adc90 sp=0xc0008adc68 pc=0x60335f
github.com/go-gl/glfw/v3.3/glfw.PollEvents()
        /home/solarlune/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20221017161538-93cebf72946b/window.go:964 +0xf fp=0xc0008adca0 sp=0xc0008adc90 pc=0x60e96f
github.com/hajimehoshi/ebiten/v2/internal/glfw.PollEvents(...)
        /home/solarlune/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.4/internal/glfw/glfw_notwindows.go:310
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).update(0xb56400)
        /home/solarlune/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.4/internal/ui/ui_glfw.go:1014 +0x99 fp=0xc0008adcc0 sp=0xc0008adca0 pc=0x69d179
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).updateGame.func1()
        /home/solarlune/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.4/internal/ui/ui_glfw.go:1070 +0x45 fp=0xc0008add08 sp=0xc0008adcc0 pc=0x69d865
github.com/hajimehoshi/ebiten/v2/internal/thread.(*OSThread).Loop.func1(0xc0008add98?, 0xc0008add70?)
        /home/solarlune/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.4/internal/thread/thread.go:51 +0x48 fp=0xc0008add38 sp=0xc0008add08 pc=0x5b41e8
github.com/hajimehoshi/ebiten/v2/internal/thread.(*OSThread).Loop(0xc000192170, {0x85a878, 0xc0004de190})
        /home/solarlune/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.4/internal/thread/thread.go:52 +0x74 fp=0xc0008addd0 sp=0xc0008add38 pc=0x5b4094
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).Run(0xb56400, {0x85c2d0?, 0xc0004e2150}, 0x6238?)
        /home/solarlune/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.4/internal/ui/run_glfw_notsinglethread.go:61 +0x3ee fp=0xc0008ade80 sp=0xc0008addd0 pc=0x69816e
github.com/hajimehoshi/ebiten/v2.RunGameWithOptions({0x859048, 0xc000516120}, 0x0)
        /home/solarlune/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.4/run.go:305 +0x175 fp=0xc0008adf18 sp=0xc0008ade80 pc=0x6ab615
github.com/hajimehoshi/ebiten/v2.RunGame(...)
        /home/solarlune/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.4/run.go:229
main.main()
        /home/solarlune/Documents/Projects/Go/resolv/examples/main.go:192 +0x25 fp=0xc0008adf40 sp=0xc0008adf18 pc=0x7009e5
runtime.main()
        /usr/lib/go/src/runtime/proc.go:267 +0x2bb fp=0xc0008adfe0 sp=0xc0008adf40 pc=0x44057b
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0008adfe8 sp=0xc0008adfe0 pc=0x46ef21

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc00005cfa8 sp=0xc00005cf88 pc=0x4409ce
runtime.goparkunlock(...)
        /usr/lib/go/src/runtime/proc.go:404
runtime.forcegchelper()
        /usr/lib/go/src/runtime/proc.go:322 +0xb3 fp=0xc00005cfe0 sp=0xc00005cfa8 pc=0x440853
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00005cfe8 sp=0xc00005cfe0 pc=0x46ef21
created by runtime.init.6 in goroutine 1
        /usr/lib/go/src/runtime/proc.go:310 +0x1a

goroutine 3 [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc00005d778 sp=0xc00005d758 pc=0x4409ce
runtime.goparkunlock(...)
        /usr/lib/go/src/runtime/proc.go:404
runtime.bgsweep(0x0?)
        /usr/lib/go/src/runtime/mgcsweep.go:321 +0xdf fp=0xc00005d7c8 sp=0xc00005d778 pc=0x42caff
runtime.gcenable.func1()
        /usr/lib/go/src/runtime/mgc.go:200 +0x25 fp=0xc00005d7e0 sp=0xc00005d7c8 pc=0x421c45
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00005d7e8 sp=0xc00005d7e0 pc=0x46ef21
created by runtime.gcenable in goroutine 1
        /usr/lib/go/src/runtime/mgc.go:200 +0x66

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc174040?, 0x3b9aca00?, 0x0?, 0x0?, 0x0?)
        /usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc00005df70 sp=0xc00005df50 pc=0x4409ce
runtime.goparkunlock(...)
        /usr/lib/go/src/runtime/proc.go:404
runtime.(*scavengerState).park(0xb55c00)
        /usr/lib/go/src/runtime/mgcscavenge.go:425 +0x49 fp=0xc00005dfa0 sp=0xc00005df70 pc=0x42a349
runtime.bgscavenge(0x0?)
        /usr/lib/go/src/runtime/mgcscavenge.go:658 +0x59 fp=0xc00005dfc8 sp=0xc00005dfa0 pc=0x42a8f9
runtime.gcenable.func2()
        /usr/lib/go/src/runtime/mgc.go:201 +0x25 fp=0xc00005dfe0 sp=0xc00005dfc8 pc=0x421be5
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00005dfe8 sp=0xc00005dfe0 pc=0x46ef21
created by runtime.gcenable in goroutine 1
        /usr/lib/go/src/runtime/mgc.go:201 +0xa5

goroutine 18 [finalizer wait]:
runtime.gopark(0x7c7380?, 0x100441b01?, 0x0?, 0x0?, 0x448b85?)
        /usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc00005c628 sp=0xc00005c608 pc=0x4409ce
runtime.runfinq()
        /usr/lib/go/src/runtime/mfinal.go:193 +0x107 fp=0xc00005c7e0 sp=0xc00005c628 pc=0x420cc7
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00005c7e8 sp=0xc00005c7e0 pc=0x46ef21
created by runtime.createfing in goroutine 1
        /usr/lib/go/src/runtime/mfinal.go:163 +0x3d

goroutine 19 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc000058750 sp=0xc000058730 pc=0x4409ce
runtime.gcBgMarkWorker()
        /usr/lib/go/src/runtime/mgc.go:1293 +0xe5 fp=0xc0000587e0 sp=0xc000058750 pc=0x4237c5
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0000587e8 sp=0xc0000587e0 pc=0x46ef21
created by runtime.gcBgMarkStartWorkers in goroutine 1
        /usr/lib/go/src/runtime/mgc.go:1217 +0x1c

goroutine 5 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc00005e750 sp=0xc00005e730 pc=0x4409ce
runtime.gcBgMarkWorker()
        /usr/lib/go/src/runtime/mgc.go:1293 +0xe5 fp=0xc00005e7e0 sp=0xc00005e750 pc=0x4237c5
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00005e7e8 sp=0xc00005e7e0 pc=0x46ef21
created by runtime.gcBgMarkStartWorkers in goroutine 1
        /usr/lib/go/src/runtime/mgc.go:1217 +0x1c

goroutine 20 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc000058f50 sp=0xc000058f30 pc=0x4409ce
runtime.gcBgMarkWorker()
        /usr/lib/go/src/runtime/mgc.go:1293 +0xe5 fp=0xc000058fe0 sp=0xc000058f50 pc=0x4237c5
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000058fe8 sp=0xc000058fe0 pc=0x46ef21
created by runtime.gcBgMarkStartWorkers in goroutine 1
        /usr/lib/go/src/runtime/mgc.go:1217 +0x1c

goroutine 34 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc000114750 sp=0xc000114730 pc=0x4409ce
runtime.gcBgMarkWorker()
        /usr/lib/go/src/runtime/mgc.go:1293 +0xe5 fp=0xc0001147e0 sp=0xc000114750 pc=0x4237c5
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0001147e8 sp=0xc0001147e0 pc=0x46ef21
created by runtime.gcBgMarkStartWorkers in goroutine 1
        /usr/lib/go/src/runtime/mgc.go:1217 +0x1c

goroutine 35 [GC worker (idle)]:
runtime.gopark(0x41524839a26?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc000114f50 sp=0xc000114f30 pc=0x4409ce
runtime.gcBgMarkWorker()
        /usr/lib/go/src/runtime/mgc.go:1293 +0xe5 fp=0xc000114fe0 sp=0xc000114f50 pc=0x4237c5
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000114fe8 sp=0xc000114fe0 pc=0x46ef21
created by runtime.gcBgMarkStartWorkers in goroutine 1
        /usr/lib/go/src/runtime/mgc.go:1217 +0x1c

goroutine 6 [GC worker (idle)]:
runtime.gopark(0x415247b02a2?, 0x3?, 0x48?, 0x5?, 0x0?)
        /usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc00005ef50 sp=0xc00005ef30 pc=0x4409ce
runtime.gcBgMarkWorker()
        /usr/lib/go/src/runtime/mgc.go:1293 +0xe5 fp=0xc00005efe0 sp=0xc00005ef50 pc=0x4237c5
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00005efe8 sp=0xc00005efe0 pc=0x46ef21
created by runtime.gcBgMarkStartWorkers in goroutine 1
        /usr/lib/go/src/runtime/mgc.go:1217 +0x1c

goroutine 7 [GC worker (idle)]:
runtime.gopark(0x415247d0559?, 0x1?, 0x3f?, 0xf8?, 0x0?)
        /usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc00005f750 sp=0xc00005f730 pc=0x4409ce
runtime.gcBgMarkWorker()
        /usr/lib/go/src/runtime/mgc.go:1293 +0xe5 fp=0xc00005f7e0 sp=0xc00005f750 pc=0x4237c5
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00005f7e8 sp=0xc00005f7e0 pc=0x46ef21
created by runtime.gcBgMarkStartWorkers in goroutine 1
        /usr/lib/go/src/runtime/mgc.go:1217 +0x1c

goroutine 8 [GC worker (idle)]:
runtime.gopark(0xba7b80?, 0x1?, 0x6a?, 0x54?, 0x0?)
        /usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc00005ff50 sp=0xc00005ff30 pc=0x4409ce
runtime.gcBgMarkWorker()
        /usr/lib/go/src/runtime/mgc.go:1293 +0xe5 fp=0xc00005ffe0 sp=0xc00005ff50 pc=0x4237c5
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00005ffe8 sp=0xc00005ffe0 pc=0x46ef21
created by runtime.gcBgMarkStartWorkers in goroutine 1
        /usr/lib/go/src/runtime/mgc.go:1217 +0x1c

goroutine 21 [GC worker (idle)]:
runtime.gopark(0x4152483a246?, 0x3?, 0x85?, 0xbb?, 0x0?)
        /usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc000059750 sp=0xc000059730 pc=0x4409ce
runtime.gcBgMarkWorker()
        /usr/lib/go/src/runtime/mgc.go:1293 +0xe5 fp=0xc0000597e0 sp=0xc000059750 pc=0x4237c5
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0000597e8 sp=0xc0000597e0 pc=0x46ef21
created by runtime.gcBgMarkStartWorkers in goroutine 1
        /usr/lib/go/src/runtime/mgc.go:1217 +0x1c

goroutine 9 [GC worker (idle)]:
runtime.gopark(0x4152483a975?, 0x1?, 0xfc?, 0x5?, 0x0?)
        /usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc000110750 sp=0xc000110730 pc=0x4409ce
runtime.gcBgMarkWorker()
        /usr/lib/go/src/runtime/mgc.go:1293 +0xe5 fp=0xc0001107e0 sp=0xc000110750 pc=0x4237c5
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0001107e8 sp=0xc0001107e0 pc=0x46ef21
created by runtime.gcBgMarkStartWorkers in goroutine 1
        /usr/lib/go/src/runtime/mgc.go:1217 +0x1c

goroutine 22 [GC worker (idle)]:
runtime.gopark(0x4152483a08e?, 0x1?, 0xe4?, 0xeb?, 0x0?)
        /usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc000059f50 sp=0xc000059f30 pc=0x4409ce
runtime.gcBgMarkWorker()
        /usr/lib/go/src/runtime/mgc.go:1293 +0xe5 fp=0xc000059fe0 sp=0xc000059f50 pc=0x4237c5
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000059fe8 sp=0xc000059fe0 pc=0x46ef21
created by runtime.gcBgMarkStartWorkers in goroutine 1
        /usr/lib/go/src/runtime/mgc.go:1217 +0x1c

goroutine 10 [GC worker (idle)]:
runtime.gopark(0x4152483a430?, 0x3?, 0x4a?, 0x57?, 0x0?)
        /usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc000110f50 sp=0xc000110f30 pc=0x4409ce
runtime.gcBgMarkWorker()
        /usr/lib/go/src/runtime/mgc.go:1293 +0xe5 fp=0xc000110fe0 sp=0xc000110f50 pc=0x4237c5
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000110fe8 sp=0xc000110fe0 pc=0x46ef21
created by runtime.gcBgMarkStartWorkers in goroutine 1
        /usr/lib/go/src/runtime/mgc.go:1217 +0x1c

goroutine 40 [select, locked to thread]:
runtime.gopark(0xc0005faef8?, 0x2?, 0x20?, 0x15?, 0xc0005faed4?)
        /usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc0005fad78 sp=0xc0005fad58 pc=0x4409ce
runtime.selectgo(0xc0005faef8, 0xc0005faed0, 0xc0001a25f8?, 0x0, 0x649f5e?, 0x1)
        /usr/lib/go/src/runtime/select.go:327 +0x725 fp=0xc0005fae98 sp=0xc0005fad78 pc=0x450505
github.com/hajimehoshi/ebiten/v2/internal/thread.(*OSThread).Loop(0xc0001921b0, {0x85a878, 0xc0004de190})
        /home/solarlune/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.4/internal/thread/thread.go:44 +0xe6 fp=0xc0005faf30 sp=0xc0005fae98 pc=0x5b4106
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).Run.func1()
        /home/solarlune/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.4/internal/ui/run_glfw_notsinglethread.go:50 +0x52 fp=0xc0005faf78 sp=0xc0005faf30 pc=0x698312
golang.org/x/sync/errgroup.(*Group).Go.func1()
        /home/solarlune/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x56 fp=0xc0005fafe0 sp=0xc0005faf78 pc=0x5b9bf6
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0005fafe8 sp=0xc0005fafe0 pc=0x46ef21
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 1
        /home/solarlune/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0x96

goroutine 41 [chan receive]:
runtime.gopark(0xc0003a9de8?, 0xc00060c300?, 0x80?, 0x2e?, 0xc0003a9de0?)
        /usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc0003a9d90 sp=0xc0003a9d70 pc=0x4409ce
runtime.chanrecv(0xc000028180, 0x0, 0x1)
        /usr/lib/go/src/runtime/chan.go:583 +0x3cd fp=0xc0003a9e08 sp=0xc0003a9d90 pc=0x40e74d
runtime.chanrecv1(0x7a4c60?, 0x1000cb801?)
        /usr/lib/go/src/runtime/chan.go:442 +0x12 fp=0xc0003a9e30 sp=0xc0003a9e08 pc=0x40e352
github.com/hajimehoshi/ebiten/v2/internal/thread.(*OSThread).Call(0xc000192170, 0xc000481380)
        /home/solarlune/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.4/internal/thread/thread.go:66 +0x38 fp=0xc0003a9e50 sp=0xc0003a9e30 pc=0x5b42b8
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).updateGame(0xb56400)
        /home/solarlune/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.4/internal/ui/ui_glfw.go:1069 +0x150 fp=0xc0003a9ee8 sp=0xc0003a9e50 pc=0x69d570
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).loopGame(0xb56400)
        /home/solarlune/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.4/internal/ui/ui_glfw.go:1044 +0x8e fp=0xc0003a9f40 sp=0xc0003a9ee8 pc=0x69d34e
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).Run.func2()
        /home/solarlune/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.4/internal/ui/run_glfw_notsinglethread.go:57 +0x37 fp=0xc0003a9f78 sp=0xc0003a9f40 pc=0x698277
golang.org/x/sync/errgroup.(*Group).Go.func1()
        /home/solarlune/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x56 fp=0xc0003a9fe0 sp=0xc0003a9f78 pc=0x5b9bf6
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0003a9fe8 sp=0xc0003a9fe0 pc=0x46ef21
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 1
        /home/solarlune/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0x96

goroutine 51 [sleep]:
runtime.gopark(0x4152cceafdf?, 0xc000071f58?, 0x1a?, 0x0?, 0xc0003c01a0?)
        /usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc000071f28 sp=0xc000071f08 pc=0x4409ce
time.Sleep(0x3b9aca00)
        /usr/lib/go/src/runtime/time.go:195 +0x125 fp=0xc000071f68 sp=0xc000071f28 pc=0x46bf65
main.NewGame.func1()
        /home/solarlune/Documents/Projects/Go/resolv/examples/main.go:71 +0xf1 fp=0xc000071fe0 sp=0xc000071f68 pc=0x709211
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000071fe8 sp=0xc000071fe0 pc=0x46ef21
created by main.NewGame in goroutine 1
        /home/solarlune/Documents/Projects/Go/resolv/examples/main.go:65 +0x305

rax    0x71
rbx    0x7ffe34891e10
rcx    0x63
rdx    0x7ffe34891e10
rdi    0x25eaf70
rsi    0x7ffe34891c90
rbp    0x7ffe34891c90
rsp    0x7ffe34891c48
r8     0x0
r9     0x7ffe34891c88
r10    0x25ea
r11    0x246
r12    0x71
r13    0x885b20
r14    0x7ffe34891c88
r15    0xb84d20
rip    0x7f8a51e010ce
rflags 0x10206
cs     0x33
fs     0x0
gs     0x0
exit status 2
```

### What is the expected result?

It doesn't crash.

### What happens instead?

It crashes.

### Anything else you feel useful to add?

I'm using EndeavourOS, which is based on Arch Linux.

**Comment by hajimehoshi** [comment]
Would it be possible create a minimized case to reproduce this? Thanks,

**Comment by SolarLune** [comment]
> Would it be possible create a minimized case to reproduce this? Thanks,

Unfortunately, given the very rare situations in which it happens, I don't think it would be possible to create a minimal test case - I'll see if I can isolate exactly when this happens, though.
