### ISSUE TITLE
examples/shader: crash on browser

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2840]
### Ebitengine Version

v2.6.2

### Operating System

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] PlayStation 5
- [ ] Xbox
- [X] Web Browsers

### Go Version (`go version`)

go version go1.21.1 darwin/amd64

### What steps will reproduce the problem?

1. Run `wasmserve ./examples/shader`
2. Open localhost:8080
3. Press down key three times

### What is the expected result?

No crash

### What happens instead?

Crash

```
panic: runtime error: invalid memory address or nil pointer dereference
wasm_exec.js:22 [signal 0xb code=0x0 addr=0x0 pc=0x0]
wasm_exec.js:22 
wasm_exec.js:22 goroutine 104 [running]:
wasm_exec.js:22 github.com/hajimehoshi/ebiten/v2/internal/graphicscommand.(*drawTrianglesCommand).Exec(0x18546c0, {0xe6a80, 0x188d0e0}, 0x6)
wasm_exec.js:22 	/Users/hajimehoshi/ebiten/internal/graphicscommand/command.go:377 +0x16
wasm_exec.js:22 github.com/hajimehoshi/ebiten/v2/internal/graphicscommand.(*commandQueue).flush(0x553e00, {0xe6a80, 0x188d0e0}, 0x1, {0xe3c38, 0x571000})
wasm_exec.js:22 	/Users/hajimehoshi/ebiten/internal/graphicscommand/command.go:291 +0x44
wasm_exec.js:22 github.com/hajimehoshi/ebiten/v2/internal/graphicscommand.(*commandQueue).Flush.func1()
wasm_exec.js:22 	/Users/hajimehoshi/ebiten/internal/graphicscommand/command.go:206 +0x4
wasm_exec.js:22 github.com/hajimehoshi/ebiten/v2/internal/thread.(*NoopThread).CallAsync(0x571000, 0x1bad400)
wasm_exec.js:22 	/Users/hajimehoshi/ebiten/internal/thread/thread.go:117 +0x3
wasm_exec.js:22 github.com/hajimehoshi/ebiten/v2/internal/graphicscommand.runOnRenderThread(0x1bad400, 0x0)
wasm_exec.js:22 	/Users/hajimehoshi/ebiten/internal/graphicscommand/thread.go:40 +0x9
wasm_exec.js:22 github.com/hajimehoshi/ebiten/v2/internal/graphicscommand.(*commandQueue).Flush(0x553e00, {0xe6a80, 0x188d0e0}, 0x1, 0x0)
wasm_exec.js:22 	/Users/hajimehoshi/ebiten/internal/graphicscommand/command.go:203 +0x16
wasm_exec.js:22 github.com/hajimehoshi/ebiten/v2/internal/graphicscommand.FlushCommands({0xe6a80, 0x188d0e0}, 0x1, 0x0)
wasm_exec.js:22 	/Users/hajimehoshi/ebiten/internal/graphicscommand/command.go:312 +0x34
wasm_exec.js:22 github.com/hajimehoshi/ebiten/v2/internal/restorable.resolveStaleImages({0xe6a80, 0x188d0e0}, 0x1, 0x0)
wasm_exec.js:22 	/Users/hajimehoshi/ebiten/internal/restorable/images.go:74 +0x2
wasm_exec.js:22 github.com/hajimehoshi/ebiten/v2/internal/restorable.EndFrame(...)
wasm_exec.js:22 	/Users/hajimehoshi/ebiten/internal/restorable/images.go:68
wasm_exec.js:22 github.com/hajimehoshi/ebiten/v2/internal/atlas.EndFrame({0xe6a80, 0x188d0e0}, 0x0)
wasm_exec.js:22 	/Users/hajimehoshi/ebiten/internal/atlas/image.go:736 +0x5
wasm_exec.js:22 github.com/hajimehoshi/ebiten/v2/internal/buffered.EndFrame(...)
wasm_exec.js:22 	/Users/hajimehoshi/ebiten/internal/buffered/image.go:46
wasm_exec.js:22 github.com/hajimehoshi/ebiten/v2/internal/ui.(*context).updateFrameImpl.func1()
wasm_exec.js:22 	/Users/hajimehoshi/ebiten/internal/ui/context.go:111 +0x4
wasm_exec.js:22 github.com/hajimehoshi/ebiten/v2/internal/ui.(*context).updateFrameImpl(0x18df810, {0xe6a80, 0x188d0e0}, 0x1, 0x4091900000000000, 0x408d280000000000, 0x4000000000000000, 0x554500, 0x0, 0x0)
wasm_exec.js:22 	/Users/hajimehoshi/ebiten/internal/ui/context.go:164 +0x4d
wasm_exec.js:22 github.com/hajimehoshi/ebiten/v2/internal/ui.(*context).updateFrame(0x18df810, {0xe6a80, 0x188d0e0}, 0x4091900000000000, 0x408d280000000000, 0x4000000000000000, 0x554500, 0x0)
wasm_exec.js:22 	/Users/hajimehoshi/ebiten/internal/ui/context.go:73 +0x3
wasm_exec.js:22 github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).updateImpl(0x554500, 0x0)
wasm_exec.js:22 	/Users/hajimehoshi/ebiten/internal/ui/ui_js.go:369 +0x2a
wasm_exec.js:22 github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).update(0x554500)
wasm_exec.js:22 	/Users/hajimehoshi/ebiten/internal/ui/ui_js.go:340 +0x12
wasm_exec.js:22 github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).loop.func1()
wasm_exec.js:22 	/Users/hajimehoshi/ebiten/internal/ui/ui_js.go:406 +0xc
wasm_exec.js:22 created by github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).loop.func2 in goroutine 12
wasm_exec.js:22 	/Users/hajimehoshi/ebiten/internal/ui/ui_js.go:427 +0x4
```

### Anything else you feel useful to add?

On the main branch, there is a different issue:

```
2023/11/15 00:16:19 opengl: fragment shader compile error: opengl: shader compile failed: ERROR: 0:81: 'assign' : cannot convert from 'const int' to 'highp float'
ERROR: 0:82: 'assign' : cannot convert from 'const int' to 'highp float'
ERROR: 0:83: 'assign' : cannot convert from 'const int' to 'highp float'
ERROR:
```

**Comment by hajimehoshi** [comment]
After cherry-picking 53525342b14403e09a937b49d11f23b17d3735a8, the error is now the same as the main branch.
