### ISSUE TITLE
Crash when using function name as variable in shader func

### ISSUE THREAD

**Issue by TLINDEN** [hajimehoshi/ebiten#2926]
### Ebitengine Version

v2.6.6

### Operating System

- [ ] Windows
- [ ] macOS
- [X] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] PlayStation 5
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

1.21.1

### What steps will reproduce the problem?

Write a shader containing this function, it must not be called:
```go
func name(x vec2) vec2 {
	return name.x * 2
}
```

Note, I used `name.x` instead of `x.x` by accident.

### What is the expected result?

life.

### What happens instead?

sudden death:
```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running, locked to thread]:
github.com/hajimehoshi/ebiten/v2/internal/shader.(*compileState).parseExpr(0xc0002cc600, 0xc0000ec150, {0xc0000152f0, 0x4}, {0x831d80?, 0xc000356090?}, 0x1)
        /home/scip/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.6.6/internal/shader/expr.go:740 +0x35cf
github.com/hajimehoshi/ebiten/v2/internal/shader.(*compileState).parseExpr(0xc0002cc600, 0xc0000ec150, {0xc0000152f0, 0x4}, {0x831d20?, 0xc0003b25a0?}, 0x1)
        /home/scip/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.6.6/internal/shader/expr.go:67 +0x29c
github.com/hajimehoshi/ebiten/v2/internal/shader.(*compileState).parseStmt(0xc000366340?, 0x40?, {0xc0000152f0, 0x4}, {0x831b70?, 0xc0003eb220?}, {0xc000367480, 0x1, 0x1}, {0x0, ...}, ...)
        /home/scip/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.6.6/internal/shader/stmt.go:334 +0x3615
github.com/hajimehoshi/ebiten/v2/internal/shader.(*compileState).parseBlock(0xc0002cc600, 0xc0002cc6f8, {0xc0000152f0, 0x4}, {0xc0003588f0, 0x1, 0x414ee5?}, {0xc000367480, 0x1, 0x1}, ...)
        /home/scip/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.6.6/internal/shader/shader.go:931 +0x51f
github.com/hajimehoshi/ebiten/v2/internal/shader.(*compileState).parseFunc(0xc0002cc600, 0xc0002cc6f8, 0xc0003b2600)
        /home/scip/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.6.6/internal/shader/shader.go:837 +0x670
github.com/hajimehoshi/ebiten/v2/internal/shader.(*compileState).parseDecl(0xc0002cc600, 0xc0002cc6f8, {0xc0000152f0?, 0x0?}, {0x831cc0?, 0xc0003b2600})
        /home/scip/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.6.6/internal/shader/shader.go:451 +0x17b
github.com/hajimehoshi/ebiten/v2/internal/shader.(*compileState).parse(0xc0002cc600, 0xc000194be0)
        /home/scip/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.6.6/internal/shader/shader.go:338 +0xaca
github.com/hajimehoshi/ebiten/v2/internal/shader.Compile({0xc0003fe000, 0x1fe4, 0x2000}, {0x7be7d6, 0x8}, {0x7be7de, 0x8}, 0x4)
        /home/scip/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.6.6/internal/shader/shader.go:206 +0x19a
github.com/hajimehoshi/ebiten/v2/internal/graphics.CompileShader({0xa63580, 0x52f, 0x52f})
        /home/scip/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.6.6/internal/graphics/shader.go:182 +0x105
github.com/hajimehoshi/ebiten/v2.NewShader({0xa63580?, 0xc000064028?, 0x200000003?})
        /home/scip/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.6.6/shader.go:41 +0x18
main.main()
        /home/scip/dev/play/shader/main.go:186 +0x117
```

### Anything else you feel useful to add?

The shader engine should catch such errors, however silly they are :)

Thanks!

**Comment by hajimehoshi** [comment]
Thanks!
