### ISSUE TITLE
image.At() crash with single thread mode after a command (Win+openGL)

### ISSUE THREAD

**Issue by Zyko0** [hajimehoshi/ebiten#2939]
### Ebitengine Version

v2.7.0-alpha.9.0.20240324180819-459ad709a69f

### Operating System

- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] PlayStation 5
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

1.21

### What steps will reproduce the problem?

Run the following program:
```go
package main

import (
	"image/color"
	"log"

	"github.com/hajimehoshi/ebiten/v2"
)

const (
	ScreenWidth, ScreenHeight = 16, 16
)

type Game struct {}

func (g *Game) Update() error {
	return nil
}

func (g *Game) Draw(screen *ebiten.Image) {
	screen.Fill(color.White)
	_ = screen.At(0, 0)
}

func (g *Game) Layout(outsideWidth, outsideHeight int) (int, int) {
	return ScreenWidth, ScreenHeight
}

func main() {
	if err := ebiten.RunGameWithOptions(&Game{}, &ebiten.RunGameOptions{
		GraphicsLibrary: ebiten.GraphicsLibraryOpenGL,
		SingleThread:    true,
	}); err != nil {
		log.Fatal(err)
	}
}
```

### What is the expected result?

No crash

### What happens instead?

A big stack:
```
Exception 0xc0000005 0x0 0x1590 0x7ffc2829cff9
PC=0x7ffc2829cff9

runtime.cgocall(0x81b840, 0xc0005802c8)
        C:/Program Files/Go/src/runtime/cgocall.go:157 +0x3e fp=0xc0002bf750 sp=0xc0002bf718 pc=0x7b815e
syscall.SyscallN(0x8?, {0xc0002bf7e8?, 0x0?, 0x0?})
        C:/Program Files/Go/src/runtime/syscall_windows.go:544 +0x107 fp=0xc0002bf7c8 sp=0xc0002bf750 pc=0x816e67
syscall.Syscall15(0x0?, 0x3ff0000000000000?, 0x8000000000000000?, 0x0?, 0x1?, 0x1?, 0x3ff0000000000000?, 0x8000000000000000?, 0x0?, 0x0, ...)
        C:/Program Files/Go/src/runtime/syscall_windows.go:506 +0xd9 fp=0xc0002bf870 sp=0xc0002bf7c8 pc=0x816d39
github.com/ebitengine/purego.syscall_syscall15X(0x0?, 0x0?, 0x0?, 0x0?, 0x0?, 0x0?, 0x0?, 0x0?, 0xc0002bf9e8?, 0x0, ...)

// ...

goroutine 26 [GC worker (idle)]:
runtime.gopark(0x26f76857e104?, 0x0?, 0x0?, 0x0?, 0x0?)
        C:/Program Files/Go/src/runtime/proc.go:398 +0xce fp=0xc000499f50 sp=0xc000499f30 pc=0x7ed7ae
runtime.gcBgMarkWorker()
        C:/Program Files/Go/src/runtime/mgc.go:1293 +0xe5 fp=0xc000499fe0 sp=0xc000499f50 pc=0x7cecc5
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000499fe8 sp=0xc000499fe0 pc=0x81a081
created by runtime.gcBgMarkStartWorkers in goroutine 1
        C:/Program Files/Go/src/runtime/mgc.go:1217 +0x1c
rax     0x0
rbx     0xc0005802c8
rcx     0x1
rdi     0xfa027ff948
rsi     0xfa027ff8d0
rbp     0xfa027ffa30
rsp     0xfa027ff8c8
r8      0x0
r9      0x0
r10     0x0
r11     0x0
r12     0xc0002bf8f0
r13     0x0
r14     0xc000346340
r15     0x0
rip     0x7ffc2829cff9
rflags  0x10283
cs      0x33
fs      0x53
gs      0x2b
exit status 2
```

### Anything else you feel useful to add?

- Happens on Windows + SingleThread mode + OpenGL (not directx)
- Also happens with a non-screen image

**Comment by hajimehoshi** [comment]
I could reproduce this with macOS + Metal.

**Comment by hajimehoshi** [comment]
I also used `-tags=ebitenginesinglethread` instead of `RunGameOptions.SingleThread`, and could reproduce this with the main branch, but not with the 2.6 branch. I'll try bisect.

**Comment by hajimehoshi** [comment]
55702a7c282d7ee3abb66750c753a2f3aded29a9 is the first bad commit
