### ISSUE TITLE
png.Encode panics when give *ebiten.Image as the argument

### ISSUE THREAD

**Issue by noppikinatta** [hajimehoshi/ebiten#2979]
### Ebitengine Version

v2.7.3

### Operating System

- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] PlayStation 5
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

v1.22.1

### What steps will reproduce the problem?

The following is a code to reproduce it. dummyImg is for operation comparison.

```
package main

import (
	"fmt"
	"image"
	"image/color"
	"image/png"
	"os"

	"github.com/hajimehoshi/ebiten/v2"
)

func main() {
	ebitenImg := ebiten.NewImage(32, 32)
	ebitenImg.Fill(color.RGBA{R: 255, A: 255})

	images := []image.Image{
		&dummyImg{},
		ebitenImg,
	}

	for i, img := range images {
		fn := func() {
			p := fmt.Sprintf("image%d.png", i)

			_, err := os.Stat(p)
			if err == nil {
				os.Remove(p)
			}

			f, err := os.Create(p)
			if err != nil {
				panic(err)
			}
			defer f.Close()

			png.Encode(f, img)
		}
		fn()
	}
}

type dummyImg struct {
}

func (d *dummyImg) ColorModel() color.Model {
	return color.RGBAModel
}

func (d *dummyImg) Bounds() image.Rectangle {
	return image.Rectangle{Max: image.Point{X: 32, Y: 32}}
}

func (d *dummyImg) At(x, y int) color.Color {
	return color.RGBA{R: 255, A: 255}
}
```

### What is the expected result?

A 32x32 red png image is output.

### What happens instead?

panics. The message is as follows.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x70 pc=0x112d9e6]

goroutine 1 [running, locked to thread]:
github.com/hajimehoshi/ebiten/v2/internal/ui.(*context).runInFrame(...)
        C:/Users/foo/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.7.3/internal/ui/context.go:306
github.com/hajimehoshi/ebiten/v2/internal/ui.(*UserInterface).readPixels(0xc0003f9088, 0xc0001eab40, {0xc000196398, 0x4, 0x4}, {{0x116bea0?, 0x0?}, {0xece5af?, 0xc000573c58?}})
        C:/Users/foo/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.7.3/internal/ui/ui.go:144 +0x226
github.com/hajimehoshi/ebiten/v2/internal/ui.(*Image).ReadPixels(0xc0001e1b60, {0xc000196398, 0x4, 0x4}, {{0xc000573cb8?, 0xecff56?}, {0x114660f?, 0x113c960?}})     
        C:/Users/foo/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.7.3/internal/ui/image.go:135 +0xa7
github.com/hajimehoshi/ebiten/v2.(*Image).at(0xc0005af1f0, 0x4f8?, 0x2955dff0a28?)
        C:/Users/foo/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.7.3/image.go:955 +0xf3
github.com/hajimehoshi/ebiten/v2.(*Image).At(0xc0005af1f0?, 0x11c7ec0?, 0x1191160?)
        C:/Users/foo/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.7.3/image.go:925 +0x13
image/png.opaque({0x1241280, 0xc0005af1f0})
        C:/Program Files/Go/src/image/png/writer.go:79 +0xd9
image/png.(*Encoder).Encode(0xc0000088a0, {0x123fe78, 0xc00035c240}, {0x1241280, 0xc0005af1f0})
        C:/Program Files/Go/src/image/png/writer.go:644 +0x47f
image/png.Encode(...)
        C:/Program Files/Go/src/image/png/writer.go:592
main.main.func1()
        C:/repo/go-app-001/cmd/png/main.go:37 +0x110
main.main()
        C:/repo/go-app-001/cmd/png/main.go:39 +0xe2
exit status 2
```

**Comment by hajimehoshi** [comment]
ReadPixels doesn't work before RunGame. I think we can have a better error message.

**Comment by hajimehoshi** [comment]
I thought returning an error was a good idea, but unfortunately there is no way to detect the error without RunGame.
