### ISSUE TITLE
graphics: Bounds() assumes Min (0,0)

### ISSUE THREAD

**Issue by j7b** [hajimehoshi/ebiten#303]
```
package main

import (
	"github.com/hajimehoshi/ebiten"
	"image"
	"image/color"
)

func main() {
	pal := make(color.Palette,256)
	for i := range pal {
		pal[i] = color.White
	}
	img := image.NewPaletted(image.Rect(0,0,240,160),pal)
	si := img.SubImage(image.Rect(238,158,240,160))
	_,err := ebiten.NewImageFromImage(si,0)
	if err != nil {
		println(err)
	}
}
```

```
panic: runtime error: index out of range

goroutine 1 [running, locked to thread]:
panic(0x40f2980, 0xc42000c0f0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/hajimehoshi/ebiten/internal/graphics.CopyImage(0x4183ae0, 0xc420070120, 0x0)
	/Volumes/Things/Shrimp/src/github.com/hajimehoshi/ebiten/internal/graphics/image.go:54 +0x5bc
github.com/hajimehoshi/ebiten.newImageImplFromImage(0x4183ae0, 0xc420070120, 0x0, 0xc4200764be, 0xc420070120, 0xc4200bd50e)
	/Volumes/Things/Shrimp/src/github.com/hajimehoshi/ebiten/imageimpl.go:79 +0xac
github.com/hajimehoshi/ebiten.NewImageFromImage(0x4183ae0, 0xc420070120, 0x0, 0xf0, 0xa0, 0x4183ae0)
	/Volumes/Things/Shrimp/src/github.com/hajimehoshi/ebiten/image.go:318 +0x43
main.main()
	/Volumes/Things/Shrimp/src/github.com/hajimehoshi/ebiten/examples/bug.go:16 +0x20a
exit status 2
```

Dx() Dy() would work but Draw should handle paletted to rgba correctly per https://blog.golang.org/go-imagedraw-package so perhaps ```case *image.Paletted:``` could be eliminated.

**Comment by hajimehoshi** [comment]
Thanks, I'm looking into that.

**Comment by hajimehoshi** [comment]
> case *image.Paletted: could be eliminated.

Yeah, but I'd keep that case for optimization. `draw.Draw` with a paletted image is slower than necessary.

**Comment by hajimehoshi** [comment]
Thanks, fixed.
