### ISSUE TITLE
.github/workflows: wasm test fails with "unexpected call to os.Exit(0) during test"

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#3075]
### Ebitengine Version

71370a01bd5f87b2f753829afcc3dc7b94b06c59

### Operating System

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] PlayStation 5
- [ ] Xbox
- [X] Web Browsers

### Go Version (`go version`)

go1.20 (and so on)

### What steps will reproduce the problem?

Run "go test" for browsers on GitHub Actions

### What is the expected result?

The test passes

### What happens instead?

The test fails

https://github.com/hajimehoshi/ebiten/actions/runs/10651026325/job/29523110919

```
panic: unexpected call to os.Exit(0) during test

goroutine 1 [running]:
os.Exit(0x0)
	/opt/hostedtoolcache/go/1.20.14/x64/src/os/proc.go:67 +0x8
main.main()
	_testmain.go:382 +0x55
http://127.0.0.1:46659/wasm_exec.js:353:23 Uncaught
TypeError: Cannot read properties of undefined (reading 'exports')
    at syscall/js.valueCall (http://127.0.0.1:46659/wasm_exec.js:354:24)
    at http://127.0.0.1:46659/ebiten.wasm:wasm-function[1465]:0x121713
    at http://127.0.0.1:46659/ebiten.wasm:wasm-function[1442]:0x11eb3f
    at http://127.0.0.1:46659/ebiten.wasm:wasm-function[1610]:0x130cc0
    at http://127.0.0.1:46659/ebiten.wasm:wasm-function[1606]:0x12f808
    at http://127.0.0.1:46659/ebiten.wasm:wasm-function[1992]:0x17b444
    at http://127.0.0.1:46659/ebiten.wasm:wasm-function[2080]:0x18a753
    at http://127.0.0.1:46659/ebiten.wasm:wasm-function[2672]:0x228baf
    at http://127.0.0.1:46659/ebiten.wasm:wasm-function[3082]:0x29567c
    at http://127.0.0.1:46659/ebiten.wasm:wasm-function[3089]:0x298969
exit with status 2
FAIL	github.com/hajimehoshi/ebiten/v2	25.578s
```

**Comment by hajimehoshi** [comment]
The mysterious thing is that `-test.paniconexit0` should be false by default. So, does a third party library change this flag value?
