### ISSUE TITLE
Crash on linux with wayland and external monitor

### ISSUE THREAD

**Issue by gucio321** [hajimehoshi/ebiten#3094]
### Ebitengine Version

6eb0271f83cb94340d5789344a1bfa22b06e8c54

### Operating System

- [ ] Windows
- [ ] macOS
- [X] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] PlayStation 5
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

go version go1.23.1 linux/amd64

### What steps will reproduce the problem?

- run any example
- turn off monitor
- turn monitor back on

### What is the expected result?

everything should be as it was before turning monitor off

### What happens instead?

```console
X Error of failed request:  BadRRCrtc (invalid Crtc parameter)
  Major opcode of failed request:  140 (RANDR)
  Minor opcode of failed request:  20 (RRGetCrtcInfo)
  Crtc id in failed request: 0x56e
  Serial number of failed request:  1855
  Current serial number in output stream:  1855
exit status 1
```

### Anything else you feel useful to add?

I use gnome-shell on Wayland, this is why I suppose that ebiten uses xwaylandbridge. Why does it need xorg?

**Comment by gucio321** [comment]
- ref: https://github.com/glfw/glfw/issues/1147

**Comment by gucio321** [comment]
I think ebiten uses glfw on linux.
I have glfw v3.3 header in /usr/include/GLFW (idk what header ebiten uses)

**Comment by gucio321** [comment]
first v3.3 was released in 2019 and the above issue was fixed in 2017, so I think this is a iplementation bug somewhere here (?)

**Comment by hajimehoshi** [comment]
Ebitengine dropped Wayland support from GLFW.

**Comment by gucio321** [comment]
> Ebitengine dropped Wayland support from GLFW.

So what deos it use for linux-wayland now? maybe I can share some more info?

**Comment by hajimehoshi** [comment]
IIUC an X emulation layer works.

**Comment by gucio321** [comment]
interessting, on examples/fullscreen it panics with
```console
[fullscreen (0) ]$ go run .
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x6d0c86]

goroutine 1 [running, locked to thread]:
github.com/hajimehoshi/ebiten/v2/internal/ui.(*Monitor).DeviceScaleFactor(...)
	/home/me/git/ebiten/internal/ui/monitor_glfw.go:45
github.com/hajimehoshi/ebiten/v2/internal/ui.(*UserInterface).registerWindowFramebufferSizeCallback.func1(0xc00017a608?, 0x280, 0x205)
	/home/me/git/ebiten/internal/ui/ui_glfw.go:968 +0x86
github.com/hajimehoshi/ebiten/v2/internal/glfw.goFramebufferSizeCB(0xc0000061c0?, 0x280, 0x205)
	/home/me/git/ebiten/internal/glfw/window_unix.go:147 +0x45
github.com/hajimehoshi/ebiten/v2/internal/glfw._Cfunc_glfwPollEvents()
	_cgo_gotypes.go:1004 +0x3f
github.com/hajimehoshi/ebiten/v2/internal/glfw.PollEvents()
	/home/me/git/ebiten/internal/glfw/window_unix.go:952 +0xf
github.com/hajimehoshi/ebiten/v2/internal/ui.(*UserInterface).update(0xc00017a608)
	/home/me/git/ebiten/internal/ui/ui_glfw.go:1377 +0x127
github.com/hajimehoshi/ebiten/v2/internal/ui.(*UserInterface).updateGame.func1()
	/home/me/git/ebiten/internal/ui/ui_glfw.go:1471 +0x45
github.com/hajimehoshi/ebiten/v2/internal/thread.(*OSThread).Loop.func1({0xc0001cc300?, 0x80?}, 0x20?)
	/home/me/git/ebiten/internal/thread/thread.go:67 +0x4f
github.com/hajimehoshi/ebiten/v2/internal/thread.(*OSThread).Loop(0xc00021ab00, {0x9632f8, 0xc0009cac30})
	/home/me/git/ebiten/internal/thread/thread.go:68 +0x79
github.com/hajimehoshi/ebiten/v2/internal/ui.(*UserInterface).runMultiThread(0xc00017a608, {0x9654e0, 0xc0000d2380}, 0xc000384dc0)
	/home/me/git/ebiten/internal/ui/run.go:75 +0x322
github.com/hajimehoshi/ebiten/v2/internal/ui.(*UserInterface).Run(0x961518?, {0x9654e0?, 0xc0000d2380?}, 0x3?)
	/home/me/git/ebiten/internal/ui/run.go:33 +0x30
github.com/hajimehoshi/ebiten/v2.RunGameWithOptions({0x961518, 0xc0009b71f8}, 0x0)
	/home/me/git/ebiten/run.go:345 +0x208
github.com/hajimehoshi/ebiten/v2.RunGame(...)
	/home/me/git/ebiten/run.go:236
main.main()
	/home/me/git/ebiten/examples/fullscreen/main.go:117 +0x56
exit status 2

```
so it uses glfw on wayland.

**Comment by hajimehoshi** [comment]
Does this issue still happen with the latest commit (264de7cf4b9fd5cf43eea1a83f41bb4e59a1a35e)?

**Comment by gucio321** [comment]
yes, tested on `a4717f7f95ab6cf537ca6a27e7b8b7e3c0d4ab30`, still same result:

```console
X Error of failed request:  BadRRCrtc (invalid Crtc parameter)
  Major opcode of failed request:  140 (RANDR)
  Minor opcode of failed request:  20 (RRGetCrtcInfo)
  Crtc id in failed request: 0x483
  Serial number of failed request:  5141
  Current serial number in output stream:  5141
exit status 1
```

**Comment by hajimehoshi** [comment]
Oops, I meant this crash: https://github.com/hajimehoshi/ebiten/issues/3094#issuecomment-2369228725

**Comment by gucio321** [comment]
youp, this one on fullscreen is fixed.

**Comment by hajimehoshi** [comment]
Analysis, and a reproduction that does not need Wayland or a second monitor.

## Why the process exits

`XRRGetCrtcInfo` is called with a CRTC XID that the X server has already destroyed. Xlib's default error handler prints the `BadRRCrtc` message and calls `exit(1)`, so the `ciPtr == 0` checks in [`internal/glfw/x11_monitor_linbsd.go`](https://github.com/hajimehoshi/ebiten/blob/main/internal/glfw/x11_monitor_linbsd.go) never get a chance to run.

This is specific to Wayland because of how XWayland models outputs. It creates one `RRCrtc` and one `RROutput` per `wl_output`, and destroys both when the output goes away: `xwl_output_remove()` in `hw/xwayland/xwayland-output.c` calls `RRCrtcDestroy()` / `RROutputDestroy()`. On bare X11 the CRTC object survives and is merely disabled, so a cached XID stays valid; under XWayland the XID becomes invalid the moment the monitor is turned off.

## The call chain

1. RandR notifies, and `processEvent` calls `pollMonitorsX11()`.
2. `pollMonitorsX11` reports newly connected outputs from inside the loop over `sr.Outputs`, and removes the monitors that went away only *after* that loop.
3. `inputMonitor()` invokes the monitor callback right away, so the callback runs while the destroyed monitor is still in `_glfw.monitors`.
4. The callback registered in `internal/ui/ui_glfw.go` calls `(*monitors).update`, which walks every monitor `GetMonitors()` returns and calls `GetPos` / `GetContentScale` / `GetVideoMode` on each of them.
5. `GetPos` on the destroyed monitor issues `XRRGetCrtcInfo(<destroyed CRTC>)` → `BadRRCrtc` → `exit(1)`.

A second, related bug feeds the same failure: when an output is already known, `pollMonitorsX11` skips it without refreshing `monitor.platform.crtc`, so a CRTC reassignment leaves a stale XID cached indefinitely.

## Reproducing

The fatal part needs no monitor at all. Under a plain `Xvfb :99 -screen 0 1280x1024x24`, asking for any CRTC XID that does not exist reproduces the report byte for byte:

```go
srPtr := randr.GetScreenResourcesCurrent(display, _glfw.platformWindow.root)
randr.GetCrtcInfo(display, srPtr, 0xdeadbeef)
```

```
X Error of failed request:  BadRRCrtc (invalid Crtc parameter)
  Major opcode of failed request:  140 (RANDR)
  Minor opcode of failed request:  20 (RRGetCrtcInfo)
  Crtc id in failed request: 0xdeadbeef
  Serial number of failed request:  88
  Current serial number in output stream:  88
exit status 1
```

For the whole chain, put a `Monitor` holding a destroyed CRTC into `_glfw.monitors` (the state XWayland leaves behind), register a monitor callback that enumerates monitors the way `internal/ui` does, and call `pollMonitorsX11()`. With logging added:

```
repro: calling pollMonitorsX11
repro: monitor callback: "screen" event=262145
repro:   GetPos on "destroyed-monitor" (crtc 0xdeadbeef)
X Error of failed request:  BadRRCrtc (invalid Crtc parameter)
  Major opcode of failed request:  140 (RANDR)
  Minor opcode of failed request:  20 (RRGetCrtcInfo)
exit status 1
```

Wrapping that single `XRRGetCrtcInfo` in `grabErrorHandlerX11()` / `releaseErrorHandlerX11()` is enough to keep the process alive; `XRRGetCrtcInfo` then returns `NULL`, the stale monitor answers harmlessly, and the disconnection is reported on the next pass:

```
repro: monitor callback: "screen" event=262145
repro:   GetPos on "destroyed-monitor" (crtc 0xdeadbeef)
repro:   -> (0, 0) err=<nil>
repro:   GetPos on "screen" (crtc 0x3b)
repro:   -> (0, 0) err=<nil>
repro: monitor callback: "destroyed-monitor" event=262146
repro: pollMonitorsX11 returned, the process survived
```

Xvfb cannot destroy a CRTC, so the reproduction injects the destroyed XID rather than unplugging a monitor; the unplug half is XWayland's `RRCrtcDestroy()` above. Upstream GLFW's `x11_monitor.c` has the same structure, which is why this also happened on the cgo GLFW builds this issue was originally filed against (see also glfw/glfw#1147).

## Fix

1. Guard every RandR query that takes a possibly stale XID with the X error handler and honour the `NULL` return. `XRRGetOutputInfo` needs the same treatment, since `BadRROutput` is the same story.
2. Refresh `platform.crtc` and `platform.index` for outputs that are already known.
3. Report disconnections before connections in `pollMonitorsX11`, so the monitor callback never observes a monitor that is already gone.

*Investigated by Claude (Claude Code) on behalf of @hajimehoshi.*

**Comment by hajimehoshi** [comment]
Follow-up to the analysis above: this now reproduces end to end on a real compositor, without needing the injected XID, and doing so corrected part of what I wrote.

## Reproducing it for real

`Xvfb` can only disable a CRTC, never destroy one, which is why the earlier reproduction had to inject a destroyed XID. `sway` on its headless backend is a real compositor with a real XWayland, and it can add and remove outputs while an app runs. In a container with `sway` and `xwayland`:

```sh
export XDG_RUNTIME_DIR=/tmp/xdg; mkdir -p $XDG_RUNTIME_DIR; chmod 700 $XDG_RUNTIME_DIR
export WLR_BACKENDS=headless WLR_LIBINPUT_NO_DEVICES=1 WLR_RENDERER=pixman LIBGL_ALWAYS_SOFTWARE=1
printf 'output HEADLESS-1 mode 1280x1024\nxwayland enable\n' > /tmp/cfg/config
sway -c /tmp/cfg/config &
export SWAYSOCK=$(ls $XDG_RUNTIME_DIR/sway-ipc.* | head -1)
export DISPLAY=:0

swaymsg create_output              # a second monitor
./anyebitengineapp &

swaymsg "output HEADLESS-2 unplug; create_output"    # turn it off and back on
```

An unmodified Ebitengine app dies on the first cycle:

```
X Error of failed request:  BadRRCrtc (invalid Crtc parameter)
  Major opcode of failed request:  139 (RANDR)
  Minor opcode of failed request:  20 (RRGetCrtcInfo)
  Crtc id in failed request: 0x22
exit status 1
```

## What I had wrong

The last line of that snippet matters more than I realised. Two things do **not** reproduce this:

- Turning a monitor off and leaving it off.
- Turning it off and back on as two separate compositor requests, even back to back with no delay. Eight rounds of that survived.

A lone disconnection is safe because `inputMonitor` removes a monitor from `_glfw.monitors` *before* it invokes the monitor callback, so the callback never sees it. The crash needs a connection and a disconnection to land in the **same** `pollMonitorsX11` call. Only then is the connection reported from inside the loop over the outputs while the disconnected monitor is still listed, and `internal/ui`'s callback enumerates straight into the destroyed CRTC. Issuing both as one `swaymsg` message forces that, and it is what a compositor that reconfigures its outputs in a single go does on real hardware, which fits turning an external monitor off and back on under GNOME.

So of the three parts of the fix, reporting disconnections before connections is the one that stops this particular crash, rather than being the defensive extra I took it for. The error handler guards are what keep every other stale-XID path from being fatal, including the plain races.

With all three in place the same script runs eight hotplug cycles, tracks the monitor list correctly throughout, and exits 0.

*Investigated by Claude (Claude Code) on behalf of @hajimehoshi.*
