### ISSUE TITLE
Go's int not supported on amd64

### ISSUE THREAD

**Issue by TotallyGamerJet** [hajimehoshi/ebiten#3135]
### Ebitengine Version

[c3ea539](https://github.com/hajimehoshi/ebiten/commit/c3ea539cdbb1b685f525f7c67e4498a7cd93d48d)

### Operating System

- [ ] Windows
- [X] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] PlayStation 5
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

go version go1.22.1 darwin/arm64

### What steps will reproduce the problem?

`CGO_ENABLED=1 GOARCH=amd64 go run examples/2048/main.go`

### What is the expected result?

Runs just fine

### What happens instead?

```
2024-10-19 08:29:33.587 ___2go_build_github_com_hajimehoshi_ebiten_v2_examples_2048[27533:680288] [CAMetalLayer nextDrawable] returning nil because allocation failed.
panic: purego: unsupported kind int

goroutine 7 [running]:
github.com/ebitengine/purego.tryPlaceRegister.func2({0x100d586c0?, 0xc0001679c0?, 0xc000156d40?})
        /Users/jarrettkuklis/go/pkg/mod/github.com/ebitengine/purego@v0.9.0-alpha.0.20241018101553-999f588e4548/struct_amd64.go:234 +0x64a
github.com/ebitengine/purego.tryPlaceRegister({0x100d586c0?, 0xc0001679c0?, 0xc000156e00?}, 0xc000081300?, 0xc0002221c0?)
        /Users/jarrettkuklis/go/pkg/mod/github.com/ebitengine/purego@v0.9.0-alpha.0.20241018101553-999f588e4548/struct_amd64.go:247 +0xf6
github.com/ebitengine/purego.addStruct({0x100d586c0?, 0xc0001679c0?, 0x10?}, 0xc0000370a0, 0xc0000370a8, 0xc000037098, 0xc0001572a8, 0xc000157288, 0xc0000372c8, {0x0, ...})
        /Users/jarrettkuklis/go/pkg/mod/github.com/ebitengine/purego@v0.9.0-alpha.0.20241018101553-999f588e4548/struct_amd64.go:103 +0x15f
github.com/ebitengine/purego.addValue({0x100d586c0?, 0xc0001679c0?, 0x2?}, {0x0, 0x0, 0x0}, 0xc0001572a8, 0x0?, 0x0?, 0xc0001570a0, ...)
        /Users/jarrettkuklis/go/pkg/mod/github.com/ebitengine/purego@v0.9.0-alpha.0.20241018101553-999f588e4548/func.go:381 +0x40e
github.com/ebitengine/purego.RegisterFunc.func4({0xc0008ffdb0, 0x3, 0x3})
        /Users/jarrettkuklis/go/pkg/mod/github.com/ebitengine/purego@v0.9.0-alpha.0.20241018101553-999f588e4548/func.go:279 +0xf34
github.com/ebitengine/purego/objc.ID.Send(...)
        /Users/jarrettkuklis/go/pkg/mod/github.com/ebitengine/purego@v0.9.0-alpha.0.20241018101553-999f588e4548/objc/objc_runtime_darwin.go:107
github.com/hajimehoshi/ebiten/v2/internal/graphicsdriver/metal/mtl.RenderCommandEncoder.SetScissorRect(...)
        /Users/jarrettkuklis/Documents/GolandProjects/ebiten/internal/graphicsdriver/metal/mtl/mtl_darwin.go:916
github.com/hajimehoshi/ebiten/v2/internal/graphicsdriver/metal.(*Graphics).draw(0xc000096000, 0xc00044c0c0, {0xc000219290, 0x1, 0x109b15018?}, {0x0, 0x0, 0x0, 0x0}, 0x0, ...)
        /Users/jarrettkuklis/Documents/GolandProjects/ebiten/internal/graphicsdriver/metal/graphics_darwin.go:581 +0xe4b
github.com/hajimehoshi/ebiten/v2/internal/graphicsdriver/metal.(*Graphics).DrawTriangles(0xc000096000, 0x400?, {0x0, 0x0, 0x0, 0x0}, 0x3, {0xc000219290, 0x1, 0x1}, ...)
        /Users/jarrettkuklis/Documents/GolandProjects/ebiten/internal/graphicsdriver/metal/graphics_darwin.go:690 +0x89d
github.com/hajimehoshi/ebiten/v2/internal/graphicscommand.(*drawTrianglesCommand).Exec(0xc00019f5e0, 0xc000832000?, {0x100d962d8, 0xc000096000}, 0x0)
        /Users/jarrettkuklis/Documents/GolandProjects/ebiten/internal/graphicscommand/command.go:161 +0x1e2
github.com/hajimehoshi/ebiten/v2/internal/graphicscommand.(*commandQueue).flush(0xc00035c630, {0x100d962d8, 0xc000096000}, 0x1, {0x100d90190?, 0x101215d40?})
        /Users/jarrettkuklis/Documents/GolandProjects/ebiten/internal/graphicscommand/commandqueue.go:305 +0x5fc
github.com/hajimehoshi/ebiten/v2/internal/graphicscommand.(*commandQueue).Flush.func1()
        /Users/jarrettkuklis/Documents/GolandProjects/ebiten/internal/graphicscommand/commandqueue.go:217 +0x78
github.com/hajimehoshi/ebiten/v2/internal/thread.(*OSThread).Loop.func1({0xc00024a900?, 0xc8?}, 0x0?)
        /Users/jarrettkuklis/Documents/GolandProjects/ebiten/internal/thread/thread.go:67 +0x4f
github.com/hajimehoshi/ebiten/v2/internal/thread.(*OSThread).Loop(0xc000025000, {0x100d93348, 0xc0008eaf00})
        /Users/jarrettkuklis/Documents/GolandProjects/ebiten/internal/thread/thread.go:68 +0x79
github.com/hajimehoshi/ebiten/v2/internal/graphicscommand.LoopRenderThread(...)
        /Users/jarrettkuklis/Documents/GolandProjects/ebiten/internal/graphicscommand/thread.go:31
github.com/hajimehoshi/ebiten/v2/internal/ui.(*UserInterface).runMultiThread.func1()
        /Users/jarrettkuklis/Documents/GolandProjects/ebiten/internal/ui/run.go:50 +0x4f
golang.org/x/sync/errgroup.(*Group).Go.func1()
        /Users/jarrettkuklis/go/pkg/mod/golang.org/x/sync@v0.8.0/errgroup/errgroup.go:78 +0x50
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 1
        /Users/jarrettkuklis/go/pkg/mod/golang.org/x/sync@v0.8.0/errgroup/errgroup.go:75 +0x96

Process finished with the exit code 2
```

### Anything else you feel useful to add?

n/a

**Comment by TotallyGamerJet** [comment]
I am currently working on a fix for purego

**Comment by hajimehoshi** [comment]
Interesting. `CGO_ENABLED=1 GOARCH=amd64 go run examples/2048` actually failed with the main branch and the 2.8 branch, but the GitHub Actions test passed.

**Comment by hajimehoshi** [comment]
Hmm? The path `examples/2048` doesn't indicate any packages.

**Comment by TotallyGamerJet** [comment]
> Hmm? The path `examples/2048` doesn't indicate any packages.

Sorry forgot to include the `/main.go` part

**Comment by hajimehoshi** [comment]
Confirmed:

```
% CGO_ENABLED=1 GOARCH=amd64 go run ./examples/2048
2024-10-19 23:12:06.141 2048[78030:175245541] [CAMetalLayer nextDrawable] returning nil because allocation failed.
panic: purego: unsupported kind int

goroutine 10 [running]:
github.com/ebitengine/purego.tryPlaceRegister.func2({0x1025ce6e0?, 0xc0002ca040?, 0xc000142d40?})
        /Users/hajimehoshi/go/pkg/mod/github.com/ebitengine/purego@v0.9.0-alpha.0.20241018101553-999f588e4548/struct_amd64.go:234 +0x64a
github.com/ebitengine/purego.tryPlaceRegister({0x1025ce6e0?, 0xc0002ca040?, 0xc000142e00?}, 0xc000081300?, 0xc000103500?)
        /Users/hajimehoshi/go/pkg/mod/github.com/ebitengine/purego@v0.9.0-alpha.0.20241018101553-999f588e4548/struct_amd64.go:247 +0xf6
github.com/ebitengine/purego.addStruct({0x1025ce6e0?, 0xc0002ca040?, 0x10?}, 0xc00003d0a0, 0xc00003d0a8, 0xc00003d098, 0xc0001432a8, 0xc000143288, 0xc00003d2c8, {0x0, ...})
        /Users/hajimehoshi/go/pkg/mod/github.com/ebitengine/purego@v0.9.0-alpha.0.20241018101553-999f588e4548/struct_amd64.go:103 +0x15f
github.com/ebitengine/purego.addValue({0x1025ce6e0?, 0xc0002ca040?, 0x2?}, {0x0, 0x0, 0x0}, 0xc0001432a8, 0x0?, 0x0?, 0xc0001430a0, ...)
        /Users/hajimehoshi/go/pkg/mod/github.com/ebitengine/purego@v0.9.0-alpha.0.20241018101553-999f588e4548/func.go:381 +0x40e
github.com/ebitengine/purego.RegisterFunc.func4({0xc0006c54a0, 0x3, 0x3})
        /Users/hajimehoshi/go/pkg/mod/github.com/ebitengine/purego@v0.9.0-alpha.0.20241018101553-999f588e4548/func.go:279 +0xf34
github.com/ebitengine/purego/objc.ID.Send(...)
        /Users/hajimehoshi/go/pkg/mod/github.com/ebitengine/purego@v0.9.0-alpha.0.20241018101553-999f588e4548/objc/objc_runtime_darwin.go:107
github.com/hajimehoshi/ebiten/v2/internal/graphicsdriver/metal/mtl.RenderCommandEncoder.SetScissorRect(...)
        /Users/hajimehoshi/ebiten/internal/graphicsdriver/metal/mtl/mtl_darwin.go:916
github.com/hajimehoshi/ebiten/v2/internal/graphicsdriver/metal.(*Graphics).draw(0xc00009e000, 0xc00038ab80, {0xc0006ce2a0, 0x1, 0x102a8a116?}, {0x0, 0x0, 0x0, 0x0}, 0x0, ...)
        /Users/hajimehoshi/ebiten/internal/graphicsdriver/metal/graphics_darwin.go:581 +0xe4b
github.com/hajimehoshi/ebiten/v2/internal/graphicsdriver/metal.(*Graphics).DrawTriangles(0xc00009e000, 0x400?, {0x0, 0x0, 0x0, 0x0}, 0x3, {0xc0006ce2a0, 0x1, 0x1}, ...)
        /Users/hajimehoshi/ebiten/internal/graphicsdriver/metal/graphics_darwin.go:690 +0x89d
github.com/hajimehoshi/ebiten/v2/internal/graphicscommand.(*drawTrianglesCommand).Exec(0xc0002d2000, 0xc0009ae000?, {0x10260c2f8, 0xc00009e000}, 0x0)
        /Users/hajimehoshi/ebiten/internal/graphicscommand/command.go:161 +0x1e2
github.com/hajimehoshi/ebiten/v2/internal/graphicscommand.(*commandQueue).flush(0xc000332630, {0x10260c2f8, 0xc00009e000}, 0x1, {0x1026061b0?, 0x102a88ca0?})
        /Users/hajimehoshi/ebiten/internal/graphicscommand/commandqueue.go:305 +0x5fc
github.com/hajimehoshi/ebiten/v2/internal/graphicscommand.(*commandQueue).Flush.func1()
        /Users/hajimehoshi/ebiten/internal/graphicscommand/commandqueue.go:217 +0x78
github.com/hajimehoshi/ebiten/v2/internal/thread.(*OSThread).Loop.func1({0xc00009ac40?, 0xc8?}, 0x0?)
        /Users/hajimehoshi/ebiten/internal/thread/thread.go:67 +0x4f
github.com/hajimehoshi/ebiten/v2/internal/thread.(*OSThread).Loop(0xc00027cec0, {0x102609368, 0xc0008c6e60})
        /Users/hajimehoshi/ebiten/internal/thread/thread.go:68 +0x79
github.com/hajimehoshi/ebiten/v2/internal/graphicscommand.LoopRenderThread(...)
        /Users/hajimehoshi/ebiten/internal/graphicscommand/thread.go:31
github.com/hajimehoshi/ebiten/v2/internal/ui.(*UserInterface).runMultiThread.func1()
        /Users/hajimehoshi/ebiten/internal/ui/run.go:50 +0x4f
golang.org/x/sync/errgroup.(*Group).Go.func1()
        /Users/hajimehoshi/go/pkg/mod/golang.org/x/sync@v0.8.0/errgroup/errgroup.go:78 +0x50
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 1
        /Users/hajimehoshi/go/pkg/mod/golang.org/x/sync@v0.8.0/errgroup/errgroup.go:75 +0x96
exit status 2
```

**Comment by hajimehoshi** [comment]
I've updated PureGo, and now the situation has changed

```
% CGO_ENABLED=1 GOARCH=amd64 go run ./examples/2048
2024-10-19 23:23:00.614 2048[81319:175268920] [CAMetalLayer nextDrawable] returning nil because allocation failed.
-[IOGPUMetalCommandBuffer validate]:216: failed assertion `commit command buffer with uncommitted encoder'
SIGABRT: abort
PC=0x7ff8058c714a m=5 sigcode=0
signal arrived during cgo execution

goroutine 12 gp=0xc000582c40 m=5 mp=0xc000180008 [syscall, locked to thread]:
runtime.cgocall(0x100be6060, 0xc0007080d0)
        /usr/local/go/src/runtime/cgocall.go:167 +0x4b fp=0xc00099e3a0 sp=0xc00099e368 pc=0x100a3278b
github.com/ebitengine/purego.RegisterFunc.func4({0xc0008c7590, 0x3, 0x3})
        /Users/hajimehoshi/go/pkg/mod/github.com/ebitengine/purego@v0.9.0-alpha.0.20241019141807-abe9f9ad3f22/func.go:299 +0x7df fp=0xc00099e7f0 sp=0xc00099e3a0 pc=0x100be26df
reflect.callReflect(0xc00011b350, 0xc00099ecb0, 0xc00099eb88, 0xc00099eb90)
        /usr/local/go/src/reflect/value.go:767 +0x53d fp=0xc00099eb38 sp=0xc00099e7f0 pc=0x100a6d81d
reflect.callReflect(0xc00011b350, 0xc00099ecb0, 0xc00099eb88, 0xc00099eb90)
        <autogenerated>:1 +0x45 fp=0xc00099eb68 sp=0xc00099eb38 pc=0x100a7fb65
reflect.makeFuncStub()
        /usr/local/go/src/reflect/asm_amd64.s:47 +0x6e fp=0xc00099ecb0 sp=0xc00099eb68 pc=0x100a7be2e
github.com/ebitengine/purego/objc.ID.Send(...)
        /Users/hajimehoshi/go/pkg/mod/github.com/ebitengine/purego@v0.9.0-alpha.0.20241019141807-abe9f9ad3f22/objc/objc_runtime_darwin.go:107
github.com/hajimehoshi/ebiten/v2/internal/graphicsdriver/metal/mtl.CommandBuffer.Commit(...)
        /Users/hajimehoshi/ebiten/internal/graphicsdriver/metal/mtl/mtl_darwin.go:829
github.com/hajimehoshi/ebiten/v2/internal/graphicsdriver/metal.(*Graphics).flushIfNeeded(0xc00017e200, 0x1)
        /Users/hajimehoshi/ebiten/internal/graphicsdriver/metal/graphics_darwin.go:249 +0xd0 fp=0xc00099ed00 sp=0xc00099ecb0 pc=0x100c1aad0
github.com/hajimehoshi/ebiten/v2/internal/graphicsdriver/metal.(*Graphics).End(0xc00017e200, 0xb8?)
        /Users/hajimehoshi/ebiten/internal/graphicsdriver/metal/graphics_darwin.go:127 +0x18 fp=0xc00099ed38 sp=0xc00099ed00 pc=0x100c19f38
github.com/hajimehoshi/ebiten/v2/internal/graphicscommand.(*commandQueue).flush.func1()
        /Users/hajimehoshi/ebiten/internal/graphicscommand/commandqueue.go:253 +0x45 fp=0xc00099edd0 sp=0xc00099ed38 pc=0x100bac685
panic({0x100ea9880?, 0xc0008b61c8?})
        /usr/local/go/src/runtime/panic.go:785 +0x132 fp=0xc00099ee80 sp=0xc00099edd0 pc=0x100a380d2
runtime.goPanicIndex(0x9, 0x9)
        /usr/local/go/src/runtime/panic.go:115 +0x74 fp=0xc00099eec0 sp=0xc00099ee80 pc=0x1009ff854
github.com/ebitengine/purego.RegisterFunc.func4.1(0x100e90fa0?)
        /Users/hajimehoshi/go/pkg/mod/github.com/ebitengine/purego@v0.9.0-alpha.0.20241019141807-abe9f9ad3f22/func.go:218 +0x31 fp=0xc00099eee0 sp=0xc00099eec0 pc=0x100be3131
github.com/ebitengine/purego.placeStack({0x100e90fa0?, 0xc0008b61b0?, 0x100a0dde6?}, 0xc00099f458)
        /Users/hajimehoshi/go/pkg/mod/github.com/ebitengine/purego@v0.9.0-alpha.0.20241019141807-abe9f9ad3f22/struct_amd64.go:247 +0x10a fp=0xc00099ef58 sp=0xc00099eee0 pc=0x100be4dca
github.com/ebitengine/purego.addStruct({0x100e90fa0?, 0xc0008b61b0?, 0xc000143088?}, 0xc000143230, 0xc000143238, 0xc000143228, 0xc000143438, 0xc000143418, 0xc000143458, {0x0, ...})
        /Users/hajimehoshi/go/pkg/mod/github.com/ebitengine/purego@v0.9.0-alpha.0.20241019141807-abe9f9ad3f22/struct_amd64.go:109 +0x1b0 fp=0xc00099efc0 sp=0xc00099ef58 pc=0x100be4190
github.com/ebitengine/purego.addValue({0x100e90fa0?, 0xc0008b61b0?, 0x3?}, {0x0, 0x0, 0x0}, 0xc000143438, 0xc000143530?, 0x100be2bb0?, 0xc000143230, ...)
        /Users/hajimehoshi/go/pkg/mod/github.com/ebitengine/purego@v0.9.0-alpha.0.20241019141807-abe9f9ad3f22/func.go:381 +0x40e fp=0xc00099f090 sp=0xc00099efc0 pc=0x100be35ae
github.com/ebitengine/purego.RegisterFunc.func4({0xc0008c74f0, 0x3, 0x3})
        /Users/hajimehoshi/go/pkg/mod/github.com/ebitengine/purego@v0.9.0-alpha.0.20241019141807-abe9f9ad3f22/func.go:279 +0xf34 fp=0xc00099f4e0 sp=0xc00099f090 pc=0x100be2e34
reflect.callReflect(0xc00011b350, 0xc00099f9a0, 0xc00099f878, 0xc00099f880)
        /usr/local/go/src/reflect/value.go:767 +0x53d fp=0xc00099f828 sp=0xc00099f4e0 pc=0x100a6d81d
reflect.callReflect(0xc00011b350, 0xc0001439a0, 0xc000143878, 0xc000143880)
        <autogenerated>:1 +0x45 fp=0xc00099f858 sp=0xc00099f828 pc=0x100a7fb65
reflect.makeFuncStub()
        /usr/local/go/src/reflect/asm_amd64.s:47 +0x6e fp=0xc00099f9a0 sp=0xc00099f858 pc=0x100a7be2e
github.com/ebitengine/purego/objc.ID.Send(...)
        /Users/hajimehoshi/go/pkg/mod/github.com/ebitengine/purego@v0.9.0-alpha.0.20241019141807-abe9f9ad3f22/objc/objc_runtime_darwin.go:107
github.com/hajimehoshi/ebiten/v2/internal/graphicsdriver/metal/mtl.BlitCommandEncoder.CopyFromTexture({{0x100a338dd?}}, {0x0?}, 0x0, 0x0, {0x0, 0x0, 0x0}, {0x4, 0x4, 0x1}, ...)
        /Users/hajimehoshi/ebiten/internal/graphicsdriver/metal/mtl/mtl_darwin.go:1007 +0x2bf fp=0xc00099fa00 sp=0xc00099f9a0 pc=0x100c0c9bf
github.com/hajimehoshi/ebiten/v2/internal/graphicsdriver/metal.(*Image).WritePixels(0xc00009b380, {0xc0000c20b0, 0x3, 0xc0000b24b0?})
        /Users/hajimehoshi/ebiten/internal/graphicsdriver/metal/graphics_darwin.go:886 +0x64d fp=0xc00099fb50 sp=0xc00099fa00 pc=0x100c1f4cd
github.com/hajimehoshi/ebiten/v2/internal/graphicscommand.(*writePixelsCommand).Exec(0xc00070a0e0, 0xc0004571e0, {0x100edd2f8?, 0xc00017e200?}, 0x6?)
        /Users/hajimehoshi/ebiten/internal/graphicscommand/command.go:290 +0x3ec fp=0xc00099fc70 sp=0xc00099fb50 pc=0x100baa10c
github.com/hajimehoshi/ebiten/v2/internal/graphicscommand.(*commandQueue).flush(0xc0004571e0, {0x100edd2f8, 0xc00017e200}, 0x1, {0x100ed71b0?, 0x101359ca0?})
        /Users/hajimehoshi/ebiten/internal/graphicscommand/commandqueue.go:305 +0x5fc fp=0xc00099fde8 sp=0xc00099fc70 pc=0x100bac45c
github.com/hajimehoshi/ebiten/v2/internal/graphicscommand.(*commandQueue).Flush.func1()
        /Users/hajimehoshi/ebiten/internal/graphicscommand/commandqueue.go:217 +0x78 fp=0xc00099fe60 sp=0xc00099fde8 pc=0x100babd38
github.com/hajimehoshi/ebiten/v2/internal/thread.(*OSThread).Loop.func1({0xc00039a6c0?, 0xc8?}, 0x100ed9380?)
        /Users/hajimehoshi/ebiten/internal/thread/thread.go:67 +0x4f fp=0xc00099fe90 sp=0xc00099fe60 pc=0x100ba866f
github.com/hajimehoshi/ebiten/v2/internal/thread.(*OSThread).Loop(0xc000123440, {0x100eda368, 0xc00097ae60})
        /Users/hajimehoshi/ebiten/internal/thread/thread.go:68 +0x79 fp=0xc00099ff30 sp=0xc00099fe90 pc=0x100ba84f9
github.com/hajimehoshi/ebiten/v2/internal/graphicscommand.LoopRenderThread(...)
        /Users/hajimehoshi/ebiten/internal/graphicscommand/thread.go:31
github.com/hajimehoshi/ebiten/v2/internal/ui.(*UserInterface).runMultiThread.func1()
        /Users/hajimehoshi/ebiten/internal/ui/run.go:50 +0x4f fp=0xc00099ff78 sp=0xc00099ff30 pc=0x100c3ae4f
golang.org/x/sync/errgroup.(*Group).Go.func1()
        /Users/hajimehoshi/go/pkg/mod/golang.org/x/sync@v0.8.0/errgroup/errgroup.go:78 +0x50 fp=0xc00099ffe0 sp=0xc00099ff78 pc=0x100bafdd0
runtime.goexit({})
        /usr/local/go/src/runtime/asm_amd64.s:1700 +0x1 fp=0xc00099ffe8 sp=0xc00099ffe0 pc=0x100a400e1
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 1
        /Users/hajimehoshi/go/pkg/mod/golang.org/x/sync@v0.8.0/errgroup/errgroup.go:75 +0x96
```
