### ISSUE TITLE
Crash on an Alpine container

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#396]
go version go1.7.3 linux/amd64

```
goroutine 1 [running, locked to thread]:
panic(0x55edf492e880, 0xc420010180)
    /usr/lib/go/src/runtime/panic.go:500 +0x1a5
github.com/go-gl/glfw/v3.2/glfw.acceptError(0x0, 0x0, 0x0, 0x1, 0xc420041e28)
    /root/Go/src/github.com/go-gl/glfw/v3.2/glfw/error.go:173 +0x27f
github.com/go-gl/glfw/v3.2/glfw.panicError()
    /root/Go/src/github.com/go-gl/glfw/v3.2/glfw/error.go:184 +0x3e
github.com/go-gl/glfw/v3.2/glfw.WindowHint(0x20004, 0x0)
    /root/Go/src/github.com/go-gl/glfw/v3.2/glfw/window.go:229 +0x3a
github.com/hajimehoshi/ebiten/internal/ui.initialize(0xc42000e360, 0x55edf49ad470)
    /root/Go/src/github.com/hajimehoshi/ebiten/internal/ui/ui_glfw.go:65 +0xc0
github.com/hajimehoshi/ebiten/internal/ui.init.1()
    /root/Go/src/github.com/hajimehoshi/ebiten/internal/ui/ui_glfw.go:54 +0x24
github.com/hajimehoshi/ebiten/internal/ui.init()
    /root/Go/src/github.com/hajimehoshi/ebiten/internal/ui/ui_xwindow.go:33 +0x1a6
github.com/hajimehoshi/ebiten.init()
    /root/Go/src/github.com/hajimehoshi/ebiten/vertices.go:126 +0x50
main.init()
    /root/Go/tst.go:15 +0x30
```

**Comment by hajimehoshi** [comment]
This is not a bug but the environment doesn't have X.

Instead, to make testing easier without X, GL initialization should be done after Run (#397)
