### ISSUE TITLE
bsp: Reach 'not reached'

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#530]
```
panic: not reached

goroutine 18 [running]:
github.com/hajimehoshi/ebiten/internal/bsp.(*Page).Free(0xc42008c328, 0xc421968080)
        /Users/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/internal/bsp/bsp.go:160 +0x134
github.com/hajimehoshi/ebiten/internal/bsp.(*Page).Free(0xc42008c328, 0xc422a8da00)
        /Users/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/internal/bsp/bsp.go:165 +0xfa
github.com/hajimehoshi/ebiten/internal/bsp.(*Page).Free(0xc42008c328, 0xc422a8dac0)
        /Users/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/internal/bsp/bsp.go:165 +0xfa
github.com/hajimehoshi/ebiten.(*sharedImagePart).Dispose(0xc421a7c0e0)
        /Users/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/shared.go:46 +0x44
github.com/hajimehoshi/ebiten.(*Image).Dispose(0xc422a780e0, 0x0, 0x0)
        /Users/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/image.go:342 +0x73
exit status 2
```

This is flakey: probably GCed image caused this.

**Comment by hajimehoshi** [comment]
Note: this happened on `example/font` with fixing `text` package's `cacheLimit` to 10.
