### ISSUE TITLE
graphics.MaxImageSize for framebuffer too small for 5K displays

### ISSUE THREAD

**Issue by nf** [hajimehoshi/ebiten#537]
I've been playing a little with `ebiten` and I've found that running the `spriteshd` example I get this panic:

```
imac:examples nf$ go run spriteshd/main.go 
panic: ebiten: width (5120) must be less than or equal to 4096

goroutine 6 [running]:
github.com/hajimehoshi/ebiten.checkSize(0x1400, 0xb40)
	/Users/nf/go/src/github.com/hajimehoshi/ebiten/image.go:576 +0x236
github.com/hajimehoshi/ebiten.newImageWithScreenFramebuffer(0x1400, 0xb40, 0x0)
	/Users/nf/go/src/github.com/hajimehoshi/ebiten/image.go:555 +0x39
github.com/hajimehoshi/ebiten.(*graphicsContext).SetSize(0xc42097c000, 0x780, 0x438, 0x4005555555555555)
	/Users/nf/go/src/github.com/hajimehoshi/ebiten/graphicscontext.go:62 +0x103
github.com/hajimehoshi/ebiten/internal/ui.(*userInterface).updateGraphicsContext(0x42c10c0, 0x4213240, 0xc42097c000)
	/Users/nf/go/src/github.com/hajimehoshi/ebiten/internal/ui/ui_glfw.go:451 +0x103
github.com/hajimehoshi/ebiten/internal/ui.(*userInterface).update(0x42c10c0, 0x4213240, 0xc42097c000, 0xc4200ae100, 0xc4204f4080)
	/Users/nf/go/src/github.com/hajimehoshi/ebiten/internal/ui/ui_glfw.go:475 +0x10a
github.com/hajimehoshi/ebiten/internal/ui.(*userInterface).loop(0x42c10c0, 0x4213240, 0xc42097c000, 0x0, 0x0)
	/Users/nf/go/src/github.com/hajimehoshi/ebiten/internal/ui/ui_glfw.go:507 +0x85
github.com/hajimehoshi/ebiten/internal/ui.Run(0x780, 0x438, 0x3ff0000000000000, 0x41f61f6, 0x18, 0x4213240, 0xc42097c000, 0x42c8ce0, 0x41cd660)
	/Users/nf/go/src/github.com/hajimehoshi/ebiten/internal/ui/ui_glfw.go:397 +0x165
github.com/hajimehoshi/ebiten.run(0x780, 0x438, 0x3ff0000000000000, 0x41f61f6, 0x18, 0xc42097c000, 0x0, 0x0)
	/Users/nf/go/src/github.com/hajimehoshi/ebiten/run.go:82 +0x78
github.com/hajimehoshi/ebiten.Run.func1(0xc4200862a0, 0x42008d8, 0x780, 0x438, 0x3ff0000000000000, 0x41f61f6, 0x18)
	/Users/nf/go/src/github.com/hajimehoshi/ebiten/run.go:127 +0xea
created by github.com/hajimehoshi/ebiten.Run
	/Users/nf/go/src/github.com/hajimehoshi/ebiten/run.go:122 +0xa0
exit status 2
```

I tracked this down to this constant in `internal/graphics/framebuffer.go`:

```
// defaultViewportSize is the default size (width or height) of viewport.
//
// defaultViewportSize also represents the maximum size of a framebuffer.
const defaultViewportSize = 4096
```

If I increase this value to 5120 the `spriteshd` example  works nicely on my 5k display. I'll send a pull request.

BTW: These are great libraries, thank you!

**Comment by hajimehoshi** [comment]
:+1:
