### ISSUE TITLE
ui: Calling DeviceScaleFactor() panics in 'init' functions on Android

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#597]
```
05-04 19:11:10.432 27137-0/org.golang.todo.fullscreen E/Go: panic: devicescale: error no current JVM
05-04 19:11:10.432 27137-0/org.golang.todo.fullscreen E/Go: goroutine 1 [running]:
05-04 19:11:10.432 27137-0/org.golang.todo.fullscreen E/Go: github.com/hajimehoshi/ebiten/internal/devicescale.impl(0x7f6f7e7a18)
05-04 19:11:10.432 27137-0/org.golang.todo.fullscreen E/Go: 	/Users/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/internal/devicescale/impl_android.go:72 +0x130
05-04 19:11:10.432 27137-0/org.golang.todo.fullscreen E/Go: github.com/hajimehoshi/ebiten/internal/devicescale.DeviceScale(0x0)
05-04 19:11:10.432 27137-0/org.golang.todo.fullscreen E/Go: 	/Users/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/internal/devicescale/devicescale.go:30 +0x68
05-04 19:11:10.432 27137-0/org.golang.todo.fullscreen E/Go: github.com/hajimehoshi/ebiten.DeviceScaleFactor(0x7f6f634120)
05-04 19:11:10.432 27137-0/org.golang.todo.fullscreen E/Go: 	/Users/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/run.go:507 +0x18
```

It's ok to call this on main function though...

**Comment by hajimehoshi** [comment]
On second thought, it is ok to panic here like `(*Image).At` as long as the panic reason is clear (https://github.com/hajimehoshi/ebiten/commit/167d21ec46203b1d44208b864f8ac04b8cd57e92).
