### ISSUE TITLE
opengl: Crash on some (old) machines on glGenFramebuffers

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#602]
Reported by @Shnifer

Any examples crash on some machines like: toshiba satellite L300-1A3, satellite A200-1GS and HP 620

Crash log:
```
D:\SCat>tiles.exe
Exception 0xc0000005 0x0 0x0 0x0
PC=0x0
signal arrived during external code execution

github.com/go-gl/gl/v2.1/gl._Cfunc_glowGenFramebuffers(0x0, 0x1, 0x12da810c)
        github.com/go-gl/gl/v2.1/gl/_obj/_cgo_gotypes.go:16030 +0x37
github.com/go-gl/gl/v2.1/gl.GenFramebuffers(0x1, 0x12da810c)
        C:/Users/1cProg/go/src/github.com/go-gl/gl/v2.1/gl/package.go:20965 +0x33
github.com/hajimehoshi/ebiten/internal/opengl.(*Context).NewFramebuffer.func1(0x12dc5eec, 0x529540)
        C:/Users/1cProg/go/src/github.com/hajimehoshi/ebiten/internal/opengl/context_desktop.go:236 +0x30
github.com/hajimehoshi/ebiten/internal/ui.(*userInterface).runOnMainThread.func1()
        C:/Users/1cProg/go/src/github.com/hajimehoshi/ebiten/internal/ui/ui_glfw.go:223 +0x2c
github.com/hajimehoshi/ebiten/internal/ui.RunMainThreadLoop(0x12dd6940, 0x0, 0x0)
        C:/Users/1cProg/go/src/github.com/hajimehoshi/ebiten/internal/ui/ui_glfw.go:129 +0x64
github.com/hajimehoshi/ebiten.Run(0x6dcb10, 0xf0, 0xf0, 0x0, 0x40000000, 0x6c248c, 0x13, 0x0, 0x0)
        C:/Users/1cProg/go/src/github.com/hajimehoshi/ebiten/run.go:270 +0xf7
main.main()
        C:/Users/1cProg/go/src/github.com/hajimehoshi/ebiten/examples/tiles/main.go:132 +0x57

goroutine 5 [chan receive]:
github.com/hajimehoshi/ebiten/internal/ui.(*userInterface).runOnMainThread(0x851fc0, 0x12dd81f8, 0x12dae8f0, 0x40f75c)
        C:/Users/1cProg/go/src/github.com/hajimehoshi/ebiten/internal/ui/ui_glfw.go:226 +0xd7
github.com/hajimehoshi/ebiten/internal/ui.(*userInterface).(github.com/hajimehoshi/ebiten/internal/ui.runOnMainThread)-fm(0x12dd81f8, 0x12dae801, 0x12dd81f8)
        C:/Users/1cProg/go/src/github.com/hajimehoshi/ebiten/internal/ui/ui_glfw.go:454 +0x28
github.com/hajimehoshi/ebiten/internal/opengl.(*Context).runOnContextThread(0x12e0a0c0, 0x12dd81f8, 0x12dae8c0, 0x0)
        C:/Users/1cProg/go/src/github.com/hajimehoshi/ebiten/internal/opengl/context_desktop.go:87 +0x27
github.com/hajimehoshi/ebiten/internal/opengl.(*Context).NewFramebuffer(0x12e0a0c0, 0x2, 0x52b5a8, 0x851fc0, 0x0)
        C:/Users/1cProg/go/src/github.com/hajimehoshi/ebiten/internal/opengl/context_desktop.go:235 +0x89
github.com/hajimehoshi/ebiten/internal/graphics.newFramebufferFromTexture(0x12da8104, 0x400, 0x400, 0x0, 0x513a51, 0x12e0a0c0)
        C:/Users/1cProg/go/src/github.com/hajimehoshi/ebiten/internal/graphics/framebuffer.go:49 +0x31
github.com/hajimehoshi/ebiten/internal/graphics.(*Image).createFramebufferIfNeeded(0x12e4f2b0, 0x518e33, 0x684d60, 0x12da8104)
        C:/Users/1cProg/go/src/github.com/hajimehoshi/ebiten/internal/graphics/image.go:127 +0x6f
github.com/hajimehoshi/ebiten/internal/graphics.(*drawImageCommand).Exec(0x12e13c20, 0x0, 0x0, 0x0)
        C:/Users/1cProg/go/src/github.com/hajimehoshi/ebiten/internal/graphics/command.go:192 +0x27
github.com/hajimehoshi/ebiten/internal/graphics.(*commandQueue).Flush(0x878e10, 0x12e13c60, 0x0)
        C:/Users/1cProg/go/src/github.com/hajimehoshi/ebiten/internal/graphics/command.go:153 +0x1a9
github.com/hajimehoshi/ebiten/internal/graphics.FlushCommands(0x132e5e44, 0x132e5e48)
        C:/Users/1cProg/go/src/github.com/hajimehoshi/ebiten/internal/graphics/command.go:172 +0x23
github.com/hajimehoshi/ebiten/internal/restorable.ResolveStaleImages(0x4, 0x6dce50)
        C:/Users/1cProg/go/src/github.com/hajimehoshi/ebiten/internal/restorable/images.go:57 +0x1a
github.com/hajimehoshi/ebiten/internal/shareable.ResolveStaleImages(0x0, 0x0)
        C:/Users/1cProg/go/src/github.com/hajimehoshi/ebiten/internal/shareable/shareable.go:351 +0x5c
github.com/hajimehoshi/ebiten.(*graphicsContext).Update(0x12ddd800, 0x12e4f390,0x0, 0x0)
        C:/Users/1cProg/go/src/github.com/hajimehoshi/ebiten/graphicscontext.go:127 +0x47b
github.com/hajimehoshi/ebiten/internal/ui.(*userInterface).update(0x851fc0, 0x81f940, 0x12ddd800, 0x69a9e0, 0x40f201)
        C:/Users/1cProg/go/src/github.com/hajimehoshi/ebiten/internal/ui/ui_glfw.go:565 +0x17f
github.com/hajimehoshi/ebiten/internal/ui.(*userInterface).loop(0x851fc0, 0x81f940, 0x12ddd800, 0x0, 0x0)
        C:/Users/1cProg/go/src/github.com/hajimehoshi/ebiten/internal/ui/ui_glfw.go:583 +0x79
github.com/hajimehoshi/ebiten/internal/ui.Run(0xf0, 0xf0, 0x0, 0x40000000, 0x6c248c, 0x13, 0x81f940, 0x12ddd800, 0x401701, 0x8785c0, ...)
        C:/Users/1cProg/go/src/github.com/hajimehoshi/ebiten/internal/ui/ui_glfw.go:473 +0x121
github.com/hajimehoshi/ebiten.run(0xf0, 0xf0, 0x0, 0x40000000, 0x6c248c, 0x13, 0x12ddd800, 0x12e44f01, 0x12e44f50, 0x12e44f60)
        C:/Users/1cProg/go/src/github.com/hajimehoshi/ebiten/run.go:88 +0x64
github.com/hajimehoshi/ebiten.Run.func1(0x12dd6940, 0x12dd81f0, 0xf0, 0xf0, 0x0, 0x40000000, 0x6c248c, 0x13)
        C:/Users/1cProg/go/src/github.com/hajimehoshi/ebiten/run.go:264 +0xc2
created by github.com/hajimehoshi/ebiten.Run
        C:/Users/1cProg/go/src/github.com/hajimehoshi/ebiten/run.go:259 +0xeb
eax     0x12dc5eb4
ebx     0x12dc5eb4
ecx     0x879550
edx     0x1
edi     0x188
esi     0x879200
ebp     0x879520
esp     0x28fdbc
eip     0x0
eflags  0x10206
cs      0x23
fs      0x53
gs      0x2b

D:\SCat>
```

I guess this is because those machines don't support OpenGL 3.x or later and 'EXT' GL functions are required.

**Comment by hajimehoshi** [comment]
Confirmed the experimental fix https://github.com/hajimehoshi/ebiten/tree/exp-glext worked!
