### ISSUE TITLE
wasm: Update wiki to say WASM support is in master / ebiten 2.0.0+

### ISSUE THREAD

**Issue by silbinarywolf** [hajimehoshi/ebiten#671]
**The problem**

I spent about 30-60 mins trying to get WebAssembly to work, but I just got crashes. My assumption right now is that Ebiten 1.7.3 doesn't support WASM, but the `master` branch does.

**The solution**

Update the wiki to clearly state that only `master` branch supports this.
https://github.com/hajimehoshi/ebiten/wiki/WebAssembly

**Crash message**
```
panic: runtime error: invalid memory address or nil pointer dereference
wasm_exec.js:45 [signal 0xb code=0x0 addr=0x0 pc=0x0]
wasm_exec.js:45 
wasm_exec.js:45 goroutine 1 [running]:
wasm_exec.js:45 github.com/gopherjs/gopherjs/js.(*Object).Get(0x0, 0xc10aa, 0x15, 0x3ff0000000000000)
wasm_exec.js:45     D:/GoProjects/src/github.com/gopherjs/gopherjs/js/js.go:32 +0x1
wasm_exec.js:45 github.com/silbinarywolf/game/vendor/github.com/hajimehoshi/ebiten/internal/opengl.init.0()
wasm_exec.js:45     D:/GoProjects/src/github.com/silbinarywolf/game/vendor/github.com/hajimehoshi/ebiten/internal/opengl/context_js.go:53 +0x2
```

```
exit code: 2
exit    @    wasm_exec.js:67
runtime.wasmExit    @    wasm_exec.js:185
runtime.wasmExit    @    wasm-02b75e42-947:4
runtime.exit    @    wasm-02b75e42-936:3
runtime.fatalpanic.func2    @    wasm-02b75e42-867:47
runtime.systemstack    @    wasm-02b75e42-891:100
runtime.fatalpanic    @    wasm-02b75e42-478:151
runtime.gopanic    @    wasm-02b75e42-471:887
runtime.panicmem    @    wasm-02b75e42-459:106
runtime.sigpanic    @    wasm-02b75e42-449:103
github.com_silbinarywolf_game_vendor_github.com_gopherjs_gopherjs_js.__Object_.Get    @    wasm-02b75e42-2327:48
github.com_silbinarywolf_game_vendor_github.com_hajimehoshi_ebiten_internal_opengl.init.0    @    wasm-02b75e42-2608:88
github.com_silbinarywolf_game_vendor_github.com_hajimehoshi_ebiten_internal_opengl.init    @    wasm-02b75e42-2648:262
github.com_silbinarywolf_game_vendor_github.com_hajimehoshi_ebiten_internal_graphics.init    @    wasm-02b75e42-2698:140
github.com_silbinarywolf_game_vendor_github.com_hajimehoshi_ebiten.init    @    wasm-02b75e42-3025:185
_rt0_wasm_js    @    wasm-02b75e42-934:37
run    @    wasm_exec.js:383
WebAssembly.instantiateStreaming.then.result    @    (index):14
Promise.then (async)        
(anonymous)    @    (index):13
```

**Comment by silbinarywolf** [comment]
**I propose the wiki is changed to the following**

The easiest way is to use [WasmServe](https://github.com/hajimehoshi/wasmserve) with the latest Go.

# Requirements

* Go 1.11
* Ebiten 2.0.0-alpha / master branch

# Compile your game

```sh
GOOS=js GOARCH=wasm go build -o yourgame.wasm github.com/yourname/yourgame
```

# Copy `wasm_exec.js` to execute the Wasm binary

```sh
cp /path/to/latest/go/misc/wasm_exec.js .
```
Source: [https://github.com/golang/go/tree/master/misc/wasm](https://github.com/golang/go/tree/master/misc/wasm)

# Create an HTML

```html
<!DOCTYPE html>
<script src="wasm_exec.js"></script>
<script>
// Polyfill
if (!WebAssembly.instantiateStreaming) {
  WebAssembly.instantiateStreaming = async (resp, importObject) => {
    const source = await (await resp).arrayBuffer();
    return await WebAssembly.instantiate(source, importObject);
  };
}

const go = new Go();
WebAssembly.instantiateStreaming(fetch("yourgame.wasm"), go.importObject).then(result => {
  go.run(result.instance);
});
</script>
```

TBD

**Comment by hajimehoshi** [comment]
I think it is fixed. Thank you!
