### ISSUE TITLE
Crash on Wine (on macOS Mojave)

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#738]
```
$ wine blocks.exe
0039:fixme:process:SetProcessPriorityBoost (0xffffffffffffffff,1): stub
0039:fixme:win:RegisterDeviceNotificationW (hwnd=0x1004e, filter=0x32fb70,flags=0x00000000) returns a fake device notification handle!                                                                                                       
0039:fixme:xinput:XInputGetCapabilities (index 0, flags 0x0, capabilities 0x32fab0) Stub!
0039:fixme:win:EnumDisplayDevicesW ((null),0,0x32f4e0,0x00000000), stub!
0039:fixme:win:EnumDisplayDevicesW (L"\\\\.\\DISPLAY1",0,0x32f830,0x00000000), stub!
0039:fixme:win:EnumDisplayDevicesW ((null),0,0x32f4e0,0x00000000), stub!
0039:fixme:win:EnumDisplayDevicesW (L"\\\\.\\DISPLAY1",0,0x32f830,0x00000000), stub!
0039:fixme:win:EnumDisplayDevicesW (L"\\\\.\\DISPLAY1",1,0x32f830,0x00000000), stub!
0039:fixme:win:EnumDisplayDevicesW ((null),1,0x32f4e0,0x00000000), stub!
0039:fixme:msg:ChangeWindowMessageFilterEx 0x20050 233 1 0x0
0039:fixme:msg:ChangeWindowMessageFilterEx 0x20050 4a 1 0x0
0039:fixme:msg:ChangeWindowMessageFilterEx 0x20050 49 1 0x0
0039:fixme:wgl:set_pixel_format DC for window 0x1004e of other process: not implemented
0039:fixme:dwmapi:DwmIsCompositionEnabled 0x32fa3c
2018/11/24 02:31:16 PlatformError: WGL: Failed to set pixel format for dummy context
panic: devicescale: GetWindowDC failed: error code: 1400

goroutine 1 [running, locked to thread]:
github.com/hajimehoshi/ebiten/internal/devicescale.getFromLogPixelSx(0x0)
        /Users/hajimehoshi/ebiten/internal/devicescale/impl_windows.go:144 +0x116
github.com/hajimehoshi/ebiten/internal/devicescale.impl(0x0, 0x0, 0xa8e470)
        /Users/hajimehoshi/ebiten/internal/devicescale/impl_windows.go:168 +0x4b
github.com/hajimehoshi/ebiten/internal/devicescale.GetAt(0x0, 0x0, 0x0)
        /Users/hajimehoshi/ebiten/internal/devicescale/devicescale.go:28 +0x81
github.com/hajimehoshi/ebiten/internal/ui.(*userInterface).forceSetScreenSize(0x719ca0, 0x100, 0xf0, 0x4000000000000000, 0x1460100)                                                                                                          
        /Users/hajimehoshi/ebiten/internal/ui/ui_glfw.go:746 +0x69
github.com/hajimehoshi/ebiten/internal/ui.(*userInterface).setScreenSize(0x719ca0, 0x100, 0xf0, 0x4000000000000000, 0xc000040100, 0xc00007be18)                                                                                              
        /Users/hajimehoshi/ebiten/internal/ui/ui_glfw.go:733 +0x8f
github.com/hajimehoshi/ebiten/internal/ui.Run.func1(0xe, 0x30000)
        /Users/hajimehoshi/ebiten/internal/ui/ui_glfw.go:556 +0xfa
github.com/hajimehoshi/ebiten/internal/mainthread.Run.func1()
        /Users/hajimehoshi/ebiten/internal/mainthread/mainthread.go:39 +0x3f
github.com/hajimehoshi/ebiten/internal/mainthread.Loop(0xc0000462a0, 0xc000002101, 0x571731)
        /Users/hajimehoshi/ebiten/internal/mainthread/mainthread.go:26 +0x42
github.com/hajimehoshi/ebiten/internal/ui.Loop(0xc0000462a0, 0x8471d0, 0xc0000462a0)
        /Users/hajimehoshi/ebiten/internal/ui/ui_glfw.go:168 +0x47
github.com/hajimehoshi/ebiten.Run(0xc0000491f0, 0x100, 0xf0, 0x4000000000000000, 0x82bd76, 0x14, 0xc00007bf88, 0x406d97)                                                                                                                     
        /Users/hajimehoshi/ebiten/run.go:149 +0x10f
main.main()
        /Users/hajimehoshi/ebiten/examples/blocks/main.go:46 +0xdf
```

As `github.com/go-gl/example/gl21-cube` works with Wine, this should work.

**Comment by hajimehoshi** [comment]
Note to my self:

# How to fix gl21-cube example to be able to be compiled for Wine

```diff
diff --git a/gl21-cube/cube.go b/gl21-cube/cube.go
index 5a84ebc..228af7d 100644
--- a/gl21-cube/cube.go
+++ b/gl21-cube/cube.go
@@ -3,7 +3,7 @@
 // license that can be found in the LICENSE file.

 // Renders a textured spinning cube using GLFW 3 and OpenGL 2.1.
-package main // import "github.com/go-gl/example/gl21-cube"
+package main

 import (
        "go/build"
@@ -220,6 +220,7 @@ func init() {
 // There doesn't need to be a valid Go package inside that import path,
 // but the directory must exist.
 func importPathToDir(importPath string) (string, error) {
+       return ".", nil
        p, err := build.Import(importPath, "", build.FindOnly)
        if err != nil {
                return "", err
```

# How to compile and execute it

```
CC=x86_64-w64-mingw32-gcc CGO_ENABLED=1 GOOS=windows go build -x . && wine gl21-cube.exe
```

**Comment by hajimehoshi** [comment]
`GetWindowDC(0)` doesn't work on Wine? 🤔
