### ISSUE TITLE
example/contextlost: Panic on wine

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#765]
```
panic: devicescale: GetWindowDC failed: error code: 1812

goroutine 7 [running]:
github.com/hajimehoshi/ebiten/internal/devicescale.getFromLogPixelSx(0x0)
        /Users/hajimehoshi/ebiten/internal/devicescale/impl_windows.go:197 +0x14b
github.com/hajimehoshi/ebiten/internal/devicescale.impl(0x0, 0x0, 0x98ad08)
        /Users/hajimehoshi/ebiten/internal/devicescale/impl_windows.go:221 +0x4b
github.com/hajimehoshi/ebiten/internal/devicescale.GetAt(0x0, 0x0, 0x0)
        /Users/hajimehoshi/ebiten/internal/devicescale/devicescale.go:28 +0x81
github.com/hajimehoshi/ebiten/internal/ui.(*userInterface).actualScreenScale(0x6b7de0, 0xc0026889e0)
        /Users/hajimehoshi/ebiten/internal/ui/ui_glfw.go:633 +0x9b
github.com/hajimehoshi/ebiten/internal/ui.(*userInterface).updateGraphicsContext.func1(0x990440, 0xc001f95db8)
        /Users/hajimehoshi/ebiten/internal/ui/ui_glfw.go:649 +0x4c
github.com/hajimehoshi/ebiten/internal/mainthread.Run(0xc0026889e0, 0xc0026889e0, 0x10)
        /Users/hajimehoshi/ebiten/internal/mainthread/mainthread.go:68 +0x183
github.com/hajimehoshi/ebiten/internal/ui.(*userInterface).updateGraphicsContext(0x6b7de0, 0x7b2e20, 0xc00007c140)
        /Users/hajimehoshi/ebiten/internal/ui/ui_glfw.go:648 +0xa8
github.com/hajimehoshi/ebiten/internal/ui.(*userInterface).update(0x6b7de0, 0x7b2e20, 0xc00007c140, 0x0, 0x0)
        /Users/hajimehoshi/ebiten/internal/ui/ui_glfw.go:688 +0xf7
github.com/hajimehoshi/ebiten/internal/ui.(*userInterface).loop(0x6b7de0, 0x7b2e20, 0xc00007c140, 0x0, 0x0)
        /Users/hajimehoshi/ebiten/internal/ui/ui_glfw.go:723 +0x7d
github.com/hajimehoshi/ebiten/internal/ui.Run(0x140, 0xf0, 0x4000000000000000, 0x76a98c, 0x1a, 0x7b2e20, 0xc00007c140, 0x401601, 0x96c580, 0x71ffe0)
        /Users/hajimehoshi/ebiten/internal/ui/ui_glfw.go:601 +0xcc
github.com/hajimehoshi/ebiten.run(0x140, 0xf0, 0x4000000000000000, 0x76a98c, 0x1a, 0xc00007c140, 0x1, 0x0, 0x0)
        /Users/hajimehoshi/ebiten/run.go:90 +0x8e
github.com/hajimehoshi/ebiten.Run.func1(0xc000046060, 0xc0005a20c0, 0x140, 0xf0, 0x4000000000000000, 0x76a98c, 0x1a)
        /Users/hajimehoshi/ebiten/run.go:139 +0xf8
created by github.com/hajimehoshi/ebiten.Run
        /Users/hajimehoshi/ebiten/run.go:134 +0x101
```

**Comment by hajimehoshi** [comment]
Oops, this is due to https://github.com/hajimehoshi/ebiten/commit/042b30a516a9ced07a8e3508ec396872a00bdf1a . Not this was reverted.
