### ISSUE TITLE
Panic if drag application from one monitor no another

### ISSUE THREAD

**Issue by crgimenes** [hajimehoshi/ebiten#807]
The application window is created in the first monitor as expected but if I try to drag the application window to my second monitor I get a panic in the terminal.

macOS Mojave 
go version go1.11.5 darwin/amd64
My secondary monitor is positioned above the primary monitor (which is part of the notebook)

```
go run main.go
panic: x must be positive

goroutine 19 [running]:
github.com/hajimehoshi/ebiten/internal/graphics.NextPowerOf2Int(0x0, 0x58)
	/Users/cesar/Projects/go/src/github.com/hajimehoshi/ebiten/internal/graphics/math.go:20 +0x61
github.com/hajimehoshi/ebiten/internal/restorable.(*Image).clear(0xc000080060)
	/Users/cesar/Projects/go/src/github.com/hajimehoshi/ebiten/internal/restorable/image.go:112 +0x7e
github.com/hajimehoshi/ebiten/internal/restorable.NewScreenFramebufferImage(0x0, 0x0, 0x439efb0)
	/Users/cesar/Projects/go/src/github.com/hajimehoshi/ebiten/internal/restorable/image.go:98 +0x112
github.com/hajimehoshi/ebiten/internal/shareable.NewScreenFramebufferImage(0x0, 0x0, 0x0)
	/Users/cesar/Projects/go/src/github.com/hajimehoshi/ebiten/internal/shareable/shareable.go:485 +0x7e
github.com/hajimehoshi/ebiten.newImageWithScreenFramebuffer(0x0, 0x0, 0x0)
	/Users/cesar/Projects/go/src/github.com/hajimehoshi/ebiten/image.go:782 +0x39
github.com/hajimehoshi/ebiten.(*graphicsContext).SetSize(0xc0000b20f0, 0x140, 0xf0, 0x0)
	/Users/cesar/Projects/go/src/github.com/hajimehoshi/ebiten/graphicscontext.go:70 +0x176
github.com/hajimehoshi/ebiten/internal/ui.(*userInterface).updateGraphicsContext(0x4378920, 0x425c3c0, 0xc0000b20f0)
	/Users/cesar/Projects/go/src/github.com/hajimehoshi/ebiten/internal/ui/ui_glfw.go:727 +0xef
github.com/hajimehoshi/ebiten/internal/ui.(*userInterface).update(0x4378920, 0x425c3c0, 0xc0000b20f0, 0x40be770, 0xc00000c080)
	/Users/cesar/Projects/go/src/github.com/hajimehoshi/ebiten/internal/ui/ui_glfw.go:751 +0xf0
github.com/hajimehoshi/ebiten/internal/ui.(*userInterface).loop(0x4378920, 0x425c3c0, 0xc0000b20f0, 0x0, 0x0)
	/Users/cesar/Projects/go/src/github.com/hajimehoshi/ebiten/internal/ui/ui_glfw.go:797 +0x76
github.com/hajimehoshi/ebiten/internal/ui.Run(0x140, 0xf0, 0x4010000000000000, 0x42299c8, 0x4, 0x425c3c0, 0xc0000b20f0, 0x4003901, 0x4380ad0, 0x420a3e0)
	/Users/cesar/Projects/go/src/github.com/hajimehoshi/ebiten/internal/ui/ui_glfw.go:664 +0x15b
github.com/hajimehoshi/ebiten.run(0x140, 0xf0, 0x4010000000000000, 0x42299c8, 0x4, 0xc0000b20f0, 0x1, 0x0, 0x0)
	/Users/cesar/Projects/go/src/github.com/hajimehoshi/ebiten/run.go:99 +0xcd
github.com/hajimehoshi/ebiten.Run.func1(0xc0000bc060, 0xc0000923f0, 0x140, 0xf0, 0x4010000000000000, 0x42299c8, 0x4)
	/Users/cesar/Projects/go/src/github.com/hajimehoshi/ebiten/run.go:152 +0xf1
created by github.com/hajimehoshi/ebiten.Run
	/Users/cesar/Projects/go/src/github.com/hajimehoshi/ebiten/run.go:147 +0xfa
exit status 2
```

**Comment by hajimehoshi** [comment]
> My secondary monitor is positioned above the primary monitor (which is part of the notebook)

Ah, that sounds a case I missed. Thank you for reporting!

I'm now on vacation, and I'll be back to Japan on Saturday (JST). I'll take a look at this then.

**Comment by hajimehoshi** [comment]
Confirmed: this is due to inverted Y axis compared to I expected in macOS.

**Comment by crgimenes** [comment]
I tested it here and it worked perfectly!
Thank you @hajimehoshi!
