### ISSUE TITLE
graphicsdriver/opengl: Optimizing out an attribute variable

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#816]
This (still) happens on some machine. Should we use glBindAttribLocation https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glBindAttribLocation.xhtml ?

**Comment by hajimehoshi** [comment]
Looks like this was fixed.

**Comment by auyer** [comment]
Registering the found errors before the fix.

Both errors were recorded in a Arch Based system running Nvidia proprietary drivers:

- Before first fix attempt
```
go run ui/main.go
panic: opengl: invalid attrib location: tex_region

goroutine 1 [running, locked to thread]:
github.com/hajimehoshi/ebiten/internal/graphicsdriver/opengl.(*context).getAttribLocationImpl(0x8437a8, 0xc000000007, 0x69c0f2, 0xa, 0x8635a0)
    /home/auyer/go/src/github.com/hajimehoshi/ebiten/internal/graphicsdriver/opengl/context_desktop.go:404 +0x185
github.com/hajimehoshi/ebiten/internal/graphicsdriver/opengl.(*locationCache).GetAttribLocation(0xc0000d6040, 0x8437a8, 0xc000000007, 0x69c0f2, 0xa, 0xc000087498)
    /home/auyer/go/src/github.com/hajimehoshi/ebiten/internal/graphicsdriver/opengl/locationcache.go:51 +0xf5
github.com/hajimehoshi/ebiten/internal/graphicsdriver/opengl.(*context).enableVertexAttribArray.func1(0xc000087440, 0x0)
    /home/auyer/go/src/github.com/hajimehoshi/ebiten/internal/graphicsdriver/opengl/context_desktop.go:419 +0x4b
github.com/hajimehoshi/ebiten/internal/mainthread.Run.func1()
    /home/auyer/go/src/github.com/hajimehoshi/ebiten/internal/mainthread/mainthread.go:59 +0x38
github.com/hajimehoshi/ebiten/internal/mainthread.Loop(0xc000198060, 0xc000000301, 0x5b381a)
    /home/auyer/go/src/github.com/hajimehoshi/ebiten/internal/mainthread/mainthread.go:39 +0x49
github.com/hajimehoshi/ebiten/internal/ui.Loop(0xc000198060, 0x6b3ba0, 0xc000198060)
    /home/auyer/go/src/github.com/hajimehoshi/ebiten/internal/ui/ui_glfw.go:163 +0x40
github.com/hajimehoshi/ebiten.Run(0x6b3cd0, 0x280, 0x1e0, 0x3ff0000000000000, 0x69eb36, 0x10, 0x0, 0x0)
    /home/auyer/go/src/github.com/hajimehoshi/ebiten/run.go:158 +0x108
main.main()
    /home/auyer/go/src/github.com/hajimehoshi/ebiten/examples/ui/main.go:502 +0x66
exit status 2
```
- Before second fix attempt

```
panic: opengl: invalid uniform location: source_size

goroutine 1 [running, locked to thread]:
github.com/hajimehoshi/ebiten/internal/graphicsdriver/opengl.(*context).getUniformLocationImpl(0xaa4028, 0xc000000003, 0x81405f, 0xb, 0xac4cc0)
    /home/auyer/go/src/github.com/hajimehoshi/ebiten/internal/graphicsdriver/opengl/context_desktop.go:368 +0x185
github.com/hajimehoshi/ebiten/internal/graphicsdriver/opengl.(*locationCache).GetUniformLocation(0xc0000dc008, 0xaa4028, 0x3, 0x81405f, 0xb, 0xc000000300)
    /home/auyer/go/src/github.com/hajimehoshi/ebiten/internal/graphicsdriver/opengl/locationcache.go:36 +0xf3
github.com/hajimehoshi/ebiten/internal/graphicsdriver/opengl.(*context).uniformFloats.func1(0xc00021e900, 0x0)
    /home/auyer/go/src/github.com/hajimehoshi/ebiten/internal/graphicsdriver/opengl/context_desktop.go:391 +0x62
github.com/hajimehoshi/ebiten/internal/mainthread.Run.func1()
    /home/auyer/go/src/github.com/hajimehoshi/ebiten/internal/mainthread/mainthread.go:59 +0x38
github.com/hajimehoshi/ebiten/internal/mainthread.Loop(0xc000164060, 0xc000000301, 0x5b905a)
    /home/auyer/go/src/github.com/hajimehoshi/ebiten/internal/mainthread/mainthread.go:39 +0x49
github.com/hajimehoshi/ebiten/internal/ui.Loop(0xc000164060, 0x8354b0, 0xc000164060)
    /home/auyer/go/src/github.com/hajimehoshi/ebiten/internal/ui/ui_glfw.go:163 +0x40
github.com/hajimehoshi/ebiten.Run(0x835600, 0x280, 0x1e0, 0x3ff0000000000000, 0x81b023, 0x14, 0x0, 0x0)
    /home/auyer/go/src/github.com/hajimehoshi/ebiten/run.go:158 +0x108
main.main()
    /home/auyer/go/src/github.com/hajimehoshi/ebiten/examples/shapes/main.go:181 +0x66
exit status 2
```
