### ISSUE TITLE
restorable: Race condition on a map

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#820]
```
fatal error: concurrent map iteration and map write

goroutine 12 [running]:
runtime.throw(0x457fdd7, 0x26)
	/usr/local/go/src/runtime/panic.go:608 +0x72 fp=0xc003be9b58 sp=0xc003be9b28 pc=0x402dfb2
runtime.mapiternext(0xc003be9bf8)
	/usr/local/go/src/runtime/map.go:790 +0x525 fp=0xc003be9be0 sp=0xc003be9b58 pc=0x4011a85
github.com/hajimehoshi/ebiten/internal/restorable.(*images).makeStaleIfDependingOnImpl(0x5014910, 0xc0000c6320)
	/Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/internal/restorable/images.go:140 +0xc5 fp=0xc003be9c68 sp=0xc003be9be0 pc=0x4167555
github.com/hajimehoshi/ebiten/internal/restorable.(*images).makeStaleIfDependingOn(0x5014910, 0xc0000c6320)
	/Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/internal/restorable/images.go:129 +0x35 fp=0xc003be9c88 sp=0xc003be9c68 pc=0x4167475
github.com/hajimehoshi/ebiten/internal/restorable.(*Image).Fill(0xc0000c6320, 0x0)
	/Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/internal/restorable/image.go:168 +0x37 fp=0xc003be9ca8 sp=0xc003be9c88 pc=0x41641c7
github.com/hajimehoshi/ebiten/internal/shareable.(*Image).Fill(0xc0002a8040, 0x0)
	/Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/internal/shareable/shareable.go:253 +0x93 fp=0xc003be9cc8 sp=0xc003be9ca8 pc=0x4168be3
github.com/hajimehoshi/ebiten.(*Image).Fill(0xc0002a8080, 0x45e7500, 0x5037640, 0x5037640, 0x0)
	/Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/image.go:190 +0xb0 fp=0xc003be9cf0 sp=0xc003be9cc8 pc=0x41879b0
github.com/hajimehoshi/ebiten.(*Image).Clear(0xc0002a8080, 0x0, 0x0)
	/Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/image.go:166 +0x5b fp=0xc003be9d28 sp=0xc003be9cf0 pc=0x41878db
github.com/hajimehoshi/ebiten.(*graphicsContext).Update(0xc000186280, 0xc0091040a0, 0x0, 0xc009104080)
	/Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/graphicscontext.go:103 +0xb0 fp=0xc003be9e00 sp=0xc003be9d28 pc=0x4186a90
github.com/hajimehoshi/ebiten/internal/ui.(*userInterface).update(0x500a600, 0x45e9d20, 0xc000186280, 0x0, 0x0)
	/Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/internal/ui/ui_glfw.go:767 +0x191 fp=0xc003be9e38 sp=0xc003be9e00 pc=0x416c491
github.com/hajimehoshi/ebiten/internal/ui.(*userInterface).loop(0x500a600, 0x45e9d20, 0xc000186280, 0x0, 0x0)
	/Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/internal/ui/ui_glfw.go:797 +0x76 fp=0xc003be9e80 sp=0xc003be9e38 pc=0x416c656
github.com/hajimehoshi/ebiten/internal/ui.Run(0x1e0, 0x356, 0x3fe8000000000000, 0x0, 0x0, 0x45e9d20, 0xc000186280, 0x4003d01, 0x50148f0, 0x450a640)
	/Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/internal/ui/ui_glfw.go:664 +0x15b fp=0xc003be9ec8 sp=0xc003be9e80 pc=0x416bddb
github.com/hajimehoshi/ebiten.run(0x1e0, 0x356, 0x3fe8000000000000, 0x0, 0x0, 0xc000186280, 0x1, 0x0, 0x0)
	/Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/run.go:99 +0xcd fp=0xc003be9f38 sp=0xc003be9ec8 pc=0x418dcad
github.com/hajimehoshi/ebiten.Run.func1(0xc0001d20c0, 0xc0001d51a0, 0x1e0, 0x356, 0x3fe8000000000000, 0x0, 0x0)
	/Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/run.go:152 +0xf1 fp=0xc003be9fa8 sp=0xc003be9f38 pc=0x418e501
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc003be9fb0 sp=0xc003be9fa8 pc=0x405d0e1
created by github.com/hajimehoshi/ebiten.Run
	/Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/run.go:147 +0xfa

goroutine 1 [select, locked to thread]:
github.com/hajimehoshi/ebiten/internal/mainthread.Loop(0xc0001d20c0, 0xc000000301, 0x418de7a)
	/Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/internal/mainthread/mainthread.go:37 +0xde
github.com/hajimehoshi/ebiten/internal/ui.Loop(0xc0001d20c0, 0x4593880, 0xc0001d20c0)
	/Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/internal/ui/ui_glfw.go:163 +0x40
github.com/hajimehoshi/ebiten.Run(0xc0001d5190, 0x1e0, 0x356, 0x3fe8000000000000, 0x0, 0x0, 0x2, 0xb)
	/Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/run.go:158 +0x108
main.main()
	/Users/daigosato/Development/Go/src/github.com/hajimehoshi/rpgsnack-runtime/main.go:48 +0x24f

goroutine 4 [runnable]:
runtime.call32(0x0, 0x4593878, 0xc0002c8360, 0x2000000020)
	/usr/local/go/src/runtime/asm_amd64.s:522 +0x6d
runtime.runfinq()
	/usr/local/go/src/runtime/mfinal.go:222 +0x1d2
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1333 +0x1

goroutine 5 [select]:
io.(*pipe).Write(0xc000186000, 0xc002023100, 0x47c, 0x700, 0x100, 0x0, 0x0)
	/usr/local/go/src/io/pipe.go:87 +0x1cc
io.(*PipeWriter).Write(0xc0035ce008, 0xc002023000, 0x57c, 0x800, 0x0, 0x4346b80, 0xc0029a5260)
	/usr/local/go/src/io/pipe.go:153 +0x4c
github.com/hajimehoshi/oto.(*Player).Write(0xc0035c03c0, 0xc002023000, 0x57c, 0x800, 0x57c, 0x0, 0x0)
	/Users/daigosato/Development/Go/src/github.com/hajimehoshi/oto/player.go:60 +0x4d
github.com/hajimehoshi/ebiten/audio.(*otoPlayer).Write(0xc0029a5260, 0xc002023000, 0x57c, 0x800, 0x57c, 0x0, 0x0)
	/Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/audio/context.go:74 +0x8b
io.copyBuffer(0xad3cdf8, 0xc0029a5260, 0x45e6b00, 0xc00200c840, 0xc002023000, 0x800, 0x800, 0x44ff0c0, 0xad3cd01, 0xc00200c840)
	/usr/local/go/src/io/io.go:404 +0x201
io.Copy(0xad3cdf8, 0xc0029a5260, 0x45e6b00, 0xc00200c840, 0x44ea1c0, 0x0, 0xad3cdf8)
	/usr/local/go/src/io/io.go:364 +0x5a
io.CopyN(0xad3cdf8, 0xc0029a5260, 0x45e6360, 0xc00000c7a0, 0x800, 0x800, 0x0, 0x0)
	/usr/local/go/src/io/io.go:340 +0x86
github.com/hajimehoshi/ebiten/audio.(*Context).loop(0xc0000c63c0)
	/Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/audio/audio.go:155 +0x280
created by github.com/hajimehoshi/ebiten/audio.NewContext
	/Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/audio/audio.go:103 +0x16b

goroutine 37 [sleep]:
time.Sleep(0x5893bc)
	/usr/local/go/src/runtime/time.go:105 +0x14f
github.com/hajimehoshi/oto.(*driverWriter).Write(0xc0035c0380, 0xc0035d4000, 0x100, 0x8000, 0x0, 0x0, 0x0)
	/Users/daigosato/Development/Go/src/github.com/hajimehoshi/oto/context.go:142 +0x1b2
io.copyBuffer(0x45e6440, 0xc0035c0380, 0x45e6460, 0xc0035be4c0, 0xc0035d4000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:404 +0x201
io.Copy(0x45e6440, 0xc0035c0380, 0x45e6460, 0xc0035be4c0, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:364 +0x5a
github.com/hajimehoshi/oto.NewContext.func1(0xc0035c03a0)
	/Users/daigosato/Development/Go/src/github.com/hajimehoshi/oto/context.go:79 +0x53
created by github.com/hajimehoshi/oto.NewContext
	/Users/daigosato/Development/Go/src/github.com/hajimehoshi/oto/context.go:78 +0x1c6

goroutine 2863 [runnable]:
github.com/hajimehoshi/ebiten/audio.(*playerImpl).readLoop(0xc0029b8320)
	/Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/audio/audio.go:413 +0x30d
github.com/hajimehoshi/ebiten/audio.NewPlayer.func1(0xc001672590)
	/Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/audio/audio.go:305 +0x2e
created by github.com/hajimehoshi/ebiten/audio.NewPlayer
	/Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/audio/audio.go:304 +0x371

goroutine 2462 [select]:
github.com/hajimehoshi/ebiten/audio.(*playerImpl).readLoop(0xc000c84820)
	/Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/audio/audio.go:413 +0x30d
github.com/hajimehoshi/ebiten/audio.NewPlayer.func1(0xc0014d2690)
	/Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/audio/audio.go:305 +0x2e
created by github.com/hajimehoshi/ebiten/audio.NewPlayer
	/Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/audio/audio.go:304 +0x371

goroutine 2953 [runnable]:
github.com/hajimehoshi/ebiten/audio.(*playerImpl).readLoop(0xc000c7a140)
	/Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/audio/audio.go:413 +0x30d
github.com/hajimehoshi/ebiten/audio.NewPlayer.func1(0xc0014d3170)
	/Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/audio/audio.go:305 +0x2e
created by github.com/hajimehoshi/ebiten/audio.NewPlayer
	/Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/audio/audio.go:304 +0x371

goroutine 1733 [select]:
github.com/hajimehoshi/ebiten/audio.(*playerImpl).readLoop(0xc00819a500)
	/Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/audio/audio.go:413 +0x30d
github.com/hajimehoshi/ebiten/audio.NewPlayer.func1(0xc007948140)
	/Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/audio/audio.go:305 +0x2e
created by github.com/hajimehoshi/ebiten/audio.NewPlayer
	/Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/audio/audio.go:304 +0x371

goroutine 2955 [runnable]:
github.com/hajimehoshi/ebiten/audio.(*playerImpl).readLoop(0xc000c7a320)
	/Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/audio/audio.go:413 +0x30d
github.com/hajimehoshi/ebiten/audio.NewPlayer.func1(0xc0014d31f0)
	/Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/audio/audio.go:305 +0x2e
created by github.com/hajimehoshi/ebiten/audio.NewPlayer
	/Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/audio/audio.go:304 +0x371

goroutine 2864 [runnable]:
github.com/hajimehoshi/ebiten/audio.(*playerImpl).readLoop(0xc0029b83c0)
	/Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/audio/audio.go:413 +0x30d
github.com/hajimehoshi/ebiten/audio.NewPlayer.func1(0xc0016725d0)
	/Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/audio/audio.go:305 +0x2e
created by github.com/hajimehoshi/ebiten/audio.NewPlayer
	/Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/audio/audio.go:304 +0x371

goroutine 2954 [runnable]:
github.com/hajimehoshi/ebiten/audio.(*playerImpl).readLoop(0xc000c7a280)
	/Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/audio/audio.go:413 +0x30d
github.com/hajimehoshi/ebiten/audio.NewPlayer.func1(0xc0014d31b0)
	/Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/audio/audio.go:305 +0x2e
created by github.com/hajimehoshi/ebiten/audio.NewPlayer
	/Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/audio/audio.go:304 +0x371
```

**Comment by hajimehoshi** [comment]
This is really a tough bug since the game doesn't use goroutines for rendering.

My guess is that the map causes race condition with finalizer routines and other regular routines. Not sure.
