### ISSUE TITLE
graphics: shareable.Image's finalizer causes race condition

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#838]
@Rosalita reported:

```
fatal error: concurrent map iteration and map write
goroutine 19 [running]:
runtime.throw(0x4415882, 0x26)
        /usr/local/Cellar/go/1.11.4/libexec/src/runtime/panic.go:608 +0x72 fp=0xc0003657e8 sp=0xc0003657b8 pc=0x402c3e2
runtime.mapiternext(0xc000365888)
        /usr/local/Cellar/go/1.11.4/libexec/src/runtime/map.go:790 +0x525 fp=0xc000365870 sp=0xc0003657e8 pc=0x4010b55
github.com/hajimehoshi/ebiten/internal/restorable.(*images).makeStaleIfDependingOnImpl(0x483a6c0, 0xc00031a050)
        /Users/rosie.hamilton/dev/go/src/github.com/hajimehoshi/ebiten/internal/restorable/images.go:140 +0xc5 fp=0xc0003658f8 sp=0xc000365870 pc=0x41658a5
github.com/hajimehoshi/ebiten/internal/restorable.(*images).makeStaleIfDependingOn(0x483a6c0, 0xc00031a050)
        /Users/rosie.hamilton/dev/go/src/github.com/hajimehoshi/ebiten/internal/restorable/images.go:129 +0x35 fp=0xc000365918 sp=0xc0003658f8 pc=0x41657c5
github.com/hajimehoshi/ebiten/internal/restorable.(*Image).Fill(0xc00031a050, 0xffffffffffff)
        /Users/rosie.hamilton/dev/go/src/github.com/hajimehoshi/ebiten/internal/restorable/image.go:168 +0x37 fp=0xc000365938 sp=0xc000365918 pc=0x41625e7
github.com/hajimehoshi/ebiten/internal/shareable.(*Image).Fill(0xc0004f0700, 0xffffffffffff)
        /Users/rosie.hamilton/dev/go/src/github.com/hajimehoshi/ebiten/internal/shareable/shareable.go:265 +0x93 fp=0xc000365958 sp=0xc000365938 pc=0x4167193
github.com/hajimehoshi/ebiten.(*Image).Fill(0xc0004f0740, 0x445cb80, 0xc00039e066, 0xc00039e066, 0x0)
        /Users/rosie.hamilton/dev/go/src/github.com/hajimehoshi/ebiten/image.go:190 +0xb0 fp=0xc000365980 sp=0xc000365958 pc=0x41818f0
```

```
goroutine 18 [runnable]:
github.com/hajimehoshi/ebiten/internal/graphicscommand.(*Image).Dispose(...)
        /Users/rosie.hamilton/dev/go/src/github.com/hajimehoshi/ebiten/internal/graphicscommand/image.go:74
github.com/hajimehoshi/ebiten/internal/restorable.(*Image).Dispose(0xc00009e550)
        /Users/rosie.hamilton/dev/go/src/github.com/hajimehoshi/ebiten/internal/restorable/image.go:525 +0x58
github.com/hajimehoshi/ebiten/internal/shareable.(*Image).dispose(0xc0004128c0, 0x4422f01)
        /Users/rosie.hamilton/dev/go/src/github.com/hajimehoshi/ebiten/internal/shareable/shareable.go:341 +0x3b5
github.com/hajimehoshi/ebiten/internal/shareable.(*Image).Dispose(0xc0004128c0)
        /Users/rosie.hamilton/dev/go/src/github.com/hajimehoshi/ebiten/internal/shareable/shareable.go:316 +0x68
github.com/hajimehoshi/ebiten.(*mipmap).dispose(0xc00036f480)
        /Users/rosie.hamilton/dev/go/src/github.com/hajimehoshi/ebiten/image.go:103 +0x3c
github.com/hajimehoshi/ebiten.(*Image).Dispose(0xc000412900, 0x0, 0x0)
        /Users/rosie.hamilton/dev/go/src/github.com/hajimehoshi/ebiten/image.go:639 +0x8a
```

```go
        picx := 150.0
        picy := 24.0
        v1 := ebiten.Vertex{
            DstX: 0 + float32(picx),
            DstY: 0 + float32(picy),
            SrcX: 0,
            SrcY: 0,
            ColorR: 1,
            ColorG: 1,
            ColorB: 1,
            ColorA: 1,
        }
        v2 := ebiten.Vertex{
            DstX: 10 + float32(picx),
            DstY: 10 + float32(picy),
            SrcX: 0,
            SrcY: 0,
            ColorR: 1,
            ColorG: 1,
            ColorB: 1,
            ColorA: 1,
        }
        v3 := ebiten.Vertex{
            DstX: 0 + float32(picx),
            DstY: 20 + float32(picy),
            SrcX: 0,
            SrcY: 0,
            ColorR: 1,
            ColorG: 1,
            ColorB: 1,
            ColorA: 1,
        }
        vs := []ebiten.Vertex{v1,v2,v3}
        indices := []uint16{0,1,2}
        op := &ebiten.DrawTrianglesOptions{}
    
        emptyImage, _ := ebiten.NewImage(36, 36, ebiten.FilterDefault)
        emptyImage.Fill(color.White)
        screen.DrawTriangles(vs, indices, emptyImage, op)
```

**Comment by hajimehoshi** [comment]
I think I understand the cause: the map is accessed by GC and the living image at the same time.

**Comment by hajimehoshi** [comment]
I could not reproduce this with the latest Ebiten. I think this bug was already fixed by https://github.com/hajimehoshi/ebiten/issues/820.

@Rosalita, which version of Ebiten are you using? I'd like to know the result of this command:

```
cd $HOME/go/src/github.com/hajimehoshi/ebiten
git log --oneline -n 1
```

**Comment by Rosalita** [comment]
@hajimehoshi 
`27dbf1bb (HEAD -> master, origin/master, origin/HEAD) restorable: Record more drawing image history items`

**Comment by hajimehoshi** [comment]
OK, this was already fixed in the latest Ebiten. Thank you!
