### ISSUE TITLE
graphicscommand: test failed

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#884]
https://travis-ci.org/hajimehoshi/ebiten/builds/548317244

```
panic: thread: the thread loop is not started yet
goroutine 5 [running]:
github.com/hajimehoshi/ebiten/internal/thread.(*Thread).Call(0xc000032590, 0xc0000a4230, 0xc000000008, 0xc00006c740)
	/home/travis/gopath/pkg/mod/github.com/hajimehoshi/ebiten@v1.10.0-alpha.0.20190620173058-3eee4754c5c0/internal/thread/thread.go:60 +0x159
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).run(0xa3b480, 0x140, 0xf0, 0x3ff0000000000000, 0x6a7041, 0x4, 0x6ec560, 0xc0000a41e0, 0x6edc60, 0xa52dc0, ...)
	/home/travis/gopath/pkg/mod/github.com/hajimehoshi/ebiten@v1.10.0-alpha.0.20190620173058-3eee4754c5c0/internal/uidriver/glfw/ui.go:587 +0xc1
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).Run.func1(0xc0000325a0, 0xc00006e360, 0xa3b480, 0x140, 0xf0, 0x3ff0000000000000, 0x6a7041, 0x4, 0x6ec560, 0xc0000a41e0, ...)
	/home/travis/gopath/pkg/mod/github.com/hajimehoshi/ebiten@v1.10.0-alpha.0.20190620173058-3eee4754c5c0/internal/uidriver/glfw/ui.go:573 +0xf7
created by github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).Run
	/home/travis/gopath/pkg/mod/github.com/hajimehoshi/ebiten@v1.10.0-alpha.0.20190620173058-3eee4754c5c0/internal/uidriver/glfw/ui.go:570 +0x1b4
FAIL	github.com/hajimehoshi/ebiten/internal/graphicscommand	13.471s
```

**Comment by hajimehoshi** [comment]
Note: this succeeded on my local machine.
