### ISSUE TITLE
Crash on El Capitan

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#886]
```
go run -tags=example ./examples/rotate
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x40b7bdb]

goroutine 18 [running]:
github.com/hajimehoshi/ebiten/internal/thread.(*Thread).Call(0x0, 0xc00017a030, 0xbf3c0a40d2becc30, 0xc000046d48)
    /Users/peter/Go/src/github.com/hajimehoshi/ebiten/internal/thread/thread.go:56 +0xab
github.com/hajimehoshi/ebiten/internal/graphicsdriver/metal.(*Driver).Reset(0x43c2180, 0x425de10, 0x43dd540)
    /Users/peter/Go/src/github.com/hajimehoshi/ebiten/internal/graphicsdriver/metal/driver.go:472 +0x67
github.com/hajimehoshi/ebiten/internal/graphicscommand.ResetGraphicsDriverState(...)
    /Users/peter/Go/src/github.com/hajimehoshi/ebiten/internal/graphicscommand/command.go:550
github.com/hajimehoshi/ebiten/internal/restorable.InitializeGraphicsDriverState(...)
    /Users/peter/Go/src/github.com/hajimehoshi/ebiten/internal/restorable/images.go:239
github.com/hajimehoshi/ebiten/internal/shareable.InitializeGraphicsDriverState(0x0, 0x0)
    /Users/peter/Go/src/github.com/hajimehoshi/ebiten/internal/shareable/shareable.go:515 +0x7b
github.com/hajimehoshi/ebiten.(*uiContext).initializeIfNeeded(0xc000098190, 0x1, 0x20)
    /Users/peter/Go/src/github.com/hajimehoshi/ebiten/uicontext.go:77 +0x76
github.com/hajimehoshi/ebiten.(*uiContext).Update(0xc000098190, 0xc000176080, 0x0, 0x0)
    /Users/peter/Go/src/github.com/hajimehoshi/ebiten/uicontext.go:94 +0x5d
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).update(0x43ba200, 0x42850c0, 0xc000098190, 0xc000178000, 0xc000178000)
    /Users/peter/Go/src/github.com/hajimehoshi/ebiten/internal/uidriver/glfw/ui.go:788 +0x1d6
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).loop(0x43ba200, 0x42850c0, 0xc000098190, 0x0, 0x0)
    /Users/peter/Go/src/github.com/hajimehoshi/ebiten/internal/uidriver/glfw/ui.go:816 +0x8c
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).run(0x43ba200, 0x140, 0xf0, 0x4000000000000000, 0x424a989, 0x14, 0x42850c0, 0xc000098190, 0x0, 0x0)
    /Users/peter/Go/src/github.com/hajimehoshi/ebiten/internal/uidriver/glfw/ui.go:688 +0x165
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).Run.func1(0xc0000963c0, 0xc000094240, 0x43ba200, 0x140, 0xf0, 0x4000000000000000, 0x424a989, 0x14, 0x42850c0, 0xc000098190)
    /Users/peter/Go/src/github.com/hajimehoshi/ebiten/internal/uidriver/glfw/ui.go:568 +0xd7
created by github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).Run
    /Users/peter/Go/src/github.com/hajimehoshi/ebiten/internal/uidriver/glfw/ui.go:565 +0x1ca
exit status 2
```

**Comment by hajimehoshi** [comment]
As `graphicsDriver()` is called from other init functions, there was a hidden dependency on init-order.

**Comment by hajimehoshi** [comment]
Fixed. Thank you @peterhellberg!
