### ISSUE TITLE
test: fix `go test` on Windows when loading image after ebiten.Run

### ISSUE THREAD

**Issue by silbinarywolf** [hajimehoshi/ebiten#937]
**Why?**
I currently have a mechanism with my game where I run `go test` and it executes the game automatically based on recorded keypress data.

Unfortunately a current limitation I have is that I have to run the game in a headless state where it just simulates only the game logic and doesn't render anything, because if I try to launch anything with `go test`, no window gets drawn.

This isn't a high priority issue as I have some sort of automated testing system, but if this is something that is trivial to fix, it'd be nice to watch the game run in test mode.

**Comment by silbinarywolf** [comment]
Looks like if I try to load an image *after* calling `ebiten.Run` on Windows, `go test` will crash on Windows. When I moved my image loading code to occur before `ebiten.Run`, `go test` worked just like `go build`.

**Crash Message**
```
Exception 0xc0000005 0x0 0x11f0 0x5931979
PC=0x5931979

syscall.Syscall(0x5931970, 0x1, 0xe, 0x0, 0x0, 0x0, 0x0, 0x0)
        c:/go/src/runtime/syscall_windows.go:184 +0xea
github.com/hajimehoshi/ebiten/internal/graphicsdriver/opengl/gl.DeleteShader(...)
        D:/GoProjects/src/github.com/hajimehoshi/ebiten/internal/graphicsdriver/opengl/gl/package_windows.go:4276
github.com/hajimehoshi/ebiten/internal/graphicsdriver/opengl.(*context).deleteShader.func1(0xc00022d680, 0x0)
        D:/GoProjects/src/github.com/hajimehoshi/ebiten/internal/graphicsdriver/opengl/context_desktop.go:305 +0x4e
github.com/hajimehoshi/ebiten/internal/thread.(*Thread).Call.func1()
        D:/GoProjects/src/github.com/hajimehoshi/ebiten/internal/thread/thread.go:57 +0x3f
github.com/hajimehoshi/ebiten/internal/thread.(*Thread).Loop(0xc0000060c0, 0x826060, 0xc000042c00)
        D:/GoProjects/src/github.com/hajimehoshi/ebiten/internal/thread/thread.go:43 +0x42
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).Run(0xad7ee0, 0x140, 0xf0, 0x3ff0000000000000, 0x7a517a, 0x4, 0x826260, 0xc000042bc0, 0x829e80, 0xadc940, ...)
        D:/GoProjects/src/github.com/hajimehoshi/ebiten/internal/uidriver/glfw/ui.go:579 +0x213
github.com/hajimehoshi/ebiten.Run(0x7ccb98, 0x140, 0xf0, 0x3ff0000000000000, 0x7a517a, 0x4, 0x4853ad, 0x5d7c63a5)
        D:/GoProjects/src/github.com/hajimehoshi/ebiten/run.go:132 +0x16f
_/D_/GoProjectsModules/ebiten-go-test.TestFoo(0xc0001be200)
        D:/GoProjectsModules/ebiten-go-test/main_test.go:24 +0x105
testing.tRunner(0xc0001be200, 0x7ccb90)
        c:/go/src/testing/testing.go:865 +0xc7
created by testing.(*T).Run
        c:/go/src/testing/testing.go:916 +0x361

goroutine 1 [chan receive, locked to thread]:
testing.(*T).Run(0xc0001be200, 0x7a59ff, 0x7, 0x7ccb90, 0x4853ad)
        c:/go/src/testing/testing.go:917 +0x388
testing.runTests.func1(0xc0001be100)
        c:/go/src/testing/testing.go:1157 +0x7f
testing.tRunner(0xc0001be100, 0xc00006fe30)
        c:/go/src/testing/testing.go:865 +0xc7
testing.runTests(0xc000004f40, 0xacf6e0, 0x1, 0x1, 0x0)
        c:/go/src/testing/testing.go:1155 +0x2b0
testing.(*M).Run(0xc000118100, 0x0)
        c:/go/src/testing/testing.go:1072 +0x169
main.main()
        _testmain.go:42 +0x145

goroutine 6 [chan receive]:
github.com/hajimehoshi/ebiten/internal/thread.(*Thread).Call(0xc0000060c0, 0xc0002c74a0, 0xc0000432c0, 0xc000067ba8)
        D:/GoProjects/src/github.com/hajimehoshi/ebiten/internal/thread/thread.go:60 +0xdf
github.com/hajimehoshi/ebiten/internal/graphicsdriver/opengl.(*context).deleteShader(0xadc9c8, 0xe)
        D:/GoProjects/src/github.com/hajimehoshi/ebiten/internal/graphicsdriver/opengl/context_desktop.go:304 +0x61
github.com/hajimehoshi/ebiten/internal/graphicsdriver/opengl.(*openGLState).reset(0xadc940, 0xadc9c8, 0x0, 0x0)
        D:/GoProjects/src/github.com/hajimehoshi/ebiten/internal/graphicsdriver/opengl/program.go:241 +0x5ba
github.com/hajimehoshi/ebiten/internal/graphicsdriver/opengl.(*Driver).Reset(0xadc940, 0xc0001cbd88, 0x10)
        D:/GoProjects/src/github.com/hajimehoshi/ebiten/internal/graphicsdriver/opengl/driver.go:99 +0x3f
github.com/hajimehoshi/ebiten/internal/graphicscommand.ResetGraphicsDriverState(...)
        D:/GoProjects/src/github.com/hajimehoshi/ebiten/internal/graphicscommand/command.go:600
github.com/hajimehoshi/ebiten/internal/restorable.InitializeGraphicsDriverState(...)
        D:/GoProjects/src/github.com/hajimehoshi/ebiten/internal/restorable/images.go:220
github.com/hajimehoshi/ebiten/internal/shareable.BeginFrame.func1()
        D:/GoProjects/src/github.com/hajimehoshi/ebiten/internal/shareable/shareable.go:585 +0x4b
sync.(*Once).Do(0xb02940, 0xc0001cbdd0)
        c:/go/src/sync/once.go:44 +0xba
github.com/hajimehoshi/ebiten/internal/shareable.BeginFrame(0x0, 0x0)
        D:/GoProjects/src/github.com/hajimehoshi/ebiten/internal/shareable/shareable.go:584 +0x99
github.com/hajimehoshi/ebiten.(*uiContext).Update(0xc000042bc0, 0xc000005560, 0x0, 0x0)
        D:/GoProjects/src/github.com/hajimehoshi/ebiten/uicontext.go:80 +0x4a
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).update(0xad7ee0, 0x826260, 0xc000042bc0, 0xc0000245a0, 0xc0000051e0)
        D:/GoProjects/src/github.com/hajimehoshi/ebiten/internal/uidriver/glfw/ui.go:793 +0x1dd
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).loop(0xad7ee0, 0x826260, 0xc000042bc0, 0x0, 0x0)
        D:/GoProjects/src/github.com/hajimehoshi/ebiten/internal/uidriver/glfw/ui.go:821 +0x93
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).run(0xad7ee0, 0x140, 0xf0, 0x3ff0000000000000, 0x7a517a, 0x4, 0x826260, 0xc000042bc0, 0x0, 0x0)
        D:/GoProjects/src/github.com/hajimehoshi/ebiten/internal/uidriver/glfw/ui.go:693 +0x16c
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).Run.func1(0xc000040e50, 0xc000044360, 0xad7ee0, 0x140, 0xf0, 0x3ff0000000000000, 0x7a517a, 0x4, 0x826260, 0xc000042bc0)
        D:/GoProjects/src/github.com/hajimehoshi/ebiten/internal/uidriver/glfw/ui.go:573 +0xde
created by github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).Run
        D:/GoProjects/src/github.com/hajimehoshi/ebiten/internal/uidriver/glfw/ui.go:570 +0x1d1
rax     0x0
rbx     0xc00003e9d0
rcx     0xe
rdi     0x32c000
rsi     0xc0001c9d00
rbp     0xc0001c9cb0
rsp     0x21afe58
r8      0x0
r9      0x0
r10     0x2030000
r11     0x4
r12     0x1d6901
r13     0x815ced
r14     0x0
r15     0x0
rip     0x5931979
rflags  0x10293
cs      0x33
fs      0x53
gs      0x2b
exit status 2
```

**Resources**
[ebiten-go-test-windows.zip](https://github.com/hajimehoshi/ebiten/files/3612317/ebiten-go-test-windows.zip)

`main.go`
```
package main

import (
	"fmt"
	"log"

	"github.com/hajimehoshi/ebiten"
	"github.com/hajimehoshi/ebiten/ebitenutil"
)

var (
	counter = 0
	img     *ebiten.Image
)

func main() {
	if err := ebiten.Run(mainLoop, 320, 240, 1, "test"); err != nil {
		log.Fatal(err)
	}
}

func mainLoop(screen *ebiten.Image) error {
	if img == nil {
		var err error
		img, _, err = ebitenutil.NewImageFromFile("gopher.png", ebiten.FilterDefault)
		if err != nil {
			log.Fatal(err)
		}
		return nil
	}
	counter++
	fmt.Printf("Count: %v\n", counter)
	if img != nil {
		op := &ebiten.DrawImageOptions{}
		op.GeoM.Translate(50, 50)
		op.GeoM.Scale(1.5, 1)
		screen.DrawImage(img, op)
	}
	return nil
}
```

`main_test.go`
```
package main

import (
	"os"
	"path/filepath"
	"runtime"
	"testing"

	"github.com/hajimehoshi/ebiten"
)

func TestFoo(t *testing.T) {
	// Set directory relative to the test code file path
	// so files load in `go test`
	_, filename, _, _ := runtime.Caller(0)
	dir := filepath.Clean(filepath.Dir(filename))
	if err := os.Chdir(dir); err != nil {
		panic(err)
	}

	//mainInit()
	ebiten.SetVsyncEnabled(false)
	ebiten.SetMaxTPS(ebiten.UncappedTPS)
	if err := ebiten.Run(mainLoop, 320, 240, 1, "test"); err != nil {
		t.Errorf("%v", err)
	}
}
```

**Comment by hajimehoshi** [comment]
Ah my guess is that `ebiten.Run` must be called on the main thread (and this is documented) but in the test the thread is not main. I hope TestMain should work.

**Comment by silbinarywolf** [comment]
It seems to! I remixed the code to use TestMain and it works!

I don't think this is the correct way to handle test things but I'll look into this deeper. I'm happy for you to close this issue :)

```
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"testing"

	"github.com/hajimehoshi/ebiten"
)

func TestMain(m *testing.M) {
	// Set directory relative to the test code file path
	// so files load in `go test`
	_, filename, _, _ := runtime.Caller(0)
	dir := filepath.Clean(filepath.Dir(filename))
	if err := os.Chdir(dir); err != nil {
		panic(err)
	}

	//mainInit()
	//ebiten.SetVsyncEnabled(false)
	//ebiten.SetMaxTPS(ebiten.UncappedTPS)
	if err := ebiten.Run(mainLoop, 320, 240, 1, "test"); err != nil {
		panic(fmt.Errorf("%v", err))
	}
	os.Exit(m.Run())
}
```

**Comment by hajimehoshi** [comment]
Sure. I understood that an Ebiten application cannot work well with `go test`. I was wondering if you want to see the animation result. If not, we could solve this by using a mock UI.

**Comment by silbinarywolf** [comment]
After more experimenting today, I've found that the test will execute fine if I call `runtime.LockOSThread` first!

```
package main

import (
	"os"
	"path/filepath"
	"runtime"
	"testing"

	"github.com/hajimehoshi/ebiten"
)

func TestMyGame(t *testing.T) {
	runtime.LockOSThread()

	// Set directory relative to the test code file path
	// so files load in `go test`
	_, filename, _, _ := runtime.Caller(0)
	dir := filepath.Clean(filepath.Dir(filename))
	if err := os.Chdir(dir); err != nil {
		panic(err)
	}

	if err := ebiten.Run(mainLoop, 320, 240, 1, "test"); err != nil {
		t.Errorf("%s", err)
	}
}
```

**Comment by hajimehoshi** [comment]
Hmm, that sounds a little dangerous because there is no guarantee which thread is used to call `Test*`.

**Comment by silbinarywolf** [comment]
Yeah, I made a note in my codebase saying that the operation might be dangerous with a link to this so I can perhaps change it later to use the "mainthread" pattern in the future.
https://github.com/golang/go/wiki/LockOSThread

My knowledge on threading / how this stuff ties together is pretty shallow, so I wouldn't be surprised if what I have is brittle or flaky.

**Comment by silbinarywolf** [comment]
Tested this solution on my Mac today. Doesn't work at all, most likely due to it not running on the correct thread as you suspected!

**Comment by hajimehoshi** [comment]
Ah, this sounds a good way to force a function on a specific thread!

> make(chan bool, 1)

I'd use `make(chan struct{})` btw :-)

**Comment by hajimehoshi** [comment]
>		_, filename, _, _ := runtime.Caller(0)
>		dir := filepath.Clean(filepath.Dir(filename))

The working directory at the tests should be deterministic, so you don't have to use `runtime`.

**Comment by silbinarywolf** [comment]
Ah, that's not needed for that small example. In my codebase, I have a function called `AssetDirectory()` which either returns the URL the binary is running from or where the EXE is running from.

Unfortunately this makes test code fallover because test EXE's run from a temp directory, at least on Windows. So as part of my test bootstrap I change the asset directory to where the test code is running from.

I can't remember why I did this, so I might look into improving / removing that logic later and simplifying. Thanks :)

**Comment by silbinarywolf** [comment]
Hey there @hajimehoshi :)

I've open-sourced a package I've been working on to record player inputs. Related to this issue, I've put together a simple Ebiten example that runs headed automated tests here:
https://github.com/silbinarywolf/swir-examples

**Comment by hajimehoshi** [comment]
https://github.com/silbinarywolf/swir-examples/blob/master/squaregame/internal/test/playrecording_test.go

That sounds a good solution! I might adopt your way for Ebiten's tests :-)

BTW, have you succeeded to test multiple `ebiten.Run`?

**Comment by hajimehoshi** [comment]
I started to think we can have benchmark for Ebiten in your way :-)

**Comment by silbinarywolf** [comment]
I have not tried running multiple tests with ebiten.Run yet. My integration test system loads all my input recording in one TestXXX function.

If I do end up having multiple tests that call ebiten.Run, Ill let you know what was involved to get that working, though hopefully its not too much effort :)

**Comment by hajimehoshi** [comment]
Any updates on this? @silbinarywolf

**Comment by silbinarywolf** [comment]
I'm most likely not going to explore this anytime in the future, so I'm going to close off the issue.
