### ISSUE TITLE
restorable: Crash: len(pixels) did not match

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#971]
```
restorable: len(pixels) must be 160640 but 0

goroutine 27 [running]:
runtime/debug.Stack(0x420f3a98, 0x90bf5bb0, 0x434cbe60)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x80
github.com/hajimehoshi/ebiten/internal/uidriver/mobile.(*UserInterface).run.func1(0x420f3fac)
        /Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/internal/uidriver/mobile/ui.go:202 +0x3c
panic(0x90bf5bb0, 0x434cbe60)
        /usr/local/go/src/runtime/panic.go:522 +0x1ac
github.com/hajimehoshi/ebiten/internal/restorable.(*rectToPixels).addOrReplace(0x4409dfa0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xa0, 0xfb)
        /Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/internal/restorable/rect.go:33 +0x648
github.com/hajimehoshi/ebiten/internal/restorable.(*Pixels).AddOrReplace(...)
        /Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/internal/restorable/image.go:49
github.com/hajimehoshi/ebiten/internal/restorable.(*Image).restore(0x43f724e0)
        /Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/internal/restorable/image.go:559 +0x2d8
github.com/hajimehoshi/ebiten/internal/restorable.(*images).restore(0x90fd9150)
        /Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/internal/restorable/images.go:214 +0x95c
github.com/hajimehoshi/ebiten/internal/restorable.RestoreIfNeeded(0x90fea620, 0x420f3e6c)
        /Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/internal/restorable/images.go:90 +0x118
github.com/hajimehoshi/ebiten/internal/shareable.BeginFrame(0x0, 0x0)
        /Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/internal/shareable/image.go:592 +0xbc
github.com/hajimehoshi/ebiten/internal/buffered.BeginFrame(0x3c, 0x1)
        /Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/internal/buffered/image.go:34 +0x14
github.com/hajimehoshi/ebiten.(*uiContext).Update(0x4089e030, 0x42e76760, 0x2, 0x1)
        /Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/uicontext.go:81 +0x3c
github.com/hajimehoshi/ebiten/internal/uidriver/mobile.(*UserInterface).update(0x90fda620, 0x90c6cfa0, 0x4089e030, 0x0, 0x0)
        /Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/internal/uidriver/mobile/ui.go:289 +0x170
github.com/hajimehoshi/ebiten/internal/uidriver/mobile.(*UserInterface).run(0x90fda620, 0x1e0, 0x2f0, 0x0, 0x3fe80000, 0x0, 0x0, 0x90c6cfa0, 0x4089e030, 0x90c6ecb8, ...)
        /Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/internal/uidriver/mobile/ui.go:231 +0x184
github.com/hajimehoshi/ebiten/internal/uidriver/mobile.(*UserInterface).RunWithoutMainLoop.func1(0x40864800, 0x90fda620, 0x1e0, 0x2f0, 0x0, 0x3fe80000, 0x0, 0x0, 0x90c6cfa0, 0x4089e030, ...)
        /Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/internal/uidriver/mobile/ui.go:188 +0x94
created by github.com/hajimehoshi/ebiten/internal/uidriver/mobile.(*UserInterface).RunWithoutMainLoop
        /Users/daigosato/Development/Go/src/github.com/hajimehoshi/ebiten/internal/uidriver/mobile/ui.go:186 +0x98
```

**Comment by hajimehoshi** [comment]
`Pixels` returns nil. I think the true cause is hidden.  This requires a lot of structural change.
