### ISSUE TITLE
Window not showing up on wayland

### ISSUE THREAD

**Issue by remicalixte** [hajimehoshi/ebiten#974]
Hello :wave:, first thank you for ebiten, this is some awesome work !

I started using it for a personal project on linux. It works great on X11 but I was to curious to see how well it would behave on Wayland. Build with the `wayland` tag used by https://github.com/go-gl/glfw, the window is not showing up.

I managed to track down the issue to this call to `swapBuffers` https://github.com/hajimehoshi/ebiten/blob/d7aa24c2955e7aed32f35fe9eb3e80e03fb1c9d9/internal/uidriver/glfw/ui.go#L886 which blocks when the window is not visible. Adding `glfw.WindowHint(glfw.Visible, glfw.True)` before creating the window here: https://github.com/hajimehoshi/ebiten/blob/d7aa24c2955e7aed32f35fe9eb3e80e03fb1c9d9/internal/uidriver/glfw/ui.go#L611 appears to fix the issue.

I don't have much experience in graphics development so I don't know if this is an acceptable solution. I can try and help you to investigate further though, if you are interested in fixing this issue. :slightly_smiling_face:

**Comment by hajimehoshi** [comment]
Thank you for reporting and nailing down the issue! I have not tested Ebiten on Wayland yet. I'll try this asap on my machine.

I think suppressing `swapBuffers` before showing the window is the way to go since the initial state of the window is dummy and we don't expect this is shown.

**Comment by hajimehoshi** [comment]
OK I set up a Wayland environment and I found the panic "NotInitialized: The GLFW library is not initialized".

**Comment by hajimehoshi** [comment]
I'm struggling to use Gnome on Wayland on my Ubuntu. I failed to login and am kicked back to the login screen soon. I succeeded to run Weston, but it looks like Ebiten doesn't work there (DISPLAY is missing but I have no idea what to set). 🤔

**Comment by hajimehoshi** [comment]
Note: I'd like to commit fix to 1.10.x, but I am not sure this will be in 1.10.1.

**Comment by remicalixte** [comment]
We need to add `-tags wayland` to build `go-gl/glfw` with wayland support

**Comment by hajimehoshi** [comment]
Thanks. I added the build tag `wayland` and commented out `glfw.WindowHint(glfw.Visible, glfw.False)`. Now I run into another crash:

```
$ go run -tags=example,wayland ./examples/blocks/
GLFW: An uncaught error has occurred: PlatformError: Wayland: Focusing a window requires user interaction
GLFW: Please report this bug in the Go package immediately.
2019/11/07 22:36:37 PlatformError: Wayland: Window position retrieval not supported
2019/11/07 22:36:37 PlatformError: Wayland: Window position retrieval not supported
2019/11/07 22:36:37 PlatformError: Wayland: Window position retrieval not supported
2019/11/07 22:36:37 PlatformError: Wayland: Focusing a window requires user interaction
2019/11/07 22:36:37 PlatformError: Wayland: Window position retrieval not supported
2019/11/07 22:36:37 PlatformError: Wayland: Window position retrieval not supported
2019/11/07 22:36:37 PlatformError: Wayland: Window position retrieval not supported
2019/11/07 22:36:37 PlatformError: Wayland: Window position retrieval not supported
2019/11/07 22:36:37 PlatformError: Wayland: Window position retrieval not supported
2019/11/07 22:36:37 PlatformError: Wayland: Window position retrieval not supported
xkbcommon: ERROR: Key "<CAPS>" added to modifier map for multiple modifiers; Using Control, ignoring Lock
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x7f2d75018be0]

runtime stack:
runtime.throw(0x7dfa21, 0x2a)
        /usr/local/go/src/runtime/panic.go:774 +0x72
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:378 +0x47c

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x703100, 0xc0000b5b10, 0x0)
        /usr/local/go/src/runtime/cgocall.go:128 +0x5b fp=0xc0000b5ae0 sp=0xc0000b5aa8 pc=0x40d22b
github.com/go-gl/glfw/v3.2/glfw._Cfunc_glfwPollEvents()
        _cgo_gotypes.go:1111 +0x41 fp=0xc0000b5b10 sp=0xc0000b5ae0 pc=0x549041
github.com/go-gl/glfw/v3.2/glfw.PollEvents()
        /home/hajimehoshi/go/pkg/mod/github.com/go-gl/glfw@v0.0.0-20190409004039-e6da0acd62b1/v3.2/glfw/window.go:778 +0x22 fp=0xc0000b5b48 sp\
=0xc0000b5b10 pc=0x54e142
github.com/hajimehoshi/ebiten/internal/glfw.PollEvents(...)
        /home/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/internal/glfw/glfw_notwindows.go:271
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).forceSetScreenSize(0xc552c0, 0x100, 0xf0, 0x4000000000000000, 0xc0000101\
00)
        /home/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/internal/uidriver/glfw/ui.go:914 +0x3e1 fp=0xc0000b5bc0 sp=0xc0000b5b48 pc=0x55\
a301
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).setScreenSize(0xc552c0, 0x100, 0xf0, 0x4000000000000000, 0x100, 0x0)
        /home/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/internal/uidriver/glfw/ui.go:853 +0x8d fp=0xc0000b5bf8 sp=0xc0000b5bc0 pc=0x559\
e9d
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).run.func1(0x0, 0xc0000741e0)
        /home/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/internal/uidriver/glfw/ui.go:653 +0x2e0 fp=0xc0000b5cb0 sp=0xc0000b5bf8 pc=0x55\
b7d0
github.com/hajimehoshi/ebiten/internal/thread.(*Thread).Call.func1()
        /home/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/internal/thread/thread.go:57 +0x38 fp=0xc0000b5ce0 sp=0xc0000b5cb0 pc=0x508438
github.com/hajimehoshi/ebiten/internal/thread.(*Thread).Loop(0xc0000960f0, 0x84b9e0, 0xc00038e0c0)
        /home/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/internal/thread/thread.go:43 +0x3b fp=0xc0000b5d80 sp=0xc0000b5ce0 pc=0x5081db
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).Run(0xc552c0, 0x100, 0xf0, 0x4000000000000000, 0x7d67b1, 0x14, 0x84bbe0,\
 0xc00038e080, 0x84f0a0, 0xc9b400, ...)
        /home/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/internal/uidriver/glfw/ui.go:579 +0x20a fp=0xc0000b5e28 sp=0xc0000b5d80 pc=0x55\
907a
github.com/hajimehoshi/ebiten.Run(0xc00007f1e0, 0x100, 0xf0, 0x4000000000000000, 0x7d67b1, 0x14, 0x7d31a8, 0xa)
        /home/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/run.go:141 +0x164 fp=0xc0000b5eb8 sp=0xc0000b5e28 pc=0x565294
main.main()
        /home/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/examples/blocks/main.go:46 +0x12a fp=0xc0000b5f60 sp=0xc0000b5eb8 pc=0x6f6d2a
runtime.main()
        /usr/local/go/src/runtime/proc.go:203 +0x21e fp=0xc0000b5fe0 sp=0xc0000b5f60 pc=0x43938e
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0000b5fe8 sp=0xc0000b5fe0 pc=0x464b01

goroutine 19 [chan receive]:
github.com/hajimehoshi/ebiten/internal/thread.(*Thread).Call(0xc0000960f0, 0xc00005a080, 0x0, 0x43679a)
        /home/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/internal/thread/thread.go:60 +0xd8
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).run(0xc552c0, 0x100, 0xf0, 0x4000000000000000, 0x7d67b1, 0x14, 0x84bbe0,\
 0xc00038e080, 0x0, 0x0)
        /home/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/internal/uidriver/glfw/ui.go:589 +0xa9
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).Run.func1(0xc00007f200, 0xc000098780, 0xc552c0, 0x100, 0xf0, 0x400000000\
0000000, 0x7d67b1, 0x14, 0x84bbe0, 0xc00038e080)
        /home/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/internal/uidriver/glfw/ui.go:573 +0x10b
created by github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).Run
        /home/hajimehoshi/go/src/github.com/hajimehoshi/ebiten/internal/uidriver/glfw/ui.go:570 +0x1c8
exit status 2
```

@remicalixte, could you help me understand what was happening? Thanks!

**Comment by remicalixte** [comment]
Yes I saw this crash too. I don't really know why it's happening. What I know is that doing it like this: https://github.com/hajimehoshi/ebiten/compare/master...remicalixte:remi/wayland?expand=1 doesn't produce this crash. I can try looking at glfw a bit to understand this

**Comment by hajimehoshi** [comment]
You mean https://github.com/remicalixte/ebiten/commit/896f0e66b626b90a2c462f84dfb82846b0601bc4 ? Thank you!

Hmm, that's pretty odd..

**Comment by hajimehoshi** [comment]
Thanks, I could confirm the change fixed the issue.

It looks like any input did not work on Wayland (Weston), but this seems another issue.

**Comment by remicalixte** [comment]
Thank you !
