### ISSUE TITLE
ui: invalid or nil reference at ShouldClose

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#978]
https://github.com/OpenDiablo2/OpenDiablo2/issues/122

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x554e7e]

goroutine 1 [running, locked to thread]:
github.com/hajimehoshi/ebiten/internal/glfw.(*Window).ShouldClose(...)
	$HOME/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.10.1-0.20191108205544-35436ea50457/internal/glfw/glfw_notwindows.go:206
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).update.func1(0xc00041a060, 0x0)
	$HOME/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.10.1-0.20191108205544-35436ea50457/internal/uidriver/glfw/ui.go:757 +0x2e
github.com/hajimehoshi/ebiten/internal/thread.(*Thread).Call.func1()
	$HOME/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.10.1-0.20191108205544-35436ea50457/internal/thread/thread.go:57 +0x38
github.com/hajimehoshi/ebiten/internal/thread.(*Thread).Loop(0xc000092078, 0x96a5c0, 0xc0020dc600)
	$HOME/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.10.1-0.20191108205544-35436ea50457/internal/thread/thread.go:43 +0x3b
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).Run(0xba25e0, 0x320, 0x258, 0x3ff0000000000000, 0xc0004a4020, 0x1a, 0x96a900, 0xc0020dc5c0, 0x96e460, 0xbde6c0, ...)
	$HOME/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.10.1-0.20191108205544-35436ea50457/internal/uidriver/glfw/ui.go:579 +0x20a
github.com/hajimehoshi/ebiten.Run(0x8fd6f0, 0x320, 0x258, 0x3ff0000000000000, 0xc0004a4020, 0x1a, 0x1, 0xc0004a4020)
	$HOME/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.10.1-0.20191108205544-35436ea50457/run.go:141 +0x164
main.main()
	$HOME/go/src/github.com/OpenDiablo2/OpenDiablo2/main.go:44 +0x2d9
exit status 2
```

In the current implementation:

1. `(*UserInterface).Run` is called in a goroutine
  a. `u.window` is set at `Run`
2. `Loop` is called in the main goroutine
  a. `(*UserInterface).update` is called
  b. `u.window.ShouldClose()` is called.

In most cases, 1a. is executed before 2b, but sometimes the order is swapped.

**Comment by hajimehoshi** [comment]
Oops, my assumptions are wrong: Loop started in Run, so the order should not be swapped. Hmm?

**Comment by hajimehoshi** [comment]
I could not reproduce this :-/
